### ISSUE TITLE
docs: duplicate index property

### ISSUE THREAD

**Issue by missinglink** [elastic/elasticsearch-js#1000]
<img width="775" alt="Screenshot 2019-10-30 at 12 55 28" src="https://user-images.githubusercontent.com/738069/67856366-a9e84500-fb14-11e9-9397-9977528e4bea.png">

**Comment by delvedor** [comment]
Hello! Thank you for opening the issue!
I'm aware of this problem, it is related to https://github.com/elastic/elasticsearch-js/issues/931 and has been solved for `7.x` and `master` thanks to the new spec format.
`6.x` and `5.x` still have the issue.

If you want, you can send a pr to fix it (but there are also other duplicates), but the next time we regenerate the API, the problem will happen again.

**Comment by missinglink** [comment]
Weird reply, ok, whatever dude just trying to help.
