### ISSUE TITLE
ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by LiangFuzhi** [elastic/elasticsearch-js#1009]
```js
ConnectionError: write EPROTO 4392689088:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

## Your Environment

- *node version*: v13.2.0
- `@elastic/elasticsearch` *version*: v5.6.20
- *os*: Mac
- *any other relevant information*

**Comment by Jacse** [comment]
@LiangFuzhi did you figure this out? Currently experiencing the same.

**Comment by dustintennill** [comment]
I have this problem as well, and have a theory it is related to our certificate provider (InCommon).

**Comment by sysmetic** [comment]
try to request "http" instead of "https". I solved the problem by it.

**Comment by Jacse** [comment]
Two years later and guess where I am again. I can confirm using `http` fixed it for me this time around.

**Comment by gauravsunstone** [comment]
I am using http only but still facing same issue automatically after some days of working perfectly
Any update regarding fix?

**Comment by ahmedtauseef4** [comment]
for those it was fixed with http switch, did you configure elasticsearch to use SSL ?

**Comment by SumairaS** [comment]
make sure you your kibana.yml has the following :
elasticsearch.ssl.verificationMode: **none**
elasticsearch.hosts: ["**https:**//localhost:9200"]
