### ISSUE TITLE
Access Through Proxy

### ISSUE THREAD

**Issue by kelaban** [elastic/elasticsearch-js#101]
Having trouble connecting through a corporate proxy to a host. 
the `http` module in node by can connect through a proxy by specifying

```
{
    host: 'proxy.example.com',
    path: 'http://example.elasticsearch.com'
}
```

however specifying this in the elasticsearch `hosts` configurations don't work as expected.

**Comment by minervas** [comment]
@spalger 
I think I'm having the same problem only with the msearch function.
```
Elasticsearch INFO: 2015-07-01T00:23:53Z
  Adding connection to http://proxy.example.com:proxyport/http://host.example.com:9200/
Elasticsearch DEBUG: 2015-07-01T00:23:53Z
  starting request { method: 'POST',
    bulkBody: true,
    path: '/_msearch',
    body:
     [ { index: 'the_index' },
       { query: [Object] } ],
    query: { search_type: 'count' } }
```
Only I am just getting a timeout.
Unfortunately the gist you mentioned is down. Could you repost it?

**Comment by neilha** [comment]
Hi. I am having the same problem. Would it be possible to make the gist withe the customized httpconnector available again? I get 404 when I try to access the link. Thanks.

**Comment by ryan65** [comment]
Hi 

I opened another issue on this  https://github.com/elastic/elasticsearch-js/issues/402
If you modify host.js not to add leading slash then it works.

**Comment by clakech** [comment]
Maybe this code can help someone.

Add an env variable to reach your proxy HTTP_PROXY = http://127.0.0.1:5000/

```javascript
const elasticsearch = require('elasticsearch');
const proxy = require('proxy-agent');

const client = new elasticsearch.Client({
  host: 'my.host.com',
  createNodeAgent: () => proxy(process.env.HTTP_PROXY)
);

client.search(query);
```

Au revoir :kissing_closed_eyes:

**Comment by imran-uk** [comment]
@clakech Thanks very much, that worked for us too.

I had to code it slightly different, like this:


```
'use strict';

const elastic = require('elasticsearch'),
      proxy = require('proxy-agent'),
      config = require('../../config/config.js');

let nodeAgent;

if(process.env.MY_ELASTIC_PROXY) {
  nodeAgent = () => proxy(process.env.MY_ELASTIC_PROXY);
}

const client = new elastic.Client({
  host:               config.elastic.host,
  log:                config.elastic.log,
  suggestCompression: config.elastic.compression,
  apiVersion:         config.elastic.apiVersion,
  createNodeAgent:    nodeAgent
});
```
