### ISSUE TITLE
Result error "unable to authenticate user [undefined]"

### ISSUE THREAD

**Issue by XOneto9** [elastic/elasticsearch-js#1010]
HI, I'm David.
I'm using a Elastic cloud service as beginning.
To test, I follow step on my server.

Problem 1.

```
import { Client } from '@elastic/elasticsearch';
const client = new Client({ 
    cloud: {
        id: 'example-name: example cloud-id',
      },
      auth: {
        username: 'elastic',
        password: '*********'
      }
})
```
but I get the erorr
```
{ root_cause:
   [ { type: 'security_exception',
       reason:
        'unable to authenticate user [undefined] for REST request [/test/_search]',
       header: [Object] } ],
  type: 'security_exception',
  reason:
   'unable to authenticate user [undefined] for REST request [/test/_search]',
......
```
But if I use 
```
const client = new Client({ 
    // node: "https://username:password@elasticEndPoint:9243"
```
this is work.
why first method is not work?

Problem2.
To solve above problem 1. I searched google and then some user answer.
make user & role.

So I make user As name 'guest' and privilege role give 'all'
but I get a same error massage

plz do you know what happen?

**Comment by XOneto9** [comment]
self answer.

I have been elastic/elasticsearch-js version v7.3
but I update module to v7.4 
all of problem solve now.

**Comment by delvedor** [comment]
Hello @XOneto9, glad you could solve the issue!
For creating a user, you can follow [this guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/get-started-users.html) :)
