### ISSUE TITLE
How can I configure the new client log verbosity

### ISSUE THREAD

**Issue by dakavisa** [elastic/elasticsearch-js#1021]
Sorry if this is already asked but I couldn't find it, I just migrated to the new client, and after doing all the necessary changes I noticed that in dev I'm getting almost everything logged to console, is there a way I can disable or configure the verbosity from the client like the log option from the old one?

**Comment by dakavisa** [comment]
I was able to disable it using DEBUG=, ... -elasticsearch in my env file but is there a way to configure it somehow to log only errors or any specific  type of message?

**Comment by dakavisa** [comment]
I think I got it now from the observability section... It should all ve logged from there

**Comment by delvedor** [comment]
Hello! Glad you were able to solve the issue yourself!

For posterity: the client uses the [`debug`](https://www.npmjs.com/package/debug) module internally, but only for debugging, and you should not rely on it.
As explained in the [observability](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/observability.html) section of the docs, the client emits different events which you can listen to, and use your favorite logging solution to log the data you need.

```js
const logger = require('my-logger')()
const { Client } = require('@elastic/elasticsearch')
const client = new Client({ node: 'http://localhost:9200' })

client.on('response', (err, result) => {
  if (err) {
    logger.error(err)
  } else {
    logger.info(result)
  }
})
```
