### ISSUE TITLE
Random `ECONNRESET` errors

### ISSUE THREAD

**Issue by tomsquest** [elastic/elasticsearch-js#1029]
## 🐛 Bug Report

Random `ECONNRESET` errors.

## To Reproduce

That's the hard thing here: some of these errors occurred in the past few days.
We are on Google App Engine connected to Elasticsearch Cloud.

I thought initially that the default retry of the client would suffice to retry given a connection was dropped, but this does not seem the case.

I am asking for help to log what is going on or _really_ retry on connection failure.
I am a bit lost on what to do.

## Expected behaviour

No `ECONNRESET` errors any more.

## Your Environment

- *node version*: 10.17.0
- `@elastic/elasticsearch` *version*: 7.5.0
- Elasticsearch Cloud
- Google App Engine (= managed Node.js)
- `retry` is set to `3` by default in the @elastic/elastic client

Stack trace on Google App Engine:

```
[ExceptionsHandler] read ECONNRESET ConnectionError: read ECONNRESET 
at onResponse (/srv/node_modules/@elastic/elasticsearch/lib/Transport.js:205:13) 
at ClientRequest.request.on.err (/srv/node_modules/@elastic/elasticsearch/lib/Connection.js:98:9) 
at ClientRequest.emit (events.js:198:13) at TLSSocket.socketErrorListener (_http_client.js:392:9) 
at TLSSocket.emit (events.js:198:13) 
at emitErrorNT (internal/streams/destroy.js:91:8) 
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3) 
at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by delvedor** [comment]
Hello! A few questions:
1. Which version of Elasticsearch are you using in the cloud?
1. Can you paste here a bare minimum example to I can try to reproduce your issue? *(redacting url/cloudId/username/password/etc)*

The client will automatically retry the request in case of a ConnectionError (3 retries by default).
What are you doing after a failure?

**Comment by delvedor** [comment]
Are you sure you are using `@elastic/elasticsearch` version `7.5.0`?
At line `205` in `7.5.0` there is a debug log.

https://github.com/elastic/elasticsearch-js/blob/95847f030c3c895e3d6417e129e0a6819933cbe3/lib/Transport.js#L205

While in `7.4.0`:
https://github.com/elastic/elasticsearch-js/blob/7f7635a44b28aaf61988d4e001d9d6e14b560bf3/lib/Transport.js#L205

Which makes more sense.

**Comment by tomsquest** [comment]
Yes, I updated our cluster and the node client to 7.5.0, 1 or 2 days ago.
I will add the `DEBUG=elasticsearch` to the deployment so see if something is going on.

Closing this issue if something occurs that I can't explain.

**Comment by delvedor** [comment]
The `debug` module is not intended for production in this case, I would recommend listening to the events that the client is emitting and log what's happening.
You can find more about this in the [observability](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/observability.html) section of the docs.
