### ISSUE TITLE
Response Body type remains "any" (Typescript)

### ISSUE THREAD

**Issue by PatrickLumenus** [elastic/elasticsearch-js#1037]
I have some code as follows

`
const newAccountDoc: RequestParams.Index<UserSource> = {/*object definition here*/};
const { body } = await client.index(newAccountDoc);
`

I want to manipulate the response body. However, it is resolving to type any. How do I cast it to a specific return type? I checked the docs. But, it is rather vague as far as explaining how to do this.

Thanks.

**Comment by delvedor** [comment]
Hello!
You should be able to find everything you need in the [TypeScript documentation](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/typescript.html) :)
Regarding your specific issue, you should use the `ApiResponse` type:
```ts
import {
  Client,
  // Object that contains the type definitions of every API method
  RequestParams,
  // Interface of the generic API response
  ApiResponse,
} from '@elastic/elasticsearch'

const client = new Client({ node: 'http://localhost:9200' })

interface SearchResponse<T> {
  hits: {
    hits: Array<{
      _source: T;
    }>
  }
}

// Define the interface of the source object
interface Source {
  foo: string
}

const response: ApiResponse<SearchResponse<Source>> = await cliient.search(...)
console.log(response.body)
```
