### ISSUE TITLE
elasticsearch-js library wrongly returns timeout error

### ISSUE THREAD

**Issue by kumaoni** [elastic/elasticsearch-js#1043]
## 🐛 Bug Report
In certain cases, the elasticsearch-js library is returning "Request Timeout after 30000ms" error without actually making an elastic DB call. This happens after a previous call to the elastic DB has failed due to some other issue (for example due to an illegal or null argument) and more than 30 secs (30000 ms) have passed before the next elastic call is made (the error happens in this call).
If the next call is made within 30 secs, the timeout error is not seen and the request goes through successfully.

## To Reproduce
Step 1 - Force an error from elastic DB for example by sending a query request with a null parameter. 
Correct error is returned:
`ERROR	Get Query error { tableName: 'User',
  error:
   { Error: [illegal_argument_exception] field name is null or empty
       at respond (/var/task/node_modules/elasticsearch/src/lib/transport.js:349:15)
       at checkRespForFailure (/var/task/node_modules/elasticsearch/src/lib/transport.js:306:7)
       at HttpConnector.<anonymous> (/var/task/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
       at IncomingMessage.wrapper (/var/task/node_modules/lodash/lodash.js:4929:19)
       at IncomingMessage.emit (events.js:203:15)
       at IncomingMessage.EventEmitter.emit (domain.js:448:20)
       at endReadableNT (_stream_readable.js:1143:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
     status: 400,
     displayName: 'BadRequest',
     message: '[illegal_argument_exception] field name is null or empty',
     path: '/lemonhat_qa/_search',
     query: { type: 'User' },
     body: '{"size":"10000","query":{"term":{"_id":null}}}',
     statusCode: 400,
     response:
      '{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"field name is null or empty"}],"type":"illegal_argument_exception","reason":"field name is null or empty"},"status":400}',
     toString: [Function],
     toJSON: [Function] } }`

Step 2 - Wait for at least 30 secs

Step 3 - Send a correct ES query request with proper parameters.
Timeout error is returned from the elasticseacrh-js library. The query request does not seem to be even sent to elastic DB:
`ERROR	Unhandled Promise Rejection	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Request Timeout after 30000ms",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Request Timeout after 30000ms",
        "displayName": "RequestTimeout",
        "message": "Request Timeout after 30000ms",
        "body": false,
        "stack": [
            "Error: Request Timeout after 30000ms",
            "    at /var/task/node_modules/elasticsearch/src/lib/transport.js:397:9",
            "    at Timeout.<anonymous> (/var/task/node_modules/elasticsearch/src/lib/transport.js:429:7)",
            "    at ontimeout (timers.js:436:11)",
            "    at tryOnTimeout (timers.js:300:5)",
            "    at listOnTimeout (timers.js:263:5)",
            "    at Timer.processTimers (timers.js:223:10)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Request Timeout after 30000ms",
        "    at process.on (/var/runtime/index.js:37:15)",
        "    at process.emit (events.js:198:13)",
        "    at process.EventEmitter.emit (domain.js:448:20)",
        "    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)",
        "    at process._tickCallback (internal/process/next_tick.js:69:34)"
    ]
}
`

## Expected behavior
When step 2 (a wait of 30 secs) is skipped and step 3 immediately executed after step 1, the query response from Elastic DB  is successfully returned. This is the expected behaviour irrespective of the waiting period before the next call.

## Your Environment

- *node version*: 10
- `@elastic/elasticsearch` *version*: >=7.0.0 (elasticsearch.js - 16.5.0)
- *os*: Linux
- *any other relevant information*: The execution environment is AWS Lambda

**Comment by delvedor** [comment]
Hello!
The behavior is correct, as the legacy client uses a global timeout per request and not per http request.
The [new client](https://www.npmjs.com/package/@elastic/elasticsearch) instead, uses a timeout for every outgoing http connection.
I would recommend you to migrate to the new client, take a look to out [documentation](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/breaking-changes.html) :)

**Comment by kumaoni** [comment]
Thanks
I am a bit new to using elastic. Can you give more detail of how the global timeout per request in the older client causes this behaviour? 
It does not look normal that any subsequent (with correct data) calls to elastic will keep on failing forever unless we call it twice in quick succession.
Regards

**Comment by delvedor** [comment]
The older client starts a single timeout for the entire request and not for every underlying http connection.
I would recommend moving to the new client if this behavior is causing you issues :)
