### ISSUE TITLE
geo_point dataTypes

### ISSUE THREAD

**Issue by waedbara** [elastic/elasticsearch-js#1051]
## 💬 Questions and Help

Hello , does this package support geo_point dataTypes 
https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html#geo-point
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-query.html

**Comment by delvedor** [comment]
Hello! Not sure what you mean.
Can you upload an example?

**Comment by waedbara** [comment]
Hello I want to use ```
GET /my_locations/_search
{
    "query": {
        "bool" : {
            "must" : {
                "match_all" : {}
            },
            "filter" : {
                "geo_distance" : {
                    "distance" : "12km",
                    "pin.location" : {
                        "lat" : 40,
                        "lon" : -70
                    }
                }
            }
        }
    }
}
``` I want to use elasticSearch engine to find a nearest car for specific coordinate and specific range(distance) ?

**Comment by delvedor** [comment]
You can use any API with this client, in your case:
```js
const result = await client.search({
  index: 'my_locations',
  body: {
    query: {
      bool: {
        must: { match_all: {} }
      }
    },
    filter: {
      geo_distance: {
        distance: '12km',
        'pin.location': {
          lat: 40,
          lon: -70
        }
      }
    }
  }
})
```
I'm still not sure about what problem you are encountering.

**Comment by waedbara** [comment]
When I try to run the code you mention above, I get  ```
  error: {
      root_cause: [Array],
      type: 'parsing_exception',
      reason: 'Unknown key for a START_ARRAY in [filter].',
      line: 1,
      col: 54
    },
```
Any Help?

**Comment by delvedor** [comment]
Can you write which version of the client and Elasticsearch are you using?
The Node.js version and OS would help as well.

**Comment by waedbara** [comment]
- @elastic/elasticsearch_ client : 7.5.0,

- Elasticsearch : 7.5.1, 

- Node.js: v12.14.1

- OS: Ubuntu 18.04.3 LTS

**Comment by waedbara** [comment]
Hello,
using  ```
 let body = {
        "query": {
          "bool": {
            "must": [
              {
                "exists": {
                  "field": "location"
              }
              },
              {
                "geo_distance": {
                  "distance": targetDistance+"km",
                  "location": {
                    "lat": location.lat,
                    "lon": location.lon
                  }
                }
              }
            ]
          }
        },
        "sort": [
          {
            "_geo_distance": {
              "location": {
                "lat": location.lat,
                "lon": location.lon
              },
              "order": "asc"
            }
          }
        ]
  };
``` with `client.search({index: index, body: body})`
works fine ...
