### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by franciscojfs** [elastic/elasticsearch-js#1067]
After install the library through Yarn, the application exits with an error because `os` is required. After install this, `zlib` is required. Running again, `http` is required.

Even after install http the application keeps exiting with the following error:

> Metro Bundler has encountered an error: While trying to resolve module `http`

The package is really missing dependencies in package.json? What are the correct dependencies?

Thank you

**Comment by delvedor** [comment]
Hello!
[`os`](https://nodejs.org/api/os.html), [`zlib`](https://nodejs.org/api/zlib.html) and [`http`](https://nodejs.org/api/http.html) are Node.js core libraries, and you don't need to add them in your `package.json`.

Are you using this code in a frontend application? If so, this client is not meant to be used ina browser environment, and you should not try to connect to Elasticsearch from the browser.

**Comment by franciscojfs** [comment]
Hello! 

I completely lost that information about the library works on back end only, and tried to use in my single page react app. This was the problem, for sure.

Thank you for your help!
