### ISSUE TITLE
"ResponseError: circuit_breaking_exception" when Sending 2 messages 4 hours apart: 

### ISSUE THREAD

**Issue by athenawisdoms** [elastic/elasticsearch-js#1095]
I have a Node.js script that runs for 4-5 hours. At the start, a log message is sent to the elasticsearch server (via `winston` logger using `winston-elasticsearch`) and several hours later, a second message is sent just before the program quits.

However, the second send fails with the error

```
(node:16296) UnhandledPromiseRejectionWarning: ResponseError: circuit_breaking_exception
    at IncomingMessage.<anonymous> (/home/athenawisdom/foo/node_modules/@elastic/elasticsearch/lib/Transport.js:294:25)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

The elasticsearch client is configured as shown:

```
        {
            node: 'http://elkstack.example.com:9200',
            maxRetries: 5,
            requestTimeout: 60000,
            sniffOnStart: false,
            auth: {
                username: 'elastic',
                password: 'password'
            }
        }
```

Why is this error occurring?

## Environment

- @elastic/elasticsearch 7.5.0
- winston 3.2.1
- winston-elasticsearch 0.8.3
- Node v12.15.0
- Ubuntu 18.04.3

**Comment by delvedor** [comment]
The circuit-breaking exception happens when the node you are contacting is overwhelmed and can't take your request, you should look at Elasticsearch's logs and try to understand what's going wrong.
Also, you are getting a UnhandledPromiseRejectionWarning, which means that `winston-elasticsearch` is not handling rejection, and this will cause memory leaks to your application. It would be a good idea to also open an issue in their repository and signal this issue.

**Comment by jasine** [comment]
> Hello! The circuit-breaking exception happens when the node you are contacting is overwhelmed and can't take your request, you should look at Elasticsearch's logs and try to understand what's going wrong.
> Also, you are getting a UnhandledPromiseRejectionWarning, which means that `winston-elasticsearch` is not handling rejection, and this will cause memory leaks to your application. It would be a good idea to also open an issue in their repository and signal this issue.

@delvedor use `ignore` when sending query, see `https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-usage.html`, though I don't know the reason of this design
