### ISSUE TITLE
[Enhancement] Better Type Names

### ISSUE THREAD

**Issue by avin-kavish** [elastic/elasticsearch-js#1105]
## 🚀 Feature Proposal

Use Domain specific type names instead of generic types names such as `Client`.

## Motivation

While a type name such as `Client` may have context within this codebase, the context is lost when it's exported and used outside the library in user code.

As an example, I have aliased the `Client` class as

```ts
export type ElasticClient = Client
```

so that when I annotate functions and properties it is clear what type of client it is.

## Example

```ts
export function clientFactory(config): ElasticClient { 
  return new Client({ ...defaultConfig, ...config })  
}

export class FooSearchService {
  private _es: ElasticClient

  constructor(es?: ElasticClient) {
    this._es = es ?? clientFactory()
  }
}
```

I would be good if the original type definitions did this.

**Comment by delvedor** [comment]
Hello! Thank you for your proposal.
I understand your issue, but unfortunately, I don't think we can fix the issue at the moment, as changing the exported type would result in a breaking change.

Would you like to send a pr to our documentation to explain the issue and the workaround?

**Comment by avin-kavish** [comment]
Hmm... we could add a type alias?

```
export type ElasticClient = Client
```

This can go in the library...

**Comment by penge** [comment]
The solution to this is the other way around―make an alias in your codebase when needed.

### A

```js
// index.js
const { Client: ElasticClient } = require('@elastic/elasticsearch')
console.log(ElasticClient)
```

### B

```js
// elastic-client.js
module.exports = require('@elastic/elasticsearch').Client

// index.js
const ElasticClient = require('./elastic-client')
console.log(ElasticClient)
```

**Comment by avin-kavish** [comment]
My point is that the library should provide it, that's the entire point of this issue. Did you read it?

**Comment by penge** [comment]
I think I know what you mean now. That the imported `Client` would have some meaningful intellisence. Like it's having a type `ElasticClient`. In that case it would make a complete sense.

For a moment I thought this isn't real typescript as I haven't seen `ts` files or `tsconfig` or `typescript` package, or much use of typescript except classes that are also in ES2015. Checking the project just for the first day, excuse me.

Right now I see, the main file `index.js` is having `Client` that extends `EventEmitter` and possible solution could be, if it implements an interface, such as `ElasticClient`.

I wonder how the generation of declaration files work here. Isn't necessary to be in repository imho. I checked `index.d.ts` and there is `ClientExtends` interface which doesn't make sense.

**Comment by delvedor** [comment]
As far as I know, you can aliasing the import:
```ts
import { Client as ElasticClient } from '@elastic/elasticsearch'
```
Would this solve your issue?

**Comment by avin-kavish** [comment]
I don't have an issue. I want the community to adopt responsible naming practices.
