### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by delvedor** [elastic/elasticsearch-js#1108]
The following test passes consistently in localhost, but it's flaky on CI. It should be refactored to avoid this issue. Very likely the problem is caused due to the use of timers.

https://github.com/elastic/elasticsearch-js/blob/94d4ac752576947a9228542bf6b958bb1d3a1907/test/behavior/sniff.test.js#L114-L149

**Comment by penge** [comment]
Do you have the log from the CI?

Wasn't the reason for the fail `TimeoutError` by any chance?

**Comment by delvedor** [comment]
This is the log for the failure: https://github.com/elastic/elasticsearch-js/runs/489895557.

You can reproduce it yourself by forking this repository and playing with GitHub actions :)

**Comment by penge** [comment]
Cool! :) I'll check it out!
