### ISSUE TITLE
id field mandatory in create document [typescript]

### ISSUE THREAD

**Issue by mfaizanse** [elastic/elasticsearch-js#1129]
## 🐛 Bug Report

According to the [description](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/docs-index_.html) the `id` parameter is optional in create API. But the typescript definition of [RequestParams.Create](https://github.com/elastic/elasticsearch-js/blob/f913f7d2d2711e021225b54a333fc7aecca0b7f5/api/requestParams.d.ts#L370) is not defining the `id` as optional. So when I am calling the `client.create` method in typescript, it gives me the error that `id` is mandatory.

## To Reproduce

1) Try create a new document without assigning the `id` field.

```js
client.create({
   "index":"test-index",
   "body":{
      "field":"name",
      "newValue":"test"
   }
});
```
2) It will give the following error:
```
(node:58123) UnhandledPromiseRejectionWarning: ConfigurationError: Missing required parameter: id
    at create (/Users/faizi/node_modules/@elastic/elasticsearch/api/api/create.js:57:19)
```

## Expected behavior

- According to the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/docs-index_.html), if `id` is not set then it will create a new id by itself.

## Your Environment

- *node version*: 10
- `@elastic/elasticsearch` *version*: >=7.6.1
- *os*: Linux
- *any other relevant information*: Docker

**Comment by delvedor** [comment]
Hello! The behavior of the client is correct :)
We do offer two API for indexing documents to Elasticsearch, `index` and `create`.
The difference is that the `create` API requires an `id`, while in the `index` API is optional. You can see it in the documentation you have linked as well:

**Index API:**
```
PUT /<index>/_doc/<_id>
POST /<index>/_doc/
```

**Create API:**
```
PUT /<index>/_create/<_id>
POST /<index>/_create/<_id>
```

**Comment by joshxyzhimself** [comment]
Hi @delvedor, also encountered this at https://github.com/elastic/elasticsearch-js/issues/1372, does this mean that the `create` operation on `client.bulk` has the incorrect behaviour since it allows creating of the document even if `_id` is not provided?

**Comment by joshxyzhimself** [comment]
Since it actually makes sense for the user to use the `index` op when there's no document `_id` yet, what do you think?
