### ISSUE TITLE
Switch Request and Response generics

### ISSUE THREAD

**Issue by delvedor** [elastic/elasticsearch-js#1130]
In #1119 we introduced a big change in how the type definitions work, and I'm very happy with the result, the code is more idiomatic and it's easier to use the TypeScript features.
While working on #970, I've noticed that there is still something we can do to improve even further the developer experience.
By reading this issue tracker and around on the internet, people is more interested in the response types rather than the request types, which in most of the cases are good enough with the body set to `Record<string, any>`.
Currently, the generics allow you to specify the request body, the response body  and the context in this order:
```ts
client.search<RequestBody, ResponseBody, Context>(...)
```
I'm wondering if it does make more sense to have the `ResponseBody` generic as the first parameter instead since it will be used more often for defining Source objects and so on. While my OCD screams when seeing about this, I think it makes way more sense given that people will use the Response types more often.
```ts
client.search<ResponseBody, RequestBody, Context>(...)
```

What do you think?

cc @Mpdreamz @joshdover @restrry @nreese @dgieselaar @fox1t @villasv

**Comment by fox1t** [comment]
I absolutely agree to have generics in order of importance for developers. ResponseBody is what is used buy the rest of the code and therefore it deserves to be put first.

**Comment by Mpdreamz** [comment]
Agreed my gut reaction wants request before response however I think


```typescript
client.search<SearchResponse<Document>>({
   body: {
      query: { match_all: {} }
   }
});
```

Is a much nicer experience for folks who develop their search in e.g the kibana console then port it over to the client and look to get type safety when programming against the response.

The alternative would be to force the user to specify the body they just wrote is untyped:

```typescript
client.search<any, SearchResponse<Document>>({
   body: {
      query: { match_all: {} }
   }
});
```

**Comment by delvedor** [comment]
I've opened https://github.com/elastic/elasticsearch-js/pull/1132 with the changes proposed in this issue so you can see how the client will change and maybe try it out!

**Comment by villasv** [comment]
> By reading this issue tracker and around on the internet, people is more interested in the response types rather than the request types

TBH I'm more interested in typing the body parameters because they help so much when people are not 100% familiar with Elasticsearch APIs, allowing the IDE to provide rich auto-complete. Still, I understand that return values are much more relevant to keep my own code well typed.

So all things considered, I'm indifferent as to which one comes first. I'm always specifying both. But it makes sense to me that lots of people may only specify the return types and so it should come first.
