### ISSUE TITLE
Include common interfaces in the source code

### ISSUE THREAD

**Issue by ismail-codinglab** [elastic/elasticsearch-js#1134]
## 🚀 Feature Proposal

I have not found an issue about this before.
It would be nice to have the common types included in the source code.
The ones that are here in this PR:
https://github.com/elastic/elasticsearch-js/pull/742/files

and use it like so:
```typescript
import { Client, ApiResponse, RequestParams, SearchResponse } from '@elastic/elasticsearch';
interface CoolBody{
  cool: 'yes';
}
client
.search(params)
.then((result: ApiResponse<SearchResponse<CoolBody>>) => {
```

## Motivation

Reduces code, maintenance, technical depth, complexity, learning curve

One argument I could think of why you wouldn't include them is if they are different per setup.
Then I would simply suggest to rename `SearchResponse` to `DefaultSearchResponse`

I can't teach my students all this workload before they can do a simple search. I want to hide this complexity.

**Comment by delvedor** [comment]
Hello! We are working on this, and hopefully, we'll start shipping the first response interfaces soon!
Closing this issue as we are already discussing it in https://github.com/elastic/elasticsearch-js/issues/933.
