### ISSUE TITLE
alias search via api goes not return any result

### ISSUE THREAD

**Issue by arupadhy** [elastic/elasticsearch-js#1135]
## 💬 Questions and Help
I am recreating index via alias strategy i.e create a new index, update alias mapping to new index and delete old index, not search via api calls (that use alias for index) are not returning any result but curling via alias works fine.
### Please note that this issue tracker is not a help forum and this issue may be closed.

It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Comment by delvedor** [comment]
Hello! Can you add a snippet of code to reproduce the issue you are facing?
Furthermore, which version of the client and Elasaticsearch are you using?

**Comment by arupadhy** [comment]
@delvedor i take that back....it was my env. api works fine (using latest 7.x version)
