### ISSUE TITLE
Is this compatible with the open-distro Elasticsearch?

### ISSUE THREAD

**Issue by acannon828** [elastic/elasticsearch-js#1147]
Let me know if I should post this elsewhere but this seemed to be the best place to ask.

I didn't see any mention of the open distro of Elasticsearch anywhere here. To what extent is this client compatible with the open distro of Elasticsearch (https://opendistro.github.io/for-elasticsearch/)?

FWIW I don't see any mention of supported clients on the https://opendistro.github.io/ page either.

**Comment by sethpayne** [comment]
Hi @acannon828 --  Unfortunately I can't provide much info on your question. We don't test against Open Distro and so can't provide any information on compatibility.
