### ISSUE TITLE
Camel Case issue with Elastic SDK in Typescript

### ISSUE THREAD

**Issue by tvvignesh** [elastic/elasticsearch-js#1152]
Hi. I am using the latest verison of elasicsearch-js SDK and I noticed the docs in `client.indices.create` that they said we can use both underscore as well as camel casing (https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html)

![Screenshot from 2020-04-11 18-29-43](https://user-images.githubusercontent.com/1165845/79044413-a52acf80-7c22-11ea-9390-0e3687c2c950.png)

That is, `wait_for_active_shards` or `waitForActiveShards`, `include_type_name` or `includeTypeName`

But, when I am using camelcase, I am getting error in typescript since they are not defined in the interface file (Screenshot below).

![Screenshot from 2020-04-11 18-32-32](https://user-images.githubusercontent.com/1165845/79044455-d905f500-7c22-11ea-8035-8e27de879a3d.png)

Thought I would let you guys know. Thanks.

**Comment by delvedor** [comment]
Hello! Thank you for reporting, but this is a design decision, as you can’t have both camelCase and snake_case keys while you need to support required parameter as well.

There is a note about this in the [typescript](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/typescript.html) documentation :)

**Comment by tvvignesh** [comment]
Oops. Missed to see that. Thanks for the clarification.
