### ISSUE TITLE
Improve Authentication header handling

### ISSUE THREAD

**Issue by delvedor** [elastic/elasticsearch-js#1163]
By default, the `authentication` header is stored [all lowercased](https://github.com/elastic/elasticsearch-js/blob/17959a41e12362aadd8cd0d4e503791cb20d4d87/lib/Connection.js#L301-L314), but if the user wants to override it, and uses the `Authorization` key with the first letter uppercased, the header will not be [correctly merged](https://github.com/elastic/elasticsearch-js/blob/17959a41e12362aadd8cd0d4e503791cb20d4d87/lib/Connection.js#L202-L203).

Example:
```js
const client = new Client({
  node: 'http://localhost:9200',
  auth: { username: 'user', password: 'pwd' }
})

// this will work
const result = await client.search({ ... }, {
  headers: { authorization: 'Basic foobar' }
})

// this will NOT work
const result = await client.search({ ... }, {
  headers: { Authorization: 'Basic foobar' }
})
```

**Comment by penge** [comment]
Hi @delvedor 
I have seen you have this assigned so, I'd like to give you my input at least :)
I think the best could be if `prepareHeaders()` and `buildRequestObject()` remain unchanged and continue to use the same underlying `authorization` (with the lowercase a) as before.

The only change then would be, from:

```js
this.headers = prepareHeaders(opts.headers, opts.auth)
```

To:

```js
this.headers = prepareHeaders(mapHeaders(opts.headers), opts.auth)
```

Where `mapHeaders()` would then be:

```js
function mapHeaders(rawHeaders) {
  const headers = { ...rawHeaders } // or Object.assign({}, rawHeaders)
  if (headers.Authorization) {
    headers.authorization = headers.Authorization
    delete headers.Authorization
  }
  return headers
}

console.log(mapHeaders({ authorization: 'Basic foobar' }));
// { authorization: "Basic foobar" }

console.log(mapHeaders({ Authorization: 'Basic foobar' }));
// { authorization: "Basic foobar" }
```

(:

**Comment by delvedor** [comment]
@penge this is a problem that came up because of authentication headers, but in reality, it applies to any header. I've opened #1187 with the fix.
