### ISSUE TITLE
Highlight Object Property not showing on result

### ISSUE THREAD

**Issue by kevinjuliano1020** [elastic/elasticsearch-js#1166]
Hi I am using Fuzzy search with highlight request, the results are showing fine when I use Postman, but when I did it on nodejs the Highlight object is not showing.

I attached files for reference
![Screenshot from 2020-04-21 02-32-43](https://user-images.githubusercontent.com/9549246/79787184-2dbf1380-8379-11ea-9537-2e79a939528e.png)
![Screenshot from 2020-04-21 02-33-05](https://user-images.githubusercontent.com/9549246/79787227-3d3e5c80-8379-11ea-847b-da0da1b11c9d.png)
![Screenshot from 2020-04-21 02-33-32](https://user-images.githubusercontent.com/9549246/79787664-f309ab00-8379-11ea-8286-dfafde372a76.png)
![Screenshot from 2020-04-21 02-34-12](https://user-images.githubusercontent.com/9549246/79787675-f6049b80-8379-11ea-8074-d224c31e8bea.png)

**Comment by kevinjuliano1020** [comment]
anyone?? :sob:

**Comment by delvedor** [comment]
Hello! I see from your screenshots that in postman you are using a fixed value, while in your code you are using a dynamic value.
Can you please upload an example to reproduce the issue?

The only thing we do with the body is to serialize it, so very likely you are passing a value that is not what you would expect.
To verify this assumption, you could add a listener for the `request` event and see the serialized body we are sending to Elasticsearch.

```js
client.on('request', (err, meta) => {
  console.log(meta.request.params.body)
})
```

**Comment by kevinjuliano1020** [comment]
Hi @delvedor ,

I think I am passing the right parameters. here's the response from the request event:

    { params:
       { method: 'POST',
         path: '/tm_mi_idx/_search',
         body:
          '{"query":{"bool":{"must":{"match":{"title":{"query":"crush fun park","fuzziness":"AUTO","max_expansions":50,"prefix_length":0}}},"filter":{"terms":{"int_class.text":["trampoline"]}}}},"highlight":{"fields":{"text":{"fragment_size":14}}}}',
         querystring: '',
         headers:
      { 'User-Agent':
         'elasticsearch-js/7.6.1 (linux 4.15.0-96-generic-x64; Node.js v11.13.0)',
        'Content-Type': 'application/json',
        'Content-Length': '237' } },
      options: { warnings: null },
      id: 6 }

I can give you access on my elasticsearch server if you want.

**Comment by delvedor** [comment]
I see that the `fragment_size` is set to `14`, while in the postman screenshot you set `13`. I'm not sure that's the issue, but I think you should at least use the exact same query :)

**Comment by kevinjuliano1020** [comment]
Hi @delvedor 

I am really sorry, the fragment_size is not the problem. but after a bit of troubleshooting and investigating where I went wrong, it turned out to be the programmers number 1 enemy, 

I am missing 1 curly brace ` } `

I am really sorry.

**Comment by delvedor** [comment]
There is no need to be sorry!
Glad you were able to sort it out :)
