### ISSUE TITLE
Base

### ISSUE THREAD

**Issue by TheChrisOneil** [elastic/elasticsearch-js#1176]
## 🐛 Bug Report
Sniff test returns results.body.nodes missing the 'http' property  required by the connectionPool.nodesToHost.  

````
results.body.nodes is missing the property http
{
  'fQOZTtH-T02SgbQWbiEL7w': {
    name: '600909800c2ae15a84cbdbef4598a58a',
    version: '7.4.2',
    build_flavor: 'oss',
    build_type: 'tar',
    build_hash: 'unknown',
    roles: [ 'ingest', 'master', 'data' ]
  }
}
`````

## To Reproduce
1.  Define Client configuration
const elasticSearchConnection = new Client({
    node: 'https://vpc-es-institutional-investor-r5ck3aevprngvntulspwqae5ha.us-west-2.es.amazonaws.com',
    maxRetries: 5,
    requestTimeout: 60000,
    sniffOnStart: true
});

2.  Deploy to AWS running nodejs v Node.js version: 12.16.1
 and using "@elastic/elasticsearch": "^7.6.1",

3.  npm start 
During the initialization the following error is observed.

Paste your code here:
Below is my debug code identifying the initialization the phase that results in the sniff test
-------------------------------------
/var/log/nodejs/nodejs.log
-------------------------------------
==== [ConnectionPool.js] update ====
==== [BaseConnection.js] Updating the connection pool ====
==== [Transport.js] sniff ====
==== [ConnectionPool.js] getConnection ====
==== [ConnectionPool.js] resurrect ====
==== [ConnectionPool.js] resurrect: Nothing to resurrect  ====
====[index.js] New Client transport established ====
====[index.js] New Client api established ====

<my code debug>
handlerId: 
Index_bulkActions
handlerCache[handlerId]: 
[Function: bulkActions]
handlerId: 
</my code debug>

==== [ConnectionPool.js]  markAlive - Updating the connection pool ====
==== [Transport.js] Sniffing ended successfully ====
sniff nodes results
{
  'fQOZTtH-T02SgbQWbiEL7w': {
    name: '600909800c2ae15a84cbdbef4598a58a',
    version: '7.4.2',
    build_flavor: 'oss',
    build_type: 'tar',
    build_hash: 'unknown',
    roles: [ 'ingest', 'master', 'data' ]
  }
}
==== [BaseConnection.js] nodesToHost ====
node[name]=
node[name]=600909800c2ae15a84cbdbef4598a58a
node[version]=
node[version]=7.4.2
node[build_flavor]=
node[build_flavor]=oss
node[build_type]=
node[build_type]=tar
node[build_hash]=
node[build_hash]=unknown
node[roles]=
[ 'ingest', 'master', 'data' ]
/var/app/current/middleware/utility/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:209
      var address = node.http.publish_address
                              ^

TypeError: Cannot read property 'publish_address' of undefined
    at ConnectionPool.nodesToHost (/var/app/current/middleware/utility/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:209:31)
    at /var/app/current/middleware/utility/@elastic/elasticsearch/lib/Transport.js:370:41
    at f (/var/app/current/node_modules/once/once.js:25:25)
    at IncomingMessage.<anonymous> (/var/app/current/middleware/utility/@elastic/elasticsearch/lib/Transport.js:305:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)## Expected behavior

The hostToNodes should handle the lack of a'http' property ' and perhaps default to the users entered configure node url.

## Your Environment

AWS running nodejs v Node.js version: 12.16.1
 and using "@elastic/elasticsearch": "^7.6.1",

**Comment by batmanhit** [comment]
@TheChrisOneil, how did you resolve this issue?

I am using Node 12.16.1 and "@elastic/elasticsearch": "7.8.0". The elastic search version on AWS is `7.7.0`.

**Comment by ameena007** [comment]
Why this is closed.

I am also getting the same error. When i test using my local es deployment then it works but with AWS deployed es it gives the error.

home/ec2-user/edx_es_manager/node_modules/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:213
      var address = node.http.publish_address
                              ^

TypeError: Cannot read property 'publish_address' of undefined
    at ConnectionPool.nodesToHost (/home/ec2-user/edx_es_manager/node_modules/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:213:31)
    at /home/ec2-user/edx_es_manager/node_modules/@elastic/elasticsearch/lib/Transport.js:482:41
    at onBody (/home/ec2-user/edx_es_manager/node_modules/@elastic/elasticsearch/lib/Transport.js:342:9)
    at IncomingMessage.onEnd (/home/ec2-user/edx_es_manager/node_modules/@elastic/elasticsearch/lib/Transport.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by raxetul** [comment]
> Why this is closed.
> 
> I am also getting the same error. When i test using my local es deployment then it works but with AWS deployed es it gives the error.
> 
> home/ec2-user/edx_es_manager/node_modules/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:213
> var address = node.http.publish_address
> ^
> 
> TypeError: Cannot read property 'publish_address' of undefined
> at ConnectionPool.nodesToHost (/home/ec2-user/edx_es_manager/node_modules/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:213:31)
> at /home/ec2-user/edx_es_manager/node_modules/@elastic/elasticsearch/lib/Transport.js:482:41
> at onBody (/home/ec2-user/edx_es_manager/node_modules/@elastic/elasticsearch/lib/Transport.js:342:9)
> at IncomingMessage.onEnd (/home/ec2-user/edx_es_manager/node_modules/@elastic/elasticsearch/lib/Transport.js:260:11)
> at IncomingMessage.emit (events.js:327:22)
> at endReadableNT (_stream_readable.js:1220:12)
> at processTicksAndRejections (internal/process/task_queues.js:84:21)

It is probably becaıse you have said "AWS".

It would be better to write a polite answer like "We don't provide support for AWS services that we don't guarantee any solution to work since Amazon's implementation might be different."

**Comment by delvedor** [comment]
@ameena007 @raxetul look at https://github.com/elastic/elasticsearch-js/issues/1178.
