### ISSUE TITLE
AWS Elastic Search support

### ISSUE THREAD

**Issue by jhhasbun** [elastic/elasticsearch-js#1182]
## 🚀 Feature Proposal

As a user of this library I would like the option to use a built-in `Connection` that handles AWS request signing (example [here](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-node)). This would allow a frictionless experience for users of this library whose Elastic Search clusters are hosted in AWS.

## Motivation

In order to make requests to AWS resources such as Elastic Search, the request must include authentication information signed with the users credentials. Specifically, AWS expects the request to adhere to the SigV4 process ([reference doc](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html)).

For the [legacy elasticsearch-js client](https://www.npmjs.com/package/elasticsearch) there was an [independent library](https://www.npmjs.com/package/http-aws-es) which added compatibility with AWS Elastic Search. However, I believe it makes sense for a similar client to live within this project given the increasing number of users who utilize AWS ES.

## Example

A user who has their Elastic Search cluster hosted in AWS would be able to use the new `AWSConnection`, which is configured to sign requests as [expected by AWS](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) and maintain a consistent experience using this library.

**Comment by Joehunk** [comment]
Agreed. I am in the process of porting a service I just wrote back to the legacy library for this precise reason.

**Comment by delvedor** [comment]
The Elasticsearch clients go through rigorous testing and validation against the official Elasticsearch distribution coming from Elastic. Since the AWS Elasticsearch Service has incompatible APIs with Elasticsearch itself, either by missing APIs or has incompatible format, we do not support it. Please consider using [Elastic Cloud](https://cloud.elastic.co/) for an official and formally supported hosted Elasticsearch distribution.

**Comment by gbvanrenswoude** [comment]
I guess AWS chose another route to go down. Shame to see both parties part ways. AWS provides quite some documentation on the matter on how to sign your requests to their ElasticSearch 'clone'. See e.g. https://docs.aws.amazon.com/opensearch-service/latest/developerguide/configuration-samples.html. With that, a function draft is quickly made:

```ts
export async function indexDocumentonAwsES(body, index, type, id, domain) {
  const request = new HttpRequest({
    body: JSON.stringify(body),
    headers: {
      'Content-Type': 'application/json',
      host: domain
    },
    hostname: domain,
    method: 'PUT',
    path: `${index}/${type}/${id}`
  });
  const signer = new SignatureV4({
    credentials: defaultProvider(),
    region,
    service: 'es',
    sha256: Sha256
  });
  const signedRequest = await signer.sign(request);
  const client = new NodeHttpHandler();
  // @ts-ignore
  const { response } = await client.handle(signedRequest);
  console.log(`${response.statusCode} ${response.body.statusMessage}`);
  let responseBody = '';
  await new Promise(() => {
    response.body.on('data', chunk => {
      responseBody += chunk;
    });
    response.body.on('end', () => {
      console.log('Response body: ' + responseBody);
    });
  }).catch(error => {
    console.log('Error: ' + error);
  });
}
```
