### ISSUE TITLE
Bulk update helper not working as expected for updates.

### ISSUE THREAD

**Issue by nmaves** [elastic/elasticsearch-js#1200]
## 🐛 Bug Report

I am trying to use the new bulk helper and I think I have found a bug with updates.

https://github.com/elastic/elasticsearch-js/blob/master/lib/Helpers.js#L225

I don't believe you want to have the `[0]` index on the action.

## To Reproduce

Paste your code here:

```js
    const response = await circulationClient.helpers.bulk({
      datasource: [{ id: 1, firstName: 'nathan}],
      onDocument: (doc) => {
        return {
          update: { _index: 'people', _id: doc.id`}
        }
      },
      retries: 3
    })
```

## Your Environment

- *node version*: 10
- `@elastic/elasticsearch` *version*: >=7.7.1
- *os*: Mac

**Comment by delvedor** [comment]
Hello! The documentation is not clear enough on this point, the `update` operation is slightly different from the others, and you should return an array, for example:
```js
const result = await client.helpers.bulk({
  datasource: [{ id: 1, firstName: 'nathan' }],
  onDocument (doc) {
    return [{
      update: {
        _index: 'people',
        _id: doc.id
      }
    }, {
      doc_as_upsert: true
    }]
  }
})
```

I'll open a pr to fix it, thanks!

**Comment by nmaves** [comment]
Why an array?  What are the expected elements of that array?

**Comment by delvedor** [comment]
Because with the bulk update API you can add more options to the action payload, see [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-update).

**Comment by aterreno** [comment]
Hey if anyone is stuck on this I've created a simple test repo to try all the different bulk options

https://github.com/aterreno/elasticsearch-bulk/blob/master/__tests__/index.test.js

well it's index/update/delete, which is all I needed ;)

**Comment by aterreno** [comment]
I've now also added a second set of tests because the helper won't cut it for my needs:

https://github.com/aterreno/elasticsearch-bulk/blob/master/__tests__/index2.test.js

**Comment by delvedor** [comment]
@aterreno would you like to elaborate? :)

**Comment by aterreno** [comment]
@delvedor on my second post you mean?

Sure, I'm handling a stream coming from dynamoDB and the documents might come from different indexes. 

so, as far as I understand

```
  const result = await client.helpers.bulk({
    datasource: dataset,
    onDocument() {
      return {
        index: { _index: 'tweets' },
      };
    },
  });
```
Will not allow me to specify a 'dynamic' index based on the document, while if I do:

```
    const updateBody = flatMap(toUpsert, (doc) => [
      { update: { _index: doc.index, _id: doc.id } },
      { doc: doc.body, doc_as_upsert: true }
    ])
    await es.es.bulk({ refresh: true, body: updateBody })
```

Where the doc is wrapped, adding 'metadata' such as index, type, and body 

Then I can do my trick. 

Not sure if it's possible to unwrap documents with the new helper, that's it.

**Comment by delvedor** [comment]
The bulk helper does allow you to specify a dynamic index based on the document, as you can see in the [documentation](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-helpers.html#_bulk_helper):

```js
const result = await client.helpers.bulk({
  datasource: [{ id: 1, firstName: 'nathan' }],
  onDocument (doc) {
    return {
      index: { _index: doc.index, _id: doc.id }
    }
  }
})
```

What the helper does not currently provide, is a callback to manipulate the document, which you can still do by piping the datasource in a transform stream or an async generator before giving the stream to the helper.

I'll open a separate feature request to investigate the support for a callback to manipulate the document.

**Comment by aterreno** [comment]
👍 you are right, my issue was exactly that one, I could not change the document and therefore couldn't use the helper. 

Happy with the 'standard' method, but as a feedback, I'd probably put an example for all the CRUD options in the documentation, just my 2 cents! 

Thanks for taking care of this!
