### ISSUE TITLE
Proper Error handling with Promise Use to precent UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by vanthome** [elastic/elasticsearch-js#1204]
Hi,
unfortunately with this code:

https://github.com/elastic/elasticsearch-js/blob/master/lib/Transport.js#L86

I can't see how I can prevent this from generating a `UnhandledPromiseRejectionWarning` in node when I don't use callbacks and an error occurs, then inevitably this promise will reject and node will throw the warning. For example I'm getting this when I use:

`.cluster.health({});`

Is this a known flaw or intended? Wouldn't it be better if as a user I can provide an error handler as option?

BG

**Comment by delvedor** [comment]
Hello! Can you add an example to reproduce the problem? :)
As you can see in the following test, the promise API works as expected:
https://github.com/elastic/elasticsearch-js/blob/1a25b623b06fd609a5b96c4367c9a4613b1b4a38/test/unit/api.test.js#L85-L110

**Comment by vanthome** [comment]
ok, I see. I will close for now and maybe reopen if needed.
