### ISSUE TITLE
ssl.rejectUnauthorised defaults to false

### ISSUE THREAD

**Issue by shusson** [elastic/elasticsearch-js#1208]
## 🐛 Bug Report

After upgrading to the new client we get a connection error when using SSL without explicitly setting `ssl.rejectUnauthorised` to false. The documentation says it defaults to false https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/auth-reference.html#_ssl_configuration

Config before: 
```js
const client = new Client({
  nodes: ['https://user:password@yyy/elasticsearch'],
  requestTimeout: 120000
});
```

Config after: 
```js
const client = new Client({
  nodes: ['https://user:password@yyy/elasticsearch'],
  requestTimeout: 120000,
  ssl: {
    rejectUnauthorized: false
  }
});
```

## Your Environment

- Node.js v12.16.1
- `@elastic/elasticsearch` *version*: =6.8.6
- elasticsearch 6.6
- Windows

**Comment by delvedor** [comment]
Hello! Can you paste here your nginx configuration?
Or,  even better, can you reproduce your issue by forking [this repository](https://github.com/delvedor/es-reproduce-issue) and adding both Nginx and a code example? :)

Thanks!

**Comment by shusson** [comment]
@delvedor I can reproduce the issue: https://github.com/shusson/es-reproduce-issue/tree/task/ssl-error

It's because in the old client `ssl.rejectUnauthorised` defaults to `false` where as in the new client it defaults to `true`.

The documentation https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/auth-reference.html#_ssl_configuration states 

> Without any additional configuration you can specify https:// node urls, but the certificates used to sign these requests will not verified (rejectUnauthorized: false)

So for us the easy workaround is to update our config with:

```
  ssl: {
    rejectUnauthorized: false
  }
```

I'll update the issue description with the new info.

similar issue: https://github.com/elastic/elasticsearch-js/issues/991

**Comment by shusson** [comment]
@delvedor A documentation update sounds good, it would also be nice to mention it in the breaking changes to the API. 

> would you like to send a pr?
No thank you :)
