### ISSUE TITLE
Getting a "400 Bad Request" when providing empty body with GET method in the scroll operation

### ISSUE THREAD

**Issue by chechu** [elastic/elasticsearch-js#1227]
## 🐛 Bug Report

Using the `scroll` method of the client, providing a `scrollId` parameter that previously was generated invoking the `search` method, in same cases a `400 Bad Request` response is generated.

We are connected to an Elastic cloud instance. We don't get this behaviour for every request, just in some cases, but very frequently from yesterday (11th June), so it could be a server configuration issue.

The server may deny `GET` requests with an empty string body. The library could do something to avoid this negative side effect, like using always `POST`, or not sending an empty string in the body when the selected method is `GET`

Reviewing the code of the `scroll` method, we think the issue is related with this:
* To select the HTTP method, the body is [compared](https://github.com/elastic/elasticsearch-js/blob/master/api/api/scroll.js#L67) to `null`
* But [then](https://github.com/elastic/elasticsearch-js/blob/master/api/api/scroll.js#L78), in the request a body is always added.

## To Reproduce

It's just the simplest use case of scroll, iterating on the results until the end. 

```js
const scroll = '1m';
const index = 'myIndex';
const body = {... your query here ...};

// Initial search with scroll
let result = client.search({ body, index, scroll })

while (results.body.hits.hits.length) {
  const scrollId = results.body._scroll_id;
  console.log('Partial hits: ', results.body.hits.hits.length);

  // Next results
  result = client.scroll({ scroll, scrollId })
}
```
I think one key factor here is that the used `client` is connected to an [Elastic cloud instance](https://www.elastic.co/cloud).

We usually get an error in the second execution of the `scroll` sentence. The response is something like this:
```
{
  "name": "ResponseError",
  "meta": {
    "body": "400 Bad Request",
    "statusCode": 400,
    "headers": {
      "content-type": "text/plain; charset=utf-8",
      "connection": "close"
    },
    "warnings": null,
    "meta": {
      "context": null,
      "request": {...}
      "name": "elasticsearch-js",
      "connection": {
        "url": "https://---.---.aws.found.io/",
        "id": "https://---.---.aws.found.io/",
        "headers": {
          
        },
        "deadCount": 0,
        "resurrectTimeout": 0,
        "_openRequests": 0,
        "status": "alive",
        "roles": {
          "master": true,
          "data": true,
          "ingest": true,
          "ml": false
        }
      },
      "attempts": 0,
      "aborted": false
    }
  }
}
```

## Expected behavior

Just complete the iteration of the scroll, without getting any errors, as we are doing in some cases now and always in the past.

## Your Environment

- *node version*: 10.18.0
- `@elastic/elasticsearch` *version*: >=7.4.0 (we have tested with 7.4.0 and 7.7.1)
- *os*: Mac
- Elastic cloud instance, mono server, version 7.4.0

**Comment by delvedor** [comment]
Hello! I'll investigate the body issue you are reporting, thanks!
Meanwhile, you can put the `scroll_id` parameter inside the body:
```js
await client.scroll({ scroll: '1m', body: { scroll_id: 'id' } })
```
If you use the client ≥v7.7, you can use the [scrollSearch](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-helpers.html#_scroll_search_helper) helper, which will take care for you about all the mechanics of doing a scroll search.

Using it will give you back and async iterator which you can easily consume with a `for await` loop :)
```js
const scrollSearch = client.helpers.scrollSearch({
  index: 'stackoverflow',
  body: {
    query: {
      match: {
        title: 'javascript'
      }
    }
  }
})

for await (const result of scrollSearch) {
  console.log(result)
}
```

**Comment by delvedor** [comment]
@chechu I tried to reproduce your issue, but I didn't get any error back.
What is your client configuration?

> To select the HTTP method, the body is compared to null

The comparison uses `==`, which checks for both `null` and `undefined`.

> But then, in the request a body is always added.


Yes, but as an empty string, which does not affect the HTTP call. Also, no content type / encoding headers are configured.

**Comment by chechu** [comment]
> Hello! I'll investigate the body issue you are reporting, thanks!

Thank you

> Meanwhile, you can put the `scroll_id` parameter inside the body:
> 
> ```js
> await client.scroll({ scroll: '1m', body: { scroll_id: 'id' } })
> ```

I see, that would force the use of POST as HTTP method, so it would be similar to the workaround that we are using:

```js
await client.scroll({ scrollId, scroll, method: 'POST' });
```

> If you use the client ≥v7.7, you can use the [scrollSearch](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-helpers.html#_scroll_search_helper) helper, which will take care for you about all the mechanics of doing a scroll search.

Thank you, we developed something similar (with a `hasMore` method instead of using a generator, but basically doing the same). Good improvement in the library 👍
