### ISSUE TITLE
System Indices Support

### ISSUE THREAD

**Issue by kobelb** [elastic/elasticsearch-js#1228]
The Elasticsearch team is working on formally implementing [system indices](https://github.com/elastic/elasticsearch/issues/50251). However, the details of how system indices will behave from the API perspective is still largely to be determined. 

Kibana currently uses the legacy elasticsearch-js client to access what will become system indices, with the intent of switching to the modern elasticsearch-js client. Kibana would benefit from the modern elasticsearch-js supporting system-indices, so we have a single way of querying all indices, regardless of them being system-indices or not. 

Do you have any current plans to implement system indices support, or thoughts on whether or not it's something that belongs within the elasticsearch-js client?

**Comment by delvedor** [comment]
> Do you have any current plans to implement system indices support, or thoughts on whether or not it's something that belongs within the elasticsearch-js client?

I'm not sure what you mean here. The client exposes the entire Elasticsearch API surface, if you can access the system indices via an API, then you can do it with the client.

**Comment by kobelb** [comment]
> I'm not sure what you mean here. The client exposes the entire Elasticsearch API surface, if you can access the system indices via an API, then you can do it with the client.

System-indices will change the way that the Elasticsearch APIs work for some indices. For example, one of the proposals would change the way that Elasticsearch indices are queried from:

```
GET .kibana/_search
```

to: 

```
GET _kibana/.kibana/_search
```

The current thinking is that each "system", will have a plugin in Elasticsearch which makes it possible to query the system-indices for that "system". There's potential that each system will implement their plugin slightly differently and add system specific APIs which deviate rather drastically from the "standard Elasticsearch APIs".

**Comment by JoshMock** [comment]
Closing as stale. Please reopen as needed.
