### ISSUE TITLE
Bulk helper with stream causes memory leak

### ISSUE THREAD

**Issue by JoHuang** [elastic/elasticsearch-js#1229]
## 🐛 Bug Report

I'm using the master branch.
Bulk helper with stream causes memory leak.
The heap memory keeps increasing with the same workload.
Even if I stopped the workload, memory doesn't decrease.

## To Reproduce

```ts
// this file is based on "pino-elasticsearch" 5.1.0
// Original License:
// ----------------------------------------------------------------------------
// The MIT License (MIT)

import * as split from 'split2'
import { Transform } from 'stream'

import { Client, ClientOptions } from '@elastic/elasticsearch'

export interface ElasticStreamOptions {
    esClientOpts: ClientOptions;
    index: string | Function;
    esVersion?: number;
    type?: string;
    flushBytes?: number;
    flushInterval?: number;
}

export function ElasticStream (opts: ElasticStreamOptions): Transform {

  const splitter = split(JSON.parse)

  const client = new Client(opts.esClientOpts)

  const esVersion = opts.esVersion || 7
  const index = opts.index
  const buildIndexName = typeof index === 'function' ? index : null
  function getIndexName (time = new Date().toISOString()): string{
    if (buildIndexName) {
      return buildIndexName(time)
    }
    return typeof index === 'string' ? index : ''
  }

  const type = esVersion >= 7 ? undefined : (opts.type || 'log')
  const b = client.helpers.bulk({
    datasource: splitter,
    flushBytes: opts.flushBytes,
    flushInterval: opts.flushInterval,
    refreshOnCompletion: getIndexName(),
    onDocument (doc: any) {
      return {
        index: {
          _index: getIndexName(doc.time || doc['@timestamp']),
          _type: type
        }
      }
    },
    onDrop (doc) {
      const error = new Error('Dropped document')
      splitter.emit('insertError', error, doc)
    }
  })

  b.then(
    (stats) => splitter.emit('insert', stats),
    (err) => splitter.emit('error', err)
  )

  return splitter
}

```

Usage:
```ts
this.streamToElastic = elasticStream({
      index: (isoTimeString: string) => this.getIndexName(isoTimeString),
      esClientOpts: options,
      esVersion: 7,
    })

// call write to write document
this.streamToElastic.write(JSON.stringify(document) + '\n')

```

<img width="1147" alt="Screen Shot 2020-06-19 at 12 31 38 AM" src="https://user-images.githubusercontent.com/4118159/85047402-5b330c80-b1c4-11ea-8503-93f5319fd18f.png">

## Expected behavior

The heap memory should not increase constantly with the same level workload.

## Your Environment

- *node version*: 12.18.0
- `@elastic/elasticsearch` *version*: master branch
- *os*: Linux (docker container, Node:12-alpine)

## Questions
I'm not sure if the stream usage is correct or not.

I saw the bulk helper document said I can pass array to datasource params.
How can I keep writing data by using array?

**Comment by Marsup** [comment]
Did you ever find a solution to this? I seem to be getting this issue as well even with the latest client.

**Comment by scott-taylor** [comment]
I'm think I'm experiencing this issue as well. Is there a workaround? Does this only occur when using the bulk helper?

**Comment by scott-taylor** [comment]
I found the problem and it wasn't in the elastic client bulk help. In fact, I manage to run a very long bulk job of about 12 hours without any memory issues. In my case I tracked down the issue to the JSONParser I was using to read a json stream. I need to set a property called keepStack to false. Once I did that memory usage was low and steady.
