### ISSUE TITLE
How to change mapping in bulk indexing

### ISSUE THREAD

**Issue by nmdis1999** [elastic/elasticsearch-js#1238]
Hello I am pretty new to elasticsearch and not successful finding documentation or answers which are still working for updating the mapping. I have following file to create index and put accounts.json, client.json and relationship.json which I am indexing in app index via bulk. Now I want to change the type of mapping for field "id", "account_number" and since I cannot do that after creating the index I am not sure how to achieve that.

Here is the code that I am trying:

```js 
//require the Elasticsearch librray
const elasticsearch = require('elasticsearch');
// instantiate an Elasticsearch client
const client = new elasticsearch.Client({
   hosts: [ 'http://localhost:9200']
});
// ping the client to be sure Elasticsearch is up
const accounts = require('./accounts.json');
const clients = require('./client.json');
const relationship = require('./relationship.json')
// declare an empty array called bulk
var bulk = [];
accounts.forEach(account =>{
   bulk.push({index:{ 
                 _index:"app", 
                 _type:"bank",
             }          
         })
  bulk.push(account)
})
clients.forEach(client_data =>{
    bulk.push({index:{ 
                  _index:"app", 
                  _type:"bank",
              }          
          })
   bulk.push(client_data)
 })

 relationship.forEach(relation => {
     bulk.push({index:{
         _index:"app",
         _type:"bank"
     }
    })
    bulk.push(relation)
 })
//perform bulk indexing of the data passed
var body = {
    app: {
        properties: {
          id: {type: 'text'},
          balance: { type: 'text' },
          account_number: { type: 'text' },
          age: {type: 'text'},
          name: {type: 'text'},
          gender: {type: 'text'},
          company: {type: 'text'},
          email: { type: 'text' },
          phone_number: { type: 'text' },
          address: {type: 'text'},
          relations: {
            //type: 'nested',
            properties: {
              id: {type: 'text'},
              name: {type: 'text'}
            }
          }
        }
    }
}
client.bulk({body:bulk}, function( err, response  ){ 
         if( err ){ 
             console.log("Failed Bulk operation", err) 
         } else { 
             console.log("Successfully imported %s", accounts.length+clients.length+relationship.length); 
         } 
}); 
```

**Comment by delvedor** [comment]
Hello!
You are using the legacy client, I strongly recommend to upgrade to the [new one](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/breaking-changes.html) :)
A very good reason for upgrading to the new client is that you can use the [bulk helper](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-helpers.html), which helps you bulk indexing data.

Regarding your mapping issue, you can't change the type of an already existing field, the easiest solution is to create a new index with the correct [mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html) and then use the [reindex](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) API for moving the data to the new index.
If this is a small index and you have all the data in your three json files, you can simply delete the index, create it again with the correct mapping and the bulk index again.

**Comment by nmdis1999** [comment]
Thank you I understand now ^^
