### ISSUE TITLE
Bulk helper update with script doesn't work

### ISSUE THREAD

**Issue by markb-trustifi** [elastic/elasticsearch-js#1244]
## 🐛 Bug Report
Cannot execute `client.helpers.bulk` when updating record by a script.

## To Reproduce
I can update the existing ES record with the script action:
```js
let response = await client.update({
  index: my_index,
   id: my_id,
   body:{
      script: {
         source: "if(!ctx._source.containsKey('my_key')) {ctx._source.my_key = [params.item]} else {ctx._source.my_key.add(params.item)}",
         params: {item:"my_value"}
      }
   }
});
```

When I'm trying to do the same by the Bulk Helper it throws an error:
```js
let response = await client.helpers.bulk({
   datasource: [{
      script: {
         source: "if(!ctx._source.containsKey('my_key')) {ctx._source.my_key = [params.item]} else {ctx._source.my_key.add(params.item)}",
         params: {item:"my_value"}
      }
   }],
   onDocument(doc) {
      return [
         {update: {_index: my_index, _id: my_id}},
         {script: doc.script}
      ];
   }
});
```

The problem is in the explicitly added "doc" parameter in the `iterate()` function in `Helpers.js` file:
```js
payloadBody = typeof chunk === 'string'
            ? `{"doc":${chunk}}`
            : serialize({ doc: chunk, ...action[1] })
```

When I don't specify "doc" at all `{script: doc.script}` or when set it to an empty object `{doc:{}, script: doc.script}`, the ES throws error:
_Validation Failed: 1: can't provide both script and doc;_

and when I set it to NULL `{doc:null, script: doc.script}`, the ES throws error:
_[1:8] [UpdateRequest] doc doesn't support values of type: VALUE_NULL_

## Your Environment

- *node version*: 12
- `@elastic/elasticsearch` *version*: 7.8
- *os*: Mac

**Comment by delvedor** [comment]
Hello, thank you for investigating the issue, you are right!
I'll investigate how to nicely solve this bug, if you would like to take it a stab, feel free to!

**Comment by senatet** [comment]
For anyone wanting to use the bulk helpers for update actions with a script, you can get around the current issue reported in this bug by setting doc to undefined in action[1]. @markb-trustifi 's comment above would work if he had tried:

`{doc: undefined, script: doc.script}`
in onDocument(...). Specifically, this should work while we wait for a fix:
```javascript
let response = await client.helpers.bulk({
   datasource: [{
      script: {
         source: "if(!ctx._source.containsKey('my_key')) {ctx._source.my_key = [params.item]} else {ctx._source.my_key.add(params.item)}",
         params: {item:"my_value"}
      }
   }],
   onDocument(doc) {
      return [
         {update: {_index: my_index, _id: my_id}},
         // merging actions with chunk in iterate() call cause doc to be 
         // removed in bulk-query send to ES.
        {script: doc.script, doc: undefined}  
      ];
   }
});```
