### ISSUE TITLE
Updating document object with post method 

### ISSUE THREAD

**Issue by nmdis1999** [elastic/elasticsearch-js#1246]
Hello again,

I am experimenting more with APIs so sorry if I am making some silly mistakes. I am trying to update the document field with following code (using post method) and it is taking forever (it is not returning anything to postman and keep sending request unless I forcefully stop it) without updating the document.

```
app.post('/update', function(req, res){
  const clientId = req.params.id;
  const clientBody = req.body;
  return client.update({
    index: "first-demo",
    type: "bank",
    id: clientId,
    body: { 
      doc: {
        name: clientBody.name,
        id: clientBody.id,
        age: clientBody.age,
        gender: clientBody.gender,
        isAlive: false
      }
    }}).then(results => {
      logger.info(results);
      res.status(200).json({
        message: "OK"
      });
    }).catch(err => {
      logger.error(err);
      res.status(500).json({
        error: "Internal server error"
      });
    });
});
```

The data I am sending:
```
{
     "name": "Iti",
     "age": "21",
     "gender": "female",
     "id": "720"
}
```

**Comment by delvedor** [comment]
Hello, there are no silly questions! :)
Which version of the library. are you using? And which version of Elasticsearch?

Furthermore, it looks like you are using Express.js, which does not support promises natively. I would recommend either using the callback API of the client or remove the `return` statement, which might cause some problems.

**Comment by nmdis1999** [comment]
I am using elasticsearch 7.7.1 and express 4.17.1. I tried removing the return statement however, it is still not updating the document or throwing error.
I have following data in index "first-demo" 
```
[
    {
        "_index": "first-demo",
        "_type": "bank",
        "_id": "UBZIDnMBsH4jTafHKOeI",
        "_score": 3.3625417,
        "_source": {
            "name": "Iti Shree",
            "age": "21",
            "gender": "female",
            "id": "720"
        }
    }
]
```

Say I want to change the name field only to "Iti" instead. but when I am passing the above json object it is either not updating the field or goes into recursion (doesn't exit the code)

**Comment by delvedor** [comment]
Which client are you using? The one you install with `npm i elasticsearch` or `npm i @elaatic/elasticsearch`?
From version 7 of Elasticsearch, you don't need to specify a type, as types are [no longer supported](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html).

Can you create a small example to reproduce the problem? eg:
```
require the client
instantiate the client
index a document
update it
```

[Here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/update_examples.html) you can see how to send an update request.

**Comment by nmdis1999** [comment]
Currently I am using the one installed with npm i elasticsearch

**Comment by delvedor** [comment]
I strongly recommend you to use the one you can install with `npm i @elastic/elasticsearch`, the other one will be deprecated in the future.

**Comment by nmdis1999** [comment]
Thanks @delvedor actually I am making a demo using it and since I already wrote most of the stuff using legacy (I wasn't aware of the changes then) I thought of continuing the demo in it. I am however, reading the documentations and implementation of the latest version.

Regarding the code. I tried following snippet.
```
app.post('/update/:id', function(req, res){
  var resource = {
    script: {
      source: 'ctx._source.name = "Iti Shree"'
    }
  }
var param = {index: 'first-demo', type: 'bank', id: req.params.id, body: resource};
  console.log("Modifying resource:", req.params.id, resource);
  client.update(param, function(error, response) {
    res.send(response);
  });
```

but it gives following error:
```
{
    "error": {
        "root_cause": [
            {
                "type": "x_content_parse_exception",
                "reason": "[1:48] [script] unknown field [value]"
            }
        ],
        "type": "x_content_parse_exception",
        "reason": "[1:56] [UpdateRequest] failed to parse field [script]",
        "caused_by": {
            "type": "x_content_parse_exception",
            "reason": "[1:48] [script] unknown field [value]"
        }
    },
    "status": 400
}
```

However when I try this:
```
app.post('/update/:id', function(req, res){
  var resource = {
    script: {
      source: 'ctx._source.name = "Iti Shree"',
    }
  }
  var param = {index: 'first-demo', type: 'bank', id: req.params.id, body: resource};
  console.log("Modifying resource:", req.params.id, resource);
  client.update(param, function(error, response) {
    res.send(response);
  });
});
````

It works fine. I wanted to assign changes from the body I am sending via POST request.

**Comment by nmdis1999** [comment]
Update: I was making not sending JSON file by Postman (I don't know how I didn't check it twice) It's working fine now. I also found this snippet is also working. Thanks a lot @delvedor . 
```
app.post('/update/:id', function(req, res){
  var resource = {
    doc: {
      name: req.body.name,
      age: req.body.age,
      gender: req.body.gender,
      id: req.body.id
    }
  }
  var param = {index: 'first-demo', type: 'bank', id: req.params.id, body: resource};
  console.log("Modifying resource:", req.params.id, resource);
  client.update(param, function(error, response) {
    res.send(response);
  });
});
```

PS after demo I'll completely migrate to using new changes ^^

**Comment by delvedor** [comment]
Glad you were able to sort it out!
