### ISSUE TITLE
How to delete, update specific record inside a specific type

### ISSUE THREAD

**Issue by Chathula** [elastic/elasticsearch-js#1270]
## 💬 Questions and Help

hello, I am using elastic search 5.6 server. I need to delete and update a specific record using NodeJS client.

the record exists inside an index called `search` and inside that, there are 2 types. let say `test1` and `test2`. how can I delete or update a specific record(document) under `test1` type or `test2` type.

Thank You,
Chathula

**Comment by delvedor** [comment]
Hello! For deleting a document you should use the `delete` API:
```js
await client.delete({
  index: 'search',
  type: 'test1',
  id: 'document-id'
})
```

Similarly, for updating a document:
```js
await client.update({
  index: 'search',
  type: 'test1',
  id: 'document-id',
  body: {
    // https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-update.html
  }
})
```
