### ISSUE TITLE
Install package with NPM failed

### ISSUE THREAD

**Issue by Nogias9x** [elastic/elasticsearch-js#1277]
## 🐛 Bug Report

Cannot install `@elastic/elasticsearch` with NPM .

## To Reproduce

1. `npm i @elastic/elasticsearch` or `npm i @elastic/elasticsearch@7.7.1`
2. See error: 
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@elastic%2felasticsearch - Not found
npm ERR! 404 
npm ERR! 404  '@elastic/elasticsearch@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

## Expected behavior

The package should be installed successfully.

## Your Environment

- *node version*: v12.16.3
- `@elastic/elasticsearch` *version*: =@latest=7.8.0
- *os*: Ubuntu 18.04
- *any other relevant information*: 
1. Also failed in docker container of `node:12-slim`
2. I tried `npm cache clean --force` but no luck
3. I tried `npm set registry https://registry.npmjs.org/` but no luck as well

**Comment by shamimmirzai** [comment]
I am having this problem as well.

**Comment by delvedor** [comment]
I just tried both your commands and the installations worked, it looks like npm is having an outage.

https://status.npmjs.org/

**Comment by Nogias9x** [comment]
Seems you are right @delvedor 

Thank you so much
