### ISSUE TITLE
asyncSearch get returns irrelevant results

### ISSUE THREAD

**Issue by lizozom** [elastic/elasticsearch-js#1280]
There's an issue with the implementation of the `elasticsearch` client's `asyncSearch.get` endpoint, that is used to fetch the data from a running async search.

Instead of returning the data from the `asyncId`, it seems to return a list of unrelated async search IDs from the `.async-search` index.

This behavior can be reproduced by using [this PR](https://github.com/elastic/kibana/pull/74529) and going to discover.
Same code works correctly if I use the new ES client with a transport request, instead of the asyncSearch one.

![image](https://user-images.githubusercontent.com/3016806/90031155-94b85d80-dcc5-11ea-9643-15fda063c259.png)

**Comment by delvedor** [comment]
Hello! Can you please create a snippet of code that just uses the client that reproduces the issue?

**Comment by lizozom** [comment]
I just created a [PR](https://github.com/elastic/kibana/pull/76872) to use the new `asyncSearch` endpoints, so I'm closing the issue.

The problem was that due to a badly formatted request, I was running a "SELECT ALL" query.
Coincidentally, data from the `.async-search` index is returned first, resulting in this weird behavior.
As soon as I fixed the query, everything works as expected.
