### ISSUE TITLE
Add type commonjs to package.json

### ISSUE THREAD

**Issue by delvedor** [elastic/elasticsearch-js#1281]
As suggested in the [ESM](https://nodejs.org/api/esm.html#esm_package_json_type_field) guidelines of Node.js it would be good to explicit the type of the module.

```diff
{
+  "type": "commonjs",
}
```

**Comment by RinkiyaKeDad** [comment]
Hi! I'm new to elastic search and will like to work on this issue. Could you point me in the right direction? As far as I understand I need to add this line in the package.json right?
