### ISSUE TITLE
Add a type for a search error response

### ISSUE THREAD

**Issue by lizozom** [elastic/elasticsearch-js#1287]
The Elasticsearch client needs a type representing an ES error.
It would be amazing to also have a type guard `isElasticseachError`, that accepts either a `SearchResponse` or a `ErrorResponse` and returns true if it's an error.

A standard response looks like this:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parsing_exception",
        "reason" : "Unknown order direction [xxx]",
        "line" : 7,
        "col" : 16
      }
    ],
    "type" : "x_content_parse_exception",
    "reason" : "[7:16] [terms] failed to parse field [order]",
    "caused_by" : {
      "type" : "parsing_exception",
      "reason" : "Unknown order direction [xxx]",
      "line" : 7,
      "col" : 16
    }
  },
  "status" : 400
}
```

It can be generated by running the following command in DevTools:

```
GET kibana_sample_data_logs/_search
{
  "aggs": {
    "2": {
      "terms": {
        "field": "machine.os.keyword",
        "order": {
          "1": "xxx"
        }
      }
    }
  }
}

```

**Comment by delvedor** [comment]
I fear I'm missing something, the errored and normal response are already separated in the client API:
```js
// callback API
client.search({ ... }, (err, result) => {
  if (err) {

  } else {

  }
})

// promise API
client.search({ ... })
  .then(result => {})
  .then(catch => {})
```

Or do you mean a property on the error instance that tells you if the error has been generated in the client or by ES?

**Comment by rylnd** [comment]
@lizozom correct me if I'm conflating multiple issues, but I think the use of the `ignore` option is one use case here: if an error is returned but "ignored," the error response follows the normal response path but does not match the `SearchResponse` type. A type guard would allow us to catch this at runtime. A union response type seems burdensome to the consumer, while a conditional response type based on the request options would be ideal.

**Comment by lizozom** [comment]
As far as I remember, @delvedor and I talked and he mentioned that at the moment, the new Elasticsearch Client doesn't provide types for responses at all. Figures that the types we're using are still from the legacy package. (Hope I remember correctly)

**Comment by delvedor** [comment]
> at the moment, the new Elasticsearch Client doesn't provide types for responses at all.

Correct.

>  if an error is returned but "ignored," the error response follows the normal response path but does not match the SearchResponse type.

Also correct.

I'm not sure how this could be solved nicely.

**Comment by lizozom** [comment]
I'm fine with closing it and \ or waiting until the new client provides types :woman_shrugging:
