### ISSUE TITLE
Max connection pool size

### ISSUE THREAD

**Issue by HayDegha0917** [elastic/elasticsearch-js#1288]
## 💬 Questions and Help

There does not seem to be an option to limit the size of the client connection pool. If requests are not completed fast enough, this can cause open connections to increase until the client runs out of file descriptors. At that point, even if the number of concurrent requests decreases, it may be a while before the client recovers since, in addition, there also does not appear to be a parameter that controls how long connections are kept open.

Of course I can customize the connection pool class, but my question goes to the out-of-the-box behavior.

Am I correct or am I missing something?

### Please note that this issue tracker is not a help forum and this issue may be closed.

It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Comment by delvedor** [comment]
> There does not seem to be an option to limit the size of the client connection pool.

The client connection pool can hold the same number of Nodes that the cluster has.
For example, if the Elasticsearch cluster has 10 nodes, then the connection pool will have between 1 and 10 nodes, based on the client configuration.

> If requests are not completed fast enough, this can cause open connections to increase until the client runs out of file descriptors.

With connections, I guess you mean sockets. Each connection can open multiple sockets (to the same ES node), by default up to 512. You can change this default with the [`agent` option](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-configuration.html).
How many requests per second are you sending?

> in addition, there also does not appear to be a parameter that controls how long connections are kept open.

You can change the defaults with the [`agent` option](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-configuration.html).
Following, the default values, which should work for the vast majority of the cases:
https://github.com/elastic/elasticsearch-js/blob/02ed45f76bc292b60aa2264ebbe56122fd7c61a6/lib/Connection.js#L60-L66

**Comment by HayDegha0917** [comment]
Yeah it took me a moment to figure out that "connection pool" is a misnomer.

Since we are using AWS ES, we changed our code to just connect to the cluster endpoint, which should distribute among the nodes using its internal load balancing algorithm.
