### ISSUE TITLE
Timeout when using javascript API

### ISSUE THREAD

**Issue by realworld666** [elastic/elasticsearch-js#1292]
## 💬 Questions and Help

I'm running an elasticsearch server on a Google Compute Engine instance. I haven't set up any authentication or users yet. I'm getting a timeout when using the javascript API in a node project but I can POST and GET to the same URL without any issues.

This is the code I'm running:

```
const client = new Client({
  node: 'http://MYSERVERIP:9200',
  maxRetries: 5,
  requestTimeout: 6000,
  sniffOnStart: true
});

client.ping({}, { requestTimeout: 20000 }, (err, response) => {
  if (err) {
    console.log(err);
  } else {

   doThings().catch(console.log);;
  }
});

async function doThings() {
const indexResult = await client.indices.create({
        index: 'organisations',
        body: {
          mappings: {
            properties: {
              id: { type: 'text' },
              title: { type: 'text' },
              name: { type: 'text' },
              description: { type: 'text' },
              accessCodes: { type: 'keyword' }
            }
          }
        }
      }, { ignore: [ 400 ] }, (err, { body }) => {
        if (err) {
          console.log(err);
        }
      });
      console.log(indexResult);
}
```

The ping works fine but creating an index causing a timeout error. Am I doing something fundamentally wrong?

**Comment by realworld666** [comment]
Further debugging reveals that my external static IP is being changed into the local private IP in the 10.x range before it starts the request. I don't know what to do about that

**Comment by delvedor** [comment]
I think that the `sniffOnStart` option is causing some issue, as very likely Elasticsearch lives in a different network, and it's returning completely useless IP addresses to the client, causing the failure.
I recommend you to read [this blog post](https://www.elastic.co/blog/elasticsearch-sniffing-best-practices-what-when-why-how) which should help to understand the best configuration for your use case :)

**Comment by realworld666** [comment]
Yes. That was exactly the problem. Thank you

>
