### ISSUE TITLE
Decompress-response version seems to be causing failures

### ISSUE THREAD

**Issue by vnenkpet** [elastic/elasticsearch-js#1298]
I suppose this should actually be tested, fixed and merged:

https://github.com/elastic/elasticsearch-js/pull/1196

We are using some other dependency which has decompress-response@6.0.0 (got) and it seems to be the likely cause of our service crashing when it's called. 

![スクリーンショット 2020-09-02 11 02 07](https://user-images.githubusercontent.com/1933654/91961645-bed0ce80-ed0b-11ea-83aa-1988aa148d37.png)

**Comment by delvedor** [comment]
We can't update `decompress-response` to the latest major, as we need to support Node 8+.
I doubt the reason that your service if failing is `decompress-response`. What is suggesting to you that?
