### ISSUE TITLE
Trying to use in Nuxt application gives node version undefined error

### ISSUE THREAD

**Issue by easherma** [elastic/elasticsearch-js#1317]
This line: https://github.com/elastic/elasticsearch-js/blob/26238634a71d26ef3b7852adbdadda7b6328e79d/index.js#L22
Gives me this error:
`client.js?06a0:97 TypeError: Cannot read property 'split' of undefined`

Now in some ways, I think this issue is more on the Nuxt side of things. It's possible it may be trying to run the code client-side where the node version doesn't exist (this is my hunch). 

However, looking at the source code, it looks like nodeMajor is mainly just used to figure out if some helper libraries can be imported. 
I think we might be able to implement some better handling to make this a bit less painful? As is, the undefined error is preventing Nuxt from running my app properly on the page where I'm trying to use the client.

**Comment by delvedor** [comment]
Hello! The browser environment is [not supported](https://github.com/elastic/elasticsearch-js#browser), nor tested.

**Comment by easherma** [comment]
Appreciate the link! I think this is a misunderstanding. I am not trying to run it on the browser. I want to use the client as part of the server-side rendering abilities of nuxt.

**Comment by delvedor** [comment]
If you are running the client in Node.js, the `process.versions` should always be defined. 🤔
Can you give me some additional info about the Node.js version and platform?
Is this happening every time or only during testing?

**Comment by SomethingNew71** [comment]
I am also encountering this issue while using the `serverMiddleware` property in NuxtJS. According to the NuxtJS documentation, this allows the developer to create files that will do the following:

> Middleware listed in the `serverMiddleware` property runs server-side before `vue-server-renderer` and can be used for server-specific tasks like handling API requests or serving assets.
More info: [serverMiddleware](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-servermiddleware/)

So this is running server-side within the node environment however it's still causing this error:
```
client.js?06a0:97 TypeError: Cannot read property 'split' of undefined
    at Object.eval (index.js?7080:22)
    at eval (index.js:330)
    at Object../node_modules/@elastic/elasticsearch/index.js
```

Node Version I am experiencing this in is `14.12.0`
