### ISSUE TITLE
searchScroll helper don't clear the scroll cursor after looping over all documents

### ISSUE THREAD

**Issue by abarre** [elastic/elasticsearch-js#1321]
## 🐛 Bug Report

After the [searchScroll](https://github.com/elastic/elasticsearch-js/blob/7b11152a128525644208b317ed073c2a38353062/lib/Helpers.js#L73) has loop over all documents, the scroll cursor is not released.

The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-scroll.html#_clear_scroll_api) states : 

> Search context are automatically removed when the scroll timeout has been exceeded. However keeping scrolls open has a cost, as discussed in the previous section so scrolls should be explicitly cleared as soon as the scroll is not being used anymore using the clear-scroll API

Current behavior leak the search context for the scroll window (1 minute by default).

## Expected behavior

After this [while loop](https://github.com/elastic/elasticsearch-js/blob/7b11152a128525644208b317ed073c2a38353062/lib/Helpers.js#L106), I think that there is a missing await clear(): 

```diff 
while (response.body.hits && response.body.hits.hits.length > 0) {
...
}
+ await clear();
```

I will be happy to make a PR if the expected behavior is confirmed.

## Your Environment

- `@elastic/elasticsearch` *version*: 7.9.1

**Comment by delvedor** [comment]
Hello! You are right, great catch!

> I will be happy to make a PR if the expected behavior is confirmed.

Please do! Remember to update the test as well, thanks!

**Comment by abarre** [comment]
Hi @delvedor, 

when do you plan to release a patch version with this fix for the branch 7.x ?

Thanks
