### ISSUE TITLE
How to resolve `Result window is too large` problem with elasticsearch-js?

### ISSUE THREAD

**Issue by brick9527** [elastic/elasticsearch-js#1323]
## 💬 Questions and Help

When I query a list more than 10000 items, ES will throw this error:

```bash
Result window is too large, from + size must be less than or equal to: [10000] but was [66700]. See the scroll api for a more efficient way to request large data sets. 
This limit can be set by changing the [index.max_result_window] index level setting. 
Error: [query_phase_execution_exception] Result window is too large, from + size must be less than or equal to: [10000] but was [66700]. 
See the scroll api for a more efficient way to request large data sets.
This limit can be set by changing the [index.max_result_window] index level setting.
```

I search the resolution of this problem:

```bash
PUT policy_document/_settings
{
  "index":{
    "max_result_window":1000000
  }
}
```
It means every time I deploy my app, I will repeat this operation.

So I want to resolve this problem with `elasticsearch-js`, that my app could configure this value automatically.

Is there any way to resolve it?

**Comment by delvedor** [comment]
Hello!
I would highly recommend following the error suggestion, so using the [scroll API](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/paginate-search-results.html#scroll-search-results). The client offers a [helper method](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-helpers.html#_scroll_search_helper) to aid you using this API.

**Comment by AnjumShehzad7** [comment]
Hi, I wanted to know if I can directly change the ```max_result_window``` value from kibana. As I have a million records that my application is fetching from Elasticsearch. I can not run the query on the daily basis. Also, tell me the maximum value that I can give in ```max_result_window```.

**Comment by brick9527** [comment]
已经收到邮件。我会尽快回复的。
