### ISSUE TITLE
Client#constructor's agent function doesn't designate the protocol

### ISSUE THREAD

**Issue by kobelb** [elastic/elasticsearch-js#1330]
Currently, the `Client#constructor` allows the `agent` option to specify a function that returns an agent. However, when the `agent` function is called, it has no arguments, so it's not possible to determine whether or not a `http.Agent` or ` https.Agent` should be returned.

I'd like to use this in Kibana, to ensure that all instances of the Client share an Agent, when possible, to efficiently reuse sockets. However, Kibana allows users to specify both HTTP and HTTPs nodes, so an Agent itself can't be passed into the `Client#constructor`. 

The legacy elasticsearch-js client is providing an instance of the `HttpConnector` as the first argument to the `createNodeAgent` function, which makes this possible.

**Comment by delvedor** [comment]
Hello! We can add this, but if in Kibana you are using the `child` method, then the connection pool is shared among all child clients, which means that all of them will reuse the same sockets :)

**Comment by kobelb** [comment]
`Client#child` reusing the same connection pools is super helpful; however, it doesn't fully address our needs in Kibana, at this point in time. 

At the moment, we're in the process of transitioning from the legacy ES client to your awesome new one. During this interim period, Kibana is communicating with the same ES hosts using the legacy and new Client, so ideally we'd reuse the sockets for all of these HTTP requests. Once Kibana transitions to only using the new Client, this won't be a problem any longer.
