### ISSUE TITLE
Proper way to handle external versioning on Update

### ISSUE THREAD

**Issue by maganap** [elastic/elasticsearch-js#1337]
### Please note that this issue tracker is not a help forum and this issue may be closed.

This is a reference to my [StackOverflow question](https://stackoverflow.com/questions/64326338/proper-way-to-handle-external-versioning-with-node-client-update) which doesn't have an answer, so I need to ask here. I hope you can help.

**Scenario:**

We're synching part of our Firestore database to an ElasticSearch instance. **We're using external versioning** with some timestamp in milliseconds as version number.

**What we're doing:**
- When a new document is created in Firestore, or when we need to completely overwrite a document, we're synching by calling the **INDEX API**, which works as expected.
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_index
Note it does include parameters for `version` and `version_type` (which we're setting as `external`).
- When we only need to update a specific field, we're calling the **UPDATE API**:
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_update
We expected it to include `version` and `version_type` as well, but it **does not** include those parameters. Not setting external versioning is causing the call to return an error:

    `Validation Failed: 1: internal versioning can not be used for optimistic concurrency control. Please use if_seq_no and if_primary_term instead`

**The problem:**

We don't have `seq_no` nor `primary_term` at hand. We're counting on optimistic concurrency control based on external versioning by the Firestore update timestamp in milliseconds.

The specific field to update is a calculation that's not even part of the original document in Firestore, so simply overwriting the whole document to ES every time is not an option. We do need to update only one field in ES.

**And... the questions:**

- Why doesn't the **update API** include `version` and `version_type`? Maybe we're missing something about the concept and this is not the correct approach at all.
- If `version` and `version_type` are out of the **update API** on purpose... what could be the correct approach for this situation? Since we're using external versioning, `seq_no` and `primary_term` were not supposed to be relevant. Saving information back to Firebase from ES is just cumbersome for what we need.

The client is @elastic/elasticsearch: 7.9.0 in Node, in case that matters.

Thank you very much in advance.

**Comment by JerryChin** [comment]
I have the exact same problem as you @maganap did you manage to solve it, please share if you could! thanks.

**Comment by maganap** [comment]
@JerryChin I'm sorry you got into this same issue because I couldn't solve it and ended up changing the data model. I replied to you in SO https://stackoverflow.com/questions/64326338/proper-way-to-handle-external-versioning-with-node-client-update?noredirect=1#comment130494119_64326338

**Comment by aman199002** [comment]
I am facing exactly same problem. We need to update our index as its being updated from 2 different sources so complete document cant be reindexed. Please inform if there is any way to update the same with external version or some other way without fetching the document again?

**Comment by maganap** [comment]
@aman199002 No that I know of. In our latest projects we've designed database structure and procedures to avoid the need of partial update just because we didn't find a way to solve it (at that moment at least, not sure of the newest versions of ES)
