### ISSUE TITLE
Bulk helper bug -- duplicating data

### ISSUE THREAD

**Issue by thekofimensah** [elastic/elasticsearch-js#1339]
## 🐛 Bug Report

We’re currently trying to send 100k events to elastic search using the bulk helper and we’re running into a strange bug. We find that 200k-400k events get posted to ES and it exits on a Timeout but our original file is only 100k long (so we’re seeing lots of duplicates).

We don’t really know why this is happening and we don’t really trust the client because it is duplicating on such a massive scale. Any ideas why this is happening? We'd prefer to use the bulk client than our manual poster, but this issue is quite concerning.

## To Reproduce

Paste your code here:

```js
const { createReadStream } = require('fs')
const split = require('split2')
const { Client } = require('@elastic/elasticsearch')

const client = new Client({ node: '<elasticcloud-ip>' })
const result = await client.helpers.bulk({
  datasource: createReadStream('./dataset.ndjson').pipe(split()),
  onDocument (doc) {
    return {
      index: { _index: 'test' }
    }
  }
})

console.log(result)

```

We're sending 100k lines of ndjson that look like this:
```{"date":"2020-05-28","time":"15:19:43","domain":"github.com","categories":"Big","user":"tester","company":"0","company_title":"0"}```

The data goes through a simple ingest pipeline.

## Your Environment

- *node version*: 14
- `@elastic/elasticsearch` *version*: 7.9.3
- *os*: Mac

**Comment by delvedor** [comment]
Hello! Can you provide an example to reproduce your issue?
I've just run your code and I'm getting the expected result.

Furthermore, as you can see in the following test, the client is indexing exactly the number of documents you are expecting.

https://github.com/elastic/elasticsearch-js/blob/87805fc17f03859b87de94cedcd9701a96b257bc/test/integration/helpers/bulk.test.js#L44-L71

**Comment by yukha-dw** [comment]
any update on this issue? I have same issue on WSL2 but not reproducible in native Linux

**Comment by yukha-dw** [comment]
@JoshMock it's exactly like @thekofimensah code. In my experience, the issue only happens on denser data
