### ISSUE TITLE
Responses that are too big cannot be handled gracefully

### ISSUE THREAD

**Issue by diegomansua** [elastic/elasticsearch-js#1347]
Hello,

## 🐛 Bug Report

Maybe not really a bug but an improvement.

The response of a query that is too big for the Node process to handle will result in an uncaught exception.

This line: https://github.com/elastic/elasticsearch-js/blob/v7.9.1/lib/Transport.js#L204

concatenates the response chunks. The problem is that the response is too big (due to the application running a "bad" query or the index containing "bad" data that is too large) this concatenation will result in a `RangeError: Invalid string length` that cannot be handled by the application other than with Node's `uncaughtException` handler, where any context is lost (not possible to know which query caused it).

## To Reproduce

Run a standard query that returns a lot of data.

## Expected behavior

I think the client should handle `RangeError`s in the `'data'` handler when the response is being concatenated, which would then cause a promise rejection with a proper `ElasticsearchClientError` error (with context about the query etc.) that the app can handle normally (handling the `search` promise rejection).

## Your Environment

- *node version*: 14.9
- `@elastic/elasticsearch` *version*: 7.3.0
- *os*: Mac, Linux

**Comment by delvedor** [comment]
Hello! The maximum string size for Node.js is around 512MB.
I'll open a pr to check the `Content-Length` header and throw a better error so this issue can be easily solved.
Meanwhile, you could try to decrease the number of documents returned by each search (with the `size` parameter), and then use the [scroll search helper](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-helpers.html#_scroll_search_helper) for reading the docuemnts.
I would also recommend redesigning your ingestion phase :)

**Comment by diegomansua** [comment]
@delvedor Thanks a lot.

Yes the root issue was definitely an application one, no question about it. We had some documents that were much bigger than expected (caused by a different issue), but the ES client made it very difficult/nearly impossible to know where the root cause was (as in, which query was failing), as it was causing an unhandled rejection where all context was lost, we literally had to resort to edit the client's source code (in prod!) to wrap the `payload += chunk` line into a `try-catch` to at least identify which query was the culprit (as we run dozens of different ones).
