### ISSUE TITLE
.gitignore configuration

### ISSUE THREAD

**Issue by robertosousa1** [elastic/elasticsearch-js#1360]
In the current configuration of .gitignore it is preventing the commit with the package-lock.json file, however it should be in the commit.

> The package-lock. json file needs to be committed to your Git repository, so it can be fetched by other people, if the project is public or you have collaborators, or if you use Git as a source for deployments. The dependencies versions will be updated in the package-lock. json file when you run npm update

https://flaviocopes.com/package-lock-json/#:~:text=system%20for%20years.-,The%20package%2Dlock.,when%20you%20run%20npm%20update%20.

https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by delvedor** [comment]
Hello! The `package-lock.json` should be used only when creating applications, for libraries it should never be committed. In this way, the CI will always pick up the last update in the dependencies and error if there is something wrong.
