### ISSUE TITLE
Add async_search/status  API to the JS client

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch-js#1368]
For example client.asyncSearch.status(id)

Corresponding issue for elasticsearch API: https://github.com/elastic/elasticsearch/pull/62947
Corresponding issue for Java client: https://github.com/elastic/elasticsearch/issues/65919

**Comment by delvedor** [comment]
The API is already present in 7.x but not yet published on npm. It will happen as soon as #1338 lands.
Closing for now, feel free to reopen :)
