### ISSUE TITLE
socket hang up on bulk update

### ISSUE THREAD

**Issue by Delagardi** [elastic/elasticsearch-js#1369]
## 🐛 Bug Report

Hi, I am not sure is this bug or my local problem. I tried all solutions that I found in Google, in docs and on this Github but nothing helps me. I trying to fix it couple of days in a row. 

I am getting docs from other API, preparing data (need to do couple request to DB) and then pass it to bulk update function.
I am trying to make bulk update for ~15000 docs, but for now I understand that even one doc could not be updated by me.

My elastic init:
```
import elasticsearch from 'elasticsearch';

export const client = new elasticsearch.Client({
  host: 'http://localhost:9200',
  log: 'error',

  // tryed this, not helped
  // requestTimeout: 180000,
  // keepAlive: false, 
  // agent: false,
});
```
My bulk update:
```
static readonly bulkUpdate = (flatMap) => {
    return client.bulk({
      refresh: true,
      body: flatMap,
      // this option not help too:
      // refresh: 'wait_for',
    })
  }
```
Flat Map example:
```
 [ { 
    update: { 
       _index: 'myindex',
       _type: 'myindex',
       _id: '5c9d59b89d75b7559b8a3482' 
    } 
  },
  { 
    doc: { inStockWarehouse: 0 }  // partial update
} ]
```

I am always getting errors. For example,  it I get this error:
```
 { StatusCodeError: Request Timeout after 30000ms
    at E:\Work\eze.tech\swag\swag-app\node_modules\elasticsearch\src\lib\transport.js:354:15
    at Timeout.<anonymous> (E:\Work\eze.tech\swag\swag-app\node_modules\elasticsearch\src\lib\transport.js:383:7)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
  status: undefined,
  displayName: 'RequestTimeout',
  message: 'Request Timeout after 30000ms',
  body: undefined }

```

if I use `requestTimeout: 180000` option, I get this error:
```
Error: Request error, retrying
 POST http://localhost:9200/_bulk?refresh=wait_for => socket hang up
```
I tried to increase it to 660000 (11 min) but the result was the same

Trying to update all docs one by one, but there was this errors too. I worked on this couple of days and for now I am lack of ideas. 

## Expected behavior
I want to update all my docs in index. All in one chunk ~15000 and could be increased or by smaller chunks by 1000. 

## Your Environment

- *node version*: 11
- `@elastic/elasticsearch` *version*: >=14.0.0
- *os*: Windows,
- *any other relevant information*

**Comment by delvedor** [comment]
Hello! For updating many documents in an index it is better to use the [update by query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html) API.
Furthermore, I highly recommend you to use the [`@elastic/elasticsearch`](https://www.npmjs.com/package/@elastic/elasticsearch), as `elasticsearch` will be deprecated in the future.
