### ISSUE TITLE
client.scroll -> Timeout

### ISSUE THREAD

**Issue by ttessarolo** [elastic/elasticsearch-js#1371]
Add to client.scroll()  a timeout options.

Is that any reason why it doesn't?

**Comment by delvedor** [comment]
Hello! The Elasticsearch API does not have a timeout for the scroll endpoint, but you can still use the client timeout option:
```js

const result = await client.scroll(
  { scroll: '30s', body: { scroll_id: '<id>' } },
  { requestTimeout: 30000 }
)
```
