### ISSUE TITLE
Q: Why is id required on client.create(), but not on client.bulk?

### ISSUE THREAD

**Issue by joshxyzhimself** [elastic/elasticsearch-js#1372]
Q: Why is id required on client.create(), but not on client.bulk()?

On `client.bulk` it allows us to use `create` operations where ES creates the `document._id` part, but on `client.create` we are getting the following:

```js
await elasticsearch.client.create({
  index: example_document._index,
  body: example_document._source,
});
```

```
ConfigurationError: Missing required parameter: id
    at Client.createApi [as create] (/home/user/Documents/project/node_modules/@elastic/elasticsearch/api/api/create.js:34:17)
```

## Your Environment

- `node` : `v14.4.0`
- `@elastic/elasticsearch` : `^7.10.0`
- `os` : `linux`

**Comment by delvedor** [comment]
It's not required in the bulk API as you can create a datastream as "append only" ops, which need to use the bulk create without an id.
But as a general rule, always use an id when using create.
