### ISSUE TITLE
Request timed out

### ISSUE THREAD

**Issue by ghost** [elastic/elasticsearch-js#1380]
Hey,

I'm trying to use this client.

First of all,  I tried to copy the example on the main page of the repository and run it.

The example is on README with the title "Let's see a complete example!".

The client is looking nicely:

`Client {
  name: 'elasticsearch-js',
  serializer: Serializer {},
  connectionPool: ConnectionPool {
    connections: [ [Object] ],
    size: 1,
    Connection: [class Connection] {
      statuses: [Object],
      roles: [Object],
      internals: [Object]
    },
    emit: [Function: bound emit],
    auth: null,
    _ssl: null,
    _agent: null,
    _proxy: null,
    dead: [],
    resurrectTimeout: 60000,
    resurrectTimeoutCutoff: 5,
    pingTimeout: 3000,
    _sniffEnabled: false,
    resurrectStrategy: 1
  },
  transport: Transport {
    emit: [Function: bound emit],
    connectionPool: ConnectionPool {
      connections: [Array],
      size: 1,
      Connection: [Function],
      emit: [Function: bound emit],
      auth: null,
      _ssl: null,
      _agent: null,
      _proxy: null,
      dead: [],
      resurrectTimeout: 60000,
      resurrectTimeoutCutoff: 5,
      pingTimeout: 3000,
      _sniffEnabled: false,
      resurrectStrategy: 1
    },
    serializer: Serializer {},
    maxRetries: 3,
    requestTimeout: 30000,
    suggestCompression: false,
    compression: false,
    context: null,
    headers: {
      'user-agent': 'elasticsearch-js/7.10.0 (win32 10.0.18363-x64; Node.js v14.15.2)'
    },
    sniffInterval: false,
    sniffOnConnectionFault: false,
    sniffEndpoint: '_nodes/_all/http',
    generateRequestId: [Function: genReqId],
    name: 'elasticsearch-js',
    opaqueIdPrefix: null,
    nodeFilter: [Function: defaultNodeFilter],
    nodeSelector: [Function: _roundRobinSelector],
    _sniffEnabled: false,
    _nextSniff: 0,
    _isSniffing: false
  },
  helpers: Helpers {
    maxRetries: 3,
    [Symbol(elasticsearch-client)]: [Circular *1]
  },
  [Symbol(configuration error)]: [class ConfigurationError extends ElasticsearchClientError],
  [Symbol(Cat)]: null,
  [Symbol(Cluster)]: null,
  [Symbol(DanglingIndices)]: null,
  [Symbol(Indices)]: null,
  [Symbol(Ingest)]: null,
  [Symbol(Nodes)]: null,
  [Symbol(Snapshot)]: null,
  [Symbol(Tasks)]: null,
  [Symbol(AsyncSearch)]: null,
  [Symbol(Autoscaling)]: null,
  [Symbol(Ccr)]: null,
  [Symbol(Enrich)]: null,
  [Symbol(Eql)]: null,
  [Symbol(Graph)]: null,
  [Symbol(Ilm)]: null,
  [Symbol(License)]: null,
  [Symbol(Migration)]: null,
  [Symbol(Ml)]: null,
  [Symbol(Monitoring)]: null,
  [Symbol(Rollup)]: null,
  [Symbol(SearchableSnapshots)]: null,
  [Symbol(Security)]: null,
  [Symbol(Slm)]: null,
  [Symbol(Sql)]: null,
  [Symbol(Ssl)]: null,
  [Symbol(Transform)]: null,
  [Symbol(Watcher)]: null,
  [Symbol(Xpack)]: null,
  [Symbol(elasticsearchjs-initial-options)]: {
    Connection: [class Connection] {
      statuses: [Object],
      roles: [Object],
      internals: [Object]
    },
    Transport: [class Transport] { sniffReasons: [Object], internals: [Object] },
    Serializer: [class Serializer],
    ConnectionPool: [class ConnectionPool extends BaseConnectionPool] {
      resurrectStrategies: [Object]
    },
    maxRetries: 3,
    requestTimeout: 30000,
    pingTimeout: 3000,
    sniffInterval: false,
    sniffOnStart: false,
    sniffEndpoint: '_nodes/_all/http',
    sniffOnConnectionFault: false,
    resurrectStrategy: 'ping',
    suggestCompression: false,
    compression: false,
    ssl: null,
    agent: null,
    headers: {},
    nodeFilter: null,
    nodeSelector: 'round-robin',
    generateRequestId: null,
    name: 'elasticsearch-js',
    auth: null,
    opaqueIdPrefix: null,
    context: null,
    proxy: null,
    node: 'http://localhost:9200'
  },
  [Symbol(elasticsearchjs-extensions)]: [],
  [Symbol(elasticsearchjs-event-emitter)]: EventEmitter {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    [Symbol(kCapture)]: false
  }
}`

But the code gets stucked on the first indexing function and after some time it returns this message:

`TimeoutError: Request timed out
    at ClientRequest.onTimeout (C:\Users\XXXX\Documents\cloud\coworking\test\node_modules\@elastic\elasticsearch\lib\Connection.js:108:16)
    at ClientRequest.emit (events.js:315:20)
    at Socket.emitRequestTimeout (_http_client.js:784:9)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:327:22)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  meta: {
    body: null,
    statusCode: null,
    headers: null,
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 3,
      aborted: false
    }
  }
}`

The Elastic Search is running on port 9200, like usual, but maybe I am doing something wrong. Glad if you can help.

Thanks.

**Comment by delvedor** [comment]
How are you running Elasticsearch?

**Comment by ryanbales** [comment]
I'm running in this same issue.  We're running a multi-node cluster in AWS on EC2 with an ELB in front.
