### ISSUE TITLE
Searches involving Chinese words/characters return different results if enclosed in double-quotes

### ISSUE THREAD

**Issue by jo3n** [elastic/elasticsearch-js#1382]
When working with Chinese, queries that are for all intents and purposes single-search terms are returning different sets if they're enclosed in double quotes.

For example, a search for **中国铁建重工集团股份有限公司** returns different results than **"中国铁建重工集团股份有限公司"**

Is this expected behavior?

**Comment by delvedor** [comment]
Hello! Can you paste here your [index mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html) and analyzers?

**Comment by jo3n** [comment]
Hello, thanks for your response. Additional info below:

**Index mapping:**
`{
  "myIndex" : {
    "mappings" : {
      "properties" : {
        "bucketName" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "content" : {
          "type" : "text",
          "analyzer" : "custom_icu_analyzer"
        },
        "fileKey" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "title" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "type" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "updated" : {
          "type" : "long"
        }
      }
    }
  }
}`

**Analyzer settings**
`{
  "analysis":{
    "analyzer":{
      "custom_icu_analyzer":{
        "type":"custom",
        "filter":[
          "icu_normalizer",
          "custom_icu_transform"
        ],
        "tokenizer":"icu_tokenizer"
      }
    },
    "filter":{
      "custom_icu_transform":{
        "type":"icu_transform",
        "id":"Any-Latin; NFD; [:Nonspacing Mark:] Remove; NFC"
      }
    }
  }
}`

**Comment by delvedor** [comment]
`中国铁建重工集团股份有限公司` is not a single word term as far as the tokenizer is concerned; if you have a look at an ES `_analyze` endpoint you'll see that it gets split up into several tokens.  Doing a search on that term with quotes means that it's a phrase search, and so will yield fewer results than the same search without quotes.
