### ISSUE TITLE
Encoded bytes are incorrect length

### ISSUE THREAD

**Issue by Akaren13** [elastic/elasticsearch-js#1385]
Hi, my elasticsearch 7.7.1 sometimes returns encoded bytes are incorrect length error with 400. It's only sometimes, when I run the same query later, it works.  Elasticserach log is empty but client returns:

`Error: [illegal_argument_exception] encoded bytes are of incorrect length
Jan  6 01:55:35: at respond (/node_modules/elasticsearch/src/lib/transport.js:308:15)
Jan  6 01:55:35: at checkRespForFailure (/node_modules/elasticsearch/src/lib/transport.js:267:7)
Jan  6 01:55:35: at HttpConnector.<anonymous> (/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
Jan  6 01:55:35: at IncomingMessage.wrapper (/node_modules/lodash/lodash.js:4929:19)
Jan  6 01:55:35: at emitNone (events.js:111:20)
Jan  6 01:55:35: at IncomingMessage.emit (events.js:208:7)
Jan  6 01:55:35: at endReadableNT (_stream_readable.js:1055:12)
Jan  6 01:55:35: at _combinedTickCallback (internal/process/next_tick.js:138:11)
Jan  6 01:55:35: at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by delvedor** [comment]
Hello! Is there a proxy of some kind between Node.js and Elasticsearch?
Furthermore, I highly recommend you to migrate to the [new elasticsearch client](https://www.npmjs.com/package/@elastic/elasticsearch), as the one you are using will be deprecated soon. You can find the migration guide [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/breaking-changes.html).

**Comment by Akaren13** [comment]
I am using  elasticsearch js client version 15.2.0 https://www.npmjs.com/package/elasticsearch
Ok, I will try to migrate. 

Thank you.
