### ISSUE TITLE
NuxtJS ServerMiddleware - Not successfully requiring @elastic/elasticsearch

### ISSUE THREAD

**Issue by SomethingNew71** [elastic/elasticsearch-js#1386]
## 🐛 Bug Report

Original bug: #1317 

I am also encountering this issue while using the `serverMiddleware` property in NuxtJS. According to the NuxtJS documentation, this allows the developer to create files that will do the following:

> Middleware listed in the `serverMiddleware` property runs server-side before `vue-server-renderer` and can be used for server-specific tasks like handling API requests or serving assets.
More info: [serverMiddleware](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-servermiddleware/)

So this is running server-side within the node environment however it's still causing this error:
```
client.js?06a0:97 TypeError: Cannot read property 'split' of undefined
    at Object.eval (index.js?7080:22)
    at eval (index.js:330)
    at Object../node_modules/@elastic/elasticsearch/index.js
```

Node Version I am experiencing this in is `14.12.0`

## Expected behavior

`Client` should import properly into the node environment.

## Your Environment

- *node version*: 14.12.0
- `@elastic/elasticsearch` *version*: 7.10.0
- *os*: Mac

**Comment by delvedor** [comment]
Hello! Can you provide a minimal example to reproduce the issue?
The code works as expected in Node.js, I'm guessing that Nuxt is doing something weird with Node.js globals.
