### ISSUE TITLE
Remove deprecation warnings

### ISSUE THREAD

**Issue by blookot** [elastic/elasticsearch-js#1387]
Hi
I'm using node10 (in AWS Lambda), the 7.9 nodejs client version and a 7.9.3 ES cluster (in Elasticsearch service from cloud.elastic.co).
Every time I'm calling Elasticsearch I get this in the error log:
```(node:8) DeprecationWarning: You are using a version of Node.js that will reach EOL in April 2021. The support for this version will be dropped in 7.13. Please refer to https://ela.st/nodejs-support for additional information.```
How can I remove this message? maybe disable the deprecation warning?
Thanks in advance!

**Comment by DaveCTurner** [comment]
This is a cross-post from https://discuss.elastic.co/t/remove-deprecation-warnings-in-elasticsearch-nodejs-client/260385 and I think it's better handled on the forums, let's keep the conversation there.
