### ISSUE TITLE
Docs for JavaScript API reference have a typing mismatch for the 'refresh' parameter

### ISSUE THREAD

**Issue by jacoblb64** [elastic/elasticsearch-js#1388]
## 🐛 Bug Report

The docs still specify the old type expected, `'true' | 'false' | 'wait_for'`, where the typing was changed in #1263 to be `boolean | 'wait_for'`. The docs should be updated to match.

This happens for all of the API endpoints that expect this parameter.

![image](https://user-images.githubusercontent.com/2818246/104517547-340ab500-55c4-11eb-991b-037565702ab9.png)

## To Reproduce

Observe the current API docs at https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html

## Expected behavior

The typing to match what the latest client expects

---
I would try to make the fix myself, but it seems like the docs have a fairly complex generation process, and this seems like it would be a small change for someone familiar with the project.

**Comment by delvedor** [comment]
Thank you for reporting!

**Comment by saikiransathpadi** [comment]
I would like to work on this. Is this the repo that generates docs as well?

**Comment by saikiransathpadi** [comment]
I found the docs folder and looked into it and haven't found this and even didn't found in the reference doc link mentioned above. Can someone confirm whether this is resolved?

**Comment by JoshMock** [comment]
I've slowly been tweaking the generated docs over the last couple months to include more and better information about each API function. The `bulk` API now documents the possible values for `refresh` accurately.
