### ISSUE TITLE
Add elastic stream support to helper.bulk

### ISSUE THREAD

**Issue by PieterVenter7** [elastic/elasticsearch-js#1389]
## 🚀 Feature Proposal

With helpers.bulk add support for elastic streams that was added in elastic 7.9.

## Motivation

From the update to elastic 7.9 and pretty soon elastic 8.0 any log streams will need to be elastic streams.

## Example

For example you want to make use of pino-elasticsearch to send ecm application logs to elastic.

Currently you get the following error, because streams change the op_type that needs to be send trough

```json
{"took":0,"errors":true,"items":[{"index":{"_index":"logs-listsmanager-2021-01-19","_type":"_doc","_id":null,"status":400,"error":{"type":"illegal_argument_exception","reason":"only write ops with an op_type of create are allowed in data streams"}}}]}
```

**Comment by delvedor** [comment]
The bulk helper only provides the mechanics to handle concurrency and retries, you should configure the `op_type` parameter yourself in the `onDocument` callback. If you like, you can open a pr against `pino-elasticsearch` with the fix.

```js
  const b = client.helpers.bulk({
    datasource: splitter,
    flushBytes: opts['flush-bytes'] || 1000,
    flushInterval: opts['flush-interval'] || 30000,
    refreshOnCompletion: getIndexName(),
    onDocument (doc) {
      return {
        index: {
          _index: getIndexName(doc.time || doc['@timestamp']),
          _type: type,
          op_type: 'create'
        }
      }
    },
    onDrop (doc) {
      const error = new Error('Dropped document')
      error.document = doc
      splitter.emit('insertError', error)
    }
  })
```

**Comment by FlyingWraptor** [comment]
Has there been any progress to this? I wouldn't mind creating a PR for this.

Would something like opts.opt_type = 'create' work?
