### ISSUE TITLE
Support creating indices with <date math> in name

### ISSUE THREAD

**Issue by lorranmira** [elastic/elasticsearch-js#1392]
## 🚀 Feature Proposal

Allow creation of indices that make use of the {date math} functionality that is available when creating the Index using direct Elasticsearch API calls.

## Motivation
Without this functionality it is not possible to create date based indices and then use the /rollover API to create a new index with todays date, as detailed here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-rollover-index.html
This appears to be due to the issue described here:
https://discuss.elastic.co/t/date-in-index-name-doesnt-change-on-rollover-on-the-next-day/226701/2

That if not using the date math.  The required information is not being put "provided_name" setting for the index

But the nodeJS API spec states:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#indices-create-api-path-params

So characters are not supported.
Attempting to set the "provided_name" parameter directly does not appear to work.

## Example
PUT /test_index-2021.01.23-1
GET /test_index-2021.01.23-1
...
"provided_name" : "test_index-2021.01.23-1"

PUT /%3Ctest_index-%7Bnow%2Fd%7D-1%3E
"provided_name" : "<test_index-{now/d}-1>"

**Comment by GuillaumeCisco** [comment]
Any update on this?
is it supported?
