### ISSUE TITLE
v7.10.0 does not build

### ISSUE THREAD

**Issue by lulurian** [elastic/elasticsearch-js#1397]
### Please note that this issue tracker is not a help forum and this issue may be closed.
Hello!
I have the same issue form this topic (https://github.com/elastic/elasticsearch-js/issues/803) but nothing from there is helping me.
 Im trying to import elasticsearch in my app. 
I installed npm install @elastic/elasticsearch and npm i @types/node

node: v12.16.1
@elastic/elasticsearch: ^7.10.0
os: MacOS 10.15.6
typescript: ^3.7.2

When i try what @delvedor suggested https://github.com/elastic/elasticsearch-js/issues/803#issuecomment-481120906 
my index is empty.

In the code i just imported:
import { Client } from '@elastic/elasticsearch';
and then const client = new Client({ node: 'http://localhost:9200' });

The error that i get when i try to run the app :
![image](https://user-images.githubusercontent.com/19392901/106881751-95ff9b80-66e6-11eb-998e-41d3d7adab68.png)

Thank you!

**Comment by delvedor** [comment]
Hello! A few questions:
- Are you using the client in the browser?
- Are you using the code in Node.js and using webpack for creating a single bundle?

**Comment by lulurian** [comment]
Yes, the client it's in the browser. 
I have a React project with typescript and i'm trying to call the elasticsearch from it.  I think we are using webpack, as far as i know the app was created with create-react-app.

Hope this answer your questions. 
Thanks a lot!

**Comment by lulurian** [comment]
> Hello! A few questions:
> 
> * Are you using the client in the browser?
> * Are you using the code in Node.js and using webpack for creating a single bundle?

**Comment by delvedor** [comment]
This library is not meant to work from the browser, as you can see [here](https://github.com/elastic/elasticsearch-js#browser).
I recommend writing a lightweight Node.js proxy to send requests to Elasticsearch and make your frontend talk with the proxy.
