### ISSUE TITLE
Missing RefreshInterval on client.indices.create({body: settings: {refreshInterval}})

### ISSUE THREAD

**Issue by cedw032** [elastic/elasticsearch-js#1403]
I've tried my darndest, but can't figure out how the heck to set the refresh interval when creating an index.  

I've tried several variations similar to this
```
await client.indices.create({
    index: indexName(company),
    body: {
      settings: {
        refreshInterval: defaultRefreshInterval,
      },
      mappings: {
        properties: {
          lineItem: {
            type: 'keyword',
          },
          pricingTier: {
            type: 'keyword',
          },
        },
      },
    },
  })
```

The docs aren't particularly helpful in this case.  Any suggestions or workarounds?

**Comment by cedw032** [comment]
Just following up on this.  Does anyone have any input?

**Comment by delvedor** [comment]
Hello! The keys in the body (aside from your mappings) should be in snake_case.
See [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-modules-settings).
