### ISSUE TITLE
RuntimeError regarding Promise when passing client in props to React.Component

### ISSUE THREAD

**Issue by faustas** [elastic/elasticsearch-js#1406]
Hi,

I checked the open issues to see if that is maybe an error, but could not find a similar problem.

_**The current situation**_

Versions
    "@elastic/elasticsearch": "^7.11.0",
    "next": "10.0.6",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "sass": "^1.32.7"

I have an index component that initializes the Elastic client.

_index.tsx_
```
import MainLayout from "../components/BasicLayout";
import Autocomplete from "../components/search/Autocomplete";
// This file contains the implemented methods for the calls to the elastic engine
const elastic = require("../services/elasticclient")

import { Client } from '@elastic/elasticsearch'
const client = new Client({
    node: 'http://localhost....',
})

const getStaticProps = async () => {

  const count_cats = await elastic.CountCategories(client)

  return {
       props: {
           count: {
               categories: count_cats
           },
       }
  }
}

const Index = props => {
  return(
      <MainLayout>
          <div className="App">
              <Autocomplete client={client} />
              {/*<Autocomplete />*/}
          </div>

          documents: {props.count.docs}

      </MainLayout>
  )
}

export default Index;
```
And I have an Autocomplete component which is a simple searchbox.
This component receives the client as prop.

_Autocomplete.tsx_
```
import React from "react";

type MyProps = {
    client
}

class Autocomplete extends React.Component<MyProps, {}> {

}
```

**_My problem_**

I get the following error:
```
Unhandled Runtime Error

TypeError: process.versions.node is undefined
Source

../../client/route-loader.ts (276:22) @ onEntrypoint/<
  274 | onEntrypoint(route: string, execute: () => unknown) {
  275 |   Promise.resolve(execute)
> 276 |     .then((fn) => fn())
      |                  ^
  277 |     .then(
  278 |       (exports: any) => ({
  279 |         component: (exports && exports.default) || exports,
```

If I remove the `client` in the props to the **Autocomplete** component, the error is gone.
But, I want to use the `client` in the `index` component to load some basic data and within the `Autocomplete` component to load e.g. suggestions depending on user input.

**_Question_**

Is this is a bug or has the client be initialized and passed differently, if it is used by different components?

**Comment by delvedor** [comment]
Hello! This module is designed to work in Node.js and not in the browser, as you can see [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/installation.html#_browser).

**Comment by faustas** [comment]
Ah, damn. Thanks for the info. Yes, that is clear. Totally overseen that point. Thanks for the link. I created an API and could integrate it into my application.
