### ISSUE TITLE
Elastic client nodejs ssl configuration error.

### ISSUE THREAD

**Issue by vasRK** [elastic/elasticsearch-js#1409]
## 🐛 Bug Report

I have setup elastic on ECK with default operator certificates, i can access my elastic search with .net client, by disabling 
ServerCertificateValidationCallback. now im trying to develop a nodejs based api that uses my elastic search but getting 
security_exception

```
ResponseError: security_exception
    at onBody (D:\Workspaces\RL.Elastic-API\node_modules\@elastic\elasticsearch\lib\Transport.js:333:23)
    at IncomingMessage.onEnd (D:\Workspaces\RL.Elastic-API\node_modules\@elastic\elasticsearch\lib\Transport.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  meta: {
    body: { error: [Object], status: 401 },
    statusCode: 401,
    headers: {
      'www-authenticate': 'Basic realm="security" charset="UTF-8", Bearer realm="security", ApiKey',
      'content-type': 'application/json; charset=UTF-8',
      'content-length': '549'
    },
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  }
}
```

## To Reproduce

below is the code i used for connecting from a nodejs app.

Code to create Client:

```
const client = new Client({
    node: 'https://myeck.cloudapp.azure.com/',
    maxRetries: 5,
    requestTimeout: 60000,
    sniffOnStart: true,
    ssl: {
        ca: fs.readFileSync('./cacert.crt'),
        rejectUnauthorized: false,
    },
    auth: {
        password: ELASTIC_PWD,
        username: ELASTIC_USER
    }
});

//Search call
const result = await client.search({
      index: 'rush_idx',
      body: {
        query: {
          match: { isbn: "243453452" }
        }
      }
    });

```
## Expected behavior

What is the correct way to configure Client in this scenarios i have seen some forums where certificates are loaded in ssl confit section,  but all i can see on my cluster secret is .crt files 

`kubectl get secret xyz-elastic-depl-es-http-certs-public -o json
{
    "apiVersion": "v1",
    "data": {
        "ca.crt": "LS0tLS1CRUdJTiBDRVJUSUZJQ0F....",
        "tls.crt": "LS0tLS1CRUdJTiBDR...."
		}
}`

## Your Environment

- *node version*: v14.15.1
- `"@elastic/elasticsearch": "^7.11.0",` 
- *os*:  Windows
- *any other relevant information*

**Comment by delvedor** [comment]
Hello! Can you share the full response body?
```
console.log(JSON.stringify(err.body, null, 2))
```
