### ISSUE TITLE
Unable to revive connection

### ISSUE THREAD

**Issue by juliendangers** [elastic/elasticsearch-js#142]
Hello,

I keep getting this error, and it never recovers. I'm using Elasticsearch 1.3.2 and elasticsearch-js 2.4.0 (node client)

```
Elasticsearch WARNING: 2014-09-09T08:09:05Z
  Unable to revive connection: https://elasticsearch.****.net/

Elasticsearch WARNING: 2014-09-09T08:09:05Z
  No living connections
```

Here is my configuration

``` js
{
    apiVersion:'1.3',
    sniffOnConnectionFault:true,
    maxRetries:5,
    keepAlive:true,
    connectionClass:'http'
}
```

**Comment by mantoni** [comment]
I also get this issue and tracked it down:
On connection loss, the client performs HEAD requests using the internal `ping()` function. The default timeout for this request is set to 100 milliseconds. One can override the timeout when calling `ping` manually, but the retry logic just goes with the defaults and there is no way to set a different timeout.

In my case this is really problematic since I'm sending reports from Asia to Europe. The ping time is always > 100, so connections never get revived.

Please consider increasing this very aggressiv default and also allow users to configure the timeout. Personally, I would have expected the timeout to be the same as the `requestTimeout`.

**Comment by spalger** [comment]
@mantoni Wow, that does seem to be the case. It was never my intention to prevent setting the default ping timeout. I'll get a fix released soon.

**Comment by spalger** [comment]
@mantoni as a temporary workaround you can do the following. This is not ideal, as it modifies the default for all instances of the client but will do the trick.

```js
Client.apis[config.apiVersion].ping.spec.requestTimeout = customDefaultMs;
```

**Comment by juliendangers** [comment]
\o/ thanks @mantoni for tracking the bug down !! the temporary workaround works like a charm, no more "Unable to revive connection" even under heavy load :+1: 
Waiting for the official fix !

**Comment by spalger** [comment]
Yes, thank you @mantoni!

**Comment by mantoni** [comment]
Ok, the workaround gets me one step further, but I still have connection issues. The elasticsearch instance is not available for a few minutes due to a reboot, and reconnects don't work after that. What I see in the logs is this:

```
Error: Request Timeout after 30000ms
Error: Request Timeout after 30000ms
Error: Request Timeout after 30000ms
Error received Request error, retrying -- socket hang up
Unable to revive connection: http://.....:9210/
No living connections
Unable to revive connection: http://.....:9210/
No living connections
Unable to revive connection: http://.....:9210/
No living connections
```

And then it continues to log the last two lines on each use of the bulk upload function, although the server is up and fine again.

**Comment by spalger** [comment]
@mantoni I hope this isn't a bug in the client, but to be sure you could shut-down and rebuild the client when you have a connection failure and you have reason to believe the server is back up – Just call `.close()` on the old client and recreate it.

If that fixes it then it is definitely a bug and I will invest as much time as required to fix it.

**Comment by mantoni** [comment]
Sorry, I just left for holidays, so I can't run this test. However, I simply creat one instance of the client and use the bulk upload every 15 seconds.

You can try and reproduce with this library: https://github.com/mantoni/measured-elasticsearch.js

**Comment by nexflo** [comment]
:+1: for a fix.
Getting same error's here.... 
indexing 6 million docs..(actually one after the other)
by row 16275 error appears. (first Elasticsearch ERROR: 2015-03-03T17:18:37Z -  Error: Request error, retrying -- connect EADDRNOTAVAIL
)

**Comment by ltamrazov** [comment]
Also getting this. 

io.js 1.2.0
elasticsearch 1.4.3
client 4.0.2

However, I am not indexing documents, but doing queries. After about 16K queries, it crashes with the following log:

`Elasticsearch ERROR: 2015-04-16T19:37:00Z`
 ` Error: Request error, retrying -- connect EADDRNOTAVAIL 127.0.0.1:9200 - Local (0.0.0.0:0)
      at Log.error (/Users/Levon/Documents/my-dev/bfm-website/server/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/Users/Levon/Documents/my-dev/bfm-website/server/node_modules/elasticsearch/src/lib/transport.js:195:18)
      at HttpConnector.<anonymous> (/Users/Levon/Documents/my-dev/bfm-website/server/node_modules/elasticsearch/src/lib/connectors/http.js:154:7)
      at ClientRequest.wrapper (/Users/Levon/Documents/my-dev/bfm-website/server/node_modules/elasticsearch/node_modules/lodash/index.js:3189:19)
      at emitOne (events.js:75:13)
      at ClientRequest.emit (events.js:150:7)
      at Socket.socketErrorListener (_http_client.js:249:9)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at net.js:432:14
      at process._tickCallback (node.js:337:11)`

`Elasticsearch ERROR: 2015-04-16T19:37:00Z
  Error: Request error, retrying -- connect EADDRNOTAVAIL 127.0.0.1:9200 - Local (0.0.0.0:0)
      at Log.error (/Users/Levon/Documents/my-dev/bfm-website/server/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/Users/Levon/Documents/my-dev/bfm-website/server/node_modules/elasticsearch/src/lib/transport.js:195:18)
      at HttpConnector.<anonymous> (/Users/Levon/Documents/my-dev/bfm-website/server/node_modules/elasticsearch/src/lib/connectors/http.js:154:7)
      at ClientRequest.wrapper (/Users/Levon/Documents/my-dev/bfm-website/server/node_modules/elasticsearch/node_modules/lodash/index.js:3189:19)
      at emitOne (events.js:75:13)
      at ClientRequest.emit (events.js:150:7)
      at Socket.socketErrorListener (_http_client.js:249:9)
      at emitOne (events.js:75:13)
      at Socket.emit (events.js:150:7)
      at net.js:432:14
      at process._tickCallback (node.js:337:11)`

`Elasticsearch WARNING: 2015-04-16T19:37:00Z
  Unable to revive connection: http://localhost:9200/`

`Elasticsearch WARNING: 2015-04-16T19:37:00Z
  No living connections`

`Elasticsearch WARNING: 2015-04-16T19:37:00Z
  Unable to revive connection: http://localhost:9200/`

`Elasticsearch WARNING: 2015-04-16T19:37:00Z
  No living connections`

I thought it might help if I increased number of nodes to handle the load, but still getting the same thing.

@spalger Any updates on this?

Thanks!

**Comment by ivarprudnikov** [comment]
Hi, have almost similar issue. In my case I listen to stream of information which comes from Firebase and was pushing it straight to ES via constructed client:

```
var client = new elasticsearch.Client({
	host: config.elasticsearch.host,
	log: config.elasticsearch.logLevel
});
```

But I used `create` action quite aggressively and for each new document I would call it, so in my case initially there were 815 documents and for each I would end up calling:

```
ids.forEach(function(itemId,idx){
	client.create({
		index: indexName,
		type: type,
		id: itemId,
		body: itemBody,
		ignore: [409]
	}).then(function(resp){
		// noop
	}, function(rejection){
		console.log(('>>> ' + (new Date()).toUTCString()));
		console.log('' + JSON.stringify(rejection));
		console.log('<<<');
	});
});
```

While testing on local elasticsearch instance I had no issues, but when I switched to remote ES on found.no and used https with basic auth I did immediatelly get 

`Error: Request error, retrying -- connect EADDRNOTAVAIL`
Followed by 
`Unable to revive connection: ...`

My solution was to switch to `bulk` indexing and problems went away.

```
var ops = [];
ids.forEach(function(itemId,idx){
	var operation = {
		create: { _index: indexName, _type: type, _id: itemId }
	};
	var operationDoc = itemBody;
	ops.push(operation);
	ops.push(operationDoc);
});

client.bulk({
	body: ops,
	ignore: [409]
}).then(function(resp){
	// noop
	console.log('bulk upload done, operation count', ops.length);
}, function(rejection){
	console.log(('>>> ' + (new Date()).toUTCString()));
	console.log('' + JSON.stringify(rejection));
	console.log('<<<');
});
```

**Comment by RongQiao** [comment]
Hi ivarprudnikov, do you have idea about if the "Unable to revive connection" a js client problem or ES service problem?
I'm set up Kibana work with ES + Shield, and Kibana server cannot connect with ES because of the connection error. curl and browser works well with the https connection, and openssl verified the certificate with https connection, so it looks server side is pretty good. Kibana is js client, I'm wondering if this is a client side issue.

**Comment by DavidTanner** [comment]
@RongQiao For me I have added a check for any time this error shows up.  I recreate the client and try again.  I think that is the expected solution from reading above.  So this did end up being a client error.

**Comment by PLEEROCK** [comment]
+1 having the same issue during importing mullion rows

**Comment by christemporale** [comment]
I have the same issue with node v0.10.33 and https connection to Elasticsearch 1.5.2.

```javascript
var client = new elasticsearch.Client({
  host: 'https://[user]:[passwd]@localhost:9200',
  log: 'trace',
  connectionClass: customHttpConnector
});
```
It works with node v.0.12

**Comment by breakbild** [comment]
Doing around 300 groovy script updates/sec and having the error within seconds. Tried setting concurrency, and all proposed solutions in here, but nothing helped. Also still happening after a quick restart of the nodejs script (while the "old" updates were still executing i guess). After a few secs it revived, but shortly after the issue is there again (renewed load).

Maybe it has something to do with ES blocking due to a lot of groovy updates, and the driver believing the connection was lost.

**Comment by dmytroleonenko** [comment]
the same problem here. ES 1.7 (latest), nodejs 0.12.13, 4.4.2, 5.10.1
No living connections. Server restart doesn't help. Anything discussed here didn't help

**Comment by tmzeek** [comment]
I have the same issue.
We established a new ES instance like 3 weeks ago.
It hasn't been used for quite a while. We used it just this last Tuesday but now we keep getting the error in question. We ran a big index several days ago and now we cannot even get new Client() in JS.

Any prediction if this gets fixed soon? Been around for a while.

**Comment by abhishekscript** [comment]
We are running our app on two different Test Servers.
Now everything is fine on TestServer 1 however TestServer 2 breaks throwing this error.
We are facing this error recently otherwise the app was working fine on both the server.
`debug: Error: No Living connections
    at sendReqWithConnection (/Users/kadhiresan/sites/tw-api/node_modules/elasticsearch/src/lib/transport.js:207:15)
    at next (/Users/kadhiresan/sites/tw-api/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickDomainCallback (node.js:403:13) { [Error: No Living connections] message: 'No Living connections' } null vendor detail`

**Comment by breakbild** [comment]
We solved this problem for good with the custom http agent "workaround". You need to install the agentkeepalive module, but hey, if it solves the issue... Example code (you don't need to specify all options; it's just a snippet of what we use. We're using Elasticsearch 2.3, node 5.3). See also #196.

var elasticsearch = require('elasticsearch');
var AgentKeepAlive = require('agentkeepalive');
var client = new elasticsearch.Client({
        hosts: ['localhost:9200'],
        maxRetries: 10,
        keepAlive: true,
        maxSockets: 10,
        minSockets: 10,
        createNodeAgent: function (connection, config) {
          return new AgentKeepAlive(connection.makeAgentConfig(config));
        }
      }
);

**Comment by filipedeschamps** [comment]
@breakbild I'm still receiving this error message:

```
Error: Request complete with error
```

Followed by

```
Elasticsearch WARNING:
 Unable to revive connection: http://...
```

I've also tried to upgrade to v12 rc4, without success.

Is there any other strategy guys?

**Comment by DavidMitnick** [comment]
correct the server host 
not like http://192.168.1.111 。if kibana and elasticsearch in the same box
try http://localhost:9200

**Comment by Cuong12** [comment]
How can i fix it ? . Plz help me :(


Elasticsearch INFO: 2017-01-11T03:19:19Z
  Adding connection to http://localhost:9200/

Elasticsearch DEBUG: 2017-01-11T03:19:19Z
  starting request {
    "method": "HEAD",
    "requestTimeout": 5000,
    "castExists": true,
    "path": "/",
    "query": {}
  }


Elasticsearch DEBUG: 2017-01-11T03:19:19Z
  starting request {
    "method": "PUT",
    "path": "/chesshub",
    "query": {}
  }


(node:7088) DeprecationWarning: Mongoose: mpromise (mongoose's default promise l
ibrary) is deprecated, plug in your own promise library instead: http://mongoose
js.com/docs/promises.html
Elasticsearch TRACE: 2017-01-11T03:19:20Z
  -> HEAD http://localhost:9200/

  <- 0


Elasticsearch ERROR: 2017-01-11T03:19:20Z
  Error: Request error, retrying
  HEAD http://localhost:9200/ => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (C:\Users\MyPC\Desktop\gamehub.io-master\node_modules\elastic
search\src\lib\log.js:225:56)
      at checkRespForFailure (C:\Users\MyPC\Desktop\gamehub.io-master\node_modul
es\elasticsearch\src\lib\transport.js:240:18)
      at HttpConnector.<anonymous> (C:\Users\MyPC\Desktop\gamehub.io-master\node
_modules\elasticsearch\src\lib\connectors\http.js:162:7)
      at ClientRequest.wrapper (C:\Users\MyPC\Desktop\gamehub.io-master\node_mod
ules\elasticsearch\node_modules\lodash\lodash.js:4968:19)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:309:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at emitErrorNT (net.js:1281:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

Elasticsearch TRACE: 2017-01-11T03:19:20Z
  -> PUT http://localhost:9200/chesshub

  <- 0


Elasticsearch ERROR: 2017-01-11T03:19:20Z
  Error: Request error, retrying
  PUT http://localhost:9200/chesshub => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (C:\Users\MyPC\Desktop\gamehub.io-master\node_modules\elastic
search\src\lib\log.js:225:56)
      at checkRespForFailure (C:\Users\MyPC\Desktop\gamehub.io-master\node_modul
es\elasticsearch\src\lib\transport.js:240:18)
      at HttpConnector.<anonymous> (C:\Users\MyPC\Desktop\gamehub.io-master\node
_modules\elasticsearch\src\lib\connectors\http.js:162:7)
      at ClientRequest.wrapper (C:\Users\MyPC\Desktop\gamehub.io-master\node_mod
ules\elasticsearch\node_modules\lodash\lodash.js:4968:19)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:309:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at emitErrorNT (net.js:1281:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

Elasticsearch TRACE: 2017-01-11T03:19:21Z
  -> HEAD http://localhost:9200/

  <- 0


Elasticsearch WARNING: 2017-01-11T03:19:21Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2017-01-11T03:19:21Z
  No living connections

elasticsearch is down!
Elasticsearch TRACE: 2017-01-11T03:19:21Z
  -> HEAD http://localhost:9200/

  <- 0


Elasticsearch WARNING: 2017-01-11T03:19:21Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2017-01-11T03:19:21Z
  No living connections

Elasticsearch DEBUG: 2017-01-11T03:19:21Z
  starting request {
    "method": "POST",
    "path": "/chesshub/game/1/_create",
    "body": {
      "white": "Foo",
      "black": "Anonymous",
      "content": "1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6 4. O-O Bc5 5. c3 O-O 6. d4 exd4
 7. cxd4 Bb4",
      "result": "1-0"
    },
    "query": {}
  }


Elasticsearch TRACE: 2017-01-11T03:19:22Z
  -> HEAD http://localhost:9200/

  <- 0


Elasticsearch WARNING: 2017-01-11T03:19:22Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2017-01-11T03:19:22Z
  No living connections

Elasticsearch DEBUG: 2017-01-11T03:19:23Z
  starting request {
    "method": "POST",
    "path": "/chesshub/game/2/_create",
    "body": {
      "white": "Anonymous",
      "black": "Bar",
      "content": "1. e4 c6 2. e5 d5 3. exd6 exd6 4. Nf3 Bg4 5. d4 Nf6 6. Bg5 Be7
",
      "result": "1-0"
    },
    "query": {}
  }


Elasticsearch TRACE: 2017-01-11T03:19:24Z
  -> HEAD http://localhost:9200/

  <- 0


Elasticsearch WARNING: 2017-01-11T03:19:24Z
  Unable to revive connection: http://localhost:9200/

Elasticsearch WARNING: 2017-01-11T03:19:24Z
  No living connections

**Comment by luthraG** [comment]
@filipedeschamps 

Were you able to solve the issue? I also got the same error where it mentions

`Elasticsearch ERROR: 2017-05-05T19:05:37Z
  Error: Request error, retrying
  GET http://<HOST>:9200/<index>/<type>/<doc_ID> => connect EMFILE <IP>:9200 - Local (undefined:undefined)`

Followed by

`Elasticsearch WARNING: 2017-05-05T19:05:37Z
  Unable to revive connection: http://HOST:9200/`

which is followed by

`Elasticsearch WARNING: 2017-05-05T19:05:37Z
  No living connections`

Since it mentions EMFILE which means that process is trying to open too many files/sockets and OS is denying that, so I suspect that to solve we might need to implement some sort of connection pooling.

However as per @spalger 's  comment on #90 i.e.

> elasticsearch.js has a pretty good connection pool built in

So I am not sure if that would solve the issue.

Thanks,

**Comment by filipedeschamps** [comment]
@luthraG thanks for calling me back to this issue.

The answer is **yes** and it was a bug in our code that used all file descriptors of the OS. The script kept opening `tmp files` without closing their buffers, until OS ran out of file descriptors.

Check this stats in your OS to see if it's related.

Best regards.

**Comment by luthraG** [comment]
Thanks @filipedeschamps for prompt reply. Let me monitor the file handles and see if error is caused by it.

**Comment by sawankumar46** [comment]
I have one query. I have hosted elastic search on aws ec2 t2 micro and node and mongodb hosted on separately two aws ec2 t2 small instance.The problem is node is able to connect to mongo but not with elastic search.Using sense plugin I am able to see my indices on chrome browser.

I am getting “error: error in searching patientsError: No Living connections”.

**Comment by BeHiz** [comment]
I have the same problem
I am using a docker compose ([YAML](https://github.com/codingexplained/complete-guide-to-elasticsearch/blob/master/docker-compose.yml) here)

```
#systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.15063 N/A Build 15063

#docker-machine version
docker-machine.exe version 0.12.2, build 9371605

#docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false```

**Comment by n3ps** [comment]
For dev purposes only, mine was resolved with http.cors.enabled and http.cors.allow-origin

**Comment by deepaksomase** [comment]
I was facing the same problem. For me issue was with setting auth configuration. Following configuration is worked for me.
var client = new elasticsearch.Client( {  
  host: [
    {
      host: '127.0.0.1',
      auth: 'username:password',
      protocol: 'http',
      port: 9200
    }
  ]
});

**Comment by XeniaSiskaki** [comment]
For me the error occurs when using the `Scroll API` with a query size of 1. My goal was to create an `rxjs` stream of the elastic query. Code is the following

```
// elasticClient initialized only with { host: 'hostname.domain:9200' } 
import elasticClient from '../elasticHelper';
import * as Rx from 'rxjs';

function scrollElastic(scroll, scrollId) {
    return Rx.Observable
        .fromPromise(elasticClient.scroll({scroll, scrollId}))
        .map(({_scroll_id, hits: {hits}}) =>
            ({scrollId: _scroll_id, data: hits.map(x => x._source)[0]}));
}

function searchElastic({query, sort})> {
    const body = {
        size: 1,
        query,
        _source: { excludes: ['editable'] },
        sort
    };
    // keep the search results "scrollable" for 30 secs
    const scroll = '30s';

    return Rx.Observable
        .fromPromise(elasticClient.search({ index: 'data', body, scroll }))
        .map(({_scroll_id, hits: {hits}}) =>
            ({scrollId: _scroll_id, data: hits.map(x => x._source)[0]}))
        // invokes scrollElastic recursively
        .expand(({scrollId}) => scrollElastic(scroll, scrollId))
        // stop resursion when there are no more data
        .takeWhile(res => res.data != null)
        .map(x => x.data);
}
```

and the error I get is:

```
Elasticsearch ERROR: 2018-06-20T12:01:13Z
  Error: Request error, retrying -- connect EADDRNOTAVAIL X.X.X.X:9200 - Local (X.X.X.X:0)
      at Log.error (.../node_modules/elasticsearch/src/lib/log.js:218:56)
      at checkRespForFailure (.../node_modules/elasticsearch/src/lib/transport.js:211:18)
      at HttpConnector.<anonymous> (.../node_modules/elasticsearch/src/lib/connectors/http.js:153:7)
      at ClientRequest.wrapper (.../node_modules/lodash/index.js:3095:19)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at Socket.socketErrorListener (_http_client.js:309:9)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at emitErrorNT (net.js:1277:8)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)

Elasticsearch WARNING: 2018-06-20T12:01:13Z
  Unable to revive connection: http://.....:9200/

Elasticsearch WARNING: 2018-06-20T12:01:13Z
  No living connections
```

Any ideas?

**Comment by deepaksomase** [comment]
Hi XeniaSiskaki , 
Have you checked with 
1. normal js connection i.e. without rx
2. by adding proper auth for rx

**Comment by XeniaSiskaki** [comment]
@deepaksomase I'll try number 1. and let you know! What do you mean though by 

> proper auth for rx?

**Comment by XeniaSiskaki** [comment]
@deepaksomase It does seem to work without Rxjs. What could that mean?

**Comment by deepaksomase** [comment]
@XeniaSiskaki , not sure. Is it showing some data and then throwing an error. 

I have tried your above-provided code (with my elasticsearch connection initialization helper class),  at my end and observed it working fine. I have verified above code with the version of node=v8.9.4 and ES version 6.2.4

**Comment by XeniaSiskaki** [comment]
> Is it showing some data and then throwing an error.

Exactly! It processes correctly some data and then at some point the driver just reports "No live connections". I'm not sure how to proceed...

**Comment by deepaksomase** [comment]
How many records (count) you have in your index for which you are doing search/ scroll?

**Comment by XeniaSiskaki** [comment]
![status3](https://user-images.githubusercontent.com/10288884/41712336-9e10999a-754a-11e8-8ec2-e2fb70baae82.png)

**Comment by deepaksomase** [comment]
Seems to be an issue with the opening of a number of socket connections simultaneously. tried
1. update log setting (set it to trace), while configuring elasticsearch. And check the logs, it may give more info about an error
2. As per the elasticsearch client version modify the configuration for timeout, hostnames ( modify this as IP address ), requestTimeout,  deadTimeout, maxRetries and check that still issue exist
3. try using agentkeepalive with http
4. configure/update net.ipv4.tcp_tw_reuse value.

**Comment by XeniaSiskaki** [comment]
I didn't see any difference

**Comment by XeniaSiskaki** [comment]
I'm not sure what point 3. means but the other points didn't help at all

**Comment by deepaksomase** [comment]
@XeniaSiskaki , I have tried to reproduce this with a huge amount of data at my end but not able to reproduce. Can you please provide http/consumer code which consuming searchElastic function ( i have tried consuming this on the console directly)

**Comment by XeniaSiskaki** [comment]
@deepaksomase You are right, there are more elastic stuff happening in the rest of the code. I updated my original code with all elastic calls.

**Comment by XeniaSiskaki** [comment]
@deepaksomase It also seems to work fine if I delay the `scrollElastic` calls by a few milliseconds, but this way feels very hackish. I would prefer if I could somehow fix this in the elastic driver

**Comment by schizobulia** [comment]
My problem has been solved.

code
```javascript
let client = new elasticsearch.Client({
    host: 'hostname.domain:9200',
    maxSockets: 20,
    keepAlive: false,  
    requestTimeout: 300000,
    sniffInterval: false
});
try {
    await client.search({
        index: 'index',
        body: {"query": {"match_all": {}}},
    });
} catch (error) {

} finally {
    client.close();
}
```

**Comment by frankorama** [comment]
We just encountered this problem and the reason was due to Elastic Search running on Node 8 which has a bug with SSL encryption

https://github.com/nodejs/node/issues/19359
