### ISSUE TITLE
[es client] Kibana can become unresponsive if a node fails to join the cluster

### ISSUE THREAD

**Issue by jbudz** [elastic/elasticsearch-js#1426]
**Kibana version:** 7.9.0	

**Elasticsearch version:**

**Server OS version:**

**Browser version:**

**Browser OS version:**

**Original install method (e.g. download page, yum, from source, etc.):**

**Describe the bug:**

**Steps to reproduce:**
1. Start a multi-node cluster
2. Define nodes in elasticsearch.hosts
3. Restart a node and have it not rejoin the cluster
4. Kibana will continue to make requests to the split node because it is responsive.  In this case, the security index was unavailable and logs were filled the authentication errors

**Expected behavior:**  Requests are eventually routed to the cluster, not the split node

**Screenshots (if relevant):**

**Errors in browser console (if relevant):**

**Provide logs and/or server output (if relevant):**

**Any additional context:**

My understanding is the legacy client will keep the node active even if there's a 4xx response.  Linking this to https://github.com/elastic/kibana/issues/83910

**Comment by delvedor** [comment]
Both the new and the legacy client will not remove a node from rotation in case of 4xx errors.
The client can't detect this situation and will continue to keep the split node in rotation.
The best way to solve this is to enable sniffing, so the client will remove the bad node from the pool.
Take a look [here](https://www.elastic.co/blog/elasticsearch-sniffing-best-practices-what-when-why-how) to learn what sniffing configuration is best suited for you :)

**Comment by mshustov** [comment]
@jbudz Can we close the issue?

**Comment by jbudz** [comment]
Works for me.  We can reopen if there's more concerns.
