### ISSUE TITLE
Value of _version in response of get api

### ISSUE THREAD

**Issue by mehdi-sh-hm** [elastic/elasticsearch-js#1429]
## 🚀 Feature Proposal

At present the implementation of [`Get API`](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html#docs-get) in [`client.get`](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_get) ([here](https://github.com/elastic/elasticsearch-js/blob/master/api/api/get.js#L57)) does not return the value of `_version` in response, :thinking: I really do not know, maybe there is a technical reason behind the issue but if it is possible, it is very appropriate :pray:

## Current behavior
`client.get({ ...options }).then((res) => debug(res)) => /* { _id: ..., _source: {...} } */`
## Example
`client.get({ ...options }).then((res) => debug(res)) => /* { _id: ..., _source: {...}, _version: ... } */`

**Comment by delvedor** [comment]
Hello! The client does nothing to the response body, can you add an example to reproduce the issue?

**Comment by mehdi-sh-hm** [comment]
I'm very sorry :disappointed: that I did not notice `filter_path` in our final request (because there are several middleware) and you are right.
