### ISSUE TITLE
Specifying number of shards and replicas during index creation

### ISSUE THREAD

**Issue by parautenbach** [elastic/elasticsearch-js#143]
I'm having trouble finding this information in the JS library's documentation, so my apologies if I've missed the obvious. I've tried to add a settings attribute with `number_of_shards` and `number_of_replicas` (as for the REST API) to the JSON request when creating an index, but it has no effect (if tried a few other variations too). Is this supported by the JS library, and if, how would one go about setting this when an index is created?

**Comment by ebaizel** [comment]
Been looking for documentation on creating indices with the JS client.  This helped a lot.  Thanks!
