### ISSUE TITLE
Bearer Token flow - Client credentials grant 

### ISSUE THREAD

**Issue by pure-zero** [elastic/elasticsearch-js#1448]
It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `invalid` label.**

## 🚀 Feature Proposal

I was wondering If we can consider supporting the bearer flow for this library, as described here https://www.elastic.co/guide/en/elasticsearch/reference/master/security-api-get-token.html

I would also like the token to be automatically regenerated when a request is made after it has expired. 

## Motivation

Given that the client credentials flow is meant to support machine to machine communication it would be good to support the feature by default and not have the user have to implement that themselves if needed.

## Example

I would like to be able to define an elastic client with params similar to this to use a bearer flow.
```
client = new Client({
  ..
  auth: {
    apiKey: apikey,
    OAuth2: true
  }
}) 
```

Thank you for your consideration.

**Comment by delvedor** [comment]
Hello! The client does not support OAuth, as it doesn't have any refresh logic.
You can still use it by providing custom authentication headers:
```js
const client = new Client({
  headers: {
    authorization: 'Bearer <token>'
  }
})
```
