### ISSUE TITLE
Erro ElasticSearch on Angular

### ISSUE THREAD

**Issue by Jonadersonmoura** [elastic/elasticsearch-js#1449]
I'm not able to use elastic in Angular 11. 
I import the elastic, and when I invoke the class, it gives these errors. 
Someone can help me. please.

![image](https://user-images.githubusercontent.com/22546157/115036468-ebed7e00-9ea3-11eb-9abb-5229bf036790.png)

**Comment by delvedor** [comment]
Hello! The browser environment [is not supported](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/installation.html#_browser), you should create a lightweight proxy in Node.js.
You can see a small example about how to do it [here](https://github.com/elastic/elasticsearch-js/tree/master/docs/examples/proxy).
