### ISSUE TITLE
filterPath in JavaScript msearch function

### ISSUE THREAD

**Issue by lsmilek1** [elastic/elasticsearch-js#1455]
Hello,

is there a way how to do it in JavaScript `msearch` function? There is no note in the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html) and trying following does not work:

```
const { body } = await esClient.msearch({
        filterPath: "hits.hits._id",
        body: mSearchBodies 
    })
    return body.responses 
```

Thank you!

_Originally posted by @lsmilek1 in https://github.com/elastic/elasticsearch-js/issues/721#issuecomment-825551548_

**Comment by delvedor** [comment]
Hello! The `filter_path` should start from the top-level keys of the response, in this case you should add `responses` as well.
For example: `filter_path: 'responses.hits.hits._id'`.

**Comment by lsmilek1** [comment]
Thank you, you are correct, I can confirm it works!
