### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by gricn** [elastic/elasticsearch-js#1456]
Although [#1345 ](https://github.com/elastic/elasticsearch-js/issues/1345) and [#1386 ](https://github.com/elastic/elasticsearch-js/issues/1386)have issued the same or similar question, this wield bug still exist. So I re-issue here.

## 🐛 Bug Report

**It seems elasticsearch module can't read Node.js global Objects such as `process` and `buffer`, because all of these objects are undefined when js run.**

## To Reproduce
No matter using `yarn create react-app ` or `npx create-next-app`, no matter using `Node 12.22.1` or `Node 14.16.1` (both are lts version), it will face the same situation.

**Steps to reproduce the behavior:**

It is much easier to find bugs using `create react-app`. I will use `create next-app` here because a CRA case already exists [#1345 ](https://github.com/elastic/elasticsearch-js/issues/1345)

- yarn create next-app test
- cd test
- yarn add @elastic/elasticsearch
- edit ./pages/index.js to require the library
```js
// ./pages/index.js

import Head from 'next/head'
import styles from '../styles/Home.module.css'

const { Client } = require('@elastic/elasticsearch')
const client = new Client({
  node: 'http://localhost:9200'
})

export default function Home() {
  return (
    <h1>Hello!</h1>
  )
}
```

- yarn dev

- error reported in the browser:

```
Unhandled Runtime Error
TypeError: Cannot read property 'split' of undefined

Source
.next/static/chunks/pages/index.js (22:0) @ Object.<anonymous>

  20 | 'use strict'
  21 | 
> 22 | const nodeMajor = Number(process.versions.node.split('.')[0])
  23 | 
  24 | const { EventEmitter } = require('events')
  25 | const { URL } = require('url')
```

- Open `./node_modules/@elastic/elasticsearch/index.js` and change `const nodeMajor = Number(process.versions.node.split('.')[0])` to `const nodeMajor = 14` and rerun `yarn dev`

- error reported in the browser:

```
.next/static/chunks/pages/index.js (39:0) @ Object.<anonymous>

  37 | const clientVersion = require('../package.json').version
  38 | const userAgent = `elasticsearch-js/${clientVersion} (${os.platform()} ${os.release()}-${os.arch()}; Node.js ${process.version})`
> 39 | const MAX_BUFFER_LENGTH = buffer.constants.MAX_LENGTH
  40 | const MAX_STRING_LENGTH = buffer.constants.MAX_STRING_LENGTH
  41 | 
  42 | class Transport {
```

- Open `./node_modules/@elastic/elasticsearch/lib/Transport.js` and change `const MAX_BUFFER_LENGTH = buffer.constants.MAX_LENGTH` to `const MAX_BUFFER_LENGTH = 4294967296` and rerun `yarn dev`

- error reported in the browser:

```
Unhandled Runtime Error
TypeError: Cannot read property 'MAX_STRING_LENGTH' of undefined

Source
.next/static/chunks/pages/index.js (40:0) @ Object.<anonymous>

  38 | const userAgent = `elasticsearch-js/${clientVersion} (${os.platform()} ${os.release()}-${os.arch()}; Node.js ${process.version})`
  39 | const MAX_BUFFER_LENGTH = 4294967296
> 40 | const MAX_STRING_LENGTH = buffer.constants.MAX_STRING_LENGTH
  41 | 
  42 | class Transport {
  43 |   constructor (opts) {
```

## Expected behavior

Successfully run without error.

## Your Environment

- *node version*: `14.16.1` and `12.22.1`
- `@elastic/elasticsearch` *version*: 7.12.0
- *os*: Win10

**Comment by delvedor** [comment]
Hello! The browser environment [is not supported](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/installation.html#_browser), you should create a lightweight proxy in Node.js.
You can see a small example about how to do it [here](https://github.com/elastic/elasticsearch-js/tree/master/docs/examples/proxy).

**Comment by gricn** [comment]
Thanks! After referring [this website](https://gist.github.com/rveitch/1b805b078a6e3cf1b2afd79acb9b984c) and using express.js, it works. I've used express.js before, but I didn't think of it for a while, because I'm currently only developing locally and doing a simple test. Hope this reply can help others.

**Comment by chrisworman-pela** [comment]
Reposting from #1345

@delvedor

Not all web clients are public web clients. What about an internal web client used to manage an ES instance? I know there are other tools (eg. Kibana), but I'm thinking about an internal tool that has specific business logic to manage the ES instance.

What arguments are there against this use case?

Also, it seems like you are relying on the string split function failing on the node versions to enforce the decision to not allow the client to be run in the browser. Was this by design?
