### ISSUE TITLE
overflow happens when sorting by a missing date field

### ISSUE THREAD

**Issue by mostafa-hz** [elastic/elasticsearch-js#1463]
## 🐛 Bug Report

I'm trying to sort my search query result based on a specific field and do key-set pagination with `search_after`. by the way when my desired field value is missing, I get an unexpected overflowed value in the `sort` result,  and afterward, when I use that value in `search_after` it throws `parse_exception`. in my case it gives `-922337203685477600` for descending order and `9223372036854776000` for ascending order.

## To Reproduce

I have an index with a nested field called `publishedAt` field with properties of type `date`.

```ts
xMapping = {
  index: 'x-index',
  body: {
    mappings: {
      dynamic: 'strict',
      properties: {
        publishedAt: {
          dynamic: false,
          properties: {
            en: { type: 'date' },
            fr: { type: 'date' },
          },
        },
        _tieBreakerId: { type: 'keyword' },
        // other fields...
      },
    },
    // other settings
  },
};
```
and here is my search request
```ts
const params: RequestParams.Search = {
  index: 'x-index',
  size: pagination.limit,
  sort: [
    '_score:desc',
   `${inputSort.field}:${inputSort.order}`, // 'publishedAt.en:desc',
    `_tieBreakerId:desc`,
  ],
  body: {
    search_after,
    query: {
      bool: {
        filter,
        should,
      },
    },
  },
};

const { body: { hits } } = await this.elasticsearchService.search(params);
console.log(hits.hits);
```

there is no problem as long as the record has a value for `publishedAt.en`
```json
[
  {
    "_index": "x-index",
    "_type": "_doc",
    "_id": "5f15789078bdf833d7a93e09",
    "_score": 142.47437,
    "_source": {
      "publishedAt": {
        "en": "2020-08-17T00:00:39.224Z"
      },
      "_tieBreakerId": "5f15789078bdf833d7a93e09"
    },
    "sort": [
      142.47437,
      1597622439224,
      "5f15789078bdf833d7a93e09"
    ]
  }
]
```
but as soon as `publishedAt.en` becomes empty, it returns such a result:
```json
[
  {
    "_index": "x-index",
    "_type": "_doc",
    "_id": "5ff878f0c42f004c6883643f",
    "_score": 67.737076,
    "_source": {
      "publishedAt": {},
      "_tieBreakerId": "5ff878f0c42f004c6883643f"
    },
    "sort": [
      67.737076,
      -9223372036854776000,
      "5ff878f0c42f004c6883643f"
    ]
  }
]
```

## Expected behavior

I expect a reasonable value that I can parse and continue the pagination. I have temprory fixed my problem by giving a value for `missing`  property of `sort`:

```ts
const params: RequestParams.Search = {
  index: 'x-index',
  size: pagination.limit,
  body: {
    search_after,
    sort: [
      { _score: 'desc' },
      {
        [inputSort.field]: {
          order: inputSort.order,
          missing: 0,
        },
      },
      { _tieBreakerId: 'desc' },
    ],
    query: {
      bool: {
        filter,
        should,
      },
    },
  },
};
```

but it raises problems when I want to get the sort as an input from the client and I don't have any idea what default value I can use for the missing fields!

## Your Environment

- *node version*: **v13.12.0**
- `@elastic/elasticsearch` *version*: **^7.12.0**
- *os*: **Ubuntu 20.04.2 LTS 64-bit**

**Comment by delvedor** [comment]
Hello! I believe this question should better be asked in our [discuss](https://discuss.elastic.co/) forum :)

**Comment by mostafa-hz** [comment]
Hello @delvedor
I thought it could be a bug in the nodeJS package implementation, as long as it seems to be a variable overflow.
tnx for your response, I'll ask about any possible solution there. :pray:

**Comment by legopin** [comment]
@mostafa-hz Did you manage to find answers on the forum? I tried searching on the forum and couldn't find a thread with this title.

**Comment by mostafa-hz** [comment]
@legopin no, I haven't yet asked nor found an answer! there was just only a post with a similar issue in the PHP client implementation.

**Comment by wealwaysyetifortrees** [comment]
I'm seeing a similar issue, and I'm 90% sure this is being caused by the fact that you can't safely represent the max negative/positive long int values in JS without using BigInt (I don't think). If you inspect what ES is returning from a "desc" search you'll see that its returning "-9223372036854775808" in the JSON, but after parsing the value becomes "-9223372036854776000". I made a very hacky piece of code that does this:

```
let searchAfter = [
  67.737076,
  -9223372036854776000,
  "5ff878f0c42f004c6883643f"
] // the sort value you want to use as search_after
searchAfter = searchAfter.map( ( i ) => {
  if ( i === -9223372036854776000 ) {
    return BigInt( -9223372036854775808 )
  }
  return i
} )
// do your search as expected here where search_after is the fixed array
```
That seems to make errors like this go away (I was also seeing it when sorting by boolean values), but I feel like this should be handled by the library if at all possible.
