### ISSUE TITLE
Field Collapse functionality missing from JS Client

### ISSUE THREAD

**Issue by olivercarlson** [elastic/elasticsearch-js#1464]
## 🐛 Bug Report

Attempting to use [Field Collapse](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/collapse-search-results.html) parameter with the js package throws the error 

> unrecognized parameter: [collapse]

 when sending a request using the npm package. 

Sending via HTTPS (e.g Postman) produces the expected results and does not throw an error. 

Mentioned in #1099 and #787

## To Reproduce

1. Create valid query with collapse parameter and test it on an ES instance and test it using Postman/HTTPS

e.g: 
```js
GET /my-index-000001/_search
{
  "query": {
      match: { hello: 'world' }
  },
  "collapse": {
    "field": "user.id"                
  }              
}
```

2. Attempt to use the same query with the npm package:
```js
const result = await client.search({
    index: "my-index",
    body: {
      query: {
        match: { hello: "world" },
      }
    },
    collapse: {
      field: "user.id"
    }
  })
```

## Expected behavior

Field collapse does not throw an error and works identical to HTTPS behavior. 

## Your Environment

- *node version*: 12
- `@elastic/elasticsearch` *version*: >=7.0.0
- *os*: OSX 10.15.7

**Comment by delvedor** [comment]
Hello! You should move the `collapse` inside the `body`.
