### ISSUE TITLE
Typescript: Incomplete definition track_total_hits parameter

### ISSUE THREAD

**Issue by deftomat** [elastic/elasticsearch-js#1475]
The value for `track_total_hits` should be:  `number | boolean`.

As mentioned in https://github.com/elastic/elasticsearch-js/issues/956, it was fixed. Unfortunately, not for version `7.*`

The fix is in `master` but not in `7.13`.

**Comment by delvedor** [comment]
Hello! Unfortunately the `boolean | number` is only present in Elasticsearch master, according to the [rest-api-spec](https://github.com/elastic/elasticsearch/blob/7.13/rest-api-spec/src/main/resources/rest-api-spec/api/search.json#L208-L211). I'll look into this.
