### ISSUE TITLE
No preference value for msearch

### ISSUE THREAD

**Issue by ADrejta** [elastic/elasticsearch-js#1482]
I noticed that when looking at the API reference that [msearch api](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_msearch) does not have a preference value like [mget](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_mget) does.

Shouldn't the msearch api also have a preference value you can pass to?

**Comment by delvedor** [comment]
Hello! As far as I know, the msearch API does not have a `preference` query parameter that you can set.
