### ISSUE TITLE
Headers Send to Response Event Should Reflect Headers Actually Sent

### ISSUE THREAD

**Issue by astorm** [elastic/elasticsearch-js#1483]
## 🚀 Feature Proposal

This issue is intended to open a discussion about whether the state of the `@elastic/elasticsearch` client should reflect the actual headers sent in an HTTP(s) request or if these headers should remain the headers the client intends to set.

For example -- when setting up an event listener for the response event _with_ the Elastic APM Agent active

    const apm = require('elastic-apm-node').start({/*...*/})
    const { Client } = require('@elastic/elasticsearch')
    const client = new Client({/*...*/})
    client.on('response', (error, event) => {
      // the value contains the headers that the @elastic/elasticsearch
      // library intended to set, and not the final headers sent to
      // with the HTTP request.  It is missing the traceparent and tracestate 
      // headers set on the request
      console.log(event.meta.request.params.headers)
    });

    async function main() {
      apm.startTransaction('testing a thing')
      await client.cat.indices()
      apm.endTransaction()
    }
    main()

The headers in `event.meta.request.params.headers` are 

    {
      'user-agent': 'elasticsearch-js/7.13.0 (darwin 19.6.0-x64; Node.js v14.16.1)',
      'accept-encoding': 'gzip,deflate',
      'x-elastic-client-meta': 'es=7.13.0,js=14.16.1,t=7.13.0,hc=14.16.1'
    }

but the actual headers set are 

    {
      authorization: 'Basic d...4',
      'user-agent': 'elasticsearch-js/7.13.0 (darwin 19.6.0-x64; Node.js v14.16.1)',
      'accept-encoding': 'gzip,deflate',
      'x-elastic-client-meta': 'es=7.13.0,js=14.16.1,t=7.13.0,hc=14.16.1',
      traceparent: '00-9899991fb53cff6fa940e4d900daf02e-fdaaada94acb92a3-01',
      tracestate: 'es=s:1'
    }

The `@elastic/elasticsearch` is missing the trace parent and trace state headers set by the agent.  It's also missing the authorization header set by -- something else?

## Motivation

The request grew out of a discussion over on the Elastic Node.js GitHub issues.

https://github.com/elastic/apm-agent-nodejs/issues/2116

There was some confusion as to whether the Node.js Agent was setting the trace parent and trace state headers based on the values returned by the `@elastic/elasticsearch`

## Example

An end-user-programmer would examine the headers while debugging an issue related to a header not sent by the client. 

An end-user-programmer would use the header values when deciding how the results of an API request should be processed.

**Comment by trentm** [comment]
> It's also missing the authorization header set by -- something else?

That's set by node's http client code, e.g. here: https://github.com/nodejs/node/blob/v14.16.1/lib/_http_client.js#L274-L277

While a "headers" property *is* on the `<RequestEvent>.meta.request.params` property, it isn't an exported field in the ES client's types: https://github.com/elastic/elasticsearch-js/blob/4933e3b9bec474511233f5a05819e493060a86e2/lib/Transport.d.ts#L70-L101  (Perhaps, separately, it could be added to the types.)

I don't think the ES client's `<RequestEvent>.meta.request.params.headers` should be expected to reflect what headers might be added lower in the HTTP client and HTTP agent -- even more so what headers might be added by APM agent monkey-patching of the HTTP client.  At best, perhaps https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/observability.html docs could be updated to note that the data is the clients view of the sent data -- data that might be extended or modified by the HTTP client/agent.

**Comment by delvedor** [comment]
You are right, the observability headers only show the headers configured by the transport layer. The authentication is currently set by the Connection class, which is the low level http client.
Unfortunately, I don't think I can do much here.

**Comment by mshustov** [comment]
> You are right, the observability headers only show the headers configured by the transport layer

Copying my answer from the root issue:
`@elastic/elasticsearch` client is already coupled with `http` layer: for example,  `headers` leak into the ES client interface. From this point of view, it might be reasonable to have access to all the headers sent. Or don't have access to them at all, if we consider a network layer to be an implementation detail.

**Comment by delvedor** [comment]
I could update the `Connection` class to gather all the headers sent and propagate them back to the `Transport` which then emits the `response` event, that would contain all the headers sent.
Would that be ok for you? Unfortunately this can't be done in the `request` event.
Also, I'm not sure how to gather all the headers sent, the documentation is not very helpful. Any suggestion?
