### ISSUE TITLE
[ES] client not support search on all index with match string

### ISSUE THREAD

**Issue by vaibhavpatil-symblai** [elastic/elasticsearch-js#1485]
## 🐛 Bug Report

[ES] client not support search on all index with match string

## To Reproduce

yellow open auditlogs3-2021.07.08 cPxSHm-8SQmYQsBxYLYEjQ 1 1 11 0 75.7kb 75.7kb
yellow open auditlogs3-2021.07.09 yi0NKt1FTcO5fVD0kd7G4g 1 1  1 0 23.4kb 23.4kb
Paste your code here:

```js
client.search({
    index:'auditlogs*',
    q: '*'

});
```

## Expected behavior

Above query should search on all index

```js

```

## Your Environment

- *node version*: 6,8,10
- `@elastic/elasticsearch` *version*: >=7.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by delvedor** [comment]
Hello! The client does support index matching, what error are you getting back?
Did you by any change disabled [`search.allow_expensive_queries`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html#query-dsl-allow-expensive-queries)?
