### ISSUE TITLE
Support _mvt endpoint

### ISSUE THREAD

**Issue by thomasneirynck** [elastic/elasticsearch-js#1489]
## 🚀 Feature Proposal

Support the `_mvt` endpoint.

`_mvt` is a new endpoint for geo-data that returns a binary response https://github.com/elastic/elasticsearch/issues/58696

An initial version has been merged into master behind a feature-flag https://github.com/elastic/elasticsearch/pull/73872.

## Motivation

This will be required for JS-clients. Specifically, the Maps-application in Kibana will need to use this.

## Example

```

// Get binary mvt-tile with  coordinate 1/3/2, for geo-field `geometry` of index `tornadoes`
const mvtTile = await client.mvt({
   index: 'tornadoes',
   x: 3,
   y: 2,
   z: 1,
   field: 'geometry'
   body: {...}
);
```

cc @iverase

**Comment by delvedor** [comment]
I'll open a PR to support the new content type directly in the client.

**Comment by delvedor** [comment]
Done in https://github.com/elastic/elasticsearch-js/pull/1500.
