### ISSUE TITLE
Possible to use the bulk API to remove fields?

### ISSUE THREAD

**Issue by dpkirchner** [elastic/elasticsearch-js#1495]
Is it possible to use the client's bulk API interface to delete fields from a document? If so, could you point me to the docs? I know you have to send two objects to do the update but I'm not sure where the script object would go.

Related: Is it possible to remove fields and update the other document in the same bulk request? Like if I'm sending this:

```
{"update": {"_id": "xyz", "_index": :"index"}}, {"doc": {"field": "value"}}
```

where would I put the script that removes a different field?

**Comment by delvedor** [comment]
Hello! Yes, you can remove a field with the update action by using a script, following a kibana console example:

```
PUT test-bulk

POST /test-bulk/_doc/1
{
  "foo": "bar",
  "bar": "baz"
}

GET /test-bulk/_doc/1

POST /_bulk
{ "update" : {"_id" : "1", "_index" : "test-bulk"} }
{ "script" : "ctx._source.remove('bar')" }
```
