### ISSUE TITLE
ES Client seems to wait for all results when multiple searches occur close together

### ISSUE THREAD

**Issue by dhatcher** [elastic/elasticsearch-js#1496]
## 🐛 Bug Report

When multiple searches get called in close succession the client seems to wait for all of the results before any of them return. In extreme cases this causes timeouts but in all cases it means none of the results are returned until they are all received.  
## To Reproduce

Send off a number of search requests in a row, I use an array of search queries. Listening and sending back the timings for each request will show them all return in about the same timeframe. 

Paste your code here:

```js
'use strict';

const config = require('config');
const {Client} = require('@elastic/elasticsearch');


let queries = config.queries;
console.log('starting queries');

queries.forEach((query, index) => {
   doQuery(query, index);
});


async function doQuery(query, index){
    try {
        let client = new Client(config.es);
        let startTime = Date.now().valueOf();
        console.log(`starting query ${index}`);
        let documents = await client.search(query);
        let totalTime = Date.now().valueOf() - startTime;
        console.log(`query ${index} done in ${totalTime/1000} seconds`);
    } catch (e) {
        console.error(e);
    }
}
```

Sample Query:
```
{
      "index": "image-footprint",
      "body": {
        "query": {
          "bool": {
            "must": [
              {
                "exists": {
                  "field": "FOOTPRINT"
                }
              }
            ],
            "filter": [
              {
                "geo_shape": {
                  "FOOTPRINT": {
                    "shape": {
                      "type": "envelope",
                      "coordinates": [
                        [
                          -45,
                          66.51326044311186
                        ],
                        [
                          0,
                          40.97989806962013
                        ]
                      ]
                    },
                    "relation": "intersects"
                  }
                }
              }
            ]
          }
        },
        "size": 5000
      },
      "_source": [
        "NAME",
        "NBANDS",
        "IMAGEID",
        "FOOTPRINT"
      ]
    }
```

## Expected behavior

I would expect the results to come through as each request finishes, so the first request in this case should always finish in around 7 seconds with the other ones at worst following after it, at best being run in parallel so that all requests are completing in around 7 seconds total.

Paste the results here:

results with 4 queries:
```
starting queries
starting query 0
starting query 1
starting query 2
starting query 3
query 0 done in 24.998 seconds
query 3 done in 26.395 seconds
query 1 done in 26.773 seconds
query 2 done in 26.891 seconds
```
results with just the first query:
```
starting queries
starting query 0
query 0 done in 7.677 seconds
```

As you can see it looks like all 4 queries finished and then results are sent out. Each query finishing in around 6-7 seconds.

## Your Environment

- *node version*: 14.15.1
- `@elastic/elasticsearch` *version*: >=7.13.0
- *os*: Windows
- *any other relevant information*

**Comment by delvedor** [comment]
I tried to reproduce this with a slightly different configuration, I’ve used this repo test dataset and a simpler query.`

```js
'use strict'

// const { createReadStream } = require('fs')
// const { join } = require('path')
// const split = require('split2')
const { Client } = require('@elastic/elasticsearch')

const INDEX = 'test-bench'

const query = {
  index: INDEX,
  body: {
    query: {
      match: { title: 'javascript' }
    }
  }
}

// const client = new Client({ node: 'http://localhost:9200' })

for (let i = 0; i < 4; i++) {
  doQuery(i).catch(err => {
    console.log(err)
    process.exit(1)
  })
}

async function doQuery (count) {
  try {
    const client = new Client({ node: 'http://localhost:9200' })
    const startTime = Date.now().valueOf()
    console.log(`starting query ${count}`)
    await client.search(query)
    const totalTime = Date.now().valueOf() - startTime
    console.log(`query ${count} done in ${totalTime / 1000} seconds`)
  } catch (e) {
    console.error(e)
  }
}

// async function indexData () {
//   await client.indices.create({ index: INDEX })
//   const stream = createReadStream(join(__dirname, 'test', 'fixtures', 'stackoverflow.ndjson'))
//   const result = await client.helpers.bulk({
//     datasource: stream.pipe(split()),
//     refreshOnCompletion: true,
//     onDocument (doc) {
//       return {
//         index: { _index: INDEX }
//       }
//     }
//   })
//   if (result.failed > 0) {
//     throw new Error('Failed bulk indexing docs')
//   }
//   console.log('done')
// }

// indexData().catch(err => {
//   console.log(err)
//   process.exit(1)
// })
```

I don’t see what you are seeing, but the query and dataset are smaller, which might influence the test.
One recommendation I would give you is to always use the same client instance, if you fire multiple request, each one with its own newly created client, you will spend a lot of time doing over and over the initial TCP handshake, while if you reuse the same client instance, you should see better results.
Furthermore, given the asynchronous nature of Node.js, if you send all the request *almost* at the same time, it’s expected to see similar duration numbers.

**Comment by dhatcher** [comment]
Yes this issue has only shown up on relatively large data sets with large results.  This query is against 2.6 million polygon documents and returning 5,000 documents per query.

I only switched to new client instances to see if it would possibly clear up the bottleneck but it did not.

I understand the asynchronous nature of node but waiting 26 seconds to get any results when they individually take around 6 seconds is a real issue for us. I would even be okay if it took 26 seconds to get all of the results if the individual queries were returning one every 6 seconds or so.

**Comment by delvedor** [comment]
I find really hard that the problem is in the client itself, as there is no code that “waits for other parts to finish”.
How are you running the client and Elasticsearch?

**Comment by dhatcher** [comment]
I'm seeing this behavior on single node ES clusters as well as clusters with dozens of nodes.  All cases involve geometry queries. 

I'm running the exact code above for test cases to reproduce the problem. 

I wasn't trying to imply there was necessarily code waiting for everything to complete, just to describe the behavior I'm seeing.

**Comment by delvedor** [comment]
Where are you running the client?

**Comment by dhatcher** [comment]
On a separate windows machine in the command prompt. Or within IntelliJ.

**Comment by delvedor** [comment]
Are you able to reproduce the issue with another http client?
You can try with `node-fetch` in Node.js and with `curl` without using Node.js. In this way we can try to understand where the issue might be.

**Comment by dhatcher** [comment]
If I do the same 4 requests outside of node (I tested using Postman) the total time from start until I get all results back is about 5 seconds. Each request returns about 3 seconds after it is initiated.  I'll test node-fetch next and get back to you on that one.

**Comment by dhatcher** [comment]
Doing the requests with node-fetch has similar results to using the elasticsearch library. So I'm guessing the issue is something to do with how node handles processing all of the requests at once?
