### ISSUE TITLE
es index as db table

### ISSUE THREAD

**Issue by ccolonna** [elastic/elasticsearch-js#1506]
## 💬 Questions and Help

I have some collections (e.g. apple, pear, peaches) I need to index in elastic search. This collections comes from different data sources and i want to keep track of which collection comes from which data source.

I created a simple index, let's call it `mapping-index`, to act as a table and there I store my mapping information, every record is:
```
{
   indexName: es-search-index-with-pears,
   source: my-pears-db
},
{
   indexName: es-search-index-with-apples,
   source: my-apples-db
}
```

My problem is that test fails if I do:

```
client.index({
   index: "mapping-index",
   body: {
       ...
   }
   refresh: "true"
})
client.indices.exists({ index: "mapping-index" })    <= FALSE
```
I get a `false`.

While adding a timer of 5000ms in between of the two operation I receive a `true`. E.g.

```
client.index({
   index: "mapping-index",
   body: {
       ...
   }
   refresh: "true"
})
timer(5000)
client.indices.exists({ index: "mapping-index" })    <= TRUE
```
I receive a `true`

Can be somehow establish some sort of predictability in this behaviour? I need that to pass tests. I can accept a wait `t` or pass this flag and you will always be sure all operation will complete. Even if it will downgrade performance. I need this to test code. 
Consistency is not a requirement. In production I can get rid of the flag, but I should be sure that code works as expected in test.

**Comment by delvedor** [comment]
Hello! You should wait for the operation to finish, your code is not using callbacks and you are not waiting for the promise to resolve, so the two calls are being sent almost at the same time.

```js
async function run () {
  await client.index({
   index: "mapping-index",
   body: {
       ...
   },
   refresh: "true"
  })
  const response = await client.indices.exists({ index: "mapping-index" })
  console.log(response.body)
})

run().catch(err => {
  console.log(err)
  process.exit(1)
})
```
