### ISSUE TITLE
Emitting a `process.emitWarning` kills the parent application

### ISSUE THREAD

**Issue by afharo** [elastic/elasticsearch-js#1510]
The following piece of code emits a warning at the process level.

https://github.com/elastic/elasticsearch-js/blob/2d1505eb2b7ad05387ca8ba8a6874f580a126ecd/lib/Transport.js#L562

Node.js is terminating the application because of that process-level warning. IMO, given that we are marking the Product Check as successful (`this[kProductCheck] = 2` and `productCheckEmitter.emit('product-check', true)`), I would expect the warning to be less destructive.

What do you think?

**Comment by mshustov** [comment]
> Node.js is terminating the application because of that process-level warning

Could you link a source where I can read about it?
I cannot find confirmation in the docs https://nodejs.org/api/process.html#process_event_warning
And my local tests cannot confirm it either.

Might it be a Kibana-specific configuration to exit a process on a warning?

**Comment by afharo** [comment]
> Might it be a Kibana-specific configuration to exit a process on a warning? I'm not saying that we should use `emitWarning` though, maybe we can consider other options.

You are correct! It's a Kibana-specific behaviour:
https://github.com/elastic/kibana/blob/master/src/setup_node_env/exit_on_warning.js#L35-L49

One thing that could help is providing a custom code so we can catch that specific warning to filter it out from the current behaviour.

**Comment by delvedor** [comment]
We could emit the warning as `ProductNotSupportedError`, so it should be easier to detect it and act accordingly.

**Comment by afharo** [comment]
How about using the `type` provided by the `process.emitWarning`? https://nodejs.org/api/process.html#process_process_emitwarning_warning_type_code_ctor

Something like 
```js
process.emitWarning(
  'The client is unable to verify that the server is Elasticsearch due to security privileges on the server side. Some functionality may not be compatible if the server is running an unsupported product.',
  'ProductNotSupportedSecurityError'
)
```

For now, I added to Kibana the check to skip on the message: https://github.com/elastic/kibana/blob/master/src/setup_node_env/exit_on_warning.js#L37-L38 

But it always feels wrong to rely on the plain message since it can change over time.
