### ISSUE TITLE
Need to handle transient 401 responses when performing the Product check

### ISSUE THREAD

**Issue by afharo** [elastic/elasticsearch-js#1511]
## 🐛 Bug Report

While doing the Product check, if Elasticsearch is still booting up, it may occur that it first gets a 401 response, but trying later, it may go through.

However, in the following piece of logic, we give up after the first attempt: 
https://github.com/elastic/elasticsearch-js/blob/2d1505eb2b7ad05387ca8ba8a6874f580a126ecd/lib/Transport.js#L560-L564
And it could even kill the application if the process-level warnings are not handled (#1510).

## To Reproduce

1. Install the latest canary version.
2. Run your app, making any request to ES but `GET /` every 2s.
3. Start ES after your app is up and running.

## Expected behavior

I would expect the Product check to confirm the 401 response was not transient. Otherwise, a malicious attacker could get around the Product check by replying 401 on the first request attempt.

## Your Environment

- *node version*: v14.17.3
- `@elastic/elasticsearch-canary` *version*: 8.0.0-canary.14
- *os*: Mac
- *any other relevant information*

**Comment by mshustov** [comment]
> I would expect the Product check to confirm the 401 response was not transient. Otherwise, a malicious attacker could get around the Product check by replying 401 on the first request attempt.

If a malicious attacker wants to get around the product check it's just easier to inject `x-elastic-product` header (via a reverse proxy, for example).
I don't think it's a protection mechanism but rather a safety check against a misconfiguration.

**Comment by delvedor** [comment]
I agree with @mshustov, also if the attacker is already controlling your reverse proxy/network, you have way worse problems 😱 
The product check aims to verify that the client is connected to a supported ES release, so we can be sure that there will not be compatibility issues.
