### ISSUE TITLE
Connection Errors swallowed by Product check

### ISSUE THREAD

**Issue by afharo** [elastic/elasticsearch-js#1512]
## 🐛 Bug Report

When there is a misconfiguration in the connection config, so it creates any sort of connection errors (i.e.: no response, not a valid certificate, timeouts, ...), the new Product check will swallow those errors only to claim `"The client noticed that the server is not Elasticsearch and we do not support this unknown product."`

## To Reproduce

1. Run your app against `localhost:9200`, but no ES actually running in that port
2. Notice that, despite the Connection Errors `ECONNREFUSED`, the error returned by the client is a `ProductCheckError`.

## Expected behavior

I would expect the product check to occur only after the connection is established. This way I can troubleshoot a possible misconfiguration in my app.

## Your Environment

- *node version*: v14.17.3
- `@elastic/elasticsearch-canary` *version*: 8.0.0-canary.14
- *os*: Mac
- *any other relevant information*

**Comment by delvedor** [comment]
Thanks for reporting! This bug has already been solved in https://github.com/elastic/elasticsearch-js/pull/1498 :)
The fix it's present in the latest canary release.
