### ISSUE TITLE
[Product check] Run on every reconnection?

### ISSUE THREAD

**Issue by afharo** [elastic/elasticsearch-js#1513]
## 🚀 Feature Proposal

Ideally, the Product check feature should apply to every host in the nodes array. When a new connection is established, I think that the first-request Product check should run, and not only on the first connection when the app started.

What do you think?

## Motivation

If the app is misconfigured with a list of nodes where 1 node is a valid Elasticsearch node, but the next one is not (`nodes: [validES:9200, notValidES:9200]`). The current behaviour will highly depend on which host is picked first to attempt the first connection:
- If the client picks `notValidES:9200` as the first node to connect, the validation will result in _Unknown Product_, and the App will refuse to work.
- If the client picks `validES:9200` during startup, the validation will resolve positively. Then, if the node goes down, and the client routes the following requests to `notValidES:9200`, it will work.

Another potential scenario: `validES:9200` is supposed to be a valid address. However, due to some architectural misconfiguration, it's routing the traffic to a non-valid product. We currently need to restart the app after fixing the routing. Ideally, the app should be able to restore the connection, and validate that the product is now correct (or vice-versa).

**Comment by delvedor** [comment]
Hello! I would say that this is an edge case that should not happen. If the user uses bad URLs there isn't much we can do!
If you know you are working with a multi-node cluster, you can enable the node discovery feature of the client and you should be good to go :)
I fear that running the check on every connection will cause a performance impact that does not justify the feature, so for now, I'll keep it as is.
If in the future we'll see that it makes sense to have a more advanced check, we can revisit this :)
