### ISSUE TITLE
The new product version check rejects oss distributions?

### ISSUE THREAD

**Issue by RTodorov** [elastic/elasticsearch-js#1519]
## 💬 Questions and Help

@delvedor Is there a reason why the new product version check introduced in 7.14.0 doesn't accept distributions with `oss` as flavor?

https://github.com/elastic/elasticsearch-js/blob/master/lib/Transport.js#L591-L595

```
          if (result.body.version.build_flavor !== 'default') {
            debug('Bad build_flavor')
            this[kProductCheck] = 4
            return productCheckEmitter.emit('product-check', null, false)
          }
```

**Comment by dlocke-rheaply** [comment]
This issue is a breaking change for us. IMO a minor version update (7.13 -> 7.14) should not introduce a change like this, it should only be included in a major version update.

**Comment by philkra** [comment]
With the `7.11` release of Elasticsearch, we will no longer be releasing oss-only distributions, as stated in the [FAQ on license change](https://www.elastic.co/pricing/faq/licensing). The recommendation is to upgrade to the latest default distribution of Elasticsearch, which is free to use under [Elastic License v2](https://www.elastic.co/licensing/elastic-license).

Please review the client's [compatibility](https://github.com/elastic/elasticsearch-js#compatibility) that states the forward compatibility. The recommendation is to upgrade the server first, then the client. If you are blocked to upgrade the cluster, we're happy to help you unblock the situation or please pin the client to an `<7.14` version according to your cluster.

**Comment by RTodorov** [comment]
IMHO this breaking change shouldn't happen in a minor release although I'm well aware of all the political situation involved here. Some people simply do not have the choice of not using AWS' flavor and you're intentionally hurting them with this.

A much more user-friendly approach would be for this check to be a warning stating that compatibility is not guaranteed with non-Elastic flavors instead of a fatal error that for sure caused lots of critical incidents around the world for ES users, at least until 8.0.0.

**Comment by jo3n** [comment]
We're also having this issue. It is a breaking change and bringing our entire production environment to a halt.

**Comment by dlocke-rheaply** [comment]
@jo3n Apparently there are no plans to fix this in 7.14, so the solution is to pin your dependency on 7.13.

**Comment by xfournet** [comment]
It look likes we should move to new clients of OpenSearch that should be available soon.
See https://aws.amazon.com/blogs/opensource/keeping-clients-of-opensearch-and-elasticsearch-compatible-with-open-source/

**Comment by futin** [comment]
I can also confirm that downgrading to `7.13` fixed this issue. But really disappointing that `minor` update broke our whole production. Everyone should definitely look for an alternative since this was a very unpleasant experience.

**Comment by gustavolsilvano** [comment]
I've already downgraded elasticsearch to 7.13, but the problem still happens. 
![image](https://user-images.githubusercontent.com/58196647/130656724-7bca3405-bdc7-4c60-9a55-cb43f0225f2d.png)

I'm using @acuris/aws-es-connection to connect to AWS, is it the one that is causing me trouble?

**Comment by Dmitry1987** [comment]
But Elastic Cloud is trash, low quality service, we had outage for 3 days with no support, and in a few months another outage for 1 day with no support - it's impossible to reach their teams when there are outages... I even called their office back then and they do not pick up the phone

**Comment by MomentQYC** [comment]
Since you're supposedly re-embracing open source, you should just ditch this restriction.

**Comment by alper** [comment]
Late to the party but we just got bit by this.

**Comment by rubnogueira** [comment]
Same. Ridiculous behavior pushing a minor version that purposefully creates a breaking change for existing users.
