### ISSUE TITLE
Typescript elasticsearch types `AggregationsRangeAggregation` have a missing property `keyed`.

### ISSUE THREAD

**Issue by briceruzand** [elastic/elasticsearch-js#1524]
## 🐛 Bug Report

Typescript elastic types `AggregationsRangeAggregation` have a missing property `keyed`.

According to [elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html#_keyed_response_4), we can use a property named `keyed`.

> Range aggregation : Keyed Response
>
> Setting the keyed flag to true will associate a unique string key with each bucket and return the ranges as a hash rather than an array:
> 
> ```json
> GET /_search
> {
>   "aggs": {
>     "price_ranges": {
>       "range": {
>         "field": "price",
>         *"keyed": true*,
>         "ranges": [
>           { "to": 100 },
>           { "from": 100, "to": 200 },
>           { "from": 200 }
>         ]
>       }
>     }
>   }
> }
> ```

The actual type `AggregationsRangeAggregation` definition does not have `keyed` property.
https://github.com/elastic/elasticsearch-js/blob/969decde2840113d1f45eca4624c532afbdb24e7/api/types.d.ts#L3033-L3037

`AggregationsRangeAggregation` types should be as below : 

```ts
export interface AggregationsRangeAggregation extends AggregationsBucketAggregationBase {
  field?: Field
  keyed?: boolean,
  ranges?: AggregationsAggregationRange[]
  script?: Script
}
```

Thx

**Comment by delvedor** [comment]
Thanks for reporting! It will be fixed in the next release.

**Comment by briceruzand** [comment]
Hello @delvedor ,
elasticsearch-js@7.15 still  not have theses properties, is that normal ?
Thx
