### ISSUE TITLE
Elastic Search Index Data not coming in App Search

### ISSUE THREAD

**Issue by yg-yash** [elastic/elasticsearch-js#1529]
I have created a full stack app in which from nodejs i ingest data in elastic search to a particular index(app search index)

const result = await client.index({
      index: ".ent-search-engine-documents-carssearch",
      id,
      body: {
        vin: "Asdad",
        year: 2103,
        make: "ACURA",
        model: "Asdad",
      },
      refresh: true,
    });

the data is getting added to the index i have checked in kibana console and using api also but in the index is pointed to app seach but in app search only id is getting added and when i open a particular document the page keeps getting loaded nothig happens

and in my front end part i the search engine also getting id of data nothing else

{
    "_meta": {
        "engine": "carssearch",
        "score": 1,
        "id": "9152a491-3c23-402d-97b4-55d688cf0dc51629490910415"
    },
    "id": {
        "raw": "9152a491-3c23-402d-97b4-55d688cf0dc51629490910415"
    }
}

![image](https://user-images.githubusercontent.com/45752285/130292540-d83298c0-5035-40bc-8524-c621c9d492c8.png)

**Comment by yg-yash** [comment]
@delvedor

**Comment by delvedor** [comment]
Hello! For interacting with app search you should use the [app search client](https://github.com/elastic/app-search-javascript).
