### ISSUE TITLE
Is it still suppose to support OSS? breaking since new productCheck (7.14.0)

### ISSUE THREAD

**Issue by JeanMGirard** [elastic/elasticsearch-js#1530]
## 💬 Questions and Help

Is it still to support the OSS flavor, as specified in the documentation [7.x api reference](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/7.x/api-reference.html) ?   
My cluster on AWS Elasticsearch service wont work since the new version

if so, the product check at [Transport.js Line 594](https://github.com/elastic/elasticsearch-js/blob/5447acb5348ae59b422dbf750fc1baf2cb966128/lib/Transport.js#L594) is breaking it... it should allow the "oss" flavor as well

**Comment by delvedor** [comment]
Hello! Please see https://github.com/elastic/elasticsearch-js/issues/1519.
