### ISSUE TITLE
How to use new typescript types?

### ISSUE THREAD

**Issue by darkLord19** [elastic/elasticsearch-js#1532]
I am following this document https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/typescript.html here to use new types but when I do `import { Client } from '@elastic/elasticsearch/api/new';` and try to run the app it doesn't work

**Comment by delvedor** [comment]
Hello! You are missing a couple of lines :)

```ts
import { Client } from '@elastic/elasticsearch'
import type { Client as NewTypes } from '@elastic/elasticsearch/api/new'

// @ts-expect-error @elastic/elasticsearch
const client: NewTypes = new Client({
  node: 'http://localhost:9200'
})
```

**Comment by darkLord19** [comment]
@delvedor from the documentation I thought we have to add ts expect error only if migrating from old client and so wasn't doing that. Thanks a lot for the answer and video.
