### ISSUE TITLE
Suddenly getting error `The client noticed that the server is not a supported distribution of Elasticsearch` 

### ISSUE THREAD

**Issue by DavidFaizulaev** [elastic/elasticsearch-js#1533]
Hello,

I'm using @elastic/elasticsearch version ^7.5.0 and Node 14. Everything worked fine, and suddenly we are getting the following error:

`The client noticed that the server is not a supported distribution of Elasticsearch`

We did not make any code changes, only ran yarn upgrade which made various changes in yarn.lock file and since then I'm getting the following error:

I tried upgrading `@elastic/elasticsearch` to latest version ^7.14.0, but it did not resolve the issue.

Nothing changed in AWS configuration either, what can be the cause for this error?

Please advise.

**Comment by delvedor** [comment]
Hello! Please see https://github.com/elastic/elasticsearch-js/issues/1519.
