### ISSUE TITLE
Is there a way to prevent credentials from being included in the Error object returned when the ES client throws an Error?

### ISSUE THREAD

**Issue by mattcobley** [elastic/elasticsearch-js#1537]
When the Elasticsearch JS client throws, the Error object contains a LOT of information, including some sensitive info such as the username and password if it is sent in the auth header of the request. Is there a way of tuning the client to NOT include information that may be sensitive in this error object, or to exclude certain URLs or object properties from the information that is returned? 

I noticed that the information in question (in the example given of basic authentication) can be found in four places in the Error object:

1) `config.auth.username` and `config.auth.password`
2) `config.httpsAgent.sockets.[socket name]._httpMessage.res.responseUrl`
3) `config.httpsAgent.sockets.[socket name]._httpMessage._redirectable._options.auth`
4) `config.httpsAgent.sockets.[socket name]._httpMessage._redirectable._currentUrl`

If there isn't a way to currently do this then I'd be happy to submit this as a feature request.

Many thanks.

**Comment by delvedor** [comment]
Hello! Unfortunately, there is no way to fix this issue unless we remove all the metadata associated with an error, which would make the debugging experience way more complex.
As far as I know, there is no way to tell Node.js what to log in case an error is thrown. The client is [already](https://github.com/elastic/elasticsearch-js/blob/master/lib/Connection.js#L266-L304) hiding sensitive data if you log the error via the standard `inspec.custom` and `toJSON` methods, but apparently thrown errors do not follow this logic.

**Comment by mattcobley** [comment]
Okay no worries, thanks for the response!
