### ISSUE TITLE
Add missing migration API's for system features upgrade

### ISSUE THREAD

**Issue by sabarasaba** [elastic/elasticsearch-js#1561]
A few new API's were recently added to the ES migration API that are missing: one for retrieving system features that require migration and one for starting the migration process. See https://www.elastic.co/guide/en/elasticsearch//reference/master/migration-api-feature-upgrade.html

We've created the types for the response of the api's already in kibana if it's of any help (see [here](https://github.com/elastic/kibana/pull/113627/files#diff-83701d29345b41938f502ca1b19f1d642cc467645aaf8cc7ab2bf0c80ea3be27R264)).

**Comment by delvedor** [comment]
The 7.x client now has those APIs.
