### ISSUE TITLE
can Client be shared between parallel requests? 

### ISSUE THREAD

**Issue by geertbrit** [elastic/elasticsearch-js#157]
Is it save to share a single Client between parallel requests or should I create a pool?

**Comment by PauloFerreira25** [comment]
Hello sirs,

Sorry for bothering.

I use elasticsearch-js to connect to my elasticsearch server.

My structure is a single server and my configuration is the standard of documentation.

However, I can not see elasticsearch-js opening more than 1 connection to my elasticsearch server.

In summary, being a single server, there is not a pool of connections.

I believe that having 2 servers, the number of connections would rise to 2 only.

I looked at all the documentation and did not find where to switch to an effective pool.

What is the problem I'm identified with:
When I have 2 or more requests for elasticsearch-js, it is queuing up those requests.
Even if the origins are different.

That is, if my elasticsearch server can respond to 200 concurrent requests, elasticsearch-js is queuing for 1 concurrent request.

Would you have any help on that?

Thanks for listening

**Comment by PauloFerreira25** [comment]
Hello again.

I think I found the solution.

If this is not the best solution, please inform me.

```Javascript
'use strict'
const elasticsearch = require('elasticsearch');
const AgentKeepAlive = require('agentkeepalive');
const client = new elasticsearch.Client({
  hosts: [
    'http://127.0.0.1:9200',
  ],
  maxSockets: 100,
  requestTimeout: 500000,
  // log: 'trace'
  log: 'error',
  createNodeAgent(connection, config) {
    console.log(config);
    return new AgentKeepAlive(connection.makeAgentConfig(config));
  }
});

module.exports = client;
```

Thanks for listening.
