### ISSUE TITLE
[discuss] sort format in search API

### ISSUE THREAD

**Issue by mshustov** [elastic/elasticsearch-js#1589]
**version** `elasticsearch-js@canary.35`
**problem**:
`search` method support `sort` parameter that can be configured either in `body` or in `query`.
The problem is the `sort` passed in `body` and `query` has different syntax.
`sort: sortField:sortOrder` syntax is valid in the `query` but cannot be used when declared in `body.sort`. Unfortunately, it's hard to realize this syntax is invalid because the Elasticsearch error response will be a cryptic `all shard failed` message. 

There are several options to fix the problem
- make the client smart enough to detect `sort: sortField:sortOrder` syntax and put `sort` parameter in query. Not sure it's a good option in the long term as it requires the `elasticsearch-js` client to cover all the possible API deviations in the future.
- reduce API surface to support `sort: SearchSortContainer` only. It doesn't allow  `sort: string` shorthand usage anymore but removes ambiguity in the accepted params.

cc @pgayvallet

**Comment by mshustov** [comment]
> and add a TypeScript deprecation tag on the querystring sort, similarly to what we are doing with body.

Since `body.sort` accepts strings too, it's hard to deprecate a specific format usage. We will have to add a runtime validation.

Deprecation tags aren't good for several reasons:
- not all library consumers use TypeScript
- it's easy to miss deprecated API usage. We should have a single mechanism to communicate deprecations. What do you use for other cases? the `warning` header, `process.warning`?

**Comment by tomtastico** [comment]
I see currently in v8.0.0, the type for `sort` in `SearchRequest` is `string | string[]`. 

https://github.com/elastic/elasticsearch-js/blob/main/src/api/types.ts#L969

So I can't really use the format shown in the docs https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html i.e. 

```
"sort" : [
    { "post_date" : {"order" : "asc", "format": "strict_date_optional_time_nanos"}},
    "user",
    { "name" : "desc" },
    { "age" : "desc" },
    "_score"
  ],
```

Gives a type error. I have to cast it to `any` to be able to use it.

**Comment by And2s** [comment]
> I see currently in v8.0.0, the type for `sort` in `SearchRequest` is `string | string[]`.
> 
> https://github.com/elastic/elasticsearch-js/blob/main/src/api/types.ts#L969
> 
> So I can't really use the format shown in the docs https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html i.e.
> 
> ```
> "sort" : [
>     { "post_date" : {"order" : "asc", "format": "strict_date_optional_time_nanos"}},
>     "user",
>     { "name" : "desc" },
>     { "age" : "desc" },
>     "_score"
>   ],
> ```
> 
> Gives a type error. I have to cast it to `any` to be able to use it.

Same problem here. It's typedef should be `sort: Sort | string | string[];`.
