### ISSUE TITLE
Update Dependencies & devDependencies ?

### ISSUE THREAD

**Issue by nelsonic** [elastic/elasticsearch-js#159]
Worth updating the **dependencies** ?
[![Dependencies](https://david-dm.org/elasticsearch/elasticsearch-js.png?theme=shields.io)](https://david-dm.org/elasticsearch/elasticsearch-js) [![devDependency Status](https://david-dm.org/elasticsearch/elasticsearch-js/dev-status.svg)](https://david-dm.org/elasticsearch/elasticsearch-js#info=devDependencies)

**Comment by MarkHerhold** [comment]
@nelsonic this can be closed

**Comment by nelsonic** [comment]
closing. thanks @MarkHerhold 👍
