### ISSUE TITLE
hits.total typed as number in typescript instead of object

### ISSUE THREAD

**Issue by RafaPolit** [elastic/elasticsearch-js#1604]
## 🐛 Bug Report

Query `hits.total` is typed as number, when it is now actually an object with 'value' and 'relation' keys according to the spec: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#hits-total-now-object-search-response

## To Reproduce

- get a javascript (nodejs) IDE working environment
- get the response of a query
- use autocomplete to navigate to `response.hits.total.value`, `total` is typed as a number and not the expected object

## Expected behavior

`total` should be typed as object with `value` and `relation` keys

## Your Environment

- *node version*: 14.18
- `@elastic/elasticsearch` *version*: ~7.10.0
- *os*: Linux

**Comment by delvedor** [comment]
`hits.total` can either be a long value or a structured object, based on the request's [`rest_total_hits_as_int`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html) value.

**Comment by stephenhmarsh** [comment]
This has been driving me crazy, though.  I cannot figure out what type to use for hits when it's not `rest_total_hits_as_int: true`

In other words, I'm forcing all my searches to use `rest_total_hits_as_int: true` just because I can't get Typescript to build with the `total.value` syntax.

Does anyone know what the proper types are??

Given:
```ts
export interface IPublicationSearchAppProps {
	hits: SearchHitsMetadata,
	// ... other stuff
}
```

Without `rest_total_hits_as_int: true` I always get:
```
components/publications/publications-search/index.tsx:256:88 - error TS2551: Property 'value' does not exist on type 'number | SearchTotalHits'. Did you mean 'valueOf'?
  Property 'value' does not exist on type 'number'.

256        <div className={styles.resultCount}>{resultsString({ total: props?.hits?.total?.value, page: page, perPage: PER_PAGE })}</div>
```

Even though `hits.total.value` is _**definitely a number.**_

<img width="1920" alt="Screenshot 2024-04-16 at 5 26 18 PM" src="https://github.com/elastic/elasticsearch-js/assets/6576730/44e8c8c9-fc46-4446-84b7-f693a4ef48c3">

**Comment by stephenhmarsh** [comment]
To clarify some more, assuming `SearchResponse` is the type for... the search response:

Here is the data with `rest_total_hits_as_int: true`:
```
{
web:dev:   took: 66,
web:dev:   timed_out: false,
web:dev:   _shards: {
web:dev:     total: 2,
web:dev:     successful: 1,
web:dev:     skipped: 0,
web:dev:     failed: 1,
web:dev:     failures: [ [Object] ]
web:dev:   },
web:dev:   hits: {
web:dev:     total: 1824,
web:dev:     max_score: null,
web:dev:     hits: [
web:dev:       [Object], [Object],
web:dev:       [Object], [Object],
web:dev:       [Object], [Object],
web:dev:       [Object], [Object],
web:dev:       [Object], [Object]
web:dev:     ]
web:dev:   },
```

Where I get this error:
```
components/publications/publications-search/index.tsx:256:61 - error TS2322: Type 'number | SearchTotalHits' is not assignable to type 'number'.
  Type 'SearchTotalHits' is not assignable to type 'number'.

256        <div className={styles.resultCount}>{resultsString({ total: props?.hits?.total, page: page, perPage: PER_PAGE })}</div>
                                                                ~~~~~

```

And without:
```
{
  web:dev:   took: 22,
  web:dev:   timed_out: false,
  web:dev:   _shards: {
  web:dev:     total: 2,
  web:dev:     successful: 1,
  web:dev:     skipped: 0,
  web:dev:     failed: 1,
  web:dev:     failures: [ [Object] ]
  web:dev:   },
  web:dev:   hits: {
  web:dev:     total: { value: 1824, relation: 'eq' },
  web:dev:     max_score: null,
  web:dev:     hits: [
  web:dev:       [Object], [Object],
  web:dev:       [Object], [Object],
  web:dev:       [Object], [Object],
  web:dev:       [Object], [Object],
  web:dev:       [Object], [Object]
  web:dev:     ]
  web:dev:   },
  ```
  

  
I still get:
  ```
components/publications/publications-search/index.tsx:256:88 - error TS2551: Property 'value' does not exist on type 'number | SearchTotalHits'. Did you mean 'valueOf'?
  Property 'value' does not exist on type 'number'.

256        <div className={styles.resultCount}>{resultsString({ total: props?.hits?.total?.value, page: page, perPage: PER_PAGE })}</div>
```
  
<img width="1920" alt="Screenshot 2024-04-16 at 5 54 25 PM" src="https://github.com/elastic/elasticsearch-js/assets/6576730/f7907e3b-41ed-49e9-91f1-0e7743c18cc9">

**Comment by JoshMock** [comment]
@stephenhmarsh what version of Elasticsearch are you using? In the 8.x client, this appears to be fixed.

https://github.com/elastic/elasticsearch-js/blob/b857d8ee71fa28ce6378746edfd445a60fbd283a/src/api/types.ts#L1670-L1673

**Comment by stephenhmarsh** [comment]
@JoshMock thanks for asking. Been getting this for a while on 8.12 and previous, but still getting it even on `8.13.1` which is latest as of today.

I have to do `rest_total_hits_as_int` with:
```ts
import { SearchHitsMetadata } from '@elastic/elasticsearch/lib/api/types'; // 8.13.1
export interface IPublicationSearchAppProps {
	// ...
	hits: SearchHitsMetadata & {
		total: number 
	},
}
```

otherwise: `(total: props?.hits?.total)` will still have:
 ```Type 'number | SearchTotalHits' is not assignable to type 'number'.
  Type 'SearchTotalHits' is not assignable to type 'number'.ts(2322)
  ```

**Comment by stephenhmarsh** [comment]
@JoshMock Ah okay, thanks for your help!  Hope this thread helps anyone else that runs into this.
