### ISSUE TITLE
Add map callback to bulk helper

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-js#1610]
Right now you pass a stream of `TDocument` to client.helpers.bulk. 

If you need to take contextual decisions in the `onDocument` callback `TDocument` might not be enough. It would be helpful if we can pass a stream of wrapped documents and unwrap the actual document to serialize using a `map` handler to `client.helpers.bulk()`

**Comment by delvedor** [comment]
Closed in https://github.com/elastic/elasticsearch-js/pull/1606.

**Comment by lennartnederstigt** [comment]
@delvedor How's this issue actually addressed by #1606? Doesn't seem to be the case, unless I'm missing something. I'd really like this functionality as well.

**Comment by JoshMock** [comment]
This has been improved in https://github.com/elastic/elasticsearch-js/pull/1732, which will be shipped in 8.8.2 and 8.9.0 next week. Docs for how to use this improvement are in https://github.com/elastic/elasticsearch-js/pull/1951.
