### ISSUE TITLE
[typescript] SearchRequest type not constant with API

### ISSUE THREAD

**Issue by nreese** [elastic/elasticsearch-js#1615]
[Search API documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-request-body) types docvalue_fields as "array of strings and objects"

<img width="600" alt="Screen Shot 2022-02-03 at 7 29 12 AM" src="https://user-images.githubusercontent.com/373691/152342993-6cf03c17-eb0b-4081-8423-a9763215c13a.png">

This usage is not reflected in the typing provided by this library.

```
// Relevant typings from https://github.com/elastic/elasticsearch-js/blob/main/src/api/types.ts.
export interface SearchRequest extends RequestBase {
  docvalue_fields?: Fields
}
export type Fields = Field | Field[]
export type Field = string
```

The correct fix is that `Field` should be type as:
```
export type Field = string | { field: string; format: string; }
```

All usages for Fields in SearchRequest should type Field as string or object.

This error greatly effects usage of typings in Kibana. Kibana heavily uses setting fields to an object so that format can be specified. For example, when getting any date, format is applied so dates are returned in a consistent format.

**Comment by Rihyx** [comment]
I found out that in docs the sorting for search is still an Object:
```
GET /my-index-000001/_search
{
  "sort" : [
    { "post_date" : {"order" : "asc", "format": "strict_date_optional_time_nanos"}},
    "user",
    { "name" : "desc" },
    { "age" : "desc" },
    "_score"
  ],
  "query" : {
    "term" : { "user" : "kimchy" }
  }
}
```

But `SearchRequest` type has sorting as `string | string[]`

```
export interface SearchRequest extends RequestBase {
    .....
    index?: Indices;
    sort?: string | string[];
    ......
}
```

**Comment by nreese** [comment]
@delvedor

How was this closed, looking at the only PR referencing this issue - https://github.com/elastic/elasticsearch-js/pull/1693 and the changes, Field is still only typed as `export type Field = string` and not  `export type Field = string | { field: string; format: string; }`. Am I missing something? I think this issue should be re-opened.

**Comment by delvedor** [comment]
`Field` if correct, the issue was the `docvalue_fields` definitions, which now have been updated to https://github.com/elastic/elasticsearch-js/blob/5603482c43ee81ef7badf2d050752c30d050fe13/src/api/types.ts#L962.

**Comment by nreese** [comment]
thanks for clarifying. Yes, the new typing for docvalue_fields resolves the issue.
