### ISSUE TITLE
Export SniffingTransport

### ISSUE THREAD

**Issue by ddolcimascolo** [elastic/elasticsearch-js#1635]
:sweat_smile:  Part of my "Upgrading to v8 is too complicated" series of issues

## 🚀 Feature Proposal

Export the SniffingTransport class

## Motivation

I'm extending the Transport class in my code to override request() in order to add custom query params to searches. Upgrading to v8 of the client indirectly made me lost support for sniffing, because that's now implemented in a Transport subclass that's not extended.
To be honest, we're close to a bug because if you don't have specific tests for sniffing, you're screwed as the change can go totally unnoticed.

Workaround for now

```
const { default: SniffingTransport } = require('@elastic/elasticsearch/lib/sniffingTransport'),
```

## Example

```
const { SniffingTransport } = require('@elastic/elasticsearch');

class MyTransport extends SniffingTransport {}
```

Thx,
David

**Comment by delvedor** [comment]
Heya, you are right! We'll release a fix for this :)
