### ISSUE TITLE
v8 changelog is missing update_by_query and delete_by_query removals

### ISSUE THREAD

**Issue by ddolcimascolo** [elastic/elasticsearch-js#1636]
:sweat_smile:  Part of my "Upgrading to v8 is too complicated" series of issues

## 🐛 Bug Report

client.update_by_query and client.delete_by_query disappeared in v8  
The change itslef is not a bug and fixing is a matter of renaming method calls to their corresponding camel-cased equivalents, but this is indeed a breaking change and the [changelog](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/8.0/changelog-client.html) does not mention it.

Can you add that to the list of breaking changes?

## Your Environment

- *node version*: 16
- `@elastic/elasticsearch` *version*: 8.0.0
- *os*: Linux

Thx,
David

**Comment by delvedor** [comment]
Thanks for the catch! I'll update the changelog :)
