### ISSUE TITLE
v8 changelog is missing client.ilm.putLifecycle breaking change

### ISSUE THREAD

**Issue by ddolcimascolo** [elastic/elasticsearch-js#1638]
:sweat_smile:  Part of my "Upgrading to v8 is too complicated" series of issues

## 🐛 Bug Report

client.ilm.putLifecycle params now accept `name` for the policy name instead of `policy` previously. This was probably required as `policy` is part of the body, cf. "removal of the body key" breaking change. 
The change itself is not a bug and fixing is a matter of renaming the `policy` param to `name`, but this is indeed a breaking change and the [changelog](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/8.0/changelog-client.html) does not mention it.

Can you add that to the list of breaking changes?

## Your Environment

- *node version*: 16
- `@elastic/elasticsearch` *version*: 8.0.0
- *os*: Linux

Thx, 
David

**Comment by delvedor** [comment]
Thanks for the catch! I'll update the changelog :)
