### ISSUE TITLE
Provide guidance to mocking undici 

### ISSUE THREAD

**Issue by ddolcimascolo** [elastic/elasticsearch-js#1639]
:sweat_smile:  Part of my "Upgrading to v8 is too complicated" series of issues

## 🚀 Feature Proposal

Provide guidance, code samples, or at least links to useful documentation about undici and more importantly, the way to mock it. 

## Motivation

In v8 undici is the default http client. If you had client tests mocking the HTTP calls they now fail miserably because all your mocking does not work (e.g. Using the excellent [nock](https://github.com/nock/nock) library) 

For now, I just resorted to using the old `HttpConnection`. Undici feels a bit like early adoption currently, to be honest. The ecosystem is very poor and that's an issue for enterprise apps... 

## Example

N/A

Thx, 
David

**Comment by delvedor** [comment]
Hello! `undici` does provide a mocking utility, you can find it [here](https://undici.nodejs.org/#/docs/best-practices/mocking-request).
Furthermore, v8 support for our [Elasticsearch mock utility](https://github.com/elastic/elasticsearch-js-mock) is coming.

**Comment by ddolcimascolo** [comment]
Great, looking forward to testing that!
