### ISSUE TITLE
[docs] Dropdown version is showing different version than page body

### ISSUE THREAD

**Issue by adriaanvanrossum** [elastic/elasticsearch-js#1644]
Today when you go to https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-connecting.html ([archive](https://web.archive.org/web/20220228232050/https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-connecting.html)) you will see this page:

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/1079135/156074844-4e405ef5-18ff-4ea6-a7b7-646b5768088c.png">

The version numbers are quite mixed and cost me a few hours of my day. It's possible this happens for more people. It would be great if all version numbers would align.

The dropdown shows 8.0, but the page body shows 7.16, and the URL shows current.

Maybe current is not the latest version, but the version mismatch is the bigger issue here.

**Comment by delvedor** [comment]
Hello! Sorry for the confusion! We have fixed this issue, let me know if you are still encountering it.

**Comment by adriaanvanrossum** [comment]
Perfect, thanks for the quick fix!
