### ISSUE TITLE
Error: request [/_transform] contains unrecognized parameter: [transformId]

### ISSUE THREAD

**Issue by cwiechmann** [elastic/elasticsearch-js#1645]
## 🐛 Bug Report

Javascript transform API is not accepting `transformId` even it's documented here: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/8.0/api-reference.html#_transform_gettransform and was working well with version 7.x.y. 
The same happens for all transform methods.

## To Reproduce

The following code fails with the following error:
```js
const client = new Client( { "some-elastic-config": "my-config" } );
client.transform.getTransform({ transformId: `myTransformId` });
```
Error:
```
ResponseError: illegal_argument_exception: [illegal_argument_exception] Reason: request [/_transform] contains unrecognized parameter: [transformId]
    at SniffingTransport.request (node_modules\@elastic\transport\lib\Transport.js:476:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Transform.getTransform (node_modules\@elastic\elasticsearch\lib\api\api\transform.js:72:16)
    at async putTransform (src\actions\transform.js:57:26)
    at async Object.method.action (src\index.js:659:19) {
```

## Expected behavior

Using the parameter: `transform_id` it's working as expected. I expect the same behavior also when using `transformId`.

```js
const client = new Client( { nodes: 'http://my-elasticsearch:9200'} );
client.transform.getTransform({ transform_id: `myTransformId` });
```

## Your Environment

- *node version*: 12.13.0
- `@elastic/elasticsearch` *version*: >=@elastic/elasticsearch@8.0.0
- *os*: Windows

**Comment by delvedor** [comment]
Hello! Thank you for catching this!
The [reference](https://github.com/elastic/elasticsearch-js/blob/main/docs/reference.asciidoc) page has not been updated for v8, we'll do that soon.

Regarding your issues, camelCase parameters are no longer supported.
