### ISSUE TITLE
undefined caFingerprint can trigger an error for a http connection

### ISSUE THREAD

**Issue by stsourlidakis** [elastic/elasticsearch-js#1659]
## 🐛 Bug Report

When creating a new client , an `undefined` caFingerprint can trigger an error for a http connection.

## To Reproduce

```js
const { Client } = require('@elastic/elasticsearch');

const node = 'http://localhost:9200';

// This works
new Client({
  node
});

// This works
new Client({
  node,
  caFingerprint: null,
});

// This throws "You can't configure the caFingerprint with a http connection"
new Client({
  node,
  caFingerprint: undefined,
});

```

## Cause
I think the problem is that an explicitly set `undefined` value will overwrite the default `null` value during the `Object.assign` [here](https://github.com/elastic/elasticsearch-js/blob/v8.1.0/src/client.ts#L159) and then it gets strictly compared with `null` [here](https://github.com/elastic/elasticsearch-js/blob/v8.1.0/src/client.ts#L189-L191).

## Expected behavior

I would expect this not to throw an error.
A use-case is a function that creates ES clients for multiple clusters, with only some of the connections having a caFingeprint available.

```js
const { Client } = require('@elastic/elasticsearch');

const client1 = createClient('https://localhost:9200', 'some-ca-fingerprint');
const client2 = createClient('http://localhost:9201'); // this one is http, we don't need a CA fingerprint

function createClient(host, caFingerprint) {
  return new Client({
    node: host,
    caFingerprint,
  });
}
```

The workaround is easy, you can just have `null` as your parameter's default value but I think the current behaviour is a bit strange and might cause bugs.

## Your Environment

- *node version*: v14.19.0
- `@elastic/elasticsearch` *version*: 7.17.0
- *os*: Ubuntu 20.04

Thank you,
Stavros

**Comment by delvedor** [comment]
Hello! IMHO this is a borderline situation to define if this is a bur or not, as in theory if you don't need to configure a CA fingerprint, you shouldn't pass it at all.
But for the sake of keeping the API flexible, and given that the change required to support this is rather small, we'll ship it.
Meanwhile, you can update your code to use a default value for the `caFingerprint` parameter.

```js
function createClient(host, caFingerprint = null) {
  return new Client({
    node: host,
    caFingerprint
  })
}
```

**Comment by stsourlidakis** [comment]
I agree, this is an edge case. It took me some time to debug this so I decided to create an issue in case someone else has this problem in the future.
Thank you for addressing it! :tada:
