### ISSUE TITLE
Unable to create documents in data stream using bulk function

### ISSUE THREAD

**Issue by Frank-from-JITbase** [elastic/elasticsearch-js#1660]
## 🐛 Bug Report

Attempting to create documents in a data stream using the bulk helper.  Index template has a `@timestamp` property defined and document has a `@timestamp` property with a date value.

**Note:** documents are successfully created in the data stream when calling the `client.create()` function individually on each document.

error message:
```json
{
  "create": {
    "_index": ".ds-my-ds-index-2022.03.10-000001",
    "_type": "_doc",
    "_id": "613cfd0cdf58923100c9d8b3",
    "status": 400,
    "error": {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse",
        "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "data stream timestamp field [@timestamp] is missing"
        }
    }
  }
}
```

## To Reproduce

```js
// template and ilm policy already created in elasticsearch
const index = 'my-ds-index'
const myDocs = [
  {'@timestamp': new Date(), 'someParam':'someVal'},
  {'@timestamp': new Date(), 'someParam':'someVal'},
]

const body = myDocs.flatMap(doc => [
  {create:{}},
  doc
]);

const res = await client.bulk({
    index,
    body,
});
```

## Expected behavior

Documents created in data stream without error

## Your Environment

- *node version*: 16.3.0
- `@elastic/elasticsearch` *version*: 7.17.0
- *os*: Mac

**Comment by delvedor** [comment]
Hello! The following code looks not valid js code:
```js
const myDocs = [
  {['@timestamp']: new Date(), someParam='someVal'},
  {['@timestamp']: new Date(), someParam='someVal'},
]
```
