### ISSUE TITLE
Unkown settings type=illegal_argument_exception, reason=unknown setting [index.settings.analysis.analyzer.my_analyzer.tokenizer] please check that any required plugins are installed, or check the breaking changes documentation for removed settings

### ISSUE THREAD

**Issue by vgoyal-ontic** [elastic/elasticsearch-js#1664]
I am making a spring Boot application and giving the settings of an elasticsearch index using the @Settings(Path) annotation. Now when I run the program I get the following error

error":org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=unknown setting [index.settings.analysis.analyzer.english_stop.tokenizer] please check that any required plugins are installed, or check the breaking changes documentation for removed settings]

Settings:
{
  "settings": {
    "analysis": {
      "analyzer": {
        "english_stop": {
          "tokenizer": "whitespace",
          "filter": [ "my_custom_stop_words_filter" ]
        }
      },
      "filter": {
        "my_custom_stop_words_filter": {
          "type": "stop",
          "ignore_case": true
        }
      }
    }
  }
}
Mapping

{
  "mappings": {
    "properties": {
      "text": {
        "type": "text",
        "analyzer": "english_stop",
        "fielddata": true
      },
      "id":{
        "type": "text"
      }
    }
  }
}

build.gradle

	implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.projectlombok:lombok:1.18.20'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
	implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch:2.6.2'
	testImplementation 'org.springframework.security:spring-security-test'
	implementation 'com.google.code.gson:gson:2.8.9'
	testImplementation 'org.awaitility:awaitility:3.1.2'

	implementation 'org.elasticsearch:elasticsearch-analysis-ik:5.1.1'

I think I need to add some dependency. can someone help

**Comment by delvedor** [comment]
Hello! This is the repository for the JavaScript client for Elasticsearch.
I'd recommend asking this question in our [discuss forum](https://discuss.elastic.co/) :)
