### ISSUE TITLE
Can we use this with React Native as well ?

### ISSUE THREAD

**Issue by MuhammadAbdullah54321** [elastic/elasticsearch-js#1677]
I am trying to use this with react native but getting a lot of error 
some times ...it cant find `http`
then it cant find `zlib`
it also cant find `os`

what's that i am doing wrong

**Comment by delvedor** [comment]
Hello! This module is designed to work in Node.js only.
I recommend using a proxy to send requests to Elasticsearch, so you can avoid exposing your ES instance to the world.
You can find an example [here](https://github.com/elastic/elasticsearch-js/tree/main/docs/examples/proxy).
