### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by pinturic** [elastic/elasticsearch-js#1678]
## Multiple Clients 

You are mentioning [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/child.html) that:

> There are some use cases where you may need multiple instances of the client. You can easily do that by calling new Client() as many times as you need, but you will lose all the benefits of using one single client, such as the long living connections and the connection pool handling.

Can you clarify what are the uses cases for having multiple clients point to the same cluster ?
what benefits do I lose (and of course what do I gain) by having multiple clients for the same cluster?
why do I lose (and what do I lose)  long living connections and the connection pool handling?

I think this part should be documented.

**Comment by delvedor** [comment]
It depends on your use case! A typical one is that you may want to have different client instances with different users (so you organize the client by permissions).
If you use a new client instance for each user you will be using more resources, as each client will need to create and maintain its own connection pool.
If you use the `.child` API instead the connection pool will be shared, and as result, you won't have the overhead of having multiple connections for the same cluster.

**Comment by zhongnansu** [comment]
@delvedor Thanks. I wonder can I create `child` for different endpoint(node)?

**Comment by zhongnansu** [comment]
> 

Thanks, could you explain a bit where to increase the max number of open connections of client?
