### ISSUE TITLE
"async_hooks" module not found

### ISSUE THREAD

**Issue by JavBurgoa** [elastic/elasticsearch-js#1687]
Hi,

I encountered an issue when trying to import `@elastic/elasticsearch`  in Nextjs. It keeps on giving me the error `Module not found: Can't resolve 'async_hooks'`. I tried installing the `esmain@github:elastic/elasticsearch-js` version and the ES6/7 versions individually aswell with the same results. 
Weirdly enough, I found that installing all of these *together* made it work. However, when I installed `dotenv` for indeèndent reasons I got the error back, and I can't get rid of it now. I tried removing node_modules, getting the version of `package.json` that worked and running `npm install .`, but it didn't work. Needles to say I tried uninstalling `dotenv` and didn't work anyway.

## Code to reproduce the problem:

**In index.js:**
```js
var elastic = require("@elastic/elasticsearch")
```

**Then in powershell**
```bash
next dev
```

**The error:**
```
wait  - compiling...
wait  - compiling /trees...
'D:\my_next_app\node_modules\next\dist\compiled\stream-browserify\index.js'
Watchpack Error (initial scan): Error: ENOTDIR: not a directory, scandir 'D:\my_next_app\node_modules\next\dist\compiled\util\util.js'
error - ./node_modules/undici/lib/api/api-connect.js:4:24
Module not found: Can't resolve 'async_hooks'
```
## Environment

- *node*: v16.13.0
- `@elastic/elasticsearch` *version*: 8.1.0
- *os*: Windows
- *Next.js*: v12.1.6
- *package.json*:
``` 
{
  "name": "app_next",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "export": "next export"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.17.0",
    "@elastic/elasticsearch": "^8.1.0",
    "aws-sdk": "^2.916.0",
    "axios": "^0.24.0",
    "bootstrap": "^5.1.3",
    "es6": "npm:@elastic/elasticsearch@^6.8.8",
    "es7": "npm:@elastic/elasticsearch@^7.17.0",
    "esmain": "github:elastic/elasticsearch-js",
    "form-data": "^4.0.0",
    "formdata-node": "^4.3.1",
    "imagemin-mozjpeg": "^10.0.0",
    "imagemin-optipng": "^8.0.0",
    "imagemin-svgo": "^10.0.1",
    "minio": "^7.0.18",
    "mozjpeg": "7.1.0",
    "next": "^12.0.4",
    "next-optimized-images": "^2.6.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^6.2.2",
    "streamsaver": "^2.0.5"
  },
  "description": "This is a [Next.js](https://nextjs.org/) project bootstrapped with [`create-next-app`](https://github.com/vercel/next.js/tree/canary/packages/create-next-app).",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://git.embl.de/burgoa/evocell-app-nextjs.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "eslint": "7.32.0",
    "eslint-config-next": "12.0.4"
  }
}
```

Thanks in advance

**Comment by delvedor** [comment]
Hello! This module can be used in Node.js only, it cannot work in the browser.
You are seeing that error because you are trying to run the client in a browser context.

**Comment by JavBurgoa** [comment]
Hi! That was it! Such a silly mistake. I had removed the code from the getStaticProps() part (node.js part) that logs into Elasticsearch. Thank you.

Now, I'm just curious, do you know why importing the module and logging into elastic through the backend gives no error, but removing the code and thus only having the import of the module gives it? Maybe this is a more Next.js question though.

Anyway, thank you so much!

**Comment by delvedor** [comment]
Not sure how to help here, it might be a question for the Next.js team :)
