### ISSUE TITLE
Typescript search response has not a body, but the response has it in 8.2.0-patch.1

### ISSUE THREAD

**Issue by molaeiali** [elastic/elasticsearch-js#1692]
## 🐛 Bug Report
Typescript is telling me that `SearchResponse` does not have a `body` property

```
response.body.hits.hits

Property 'body' does not exist on type 'SearchResponse<unknown, Record<string, AggregationsAggregate>>'.ts(2339)
```

But when you console.log the response there is a body in there:

```
console.log
  { body: { hits: { hits: [Array], total: [Object] } } }
```

## To Reproduce

```ts
const response = await this.client.search({
    ...
});
console.log(response);
```

## Expected behavior
The response should not have a `body` field, or the typescript type should expect it to be there.

## Your Environment

- *node version*: 18.1.0
- `@elastic/elasticsearch` *version*: ^8.2.0-patch.1
- *os*: Linux

**Comment by dfernandesbsolus** [comment]
I have the same problem :(

**Comment by molaeiali** [comment]
> I have the same problem :(

For now I made it 
```
const response: any = await this.client.search({
```
until it's fixed
