### ISSUE TITLE
Current documentation on using keepAlive

### ISSUE THREAD

**Issue by tao** [elastic/elasticsearch-js#1698]
I can't seem to figure out if I should or how I should use `keepAlive` when creating the Client. 

I found lots of bugs and old issues mentioning it, and lots of results for `keepAlive` when searching in the legacy client (https://github.com/elastic/elasticsearch-js-legacy/search?q=keepAlive). However, I don't see any mention of using it now (or no longer needing to use it in the migration guide) and when I search this repository. 

I don't see it being used in the proxy example either but I'm worried about not setting up my cClient correctly without it and overloading my self-hosted ElasticSearch cluster.

Can you provide guidance or improve the documentation on when and how to use `keepAlive` or if it is no longer necessary to specify it when creating the Client?

**Comment by tao** [comment]
Ok, so it's enabled by default. It might be good to update the docs to mention that somewhere.

**Comment by sibelius** [comment]
I'm getting a lot of `ConnectionError: Socket connection timeout` when doing a lot of requests using elastic search client

is there a way to fix it?

keepAlive is still an option?

this is my config

```jsx
new Client({
      node: config.ELASTICSEARCH,
      maxRetries: 2,
      requestTimeout: 3000,
    })
    ````

**Comment by JoshMock** [comment]
@sibelius The default for `requestTimeout` is 30000. By reducing the default by a factor of 10, you're very likely to experience timeouts on slower requests.

**Comment by JoshMock** [comment]
> Ok, so it's enabled by default. It might be good to update the docs to mention that somewhere.

It does mention on [the intro page](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/introduction.html#_features) of the docs that connections are persistent and keep-alive. And on the [basic config](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/basic-config.html) page it notes that disabling the HTTP agent disables keep-alive connections.

I've also [opened a PR](https://github.com/elastic/elasticsearch-js/pull/2048) to add a section about keep-alive connections to the connection config page. If there are other places we can make that more clear, let me know.
