### ISSUE TITLE
Cannot connect to elasticsearch server with version "8.2.1"

### ISSUE THREAD

**Issue by HuseynQasimov** [elastic/elasticsearch-js#1710]
## 🐛 Bug Report

I tried to connect from a Node js app to Elasticsearch server with latest client package which is "8.2.1". But it says the server which is I am trying to connect is not a Elasticsearch server and Elasticsearch client do not support connection like that. How ever I downgraded client version to "7.13.0" and it worked without any other change.

```
client = new Client({
            node: `http://${config.get('elasticsearch.host')}`,
        });
```

## Expected behavior

To connect to server

## Result
```
The client noticed that the server is not a Elasticsearch server and Elasticsearch do not support it
```

## Your Environment

- *node version*: 14.17.5
- `@elastic/elasticsearch` *version*: =7.13.0
- *OS*: Windows 11
- *Server OS: Debian 10 (buster)

**Comment by pgayvallet** [comment]
Which version of ES were you trying to connect to? You are supposed to use a matching version of `@elastic/elasticsearch`. Could it be that you tried to connect to an ES 7.x with a version 8 of the client?

**Comment by HuseynQasimov** [comment]
Yes, the version compability was correct. A suspicious case was that I was connected to ES at first time. Problem was accured after server reboot. The problem fixed after remove and reinstall of ES.
