### ISSUE TITLE
`function_score` type missing `script_score`

### ISSUE THREAD

**Issue by eliseumds** [elastic/elasticsearch-js#1711]
According to [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-script-score), one can write the following query:

```json
{
  "query": {
    "function_score": {
      "query": {
        "match": { "message": "elasticsearch" }
      },
      "script_score": {
        "script": {
          "source": "Math.log(2 + doc['my-int'].value)"
        }
      }
    }
  }
}
```

However, the `script_score` key is not defined in [the TypeScript types](https://github.com/elastic/elasticsearch-js/blob/24890fd11d87c12fd6275c62f9b37dfd6cf1401a/src/api/types.ts#L4984-L4991) for `function_score`.

## Your Environment

- *node version*: 15
- `@elastic/elasticsearch`: 8.2.1

**Comment by JoshMock** [comment]
@eliseumds I do see that `script_score` is supported in `QueryDslFunctionScoreContainer`, but not `QueryDslFunctionScoreQuery`. :thinking: I'll take a look at the underlying spec when I have a chance to see if I can sort this out.

**Comment by JoshMock** [comment]
Actually, this looks to be caused by the same underlying issue mentioned here. https://github.com/elastic/elasticsearch-specification/issues/2109

Hopefully I can get back around to solving that soon.
