### ISSUE TITLE
I found a discrepancy  between the type and the documentation on MultiTermsAggregation

### ISSUE THREAD

**Issue by robscrak** [elastic/elasticsearch-js#1720]
## 💬 Questions and Help

Hi,

I am having a problem with the AggregationsMultiTermsAggregation.
The type inside the lib as no order property, but inside the documentation it is available. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-multi-terms-aggregation.html
/src/api/types.ts, (line 3276)

I am wondering if this discrepancy is normal, since it will be deprecated in the future.
If so what will be the new ways to order a multi terms aggregation?

Thank you for the help

**Comment by JoshMock** [comment]
This was [fixed](https://github.com/elastic/elasticsearch-js/commit/8f9ed67fda9f8887275a809b46dec23a358c7753) in 8.5.0.
