### ISSUE TITLE
Provide an ES Module entrypoint for @elastic/elasticsearch

### ISSUE THREAD

**Issue by adamyeats** [elastic/elasticsearch-js#1743]
Related to https://github.com/elastic/elasticsearch-js/issues/1281 and https://github.com/elastic/elasticsearch-js/issues/1742.

## 🚀 Feature Proposal

`@elastic/elasticsearch` is currently a CommonJS module. While CommonJS isn't going away any time soon, ECMAScript Modules are very much "the future" of the JavaScript ecosystem. As the community moves in this direction, it may be wise for us to consider moving this library in the same way.

To accommodate both CJS and ESM users, we might want to [create an ES module wrapper](https://nodejs.org/api/packages.html#packages_approach_1_use_an_es_module_wrapper) that exports both a CJS and ESM version of the library.

At the very least, as suggested in https://github.com/elastic/elasticsearch-js/issues/1281, it would be good to make the type of the module explicit in `package.json` if we decide to remain with CJS for the time being.

## Motivation

This will allow the library to work in Deno, and enable asynchronous module loading in Deno and Node.js.

**Comment by JoshMock** [comment]
Still relevant. We've got Deno/Bun.js support on the long-term roadmap. I recently merged https://github.com/elastic/elasticsearch-js/issues/1281 to explicitly declare the library as a CommonJS package, but improving to include ESM support will be an important step toward multi-runtime compatibility.

**Comment by karfau** [comment]
FYI: I'm able to use `import * as elasticsearch from "npm:@elasticsearch/elasticsearch";` in Deno already without any issues.

**Comment by karfau** [comment]
4 months ago it was said it is still relevant

**Comment by JoshMock** [comment]
thanks for your patience, @karfau. I was on leave for 2 months, just getting back to addressing open issues now.

**Comment by karfau** [comment]
At least for more recent deno versions this might have been "resolved" by improved nodejs compatibility...

**Comment by JoshMock** [comment]
It would still be ideal to have good ESM support soon, since that's the unified standard everyone is moving toward. I managed to improve things a bit for `@elastic/transport` recently, so it should hopefully be relatively straightforward by adding `exports` metadata to package.json.

**Comment by harshulj** [comment]
#2348 This seems to have broken import in ECMAScript modules.

**Comment by JoshMock** [comment]
Fixed in https://github.com/elastic/elasticsearch-js/pull/2475
