### ISSUE TITLE
TypeError: client.ml.inferTrainedModel is not a function

### ISSUE THREAD

**Issue by truskavets-transf** [elastic/elasticsearch-js#1747]
## 🐛 Bug Report

The [inferTrainedModel](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_infer_trained_model) method is not recognized.

I am trying to create a semantic search functionality using Elastic and a Next.js frontend. As part of this process, I need to convert a string into an embedding vector. 

I am able to do this in the dev console without any issues:

```js
POST /_ml/trained_models/<model_id>/_infer
{
  "docs": {
    "text_field": "test string"
  }
}
```

However, when I try to call the same method using this library, I get an error saying that the method is not recognized: 

`TypeError: client.ml.inferTrainedModel is not a function`

The relevant code from the API route is here: 

```js
    try {
      const test = await client.ml.inferTrainedModel({
        index: 'embeddings-test',
        model_id: <model_id>,
        docs: { text_field: req.body },
      });
```

As a sanity check, I was able to successfully access other methods in the ml class, like the [getTrainedModelStats](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_get_trained_models_stats) method.

## To Reproduce

1. upload transformer model to Elastic (in this case, a custom fine-tuned BERT model)
2. create dense vector field in mapping
3. create API route to the inferTrainedModel endpoint in Next.js
4. send string to this route

## Expected behavior

An embedding vector in response to the inferTrainedModel request.

## Your Environment

- node version: 18.2.0
- `@elastic/elasticsearch` version: 8.2.1
- *os*: Mac
- framework: Next.js

**Comment by popmatik** [comment]
Heya. I've stumbled across this and found the solution was to not have an index declared . So removing 
` index: 'embeddings-test',`

Got things working for me. 
Cheers

**Comment by JoshMock** [comment]
This was [fixed](https://github.com/elastic/elasticsearch-js/commit/33e0873ecf44878acc8842ca8a94c953d2a63f79) in 8.4.0.
