### ISSUE TITLE
Incorrect type for mappings.dynamic property

### ISSUE THREAD

**Issue by gsoldevila** [elastic/elasticsearch-js#1796]
## 🐛 Bug Report

The `client.indices.get()` API returns a String for the `mappings.dynamic` property, even when specifying a boolean.
This is error prone:
```ts
// dynamic === 'false'
if (response.mappings.dynamic) {
  console.log('ouch!');
}
```

## To Reproduce

Create and retrieve a new index using the Dev Console:

```
PUT /test_index
{
  "mappings": {
    "dynamic": false
  }
}

GET /test_index
```

Notice how the `dynamic` property comes back as a String
```
{
  "test_index": {
    "aliases": {},
    "mappings": {
      "dynamic": "false"
    },
    "settings": {
      "index": {
        "routing": {
          "allocation": {
            "include": {
              "_tier_preference": "data_content"
            }
          }
        },
        "number_of_shards": "1",
        "provided_name": "test_index",
        "creation_date": "1669631337348",
        "number_of_replicas": "1",
        "uuid": "bUae4NZHTFu00mL0zH7pfw",
        "version": {
          "created": "8040099"
        }
      }
    }
  }
}
```

## Expected behavior

We'd expect the `dynamic` property to have the correct type (in this case, a `boolean`).

## Your Environment

- *node version*: 16
- `@elastic/elasticsearch` *version*: 8.6.0
- *os*: Mac

**Comment by gsoldevila** [comment]
Quick test reveals that the issue comes from ES side already:

```bash
> curl -X GET "kibana:changeme@localhost:9200/test_index?pretty" -H 'Content-Type: application/json'
```

So all in all, the safest / easiest solution might be to define the `mappings.dynamic` as a `string` instead.

**Comment by JoshMock** [comment]
This one is labeled as an `@es_quirk` in [the spec](https://github.com/elastic/elasticsearch-specification/blob/4cb8d4d9388da285c6da53d2b4c2d5d297cf400c/specification/_types/mapping/dynamic-template.ts#L38). The JS code generator should be handling it as a special case. I'll take a look soon.
