### ISSUE TITLE
How to check index status

### ISSUE THREAD

**Issue by priscofarina** [elastic/elasticsearch-js#1799]
Hi guys, 
   I am tryng to get how to verify the index status (closed/open) and if there is a way to map its status to the healthy of the cluster.

How can I verify such status?
Should I check the status of the cluster first and then iterate on each index ?
Thank you for the help

**Comment by JoshMock** [comment]
You can use the [`client.indices.get`](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_get_4) API for this.
