### ISSUE TITLE
8.6.0 breaks usage over PrivateLink: SniffingTransport Forbidden

### ISSUE THREAD

**Issue by jamieparkinson** [elastic/elasticsearch-js#1834]
## 💥 Regression Report
An application running in an AWS VPC and making requests to a cluster in Elastic Cloud via a VPC Endpoint and AWS PrivateLink (as per [Elastic docs](https://www.elastic.co/guide/en/cloud/current/ec-traffic-filtering-vpc.html)) ceased to function after we upgraded the Elasticsearch client to version 8.6.0, failing with the following error:

```
ResponseError: {"ok":false,"message":"Forbidden"} 
  at SniffingTransport.request (/app/node_modules/@elastic/transport/src/Transport.ts:535:17)
```

I suspect this is related to the [upgrade](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/8.6/changelog-client.html#_8_6_0) of the `@elastic/transport` client dependency. The error was resolved by either downgrading the client, or connecting over the public internet.

The [docs](https://www.elastic.co/guide/en/cloud/current/ec-traffic-filtering-vpc.html) note that
> Transport client is not supported over PrivateLink connections.

but this is not well documented for the JS client: I can only find references to the deprecated Java Transport client. I expect this failure could well be expected behaviour (and that it worked previously was a coincidence and shouldn't have been relied upon), in which case I hope this issue is helpful to anyone else seeing the error.

It would be great to get some more clarity on this in the docs, and I'd be interested to know whether the roadmap for this client includes deprecation of Transport to match with the Java client: it would be very helpful for us to be able to use the JS client over PrivateLink.
 
## Last working version

Worked up to version: _8.5.0_

Stopped working in version: _8.6.0_

## To Reproduce

1. Run an application in an AWS VPC that uses the 8.5.0 client (for example, a Fargate task) to query a cluster in Elastic Cloud via a PrivateLink
2. Upgrade the client to 8.6.0
3. See that the application's queries fail

## Expected behaviour

Queries using the JS client over PrivateLink succeed (or fail) consistently across versions.

**Comment by JoshMock** [comment]
> I suspect this is related to the [upgrade](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/8.6/changelog-client.html#_8_6_0) of the `@elastic/transport` client dependency. The error was resolved by either downgrading the client, or connecting over the public internet.

I'm fairly certain you're right about this being related to the upgrade of `@elastic/transport` from 8.3.0 to 8.3.1. That was the only significant code change between 8.5.0 and 8.6.0, aside from some adjustments to support changes to Elasticsearch APIs between stack release versions.

When comparing transport [8.3.0 to 8.3.1](https://github.com/elastic/elastic-transport-js/compare/90f653e56601fe5bb56e7c41eba0a996f5e8e39c...64d6fa2c734ac446e15d384c17f61bf5bb755a76#files_bucket), the main changes are the upgrade of [Undici](https://github.com/nodejs/undici) from 5.1.1 to 5.5.1, and more helpful context included in some error messages. So, my initial exploration will be on what changed in Undici between those two versions. My suspicion is that something changed that causes requests sent via PrivateLink to fail with a `Forbidden` where they weren't before.

@jamieparkinson Any extra context you can provide&mdash;raw request data from both 8.5.0 and 8.6.0, debug logs, specific API calls you're making&mdash;will help a lot!

As an aside: there's a sort of naming collision between [transport](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#transport-settings), the networking interface used by Elasticsearch to communicate between nodes, and [transport](https://github.com/elastic/elastic-transport-js/), the library that manages HTTP connections, requests, and responses between the Node.js client and an Elasticsearch cluster. In your case, the issue we're seeing is happening in the latter, whereas the former is what isn't supported via PrivateLink connections. Your confusion is totally warranted; I just wanted to clarify that, in case it helps guide your own investigation of the issue.

More to come soon!

**Comment by JoshMock** [comment]
@jamieparkinson Can you also let me know what version of Elasticsearch you're trying to connect to?

**Comment by JoshMock** [comment]
It would also be helpful to [open a support ticket](https://www.elastic.co/cloud/elasticsearch-service/support) so we can look at how your Elastic Cloud deployment is set up. Even if it's a bug in the client, we can see if it's somehow related to how your specific deployment is configured.

**Comment by JoshMock** [comment]
No worries! It was a fun and educational exploration. :laughing:
