### ISSUE TITLE
I recommend the development of a compatible Mongoose populate feature

### ISSUE THREAD

**Issue by janryWang** [elastic/elasticsearch-js#184]
I recommend the development of a compatible Mongoose populate feature, because the current situation is mongoose and elasticsearch.js not be completely smooth transition. If you can, I believe many people will be very grateful.

**Comment by norbertFeron** [comment]
+1

**Comment by spalger** [comment]
I'm interested in the option, can you provide some info about how such a feature would work?

**Comment by guumaster** [comment]
There is a plugin to automatically save `mongoose` models into `elasticsearch`, its called [mongoosastic](https://github.com/mongoosastic/mongoosastic), but it's currently lacking of a populate feature to save a document with populated data. (also, it depends on this project)
