### ISSUE TITLE
@elastic/elasticsearch npm library not working in mongodb realm function

### ISSUE THREAD

**Issue by Faisal-vyomr** [elastic/elasticsearch-js#1842]
I am trying to integrate @elastic/elasticsearch npm library in mongodb realm function. To achieve that I addded @elastic/elasticsearch as dependency.

```
exports = async function(arg){
const { Client } = require('@elastic/elasticsearch');
  try {
    const apiKey = context.values.get("ES_API_KEY");
    const cloudId = context.values.get("ES_CLOUD_ID");
    const client = new Client({
    cloud: {
        id: cloudID
    },
    auth: {
        apiKey
    }
})
   return client;
   
  } catch(err) {
    console.log("Error occurred while executing:", err.message);
    return { error: err.message };
  }
```

When I did so I get below error.

`failed to execute source for 'node_modules/@elastic/elasticsearch/index.js': FunctionError: failed to execute source for 'node_modules/@elastic/transport/index.js': FunctionError: failed to execute source for 'node_modules/@elastic/transport/lib/connection/index.js': FunctionError: failed to execute source for 'node_modules/@elastic/transport/lib/connection/UndiciConnection.js': FunctionError: failed to execute source for 'node_modules/undici/index.js': FunctionError: failed to execute source for 'node_modules/undici/lib/api/index.js': FunctionError: failed to execute source for 'node_modules/undici/lib/api/api-request.js': FunctionError: Cannot find module 'async_hooks'`

what is causing this issue?

**Comment by Faisal-vyomr** [comment]
It seems at this point of time mongodb functions does not support latest @elastic/elasticsearch version 8.

Downgrading version to 7.17.0 resolved this issue.

**Comment by JoshMock** [comment]
Thanks for following up, @Faisal-vyomr. I'd also note that the error `Cannot find module 'async_hooks'` suggests you might be using a version of MongoDB that depends on a Node.js version that's older than 8.x. If you have the ability to upgrade your MongoDB to the latest stable&mdash;which uses Node.js 10.18.1, if [these docs](https://www.mongodb.com/docs/atlas/app-services/functions/javascript-support/#built-in-modules) are accurate&mdash;you might find that the 8.x client works.

Closing this for now, but please reopen if you need more assistance.
