### ISSUE TITLE
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@elastic%2ftransport - Not found

### ISSUE THREAD

**Issue by dsaydon90** [elastic/elasticsearch-js#1894]
It seems that your package `@elastic/elasticsearch` is unable to find `@elastic/transport`

```
npm install @elastic/elasticsearch
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@elastic%2ftransport - Not found
npm ERR! 404 
npm ERR! 404  '@elastic/transport@^8.3.1' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2023-05-15T09_42_20_779Z-debug-0.log
```

related: https://github.com/elastic/elastic-transport-js/issues/65

**Comment by llllvvuu** [comment]
npm outage currently:

https://status.npmjs.org/incidents/drj38qn6qm59
https://github.com/search?q=+npm+ERR%21+404&type=issues&s=created&o=desc

**Comment by JoshMock** [comment]
Closing this as it appears to be an issue with npm rather than Elastic. Let us know if this recurs and appears to be a problem on our end.
