### ISSUE TITLE
proxy method provided has Undici connection can\'t work with proxies error

### ISSUE THREAD

**Issue by asde29873012549** [elastic/elasticsearch-js#1899]
It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `not reproducible` label.**

## 🐛 Bug Report

According to your documentation, i can simply provide an "proxy" key to the client object, but it always gives the Undici connection can\'t work with proxies.

## To Reproduce

Paste your code here:

```js
const client = new Client({
    node:'mynode',
    auth: {
        username: 'myname',
        password: 'mypassword'
      },
    proxy:'http://myproxy:myport'

```

## Expected behavior

Paste the results here:

```js
ConfigurationError: Undici connection agent options can't be a function or a boolean


```

## Your Environment

- *node version*: 14.19
- `@elastic/elasticsearch` *version*: >=8.5.0
- *os*: Windows
- *any other relevant information*

**Comment by vineetScaletech** [comment]
Any update on this @JoshMock ?
Can't connect with node version 20 to AWS hosted elasticsearch.

**Comment by JoshMock** [comment]
This is because the `UndiciConnection` is used by default, but proxy configurations are currently only supported by the `HttpConnection` class. You can configure your client to override this default during instantiation:

```js
import { HttpConnection } from '@elastic/transport'
import { Client } from '@elastic/elasticsearch'

const client = new Client({
  Connection: HttpConnection,
  proxy: '...',
})
```

I'm noticing that the docs currently do not indicate that this is necessary, so I'll update those to reflect this requirement until we can look into adding proxy support to `UndiciConnection`.

**Comment by JoshMock** [comment]
[Proxy connection docs](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-connecting.html#client-connect-proxy) now include a note about using `HttpConnection` in 8.0+ when you need to configure a proxy.
