### ISSUE TITLE
Documentation enhancement: creation of a client with elasticsearch.angular.js

### ISSUE THREAD

**Issue by kalumet** [elastic/elasticsearch-js#19]
Hi there,

unfortunately it is quite difficult for a newby in both angular and elasticsearch to get a grap on how to instantiate a client with elasticsearch.angular.js according to the documentation.

The example stated on http://www.elasticsearch.org/guide/en/elasticsearch/client/javascript-api/current/index.html#_setting_up_the_client_in_the_browser

```
// elasticsearch.angular.js creates an elasticsearch
// module, which provides an esFactory
var app = angular.module('app', ['elasticsearch']);
app.service('es', function (esFactory) {
  return esFactory({ ... });
});

is different to the example provided under 

http://elasticsearch.github.io/elasticsearch-js/

module.service('es', function (esFactory) {
  return esFactory({
    host: 'localhost:9200',
    // ...
  });
});
```

and in both cases I'm actually missing the step on how to actually retrieve the client. Could you please enhance the documentation by an explizit example?

Sorry to bother you,

many thanks and regards,

Kalumet

**Comment by BearandYoon** [comment]
I have a question.

**Comment by spalger** [comment]
@BearandYoon I recommend the elastic user forums https://discuss.elastic.co/
