### ISSUE TITLE
support for import instead of require

### ISSUE THREAD

**Issue by sdetweil** [elastic/elasticsearch-js#1914]
### Please note that this issue tracker is not a help forum and this issue may be closed.
I searched thru the issues, didn't see anything related

I am building an Ionic Vue app, and need to access our elasticsearch service.
the standalone nodejs client works fine, but, the vue system requires es6 import.

I hate to fall back to the http search

did I miss  something? all the examples use require()

**Comment by JoshMock** [comment]
@sdetweil all examples use `require` but `import` statements should also work. `import { Client } from '@elastic/elasticsearch'` should work just fine for your use case.

Closing this, but if you have issues using ES6-style imports feel free to reopen with more details.
