### ISSUE TITLE
problem about the version of elasticsearch.js and node.js

### ISSUE THREAD

**Issue by wxlfight** [elastic/elasticsearch-js#193]
when i install the elasticsearch ,i got this warn information:
npm WARN engine elasticsearch@3.1.3: wanted: {"node":">=0.8 <0.11"} (current: {"node":"0.11.14","npm":"2.0.0"})

as the log shows ,my node version is greater than 0.11, is there any problem with this?

**Comment by zenorocha** [comment]
+1

https://github.com/elasticsearch/elasticsearch-js/blob/3.1/package.json#L97

This should be updated now that Node 0.12 is out.

**Comment by hellboy81** [comment]
What about `io.js` and `0.12` support?

**Comment by karlbohlmark** [comment]
Yup, so far it seems to work with io.js though.

**Comment by spalger** [comment]
@karlbohlmark which version are you using? The tests are running find in 1.5 but I'm not sure how different 1.0 and 1.5 are

**Comment by spalger** [comment]
This should be resolved now
