### ISSUE TITLE
CamelCase variable Issue?

### ISSUE THREAD

**Issue by nexflo** [elastic/elasticsearch-js#197]
Could there be an issue with camelcased variables inside elasticsearch? or the client connector?

I've had a variable in there called consumerId, I mapped it using

```javascript 
 esearch.indices.putMapping({
    "index":"XY",
    "type":"consumer",
    "body":{
        "consumer":{
            "properties":{
                "consumerId": {
                    "type": "string",
                    "index": "not_analyzed"
                }
         }
     }
}})
```
But searching for it via filtered term always returned 0 results (other fields no camelcased, didnt have the issue). I reindexed the field with consumerid -> and voila everything was fine?!?

**Comment by spalger** [comment]
Hmm, I'm not sure what the issue is but the client doesn't touch anything in the body. If this is still an issue I'd suggest asking for help in the #elasticsearch channel on freenode.net
