### ISSUE TITLE
🐛 Bug: Snapshot repo settings is missing required types

### ISSUE THREAD

**Issue by DesAWSume** [elastic/elasticsearch-js#1988]
## 🐛 Bug Report

This typescript client is missing required type for the creating Snapshot repo (S3).
and it is missing require field like:
bucket,
base_path,
client

Reference:
https://www.elastic.co/guide/en/elasticsearch/reference/8.9/repository-s3.html

the most 3 important fields to successfully create the snapshot repo

## To Reproduce
Current interface
```js
export interface SnapshotRepositorySettings {
    chunk_size?: string;
    compress?: string | boolean;
    concurrent_streams?: string | integer;
    location: string;
    read_only?: string | boolean;
    readonly?: string | boolean;
}
Which will cause the Repository failed to create, 

```
Error:
ResponseError: repository_verification_exception
        Caused by:
                i_o_exception: Exception when listing blobs by prefix [index-]
        Root causes:
                repository_verification_exception: [xxx-xx-xx] path  is not accessible on master node

Paste your code here:

```js
    const resquest = client.snapshot.createRepository({
        type: 's3',
        name: repo,
        settings:{
            location: 'dev/abc',
            read_only: true,
            readonly: true,
        },
    })

```

## Expected behavior

Create the s3 snapshot repo with no issue
Paste the results here:
After manually modify the SnapshotRepositorySettings in type.ts under src/api/type.ts

it will create with no issue

```js
export interface SnapshotRepositorySettings {
    chunk_size?: string;
    compress?: string | boolean;
    concurrent_streams?: string | integer;
    location: string;
    read_only?: string | boolean;
    readonly?: string | boolean;
    client: string;
    base_path: string;
    bucket: string;
}


```

## Your Environment

- *node version*: 6,8,10
- `@elastic/elasticsearch` *version*: >=7.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by JoshMock** [comment]
Thanks for calling this out @DesAWSume! I referred to [the spec](https://github.com/elastic/elasticsearch-specification) we use to generate these type definitions and noticed that it was missing a lot of key differences between each of the snapshot repository types, so I've [opened a PR there](https://github.com/elastic/elasticsearch-specification/pull/2255) to resolve this for all repository types across all Elasticsearch clients.

**Comment by DesAWSume** [comment]
@JoshMock  Many Thanks!! Very looking forward this got moving forward, and appreciated your prompt turn around

**Comment by DesAWSume** [comment]
Any movement to this?

**Comment by JoshMock** [comment]
https://github.com/elastic/elasticsearch-specification/pull/2255 was finished and merged today. This fix will show up in the next minor release, 8.13.
