### ISSUE TITLE
Types - IndicesIndexSettingsKeys should allow for null values

### ISSUE THREAD

**Issue by diogoalmiro** [elastic/elasticsearch-js#2000]
## 🐛 Bug Report

According to the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html#reset-index-setting), to revert an index setting to the default value we should set its value to `null`.

## To Reproduce

There is no runtime error using `null`, running the following code:

```ts
import { Client } from "@elastic/elasticsearch";

let client = new Client({...});

client.indices.putSettings({
    index: "...",
    settings: {
        refresh_interval: null
    }
}).then(console.log)
```

It prints `{ acknowledged: true }` and it removes `refresh_interval` setting if it was set to something. However, according to the IDE and the typescript compiler this is an error:

```
src/util/example.ts:8:9 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(this: That, params: import(".../node_modules/@elastic/elasticsearch/lib/api/types").IndicesPutSettingsRequest | import(".../node_modules/@elastic/elasticsearch/lib/api/typesWithBodyKey").IndicesPutSettingsRequest, options?: TransportRequestOptionsWithOutMeta | undefined): Promise<...>', gave the following error.
    Type 'null' is not assignable to type 'Duration | undefined'.
  Overload 2 of 3, '(this: That, params: import(".../node_modules/@elastic/elasticsearch/lib/api/types").IndicesPutSettingsRequest | import(".../node_modules/@elastic/elasticsearch/lib/api/typesWithBodyKey").IndicesPutSettingsRequest, options?: TransportRequestOptionsWithMeta | undefined): Promise<...>', gave the following error.
    Type 'null' is not assignable to type 'Duration | undefined'.
  Overload 3 of 3, '(this: That, params: import(".../node_modules/@elastic/elasticsearch/lib/api/types").IndicesPutSettingsRequest | import(".../node_modules/@elastic/elasticsearch/lib/api/typesWithBodyKey").IndicesPutSettingsRequest, options?: TransportRequestOptions | undefined): Promise<...>', gave the following error.
    Type 'null' is not assignable to type 'Duration | undefined'.

8         refresh_interval: null
```

## Expected behavior

No typescript or IDE errors when setting any setting to `null`.

## Your Environment

- *node version*: v20.5.1
- `@elastic/elasticsearch` *version*: 8.9.0
- *os*: Mac

**Comment by JoshMock** [comment]
Thanks for the report! I'll take a look soon.

Most type definitions in this repo are automatically generated using the specification Elastic maintains in the [elastic/elasticsearch-specificaton](https://github.com/elastic/elasticsearch-specification/) repo. I'll see if the issue can be resolved there first, so that all clients can benefit from the improvement.

In the meantime, as with any build-time TypeScript error, you can always use [ignore instructions](https://smartdevpreneur.com/typescript-eslint-ignore-and-disable-type-rules/) to skip over typing bugs that you know will not result in errors at runtime.

**Comment by diogoalmiro** [comment]
Maybe every property [here](https://github.com/elastic/elasticsearch-specification/blob/main/specification/indices/_types/IndexSettings.ts#L72) should have `| null`?

**Comment by diogoalmiro** [comment]
This can be closed in favor of https://github.com/elastic/elasticsearch-specification/issues/2274
