### ISSUE TITLE
refresh_interval cannot be set to null (= let ES reset the value to the default)

### ISSUE THREAD

**Issue by tomsquest** [elastic/elasticsearch-js#2014]
## 🐛 Bug Report

Typescript issue.

It is not possible to set a `refresh_interval` to `null` using the typescript client.

`null` is allowed in Elastic to reset the value of a setting to its default.

## To Reproduce

```ts
  await elastic.indices.putSettings({
    index: indexName,
    settings: {
      refresh_interval: null, // <---- Error: IndicesIndexSettingsKeys.refresh_interval?: Duration | undefined
    },
  });
```

## Expected behavior

`putSettings` should accept a `refresh_interval` of null.

```ts
export interface IndicesIndexSettingsKeys {
   // ...lines skipped...

    refresh_interval?: Duration | null; /// <---- proposal
```

## Your Environment

- *node version*: 18
- `@elastic/elasticsearch`: 8.0
- *os*: Linux
- Typescript: 5.2.2

**Comment by bijela-gora** [comment]
Agree. It should be allowed to assign `null`. Link to documentation: https://www.elastic.co/guide/en/elasticsearch/reference/8.10/indices-update-settings.html#reset-index-setting

It's the second opened issue with TS types. Previous one: https://github.com/elastic/elasticsearch-js/issues/2013

**Comment by JoshMock** [comment]
Yep, this does look like another TypeScript bug. I'll check the [elasticsearch-specificaton](https://github.com/elastic/elasticsearch-specification/) soon to see if we can resolve it there. I've had to divert my focus away from this client for the last couple of months, but should be able to address several of the open issues soon.

In the meantime, you can use [ignore instructions](https://smartdevpreneur.com/typescript-eslint-ignore-and-disable-type-rules/) to skip over this bug and any others like it. 

Thanks for the report!

**Comment by tomsquest** [comment]
Hi @JoshMock , I found the issue of the same kind
https://github.com/elastic/elasticsearch-specification/issues/2274

You can close it here, or keep it for reference. No problem.

**Comment by JoshMock** [comment]
Closing as duplicate since a spec issue already exists.
