### ISSUE TITLE
API does not support updating a whole document

### ISSUE THREAD

**Issue by asargento** [elastic/elasticsearch-js#202]
On the API does not exist any function for [updating a whole document](http://www.elastic.co/guide/en/elasticsearch/guide/master/update-doc.html).
Only partial update can be done with [update](http://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-update).

**Comment by spalger** [comment]
As mentioned at the top of the page, updateing the whole document is done via the index api.

http://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-index
