### ISSUE TITLE
Connection pool size

### ISSUE THREAD

**Issue by Emmanuel312** [elastic/elasticsearch-js#2031]
Hello, is it possible increase the connection pool size? How to do it?

**Comment by JoshMock** [comment]
Yes, you can pass your own `ConnectionPool` instance as is documented [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/advanced-config.html#_connectionpool).

You can get an understanding of how to override the default connection pool [by looking at the `BaseConnectionPool` implementation](https://github.com/elastic/elastic-transport-js/blob/c1ae86faad894b352614d7ba617dc05709e0f76e/src/pool/BaseConnectionPool.ts#L81) in the `@elastic/transport` library.
