### ISSUE TITLE
The query attribute on the `EnrichPolicy`  should be `QueryDslQueryContainer | QueryDslQueryContainer[]` not `string`

### ISSUE THREAD

**Issue by simianhacker** [elastic/elasticsearch-js#2074]
## 🐛 Bug Report

The query attribute on the `EnrichPolicy` type is set to `string`, it should be set to `QueryDslQueryContainer | QueryDslQueryContainer[]`. This causes problems when working with any of the Enrich APIs or mocking the APIs for testing.

https://github.com/elastic/elasticsearch-js/blob/b7b16d81ee3bdeafbaad393801bda4abfa30fe78/src/api/typesWithBodyKey.ts#L9052-L9059

## Expected behavior

When using a DSL for the query, I shouldn't get a Typescript error.

**Comment by JoshMock** [comment]
Good catch @simianhacker. Can `query` also take a string, or should it only support `QueryDslQueryContainer`? I looked through the docs and it wasn't very clear.

**Comment by simianhacker** [comment]
I've never used just a `string`, I've always used the DSL at that level. I wonder if in the early days you could just put a string and it would be interpreted as a `query_string` query.

**Comment by JoshMock** [comment]
Merged a fix to the spec, so this fix should go out with the next client release.
