### ISSUE TITLE
Get all results if query filed is null or empty?

### ISSUE THREAD

**Issue by jackbbhua** [elastic/elasticsearch-js#208]
Hi,i want know if the query filed is empty or null then how to search not use this query line?like below example:

```
client.search({
  index: 'twitter',
  type: 'tweets',
  body: {
    query: {
      match: {
        body: 'elasticsearch'
      }
    }
  }
}).then(function (resp) {
    var hits = resp.hits.hits;
}, function (err) {
    console.trace(err.message);
});

if match: {
        body: 'elasticsearch'
      }
body is empty of null like 

match: {
        body: ''
      }
```

.how to make it search for all results?

**Comment by spalger** [comment]
In the future, please direct questions like this to IRC rather than filing an issue.

Sounds like you are looking for [the elasticsearch exists filter](http://www.elastic.co/guide/en/elasticsearch/reference/1.x/query-dsl-exists-filter.html).
