### ISSUE TITLE
Deno: Module '"npm:@elastic/elasticsearch"' has no exported member 'CatIndicesIndicesRecord'.

### ISSUE THREAD

**Issue by sspilleman** [elastic/elasticsearch-js#2088]
Hi,

I did search the issues prior to opening this question, so please be gentle.
Im using deno with the following code:

```typescript
import { Client, type CatIndicesIndicesRecord } from "npm:@elastic/elasticsearch";

const client = new Client({
  nodes: ["http://es:9200"],
  maxRetries: 2,
  requestTimeout: 10 * 60 * 1000,
});

const print = (i:CatIndicesIndicesRecord) => {
  // green, yellow, red
  console.log(i.health, i.index);
};

const r = await client.cat.indices({ format: "json" });
r.forEach((i) => print(i));
```
In VSCode I'm getting the following error:

`Module '"npm:@elastic/elasticsearch"' has no exported member 'CatIndicesIndicesRecord'.`

**<ins>The code does work</ins>**, but code completion is a nice to have, always.

It seems that the Types are not exported? Or am I doing something wrong? Or do I need additional imports?
I do realize that deno is not on your official clients list, but its popular these days :-)

**Comment by JoshMock** [comment]
Thanks for the report, @sspilleman. It's perhaps a bit hidden in [the docs](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/typescript.html#_request_response_types), but you can import `estypes` and use `estypes.CatIndicesIndicesRecord`. Hope that helps!
