### ISSUE TITLE
Internal module error

### ISSUE THREAD

**Issue by jayeshx10** [elastic/elasticsearch-js#2089]
It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `not reproducible` label.**

## 🐛 Bug Report

Internal module error

Paste the results here:

internal/modules/cjs/loader.js:883
 throw err;
 ^

Error: Cannot find module 'node:assert'
Require stack:
- /data/azure/KS-Kafka/node_modules/undici/lib/handler/RetryHandler.js
- /data/azure/KS-Kafka/node_modules/undici/index.js
- /data/azure/KS-Kafka/node_modules/@elastic/transport/lib/connection/UndiciConnection.js
- /data/azure/KS-Kafka/node_modules/@elastic/transport/lib/connection/index.js
- /data/azure/KS-Kafka/node_modules/@elastic/transport/index.js
- /data/azure/KS-Kafka/node_modules/@elastic/elasticsearch/index.js
- /data/azure/KS-Kafka/consumer.js
   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
   at Function.Module._load (internal/modules/cjs/loader.js:725:27)
   at Module.require (internal/modules/cjs/loader.js:952:19)
   at require (internal/modules/cjs/helpers.js:88:18)
   at Object.<anonymous> (/data/azure/KS-Kafka/node_modules/undici/lib/handler/RetryHandler.js:1:16)
   at Module._compile (internal/modules/cjs/loader.js:1063:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
   at Module.load (internal/modules/cjs/loader.js:928:32)
   at Function.Module._load (internal/modules/cjs/loader.js:769:14)
   at Module.require (internal/modules/cjs/loader.js:952:19) {
 code: 'MODULE_NOT_FOUND',
 requireStack: [
   '/data/azure/KS-Kafka/node_modules/undici/lib/handler/RetryHandler.js',
   '/data/azure/KS-Kafka/node_modules/undici/index.js',
   '/data/azure/KS-Kafka/node_modules/@elastic/transport/lib/connection/UndiciConnection.js',
   '/data/azure/KS-Kafka/node_modules/@elastic/transport/lib/connection/index.js',
   '/data/azure/KS-Kafka/node_modules/@elastic/transport/index.js',
   '/data/azure/KS-Kafka/node_modules/@elastic/elasticsearch/index.js',
   '/data/azure/KS-Kafka/consumer.js'
 ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ksec/kafka-logger@1.0.1-alpha start-lst: `node consumer.js`
npm ERR! Exit status 1

## Your Environment

- *node version*: 6,8,10
- `@elastic/elasticsearch` *version*: >=7.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by JoshMock** [comment]
@jayeshx10 If I'm understanding correctly that you're running this code on Node.js versions 6, 8 and 10, please note that this library only supports Node.js 18.x and newer. There is more information about this in [the documentation](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/installation.html#nodejs-support).
