### ISSUE TITLE
Is it possible to migrate from elastic.js?

### ISSUE THREAD

**Issue by Asimov4** [elastic/elasticsearch-js#209]
We were using https://github.com/fullscale/elastic.js
How easy is it to migrate from elastic.js to elasticsearch.js?

**Comment by spalger** [comment]
Elastic.js is essentially a query builder. It's generally used in conjunction with elasticsearch.js as detailed in the first paragraph of their readme. No need to replace it with elasticsearch.js.

To answer your question though, the concepts in the elastic.js API generally translate directly to the elasticsearch query DSL, so I n order to swap out elastic.js with elasticsearch.js you would need to manually translate all of your queries to elasticsearch query DSL.

**Comment by spalger** [comment]
Closed the issue since it's more of a question, but feel free to ask follow up questions if you have any!

**Comment by Asimov4** [comment]
That makes sense!
The question was prompted by the fact that elastic.js looks dead (no update in the past 6 months) and we were trying to find an officially supported replacement.
Does Kibana 4 use any query builder library or do you go straight with query DSL?

**Comment by spalger** [comment]
In Kibana 4 the queries are constructed using the DSL :)
