### ISSUE TITLE
bulk helper add onSuccess callback

### ISSUE THREAD

**Issue by zivni** [elastic/elasticsearch-js#2090]
## 🚀 Feature Proposal

The bulk helper API gives onDrop callback that is called when the document can’t be indexed. 

Is it  possible  to add an onSuccess callback or onIndex callback that will be called when the document is indexed successfully? 

## Motivation

When uploading from other source a lot of documents using a stream or generator I want to mark the documents that where actually indexed  so if the program crashes it can be resumed from the point of failure.

**Comment by daniel-yit** [comment]
I hope you'll include it in the next release, its super important

**Comment by JoshMock** [comment]
#2199 has been merged, and the feature will be available in 8.14.
