### ISSUE TITLE
Support for ES|QL

### ISSUE THREAD

**Issue by timtutt** [elastic/elasticsearch-js#2120]
Hi - was curious if this library has planned support for ES|QL?

**Comment by JoshMock** [comment]
Hi @timtutt! Thanks for asking.

[Low-level support](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_esql) is already supported as of 8.12. We also plan to add higher-level ES|QL helpers in an upcoming minor release.
