### ISSUE TITLE
enum and/or type guard for QueryDslTextQueryType

### ISSUE THREAD

**Issue by y-nk** [elastic/elasticsearch-js#2122]
## 🚀 Feature Proposal

We have a usecase where we receive/produce `string` as a type, which should be typed as `QueryDslTextQueryType`. I would like to have a way in this library (as single source of truth) to produce a `QueryDslTextQueryType` from a string.

## Motivation

It's much better if the guard is produced and maintained tightly with this library.

## Example

```
enum QueryDslTextQueryType {
  // the values of QueryDslTextQueryType union type
}

function isQueryDslTextQueryType(arg: any): arg is QueryDslTextQueryType {
  return Object.values(QueryDslTextQueryType).includes(arg)
}
```

**Comment by JoshMock** [comment]
Seems like this could be an opportunity to generate type guards for most or all types in the whole library. Going to think about this for a bit and see if it's reasonable to implement.

Thanks for the request!
