### ISSUE TITLE
Redaction mechanism transform arrays properties into objects

### ISSUE THREAD

**Issue by pgayvallet** [elastic/elasticsearch-js#2128]
## 🐛 Bug Report

The redaction mechanism introduced in `8.11.0-canary.1` by https://github.com/elastic/elastic-transport-js/pull/76 seems to be transforming arrays into object during the introspection required for the redaction, even for properties that aren't redacted. 

## To Reproduce

```ts
import { errors } from '@elastic/elasticsearch';

const errResponse = new errors.ResponseError({
  body: {
    error: {
      root_cause: [
        {
          type: 'index_not_found_exception',
          reason: 'no such index [poop]',
        },
      ],
    },
    status: 404,
  },
  statusCode: 404,
  headers: {},
  warnings: [],
  meta: {} as any,
});

expect(Array.isArray(errResponse.body.error.root_cause)).toBe(true);
// => assertion fails

console.log(errResponse.body.error.root_cause)
// => returns     { '0': { type: 'index_not_found_exception', reason: 'no such index [poop]' }}
```

## Expected behavior

Non-redacted properties remains untransformed

## Your Environment

- *node version*: `20.10.0`
- `@elastic/elasticsearch` *version*: >= `8.11.0-canary.1`
- *os*: Any

**Comment by ezimuel** [comment]
@pgayvallet I just sent this PR https://github.com/elastic/elastic-transport-js/pull/83 to fix this issue in `elastic-transport-js` repository.
