### ISSUE TITLE
Using the `[]` chars for an enrich policy name isn't wrapped correctly on `deletePolicy` method

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch-js#2134]
It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `not reproducible` label.**

## 🐛 Bug Report

While deleting an enrich policy with a name containing the `[]` chars, the response parser throws an error:

```
ResponseError: pattern_syntax_exception
         │ 	Root causes:
         │ 		pattern_syntax_exception: Illegal character range near index 18
         │ .enrich-policy[]-\d+
         │                   ^
```

## To Reproduce

Paste your code here:

```js
await es.enrich.putPolicy({
          name: "policy[]",
          body: {
            match: {
              indices:["my_index"],
              match_field:["fieldA"],
              enrich_fields:["fieldB", "fieldC"],
            },
          },
        }, {ignore: [409]});
await es.enrich.executePolicy({ name: "policy[]" });
...
await es.enrich.deletePolicy({ name: "policy[]" }, { ignore: [404] });
```

I have no data in the target index and the creation request raises no error. Only the delete one.
I found out this one while writing some automated tests, so it wasn't strictly a production code. In my case I just switched to some other combination of chars for the policy name to work.

## Expected behavior

No error should be thrown.

## Your Environment

- *node version*: v20.10.0
- `@elastic/elasticsearch` *version*: 8.9.1-canary.1 (used within Kibana)
- *os*: Mac

**Comment by JoshMock** [comment]
Hi @dej611. Is this an issue with the JS client itself, or with Elasticsearch? The error is an HTTP response from Elasticsearch itself so it's not clear how this is an issue with the client code.

I looked at the way [the `enrich` API code](https://github.com/elastic/elasticsearch-js/blob/main/src/api/api/enrich.ts) is generated, and the `name` parameter is handled the same way for all methods.

Closing this for now, but feel free to reopen if you can clarify how this is a client issue.
