### ISSUE TITLE
ProductNotSupportedError: The client noticed that the server is not a supported distribution of Elasticsearch

### ISSUE THREAD

**Issue by handc0de** [elastic/elasticsearch-js#2143]
I have just upgraded the node from version 14 to version 20. The Elasticsearch package we are using is version ^7.10.0. When running, an error like this appears. I have read this topic #1519 and made changes in the node_modules, and it runs normally. What I want to ask is, how do we deploy it to the server while we have to modify its node_modules?

**Comment by JoshMock** [comment]
@handc0de It sounds like you need to update your package.json to pin your dependencies to the appropriate version. If you're unfamiliar with how to do so, [npm's docs on using semver ranges](https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept) to pin that dependency correctly.
