### ISSUE TITLE
Add types for plugins

### ISSUE THREAD

**Issue by yacoubb** [elastic/elasticsearch-js#2148]
## 🚀 Feature Proposal

We are using `icu_collation_keyword` field type from the `analysis-icu` plugin in elastic cloud. It would be useful if the elasitcsearch package included types, or the ability to extend types, to include plugins.

## Motivation

Adding the type `icu_collation_keyword` to a property throws a type error, currently we have to `@ts-ignore` these errors as the config is accepted when sent to the cluster.

## Example

When describing index configurations, adding a mapping of type `icu_collation_keyword`.

**Comment by yacoubb** [comment]
I have tried overriding the type for `MappingProperty` using module declaration merging:

```ts
// src/types/elastic.d.ts

// override the MappingProperty type to allow for the icu_collation_keyword type
// (the icu_collation_keyword type comes from a plugin, so it's not in the default MappingProperty type)

import type {
  MappingAggregateMetricDoubleProperty,
  MappingBinaryProperty,
  ...
} from '@elastic/elasticsearch/lib/api/typesWithBodyKey';

interface MappingIcuProperty extends MappingPropertyBase {
  type: 'icu_collation_keyword';
}

type AugmentedMappingProperty =
  | MappingIcuProperty
  | MappingBinaryProperty
  | MappingBooleanProperty
  ...

declare module '@elastic/elasticsearch' {
  export type MappingProperty = AugmentedMappingProperty;
}

declare module '@elastic/elasticsearch/lib/api/types' {
  export type MappingProperty = AugmentedMappingProperty;
}

declare module '@elastic/elasticsearch/lib/api/typesWithBodyKey' {
  export type MappingProperty = AugmentedMappingProperty;
}

```

To no avail, the `MappingProperty` used by `IndicesIndexState` is still the internal `MappingProperty` defined in `typesWithBodyKey`.

**Comment by JoshMock** [comment]
Thanks @yacoubb. These types are generated using our [Elasticsearch specification](https://github.com/elastic/elasticsearch-specification) project, which all language clients source to generate API code. I've opened https://github.com/elastic/elasticsearch-specification/issues/2439 there to track this issue.
