### ISSUE TITLE
Release notes for version 5.0

### ISSUE THREAD

**Issue by skarfacegc** [elastic/elasticsearch-js#225]
Since this is a major version bump I'd love to see the release notes for 5.0 ... couldn't find any information on what in the API changed.

Thanks

**Comment by spalger** [comment]
The changelog can be found here: https://github.com/elastic/elasticsearch-js/blob/master/CHANGELOG.md#50-jun-9-2015

**Comment by spalger** [comment]
Oh, are you asking about the difference between the 1.6 and 1.5 api's?

**Comment by skarfacegc** [comment]
mostly the difference between 1.6 and 1.5  I just didn't see many code changes between releases on the library side.  Is it just the API differences on the ES side of things?

**Comment by skarfacegc** [comment]
Found what I was looking for.  5.0 was just the shift to the 1.6 ES API?  I'm closing, let me know if I missed something.  :)

**Comment by spalger** [comment]
Nope, that's it :)

**Comment by skarfacegc** [comment]
thx.
