### ISSUE TITLE
ES|QL Apache Arrow Support

### ISSUE THREAD

**Issue by srikanthmanvi** [elastic/elasticsearch-js#2269]
When the ES|QL API [supports Apache Arrow streaming](https://github.com/elastic/elasticsearch/pull/104877), we should add an ES|QL helper to the JS client to make it simpler to work with those streaming responses.

**Comment by JoshMock** [comment]
Notes from Kibana tests:

- https://github.com/elastic/kibana/issues/175695#issuecomment-2382859377
- https://github.com/elastic/elasticsearch/issues/109576

**Comment by JoshMock** [comment]
Apache Arrow support has been added to the ES|QL helper, providing helpers to return query results as an Apache Arrow `Table` (non-streaming) or `RecordBatchStreamReader` (streaming).
