### ISSUE TITLE
bulk api helper

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch-js#227]
There is a nice package called [elastic-queue](https://www.npmjs.com/package/elastic-queue/) that allows you to add items to a queue and that one is batched based on size or age, similar to the java [BulkProcessor](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/bulk/BulkProcessor.java)

Can we get that helper as part of the official package, or at least an official helper package? I saw that you did something like that in `makelogs` already, so I think it would be a nice addition.

Please fix the subject to something more JS'y :-)

**Comment by spalger** [comment]
Haha :) I think a set of helpers for esjs would be a great thing. Finding the time to do it is tough these days.

**Comment by spinscale** [comment]
I still think that this is a valid feature request for the core client as it is still a missing feature. The python client has a similar feature for example. See https://elasticsearch-py.readthedocs.io/en/master/helpers.html
