### ISSUE TITLE
nodejs require() not working 

### ISSUE THREAD

**Issue by jbbush** [elastic/elasticsearch-js#229]
(I'm very new to JS so you may need to spoon feed me some details :) )

I'm trying to write js to query my ES indexes.  I've read a ton of material and seen lots of examples but I can't make it work.    I'm looking for some working examples and instructions on how to install the required parts to make this work.   I already have ES indexes to use so I just need help with my js client.

The following is straight from some examples that I've seen. I keep getting errors like the following but I'm not really sure what to do with this since I can't find any examples using require([])
SCRIPT5022: Module name "scripts/elasticsearch" has not been loaded yet for context: _. Use require([])  http://requirejs.org/docs/errors.html#notloaded 

I have a dir structure like 
 ../ESIntegration
       ESIntegration.js
    /scripts
       elasticsearch.js
       require.js

```
<!DOCTYPE html>
<html lang="en">
  <head>
  
  <script data-main="scripts/main" src="scripts/require.js"></script>   
   
 <script type = "text/javascript"> 
  var elasticsearch = require("scripts/elasticsearch");
  var client = new elasticsearch.Client({
  host: 'localhost:9200',
  log: 'trace'
   });
   </script>
   
  </head>
  <body >
  	 
		 
  </body>
    
</html>
```

**Comment by spalger** [comment]
@jbbush these types of questions are better asked over [at the elasticsearch forums](https://discuss.elastic.co/c/elasticsearch).

It looks like you need to research require.js a bit more. the call to `require("scripts/elasticsearch");` should be formatted more like `require(['scripts/elasticsearch'], function () { ... });`. Hope that helps a little bit, and that you can find more help in the forums.

**Comment by jbbush** [comment]
I would agree that the call to require() may need to use a different format.  The problem is that I can't find a good example that pulls this all together.   I need a working example since I'm not familiar enough with JS.   I try the ES forum too.
