### ISSUE TITLE
Support for Node URLs with Subpaths

### ISSUE THREAD

**Issue by isimisi** [elastic/elasticsearch-js#2296]
## 🚀 Feature Proposal

Currently, when setting up a Client instance with a node URL that includes a subpath, the client throws an "invalid url" error. This issue occurs when trying to provide a node URL such as https://www.example.com/my-path/ instead of https://www.example.com/

The Client should accept node URLs with subpaths and correctly route requests through the specified subpath.

## Motivation

Allowing subpaths in node URLs can be particularly useful for setups where Elasticsearch is behind a proxy or when multiple services are hosted on the same domain. Support for subpaths would enhance the flexibility and usability of the client in various deployment scenarios.

## Example

```js
const { Client } = require('@elastic/elasticsearch');
const client = new Client({ node: 'https://www.example.com/my-path/' });
```

**Comment by JoshMock** [comment]
This is an interesting idea. There are a ton of features like this we could implement natively, but for many situations like this, providing your own Transport class is a simple enough solution:

```javascript
const { Transport } = require('@elastic/transport')

class CustomTransport extends Transport {
  async request (params, options) {
    params.path = `/my-path/${params.path}`
    return super.request(params, options)
  }
}

const client = new Client({
  node: 'https://www.example.com/',
  transport: CustomTransport,
})
```

You might have to play with that a bit to get it to run how you need, but that's the general idea.

Closing this for now, but if you have questions or that solution isn't working for you, feel free to comment here.

**Comment by bruceCzK** [comment]
This workaround might work, but it's insane that an official library can't even handle such a basic feature. Like, how is this not built-in already?
