### ISSUE TITLE
Issue in Node -v 16 and  eleastic search -v 8.12.2 connectivity 

### ISSUE THREAD

**Issue by palvevaibhav** [elastic/elasticsearch-js#2305]
It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `Category: Not an issue` label.**

## To Reproduce

Paste your code here:

```js

```

## Expected behavior

Paste the results here:

```js

```

## Your Environment

- *node version*: 6,8,10
- `@elastic/elasticsearch` *version*: >=7.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

=> => # npm WARN EBADENGINE Unsupported engine {
=> => # npm WARN EBADENGINE   package: '@elastic/elasticsearch@8.12.2',
=> => # npm WARN EBADENGINE   required: { node: '>=18' },
=> => # npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
=> => # npm WARN EBADENGINE }

getting error when i am trying to build or compose docker image

**Comment by JoshMock** [comment]
If you upgrade to `@elastic/elasticsearch` v8.12.3 you will be able to use Node.js v16. See [this issue](https://github.com/elastic/elastic-transport-js/issues/91) for context.

**Comment by palvevaibhav** [comment]
Thank you!! @JoshMock
