### ISSUE TITLE
Document not found immediately after it is saved

### ISSUE THREAD

**Issue by bttf** [elastic/elasticsearch-js#231]
Searching for a document immediately after it is saved, i.e. searching for it in its callback/promise will give you no matching results. For example:

```
client.create({
  ...
}).then(function (res) {
  client.search({ ... }) // no matching results
});
```

Wildcard query string '*' results in list of matching entries but newly created document missing from that list.

I tried searching after a slight delay (500ms) and the search did come back with the newly saved document.

**Comment by rahulpatel** [comment]
Elasticsearch by default refreshes each shard every 1s, so the document will be available to search 1s after indexing it.

Search for `index.refresh_interval` on the [indicies settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html) page. You'll want to set that to either something low or manually call [refresh](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-refresh.html) after indexing the document.

**Comment by bttf** [comment]
Nice; I will try that later this afternoon and update this ticket accordingly. 

I see that the JS client has a way to [manually refresh indices](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-indices-refresh), but is there a way to pass in the configuration for `refresh_interval` on client instantiation?

**Comment by bttf** [comment]
On second thought it would make better sense to set `refresh_interval` server-side than client side

**Comment by rahulpatel** [comment]
So you can set it in the server-side config if this is going to be your use-case, but I'd recommend manually refreshing the index if you're not making a lot of these requests.
