### ISSUE TITLE
There is no "client.connector"

### ISSUE THREAD

**Issue by canhtd-aipro** [elastic/elasticsearch-js#2325]
It appears that the client lib doesn't include connector module. I saw the docs here  [https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_connector](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_connector). It says that there is property `connection` of the client object. But when I started coding, there is none. I looked at the source code, too. There is supposed to be `connector.js` and` connector.d.ts` in `/lib/api/api`

![image](https://github.com/user-attachments/assets/f4ed716c-8474-4382-b32b-c22fe6591431)

Has the feature been implemented yet?

EDIT:
I saw a new commit pushed yesterday? When will this patch be on npm repository?

**Comment by JoshMock** [comment]
Correct, connector API was added in https://github.com/elastic/elasticsearch-js/pull/2322 and will go out when we publish the 8.15.0 client. I plan to get that published within the next few days.
