### ISSUE TITLE
indices.resolveIndex should support ignore_unavailable

### ISSUE THREAD

**Issue by mattkime** [elastic/elasticsearch-js#2356]
indices.resolveIndex should support ignore_unavailable as described in https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-resolve-index-api.html

This will result in fewer expected errors making monitoring the health of ES and kibana servers a bit easier.

**Comment by JoshMock** [comment]
This was fixed by https://github.com/elastic/elasticsearch-specification/pull/2856.
