### ISSUE TITLE
Port being added to end of Url

### ISSUE THREAD

**Issue by jackiv** [elastic/elasticsearch-js#238]
When I do:

var esClient = esFactory({
                    host: {
                        host: mydomain.com/myendpoint,
                        port: 9200
                    }
                });

the url get's built as 'mydomain.com/myendpoint:9200' instead of 'mydomain.com:9200/myendpoint'

**Comment by mikend** [comment]
+1

**Comment by spalger** [comment]
The issue here is that `/myendpoint` is not a part of the host, it belongs in the path like so:
```js
var esClient = esFactory({
  host: {
    host: 'mydomain.com',
    path: '/myendpoint',
    port: 9200
  }
});
```
