### ISSUE TITLE
Cannot update any data using 'update' method at 7.x version

### ISSUE THREAD

**Issue by Cempakers87** [elastic/elasticsearch-js#2383]
Start from yesterday (oct 19th) I can't update any data on elasticsearch cloud using 'update' method. At the same time, when using 'search' method still working (no issue).

The following was code I use. Always end-up with 'request timed out'. Please help me.
```
const { Client: EsClient7 } = require('es7');
let client7;

const setUpEs7 = function(host, user, pwd){
    return new Promise(function(resolve, reject){
        try {
            client7 = new EsClient7({
                node: host,
                auth: {
                    username: user,
                    password: pwd
                },
                requestTimeout: 300000
            });
            return resolve(client7);
        } catch (error) {
            console.log(error)
            return reject(error);
        }
    });
}

const saveData = async function(data){
    try {
        const param_insert = {
            id: `some_id`,
            index: `some_index`,
            body: {
                doc: data,
                doc_as_upsert : true
            }
        }

        const result = await client7.update(param_insert);
        return result;
    } catch (error) {
        console.log(error);
        throw error;
    }
}
```

Current client version: 7.14.1

**Comment by JoshMock** [comment]
Nothing has changed in the 7.14.1 client for a very long time, so if that is indeed the version you are using, you may need to try recreating requests using `curl` or another HTTP library to see if the problem is somewhere else between client and server.

Feel free to drop more information here if you can.

**Comment by Cempakers87** [comment]
I'm sorry for my mistake. it was my elasticsearch cloud issue.
