### ISSUE TITLE
Looks like latest elasticsearch-js in npm hasn't supported 1.7 yet

### ISSUE THREAD

**Issue by philipskokoh** [elastic/elasticsearch-js#243]
`npm install elasticsearch` gives latest v5.0.0 but this one does not support elasticsearch 1.7. 
I have to use apiVersion: 1.x for now.

**Comment by roicellaya** [comment]
I have the same problem, I tried to set apiVersion to 1.7 and got this error:

>TypeError: Invalid apiVersion "1.7", expected a function or one of master, 1.x, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1, 1.0, 0.90

**Comment by shekit** [comment]
Same problem here. Changelog mentions it will be the default in the yet unreleased 6.0. When will it be released?

**Comment by spalger** [comment]
Sorry about this, just published 6.0
