### ISSUE TITLE
Is including tap files into the npm bundles intentional?

### ISSUE THREAD

**Issue by Marsup** [elastic/elasticsearch-js#2483]
### Question

Hi,

I guess the title says it all, but the `.tap` folder has been included in the npm packages (and it's fairly big) since 8.15.2.
I intended to propose a patch to add this folder to .gitignore, but probably a developer would have seen it locally, so maybe that's intentional?

Thanks.

**Comment by JoshMock** [comment]
It's not intentional! Thanks for catching that. Fixed in https://github.com/elastic/elasticsearch-js/pull/2487 and will be publishing 8.15.3 and 8.16.2 with the correction.
