### ISSUE TITLE
Util Method For Lucene Escape

### ISSUE THREAD

**Issue by iojohnso** [elastic/elasticsearch-js#257]
Often I find myself escaping the queries prior to executing them.  I was using [lucene-escape-query](https://www.npmjs.com/package/lucene-escape-query), but realized it isn't quite right.  I was going to create a pull request for that repo, but it seems like such a common thing that it would be beneficial to be included in this client library.

How are others handling this right now?  Is there existing way or another package util people are using to do this?

What I was thinking is a simple util method as follows could be added to this client library...

```javascript
// Based on https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-query-string-query.html#_reserved_characters
// TODO: This might not be exactly right
function escape (query) {
  return query.replace(/([\!\*\+\&\|\(\)\[\]\{\}\^\~\?\:\"\/])/g, "\\$1");
}
```

Thanks!

**Comment by spalger** [comment]
Why not just use the JSON API and benefit from the perfect escaping provided there?

What kind of query are you trying to compile that works better as a query string?

**Comment by iojohnso** [comment]
Oh ok, i think i understand now.

So if I use a query string, i need to escape it.  If I use the JSON API it will automatically escape it.

Correct?

**Comment by spalger** [comment]
Yep, using something like a [match query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html) and defining it as JSON allows you to pass arbitrary user input to elasticsearch without needing to worry about escaping the query string syntax or quoting.

**Comment by iojohnso** [comment]
Great.  I have started implementing the searches using the JSON API and did away with escaping.  Thanks for your help!

**Comment by npow** [comment]
@spalger: Not sure what you mean by defining the query as JSON? I'm using `client.search()` which expects `q` as a string.

**Comment by spalger** [comment]
@npow that is an option, but it also accepts a Query DSL as the request body:

```js
client.search({
  index: 'myindex',
  body: {
    query: {
      match: {
        title: 'test'
      }
    },
    facets: {
      tags: {
        terms: {
          field: 'tags'
        }
      }
    }
  }
})
.then(..., ...);
```

**Comment by npow** [comment]
@spalger Is automatic escaping supposed to work with a filtered query string? I'm trying the following code and getting a parsing error. If I manually escape the square bracket there is no parsing error.

```
var elasticsearch = require('elasticsearch');
var client = elasticsearch.Client();
client.search({
  "index": "test-index",
  "body": {
      "query": {
          "filtered": {
              "query": {
                  "query_string": {
                      "query":"]"
                  }
              }
          }
      }
  },
}, function (err, res) {
    if (err) console.log('error: %j', err);
    else console.log('res: %j', res);
})
```

```
error: {"status":"400","message":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[TC9oNBGmRPqhwuz2eIqnjg][test-index][0]: SearchParseException[[test-index][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"query_string\":{\"query\":\"]\"}}}}}]]]; nested: QueryParsingException[[test-index] Failed to parse query []]]; nested: ParseException[Cannot parse ']': Lexical error at line 1, column 2.  Encountered: <EOF> after : \"\"]; nested: TokenMgrError[Lexical error at line 1, column 2.  Encountered: <EOF> after : \"\"]; }{[TC9oNBGmRPqhwuz2eIqnjg][test-index][1]: SearchParseException[[test-index][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"query_string\":{\"query\":\"]\"}}}}}]]]; nested: QueryParsingException[[test-index] Failed to parse query []]]; nested: ParseException[Cannot parse ']': Lexical error at line 1, column 2.  Encountered: <EOF> after : \"\"]; nested: TokenMgrError[Lexical error at line 1, column 2.  Encountered: <EOF> after : \"\"]; }{[TC9oNBGmRPqhwuz2eIqnjg][test-index][2]: SearchParseException[[test-index][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"query_string\":{\"query\":\"]\"}}}}}]]]; nested: QueryParsingException[[test-index] Failed to parse query []]]; nested: ParseException[Cannot parse ']': Lexical error at line 1, column 2.  Encountered: <EOF> after : \"\"]; nested: TokenMgrError[Lexical error at line 1, column 2.  Encountered: <EOF> after : \"\"]; }{[TC9oNBGmRPqhwuz2eIqnjg][test-index][3]: SearchParseException[[test-index][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"query_string\":{\"query\":\"]\"}}}}}]]]; nested: QueryParsingException[[test-index] Failed to parse query []]]; nested: ParseException[Cannot parse ']': Lexical error at line 1, column 2.  Encountered: <EOF> after : \"\"]; nested: TokenMgrError[Lexical error at line 1, column 2.  Encountered: <EOF> after : \"\"]; }{[TC9oNBGmRPqhwuz2eIqnjg][test-index][4]: SearchParseException[[test-index][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"query_string\":{\"query\":\"]\"}}}}}]]]; nested: QueryParsingException[[test-index] Failed to parse query []]]; nested: ParseException[Cannot parse ']': Lexical error at line 1, column 2.  Encountered: <EOF> after : \"\"]; nested: TokenMgrError[Lexical error at line 1, column 2.  Encountered: <EOF> after : \"\"]; }]"}
```

**Comment by spalger** [comment]
There is no "automatic escaping" of query string syntax. If you are using a query string in the url or body it will always be subject to the same syntax restrictions ("]" is invalid query string syntax). If you want a version of query string that isn't subject to syntax errors I suggest you use [simple query string](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html)

**Comment by spalger** [comment]
Can you go into more detail about why you need escaping?

If you are sending the query in there body of the request (and you should) then the client will automatically escape it for you (by serializing to JSON)

**Comment by spalger** [comment]
The request should look something like this

```js
client.search({
  index: '...',
  body: {
    query: {
      query_string: {
        query: 'foo bar location:uk'
      }
    }
  }
})
```

**Comment by vitorbaptista** [comment]
Thanks for the quick answer! I'm running this like:

```javascript
// https://github.com/opentrials/api/blob/master/api/controllers/search.js#L16-L23
const searchQuery = {
    index: 'trials',
    type: 'trial',
    q: params.q.value,
    from: (page - 1) * perPage,
    size: perPage,
    defaultOperator: 'AND',
  };

return client.search(searchQuery)
```

That `q` param comes from an API call (`api.foo.com/search?q=foo bar location:uk`). I'm escaping the request from the API-client side, which generates that call. Would it change anything if I queried passing the `params.q.value` as `body: { query: { query_string: { query: params.q.value } } }`?

**Comment by spalger** [comment]
Nope, this should be fine. The client with url-encode the `?q=` query string param before sending it to elasticsearch, so unless [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) has been compromised you should be good to go!

**Comment by vitorbaptista** [comment]
@spalger I'm more worried on keeping the semantics of the query. For example, a query for `foo bar location:united kingdom` is different from `foo bar location:"united kingdom"`, so I need to escape the filters contents before actually doing the API call.

From what I understood, `encodeURIComponent` will make sure the elasticsearch queries won't raise exceptions, but the queries themselves might be wrong.

**Comment by spalger** [comment]
They shouldn't be... if you specify `{ q: 'foo bar location:"united kingdom"" }` in your query params elasticsearch will receive `foo bar location:"united kingdom"` exactly. If the quotes get lost on the wire then there is a bug in the client.

**Comment by vitorbaptista** [comment]
My problem is that `united kingdom` is coming from the client, so she could sent things like `united"king"dom` or `united (king)dom`, which changes their meaning in ElasticSearch. That's why I need to escape these strings before sending them to ES.

I'm leaning towards using the code from [lucene-escape-query](https://www.npmjs.com/package/lucene-escape-query), but was wondering if there was a better way.

**Comment by spalger** [comment]
Okay, I guess I don't understand what you're trying to accomplish.

Last note, if you're saying that the only thing the user is entering is `united kingdom` then you should really be using a [bool query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html) containing a query string, rather than composing multiple query strings into one.

```js
client.search({
  body: {
    query: {
      bool: {
        must: [
          { term: { user: req.session.userId } },
          { query_string: { query: params.q.value } }
        ]
      }
    }
  }
})
```

One of those queries could be `query_string: { query: params.q.value }` but others could be anything.

**Comment by vitorbaptista** [comment]
Sorry for not explaining myself better. The user can query elasticsearch through http://explorer.opentrials.net/search. The filters in "Advanced search" work under the hood by generating a query string (e.g. `foo bar location:uk`) and passing that to ElasticSearch. I felt that this would give users the most searching power, but there're many issues that I haven't realized.

Thanks to you, now I see that I should at least use simple query strings, so no search query could raise an exception. I wonder if there's more I should change.

I needed the escaping for the "Advanced search" filters, where the user can add a filter for `Cambridge (UK)`, which should be passed to ElasticSearch as `location:"Cambridge \(UK\)"` or something similar. As far as I can see, while using query strings, I need to escape these values.

There're methods to escape strings in Lucene (http://lucene.apache.org/core/4_6_0/queryparser/org/apache/lucene/queryparser/classic/QueryParserBase.html#escape%28java.lang.String%29), and I remember seeing one of those in ElasticSearch's Java SDK. There're no plans in adding one for the JavaScript SDK, right?

**Comment by spalger** [comment]
Okay, missed that tidbit! If you create a query string programmatically then you will absolutely want to escape it, _but you shouldn't do that_.

I suggest moving to the JSON query dsl, it is the only way that elasticsearch supports creating queries programmatically.

From experience, I would also suggest building the query server side and support specific parameters for the different advanced filters. This way you maintain some form of control over the inputs you receive and can protect the data you have in elasticsearch. Today all of the data in es might be safe to query publically, but elasticsearch has a tendency to attract all sorts of data once different parts of an organization see it in action ;)

**Comment by vitorbaptista** [comment]
Thanks a lot for your help, @spalger. I really appreciate it.

I used the query string because I wanted to allow some advanced search functionalities (like `foo OR bar AND (baz OR location:uk)`) without having to parse this query string myself to generate ElasticSearch's JSON query. Is there any helper on parsing a query string to (say) extract filters?

Also, is there any interest in adding a query escaper helper to `elasticsearch-js`? I'll probably write one for my project anyway, so I can clean it and submit a PR to you guys.

**Comment by spalger** [comment]
>  wanted to allow some advanced search functionalities (like foo OR bar AND (baz OR location:uk)) without having to parse this query string myself

That shouldn't be necessary.

Take this query for instance:
![image](https://cloud.githubusercontent.com/assets/1329312/15513845/31c32d7a-219b-11e6-83b2-7fc2ddc0e9be.png)


In elasticsearch query DSL it would look like this:

```js
{
  query: {
    bool: {
      must: [
        // we can just plop the entire query here
        { query_string: { query: $searchBox.val(), default_operator: 'AND' } },
      ],
      filter: [
        // add the filters for the advanced facets
        { term: { condition: 'Obstructions' } },
        { term: { organization: 'Dr. Sandy Garden' } },
        { range: { sample_size: { gte: 10, lte: 50 } } },
        { range: { registration_date: { gte: '2016-05-18', lte: '2016-05-20' } } }
      ]
    }
  }
}
```

**Comment by vitorbaptista** [comment]
Thanks a lot, @spalger. You've given me lots of food for thought :smile: 

I still need to use the query string for now, because the API doesn't receive the filters separated like that, but inside a `q` parameter. However, I'll probably start adding those filters explictly as API parameters, then your suggestion will come in handy :+1:

**Comment by GuillaumeCisco** [comment]
Done simply with lucene by using :
```js
// https://lucene.apache.org/core/6_0_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Escaping_Special_Characters
const toEscape = [
  '+',
  '-',
  '&',
  '|',
  '!',
  '(',
  ')',
  '{',
  '}',
  '[',
  ']',
  '^',
  '"',
  '~',
  '*',
  '?',
  ':',
  '\\',
  '/',
]

const luceneEscape = (str) => {
  let res = ''
  for (let i = 0; i < str.length; i += 1) {
    const char = str.charAt(i)
    if (toEscape.includes(char)) {
      // handle special case && and ||
      if (['&', '|'].includes(char)) {
        if (char === str.charAt(i + 1)) {
          res = `${res}\\${char}\\${str.charAt(i + 1)}`
          i += 1
        } else res = `${res}${char}`
      } else res = `${res}\\${char}`
    } else res = `${res}${char}`
  }

  return res
}
```
