### ISSUE TITLE
Infinite loop in log.js

### ISSUE THREAD

**Issue by nopnop** [elastic/elasticsearch-js#258]
Starting from iojs > v3 the `EventEmitter` core class prototype has a `listenerCount` method. 

node.js / iojs < v3:
```
typeof require('events').EventEmitter.prototype.listenerCount === 'undefined'
```

iojs >= v3:
```
typeof require('events').EventEmitter.prototype.listenerCount === 'function'
```

Hence, the [line 68 in log.js](https://github.com/elastic/elasticsearch-js/blob/master/src/lib/log.js#L68) produce an infinite loop in iojs > v3 (as will nodejs in a future release, probably). 

A quick and ugly fix on [line 65 in log.js](https://github.com/elastic/elasticsearch-js/blob/master/src/lib/log.js#L65) could be:
```
Log.prototype.listenerCount = function (event) {
  // compatability for node < 0.10
  if (EventEmitter.listenerCount && !EventEmitter.prototype.listenerCount) {
    return EventEmitter.listenerCount(this, event);
  } else {
    return this.listeners(event).length;
  }
};
```

**Comment by spalger** [comment]
Fixed in f2a0cede2eff793dd894ee8bef2a2e051f6bafe6. Thanks!
