### ISSUE TITLE
elasticsearch.angular.js uses require, but its not included as a dependency?

### ISSUE THREAD

**Issue by boneill42** [elastic/elasticsearch-js#26]
(is there an email list for this project?)

I installed this into an Angular application with:
"bower install elasticsearch-js --save"

When attempting to include the elasticsearch.angular.js module, it complains about 'require' not being define.  Requires is used on lines 7 and 8:
var AngularConnector = require('./lib/connectors/angular');
var Client = require('./lib/client');

I'm noob to the JS package management.  Should RequireJS be listed as a dependency in the package.json?

**Comment by adamcee** [comment]
Hi all, we are trying to go from the ES client version 8.1.x to most recent (10.1.x) and have been previously using bower....should we be using a different frontend deployment tool, or has bower support become official?

**Comment by ksteigerwald** [comment]
Still fresh for me. No dice using bower, works fine with the tar file.

**Comment by juandelia** [comment]
Now you could use:

npm install elasticsearch-browser
