### ISSUE TITLE
Problems getting Infinity values

### ISSUE THREAD

**Issue by joliveira-3333** [elastic/elasticsearch-js#261]
I have some problems while getting Infinity values in the Elastic Search results.

Basically I have a document type indexed with a field mapped as long. Some of the indexed documents have that field set as Infinity.

When I make a search through the Elastic Search Javascript library the field with the Infinity value is returned as a string with the value "Infinity"

Is there a way to retrieve the field with the correct mapping?

**Comment by spalger** [comment]
@skynleka unfortunately there is no way to represent the value `Infinity` in JSON without passing it as a string, and the low-level client is not the right place to add mapping awareness.

One solution you might try is implementing a custom serializer: passing a class to for the `config.serializer` config will initialize that Class and use it to serialize and deserialize each request/response body.

Your serializer should probably extend [the json serializer](https://github.com/elastic/elasticsearch-js/blob/master/src/lib/serializers/json.js) and be passed to the client like so:

```js
'use strict'

let elasticsearch = require('elasticsearch')
let EsJsonSerializer = elasticsearch.Transport.serializers.json

class CustomSerializer extends EsJsonSerializer {
  deserialize(body) {
    // recursively replace "Infinity" values with constants
  }
}

let client = new elasticsearch.Client({
  serializer: CustomSerializer
})
```
