### ISSUE TITLE
TypeErrors in transport.js don't have defer defined.

### ISSUE THREAD

**Issue by zackiles** [elastic/elasticsearch-js#263]
When a TypeError is thrown and caught at [line 264 in transport.js](https://github.com/elastic/elasticsearch-js/blob/master/src/lib/transport.js#L264) the defer value is undefined, which causes the defer.reject() call to throw an uncaught exception (Cannot read property 'reject' of undefined) when using promises, and the true error is not returned. I believe it's related to TypeErrors, as any server response based errors have defer defined and are properly caught using .catch() with the correct error passed.

Sorry if this is intended behavior, in this case my TypeError was: "body can not be sent with method GET"

**Comment by spalger** [comment]
Good catch, [this line](https://github.com/elastic/elasticsearch-js/blob/master/src/lib/transport.js#L135) has an early return, which means [line 296](https://github.com/elastic/elasticsearch-js/blob/master/src/lib/transport.js#L296), which creates the actual promise, never executes.

**Comment by zackiles** [comment]
Ahh good stuff. Thanks for the quick reply.
