### ISSUE TITLE
what does the index promise actually promises?

### ISSUE THREAD

**Issue by terebentina** [elastic/elasticsearch-js#271]
Hi,

When I use `esClient.index({...}).then(...)` - at which stage is the promise actually resolved?
Does it guarantee that the data has been indexed into elasticsearch or is it resolved as soon as the data has been passed to elasticsearch, with the actual indexing taking extra time?

I ask because some of my tests fail when I add something to elasticsearch (with the code above) then I immediately search for that data.

**Comment by spalger** [comment]
The index promise doesn't resolve until the document is successfully written into elasticsearch, and the document will always come back using the [`get` api](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-get). The search indices in elasticsearch, however, are "near real-time" and are refreshed every second (which is when newly indexes documents become searchable). You can use the `refresh` parameter of the [`index` api](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-index) to prevent this from being an issue, but please [read up on refresh](https://www.elastic.co/guide/en/elasticsearch/guide/current/near-real-time.html#refresh-api) **before** doing so as it has several negative side effects.
