### ISSUE TITLE
Website missing docs for 1.5 API

### ISSUE THREAD

**Issue by dsernst** [elastic/elasticsearch-js#272]
The website mysteriously skips versus 1.5 in the docs: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/index.html

![screen shot 2015-09-16 at 4 43 47 pm](https://cloud.githubusercontent.com/assets/6340841/9921406/228f5eb0-5c92-11e5-9468-c06e0c85a05c.png)

Although they are available in this repo: https://github.com/elastic/elasticsearch-js/blob/master/docs/api_methods_1_5.asciidoc

Is there a reason for the discrepancy?

**Comment by spalger** [comment]
Good catch @dsernst, the index for the docs was simply out of date.

This isn't the first time I have forgotten to update a list of the apiVersions, so with https://github.com/elastic/elasticsearch-js/commit/fc66381aee499936131d1c3a08a65a971651cc53 all of these updates are now automated. The online docs should update automatically in the next hour.

**Comment by dsernst** [comment]
Awesome :+1:
