### ISSUE TITLE
ignoreUnavailable param ignored by client.indices.close

### ISSUE THREAD

**Issue by zumo64** [elastic/elasticsearch-js#273]
on the client API 1.7 from nodeJs closing an non existent index even with ignoreUnavailable = true generates an error
{"error":"Error: IndexMissingException[[myIndex] missing]"}

**Comment by spalger** [comment]
Hmm, this appears to be an elasticsearch behavior

```sh
$ curl -XPOST  'http://localhost:9200/nonExistant/_close?ignore_unavailable=true&pretty'
{
  "error" : "IndexMissingException[[nonExistant] missing]",
  "status" : 404
}
```

**Comment by zumo64** [comment]
I just noticed the open does the same thing .. I should open an issue in ES then
