### ISSUE TITLE
EventEmitter.listenerCount is deprecated. Causing a "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by louy** [elastic/elasticsearch-js#278]
> Class Method: EventEmitter.listenerCount(emitter, event)
> Stability: 0 - Deprecated: Use emitter.listenerCount instead.
— [NodeJS Docs | Events | listenerCount](https://nodejs.org/api/events.html#events_class_method_eventemitter_listenercount_emitter_event)

Apparently it's calling `emitter.listenerCount` internally.
However... [src/lib/log.js#L65-L77](https://github.com/elastic/elasticsearch-js/blob/master/src/lib/log.js#L65-L77)

emitter.listenerCount is being overriden here, causing an infinite loop.

**Comment by louy** [comment]
For people who are looking for a workaround, add this once anywhere in your project.

```js

var EventEmitter = require('events');
var Log = require('elasticsearch/src/lib/log');
Log.prototype.listenerCount = EventEmitter.prototype.listenerCount;
```

**Comment by spalger** [comment]
@louy this was fixed by v8.2.0 Is it possible for you to upgrade? What version of the client are you using?

**Comment by meash-nrel** [comment]
@spalger thanks for that info.  npm was freezing my ver at 5.0. upgraded to 10.0 latest and it's working.

**Comment by louy** [comment]
I was using version 3. I think I'll update as soon as I get the chance to. Thanks.
