### ISSUE TITLE
no partial_fields support for search API call

### ISSUE THREAD

**Issue by basvanmeurs** [elastic/elasticsearch-js#279]
Please note the parameter 'partial_fields' in the search operation.

https://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-request-fields.html:

```json
{
    "query" : {
        "match_all" : {}
    },
    "partial_fields" : {
        "partial1" : {
            "include" : "obj1.obj2.*"
        }
    }
}
```

This can be handy when you have a mapping with some property as 'enabled: false', because you can fetch a value within that not-indexed object using partial_fields but not using fields.

I tested it directly on elasticsearch and it works, but the elasticsearch-js module seems to ignore this parameter altogether.

**Comment by spalger** [comment]
@basvanmeurs elasticsearch.js does not impose any restrictions on the body of the request. Everything under the `body:` key in the parameters object is simply serialized and sent to elasticsearch. This means that the `"partial_fields"` portion of that body doesn't need to be specifically supported, you just need to send it like this:

```js
var client = new elasticsearch.Client();
client.search({
  index: '...',
  body: {
    query: {
      match_all: {}
    },
    partial_fields: {
      partial1: {
        include: "obj1.obj2.*"
      }
    }
  }
});
```
