### ISSUE TITLE
Proposal: Add scrollToEnd method

### ISSUE THREAD

**Issue by xpepermint** [elastic/elasticsearch-js#283]
I have indices with millions of documents thus I scroll through search results quite often. Each batch is usually processed asynchronously using promises. It would be great if this api would provide a method for easy batch processing.

```js
let index = `products`;
let scroll = '60s';
let scrollToEnd = client.scrollToEnd(scroll, res => console.log(res));
return client.search({index, scroll, search_type: 'scan'}).then(scrollToEnd);
```

I made my own [elasticsearch-scrolltoend](https://github.com/xpepermint/elasticsearch-scrolltoend) module for now.

**Comment by spalger** [comment]
I like the idea but we intentionally keep the official clients simple and without frills. Our new [extensions](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/extensions.html) page is looking a little empty though :wink:

If you want to write a little library with scrolling helpers I would be happy to list it.

**Comment by xpepermint** [comment]
I see. Well, the library mentioned above works so you can add it to the list.

**Comment by spalger** [comment]
Looks like this is distributed as un-transpiled es6 code, want a pr that transpiles it before publishing to npm?

**Comment by xpepermint** [comment]
Ow... I use es6 features supported by nodejs ~4.1. Yeah, a PR is more then welcome. We can also just change it to be es5 (only a few lines of code). What do you suggest?

**Comment by xpepermint** [comment]
You are fast. While I was writing the message above you did this https://github.com/xpepermint/elasticsearch-scrolltoend/pull/1. I'll merge today.

**Comment by spalger** [comment]
Haha :) It's probably easier to just use babel and also export a umd module (so it's easy to use in the browser). Pr incoming.

**Comment by xpepermint** [comment]
Haha, you are the man!

**Comment by xpepermint** [comment]
I merged your PRs. Looks perfect!
I guess you can now add it to the plugins page.
Thanks!
