### ISSUE TITLE
client.deleteByQuery in undefined in v1.7+

### ISSUE THREAD

**Issue by xpepermint** [elastic/elasticsearch-js#285]
I get `methos undefined` error when calling `client.deleteByQuery`. The method is not documented in the latest api version. Will this still be supported or there's an alternative?

**Comment by spalger** [comment]
Hmm, are you sure that you are using the `1.7` api? Starting in `2.0` the `deleteByQuery()` api is [moving to a plugin](https://www.elastic.co/blog/core-delete-by-query-is-a-plugin) so it is not a part of the base api.

**Comment by spalger** [comment]
I'm still seeing it in the 1.7 api files. https://github.com/elastic/elasticsearch-js/blob/master/src/lib/apis/1_7.js#L1397

**Comment by xpepermint** [comment]
Hey I meant (1.7, +) not [1.7, +]. Sorry the title is wrong. The plugin was what I was looking for. Thanks!
