### ISSUE TITLE
Update docs for support version in browser build

### ISSUE THREAD

**Issue by royrusso** [elastic/elasticsearch-js#287]
The current docs state that ES 1.5+ is supported in the browser builds (https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html)

It appears that it should be ES 1.6+

```
module.exports = {
  '2.0': require('./2_0'),
  '_default': require('./1_7'),
  '1.7': require('./1_7'),
  '1.6': require('./1_6')
};
```

**Comment by spalger** [comment]
Good catch, I forgot to release that change. It's out now, in 9.0.0 (note that the default is now 2.0).
