### ISSUE TITLE
Error constructors object is missing "Forbidden"

### ISSUE THREAD

**Issue by Bargs** [elastic/elasticsearch-js#288]
This docs mention a Forbidden error constructor, but it seems to only be accessible under errors[403]. require('elasticsearch').errors.Forbidden is undefined. 

https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/errors.html

**Comment by spalger** [comment]
Yeah, with the shield update it was renamed to "Authorization Exception"... I'll put Forbidden back though, because that's the canonical name.

**Comment by spalger** [comment]
Fixed with f269d8b6ad061df2bc809967bdccbc33ace4e5b8 and released in 9.0.0
