### ISSUE TITLE
Better version checking in log.js

### ISSUE THREAD

**Issue by saksham0808** [elastic/elasticsearch-js#292]
elasticsearch-js broke on node version shift from 0.12 to 5.0.0 thanks to a weird way of implementing version checks for node. There are currently no checks for node version directly. Instead there are checks like
```
// node >= 3.0 supports EE#listenerCount()
if (EventEmitter.prototype.listenerCount)
```
and
```
// compatability for node < 0.10
if (EventEmitter.listenerCount)
```
Instead
```
process.version
```
should be used.

**Comment by spalger** [comment]
I disagree. I always use [feature detection](http://learn.jquery.com/code-organization/feature-browser-detection/) when possible, which was the intent here. To make that less confusing I have created #301
