### ISSUE TITLE
Allow `doc` parameter for termvector method

### ISSUE THREAD

**Issue by DavidBruant** [elastic/elasticsearch-js#295]
I haven't dug further than 1.7, but at least for [1.7](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/docs-termvectors.html#docs-termvectors-artificial-doc) and [2.0](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/docs-termvectors.html#docs-termvectors-artificial-doc), it's possible to use a `doc` parameter to analyze the termvector of an artificial (non-indexed) document.

I cannot see this parameter in the [comments](https://github.com/elastic/elasticsearch-js/blob/4b7cd3d92f6cbb565366e33f817d5a723cfc52cb/src/lib/apis/1_7.js#L6155-L6168) nor in the elasticsearch-js doc. I've tried the naive approach (just add a `doc` field in the parameter object) and it didn't seem to work.

Am I doing something wrong? If not, can this parameter be added?

Thanks!

**Comment by spalger** [comment]
@DavidBruant elasticsearch.js does not impose any restrictions on the body of the request. Everything under the `body:` key in the parameters object is simply serialized and sent to elasticsearch. This means that the `"doc"` portion of that body doesn't need to be specifically supported, you just need to send it like this:

```js
var client = new elasticsearch.Client();
client. termvector({
  body: {
    doc: { ... }
  }
});
```

**Comment by DavidBruant** [comment]
Oh ok. 
For some reason, this doesn't work; I constantly get a 503 `NoShardAvailableActionException`, but I'll look into it separately.
Thanks!
