### ISSUE TITLE
_msearch sends invalid JSON, with content-type: application/json

### ISSUE THREAD

**Issue by mstorus** [elastic/elasticsearch-js#296]
elasticsearch-js calls the `elasticsearch/_msearch` endpoint with Request header 
`Content-Type   application/json;charset=utf-8`, but then the body looks like this:

```
{"index":"my-logstash-*","ignore_unavailable":true}
{"size":500,"sort":[{"@timestamp":{"order":"desc","unmapped_type":"boolean"}}],"highlight":{"pre_tags"
:["@kibana-highlighted-field@"],"post_tags":["@/kibana-highlighted-field@"],"fields":{"*":{}},"fragment_size"
:2147483647},"aggs":{"2":{"date_histogram":{"field":"@timestamp","interval":"30s","pre_zone":"-08:00"
,"pre_zone_adjust_large_interval":true,"min_doc_count":0,"extended_bounds":{"min":1447202900252,"max"
:1447203800252}}}},"query":{"filtered":{"query":{"match_all":{}},"filter":{"bool":{"must":[{"range":
{"@timestamp":{"gte":1447202900253,"lte":1447203800253}}}],"must_not":[]}}}},"fields":["*","_source"
],"script_fields":{},"fielddata_fields":["@timestamp"]}
```

which is not valid JSON.

We have a proxy in front of these requests that will return a `400 Bad Request` due to the invalid JSON.
It seems like the msearch endpoint in elasticsearch expects newline separated json fragments,
so can we change the `Content-Type` of this request to not be `application/json`?

**Comment by spalger** [comment]
Interesting, [wikipedia says](https://en.wikipedia.org/wiki/Line_Delimited_JSON#MIME_type_and_file_extensions) the content type should be `application/json; boundary=NL`, does that satisfy your proxy?

**Comment by nwadams** [comment]
I manually curled a request with the content type `application/json; boundary=NL` and it didn't work. The reason is the proxy tries to parse the body as json and ignores the boundary part I guess. I should try to get that to work, but the default content type doesn't have the `boundary=NL` in it.

**Comment by spalger** [comment]
Correct it does not send this currently. Are you're fine with this content type though? Seems like the right choice.

**Comment by nwadams** [comment]
according to the linked wikipedia article with this section `When using HTTP/email the MIME type for Line Delimited JSON should be application/x-ldjson`. shouldn't it be `application/x-ldjson`. My parser supports the `x-ldjson` (Its express, https://github.com/expressjs/body-parser). My version is probably old, so the `application/json; boundary=NL` may have been added later. From reading the google doc it seems the `boundary` format was a suggested name if it ever left experimental status.

**Comment by spalger** [comment]
Wow, yeah, totally missed that! I like `application/x-ldjson`.

**Comment by nwadams** [comment]
:+1:

**Comment by mstorus** [comment]
I support sending `application/x-ldjson` as well
:+1:
