### ISSUE TITLE
Has client.indices.deleteMapping been deprecated in v2.0?

### ISSUE THREAD

**Issue by tundrax** [elastic/elasticsearch-js#297]
Just updated to v2.0 and `client.indices.deleteMapping` seems to be removed?

**Comment by spalger** [comment]
That is correct: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/indices-delete-mapping.html

**Comment by spalger** [comment]
Correct @lazutkin. The strategy I have heard most often is "stop using types", this simplifies things on both the API and server side of things and I suggest taking that approach in the future as well.
