### ISSUE TITLE
searchType vs search_type

### ISSUE THREAD

**Issue by ghusse** [elastic/elasticsearch-js#306]
Hi,

I had trouble using `searchType` with the ES javascript lib. The docs says that `search` is accepting parameter `searchType`:

https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-search

>  searchType
> String — Search operation type
> Options
>        "query_then_fetch"
>        "dfs_query_then_fetch"
>        "count"
>        "scan"

But the given example shows that I should use `search_type` instead of `searchType`.

https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-scroll

```
var allTitles = [];

// first we do a search, and specify a scroll timeout
client.search({
  index: 'myindex',
  // Set to 30 seconds because we are calling right back
  scroll: '30s',
  search_type: 'scan',
  fields: ['title'],
  q: 'title:test'
},
```

I made my own tests, with a server on v1.4, and it seems that the parameter `searchType` is ignored. I suppose the correct param name is `search_type`.

Is it possible to update the docs?

**Comment by spalger** [comment]
`searchType` is actually [an alias for](https://github.com/elastic/elasticsearch-js/blob/master/src/lib/apis/2_1.js#L4501) `search_type`. I'm not 100% sure which option will win if you include both but they should both work on their own.

If that is not the case then that's a pretty serious bug. Can you verify that searchType does nothing? It should set the search_type query string parameter

**Comment by ghusse** [comment]
Hi,

I just ran another test, this time I don't have any difference. I don't understand why previous measures were not the same...

Thanks for your answer.
