### ISSUE TITLE
Can't inherit es.Client

### ISSUE THREAD

**Issue by ecdeveloper** [elastic/elasticsearch-js#307]
I'm trying to extend es client by overriding one of it's methods. The simple code below normally works, but in case of `elasticsearch` module - it doesn't.

```javascript
var util = require('util');
var esClient = require('elasticsearch').Client;

function CustomES() {
	esClient.apply(this, arguments);
}

util.inherits(CustomES, esClient);

var obj = new CustomES();
console.log(obj.search);
```

The expected output is `[Function]`. The actual output is `undefined`.

Any ideas?

**Comment by spalger** [comment]
Correct, this is a side effect of supporting multiple `apiVersion`s. If you want to extend the client I suggest using a plugin. A plugin is simply a function that gets passed the Client class before it's created.

```js
var Client = require('elasticsearch').Client;

function customPlugin(Client) {
  Client.prototype.customMethod = function () {};
}

var client = new Client({
  plugins: [ customPlugin ]
});

console.log(obj.customMethod);
```

**Comment by ecdeveloper** [comment]
Got it, thanks. The actual solution won't work for me though, since I want to extend the es module by wrapping it into a custom module, and I won't be able to instantiate the Client within this custom module. But thanks anyway.

**Comment by spalger** [comment]
Got it, maybe you should expose your module as a plugin, like other client extensions: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/extensions.html
