### ISSUE TITLE
bulk: Inconsistency action error handling (deleting/update).

### ISSUE THREAD

**Issue by asaf** [elastic/elasticsearch-js#314]
Hey,

`bulk` doesn't flag `errors` as true if payload contains a deletion of a document that doesn't exist,

IMO any error that is > 400 should be threat as an error,

Whatever you choose, it should be consistent as currently trying to update a document that doesn't exist actually flags `errors=true`

Another thing (less important) is the fact that the result of failure update contains an `error` object with error description while `delete` result only contain `found: false` and `status: 404`

Thanks!

**Comment by spalger** [comment]
The body of a bulk response is completely dictated by elasticsearch itself, not the client library. Please refile your issue here: https://github.com/elastic/elasticsearch/issues
