### ISSUE TITLE
Error/response undefined when pinging

### ISSUE THREAD

**Issue by lengoyvaerts** [elastic/elasticsearch-js#315]
When pinging to http://localhost:9200/ using client.ping as described in the readme, both the error or response are always undefined (tested when elasticsearch is up and down). Is there something I'm missing or doing wrong?

**Comment by spalger** [comment]
Can you share your code? That definitely shouldn't be the case.

**Comment by lengoyvaerts** [comment]
It was a (small) mistake from my side, this can be closed, thanks!
