### ISSUE TITLE
Sniff not working properly 

### ISSUE THREAD

**Issue by agencia** [elastic/elasticsearch-js#318]
Not sure if this is a regression bug of #281 but i got the same on __elasticsearch@10.0.1__

```
Elasticsearch ERROR: 2015-12-13T05:18:13Z
  Error: Unable to convert node list from undefined to hosts durring sniff. Encountered error:
  Error: expected node's http_address property ("monitor.agei.mx/10.0.1.43:9200") to match either /^([\.:0-9a-f]*):([0-9]+)?$/ or /\[\/*([^:]+):(\d+)\]/.
```
I have a 3 nodes cluster, 2 nodes and 1 data-less node (monitor.agei.mx)

**Comment by corbinu** [comment]
Same issue here

**Comment by spalger** [comment]
Fixing this regular expression to accept a hostname before the ip address is simple enough, but can you explain where that hostname is coming from (specifically "monitor.agei.mx" in @agencia's example)?

**Comment by spalger** [comment]
Looks like it's the publish_host

**Comment by spalger** [comment]
@agencia @corbinu this should be working now. Can you give it a shot?

**Comment by corbinu** [comment]
Just updated to the latest version and same error still

```
Elasticsearch ERROR: 2016-01-10T22:55:35Z
  Error: Unable to convert node list from undefined to hosts durring sniff. Encountered error:
  Error: node's http_address property ("127.0.0.1:9200") does not match the expected pattern /\[\/*([^:]+):(\d+)\]/.
```

**Comment by spalger** [comment]
@corbinu are you sure you installed 10.1.2? That error message was removed https://github.com/elastic/elasticsearch-js/commit/3cd5d5abd84e90162306845f0d9d5b2bbfdaf4fb#diff-8e0b8bfde35c84c7baa1882260fa1b79L19

**Comment by corbinu** [comment]
@spalger you are correct `npm cache clean` and a reinstall again fixed it

**Comment by spalger** [comment]
Great, then I'll assume that it fixed the issue. Thanks :)
