### ISSUE TITLE
Using elasticsearch-js with Angular 2

### ISSUE THREAD

**Issue by jhiemer** [elastic/elasticsearch-js#323]
Hi,
when I try to use es-js with Angular 2 and try to load it like:

```js
  System.config({
        transpiler: 'typescript',
        typescriptOptions: { emitDecoratorMetadata: true },
        defaultExtension: 'js',
        packages: {
          'app': {
            defaultExtension: 'js'
          }
        },
        map: {
          'elasticsearch': 'node_modules/elasticsearch/src'
        }
      });
      System.import('app/bootstrap')
        .then(null, console.error.bind(console))
```

Then I have two options, either defining 'elasticsearch' : { defaultExtension: 'js' }}, which leads to higher amount of 404s, or by not using it, which also leads to an error.

Any idea for a proper work-around?

**Comment by spalger** [comment]
Hmm, you probably want to try using the [elasticsearch-browser](https://www.npmjs.com/package/elasticsearch-browser) version, which is bundled and includes all of it's dependencies.

**Comment by spalger** [comment]
Let me know how it goes with angular 2 by the way, I have yet to try it.

**Comment by jhiemer** [comment]
@spalger going to check thx.

**Comment by jhiemer** [comment]
@spalger after having some discussion with the Systemjs guys we have come this point: https://github.com/systemjs/systemjs/issues/988#issuecomment-167355641

Is it planned to the add the AMD module definition?

**Comment by spalger** [comment]
It isn't planned, but might not be too hard. I'm not sure what would be required. I haven't looked at the way the client is built in at least a year.

**Comment by jhiemer** [comment]
So there is no Angular 2 integration planned at all?

**Comment by spalger** [comment]
No, it's not planned. *Planned* implies that it's on my todo list, which is long and full of other things (mostly related to [kibana](https://github.com/elastic/kibana)). System.js isn't required to use angular 2 though, elasticsearch.js does work with browserify and webpack.

**Comment by jhiemer** [comment]
All right, seems reasonable. Afaik System.js seems to be the choice at the moment for the Angular guys, so I though it would be suitable to get it working with it. But that's up to you and your priority schedule. :-)

**Comment by jhiemer** [comment]
@spalger do you know any workaround to include the library into a Angular 2 project?

**Comment by spalger** [comment]
@jhiemer looks like you just need to tell SystemJS that elasticsearch is a "global" module:
```js
System.config({
  packages: {
    app: {
      format: 'register',
      defaultExtension: 'js'
    }
  },
  map: {
    elasticsearch: 'node_modules/elasticsearch-browser/elasticsearch.js'
  },
  meta: {
    elasticsearch: {
      format: 'global',
      exports: 'elasticsearch'
    }
  }
});
```

**Comment by jhiemer** [comment]
@spalger that's what I tried as well, but when I import the library via `import 'elasticsearch';` the typescript compiler is calm in the browser I get:

`Error: AMD module http://localhost:3000/node_modules/elasticsearch-browser/elasticsearch.js did not define(…)`

though.

**Comment by spalger** [comment]
Did you try the exact config I used? Because that works for me when I run it. See https://github.com/spalger/esjs-angular2-test

**Comment by jhiemer** [comment]
@spalger thank you very much. I have found my error. I had two problems: my type definition file was not as yours, some parts were missing, and I had an issue regarding the definition in my System config, which I have found. 

Thanks a lot!

**Comment by spalger** [comment]
Glad you got it working. Please let me know if you have to do anything else to get it integrated (besides expand the typescript definition).

**Comment by henninga** [comment]
I can't seem to get this to work. I've done exactly as you have in your demo and it doesn't work. Could you perhaps recheck it with the latest versions of es and angular2?

**Comment by henninga** [comment]
When running your example using npm run start I get the error "elasticsearch is not defined"

**Comment by ldkge** [comment]
Same thing here! I get:

`ReferenceError: Can't find variable: elasticsearch
	Evaluating http://localhost:3002/node_modules/elasticsearch-browser/elasticsearch.js
	Error loading http://localhost:3002/app/boot.js`
