### ISSUE TITLE
Re-configure client host dynamically

### ISSUE THREAD

**Issue by xSAVIKx** [elastic/elasticsearch-js#324]
I've found #137 and tried to use such approach in my app, but have reached another problem:
I'm using elasticsearch - v10.0.1 - 2015-11-30 with elasticsearch.angular.js and method, described in the #137  run me into Type error, due to this check in elasticsearch.angular.js (part of function `ConnectionAbstract(host, config)` function):
```javascript
  if (!host) {
    throw new TypeError('Missing host');
  } else if (host instanceof Host) {
    this.host = host;
  } else {
    throw new TypeError('Invalid host');
  }
```
And, actually, if I'm passing new host as string, like described above, I'll not pass `host instanceof Host` check, but, I also cannot create instance of Host object (I simply cannot access that type).

I'm trying to do smth like this:
```javascript
elasticsearchClient.$inject = ['esFactory', 'configurationResource'];
  function elasticsearchClient(esFactory, configurationResource) {
    var host = 'http://old.host.com:6901/';
    var apiVersion = '1.7';
    var client = esFactory({
      hosts: [host],
      apiVersion: apiVersion
    });
    configurationResource.configValues.get({
      fullName: 'ElasticsearchUrl'
    }).$promise.then(function(result) {
      var newHost = result.currentValue; // newHost==='http://new.host.com:6901/'
      client.transport.connectionPool.setHosts([newHost]);
    });

    return client;
  }
```
Maybe I'm doing smth wrong ? Could you please help me ?

**Comment by cchandurkar** [comment]
I cannot see this change in v12.0.1? Is it reverted back? I'm facing this similar issue.

**Comment by spalger** [comment]
[`client.transport.connectionPool.setHosts([])`](https://github.com/elastic/elasticsearch-js/blob/master/src/lib/connection_pool.js#L306) is still available.

**Comment by tilchl** [comment]
Hey I tried setting the new host like this
elasticsearch.angular.min.js v13.3.1 - 2017-08-08
```
hosts = ['http://elastic:changeme@hcd1515g:9200'];
client.transport.connectionPool.setHosts(hosts)
```
But I only get 

> TypeError: Invalid host

I use the elasticsearch.angular.min.js v13.3.1 - 2017-08-08

Any ideas?
Thanks
