### ISSUE TITLE
Remove `index` and `name` from indices.getAliases API

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch-js#331]
When using get aliases, I came to strange results while using `index` and `name` parameters.
It could come from an issue in elasticsearch itself but for the elasticsearch JS client, I think we should remove the support of `index` and `name`. 

`get aliases` API is actually not documented in [elasticsearch reference guide](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/indices-aliases.html) and we invite users to use `get alias` API instead. 

Here is a script which reproduces the REST API issue. I'll open a similar bug in elasticsearch repo as well.

```sh
curl -XDELETE localhost:9200/foo,bar?pretty
curl -XPUT localhost:9200/foo?pretty
curl -XPUT localhost:9200/bar?pretty
curl -XPOST localhost:9200/_aliases?pretty -d '{
    "actions" : [
        { "add" : { "index" : "foo", "alias" : "myalias" } }
    ]
}'
curl -XGET localhost:9200/_aliases/myalias?pretty
# {
#   "bar" : {
#     "aliases" : { }
#   },
#   "foo" : {
#     "aliases" : {
#       "myalias" : { }
#     }
#   }
# }

curl -XGET localhost:9200/_alias/myalias?pretty
# {
#   "foo" : {
#     "aliases" : {
#       "myalias" : { }
#     }
#   }
# }
```

**Comment by spalger** [comment]
The elasticsearch.js client's API is totally based on the [rest-api-spec](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/main/resources/rest-api-spec/api) in elasticsearch search, so any changes to the API would need to happen there.

**Comment by dadoonet** [comment]
May be we should change the documentation then and as we don't document GET _aliases in core doc, we should may be not document it here as well?

**Comment by spalger** [comment]
I we don't want the API documented then we should remove [this file](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/indices.get_aliases.json), or update it to use the `_alias` urls.

**Comment by dadoonet** [comment]
Up to you.

Just saying that I hit the issue those days so other guys could also hit it...
