### ISSUE TITLE
Use extended promises code

### ISSUE THREAD

**Issue by yetithefoot** [elastic/elasticsearch-js#337]
In a lot of applications use ```.then().fail().done()``` style syntax promises.
Like:
```
			client.count({
				index: index
			})
			.then(function(data){
			})
			.fail(function(err){
			})
			.done();
```

Would be great if it will compatible with popular promises lib with ```done()/fin()```.

**Comment by spalger** [comment]
We went that route originally and shipped with Bluebird, but it required that we ship with a specific version of bluebird which presented complications. Instead you can use the [defer config](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html#config-defer) to use your favorite promise library.
