### ISSUE TITLE
get method returns `error` object on document not found

### ISSUE THREAD

**Issue by miksago** [elastic/elasticsearch-js#339]
Rather than reserving `error` for internal, API and network errors, the `get` API method triggers the error handling logic if the document with the specified ID is not found (due to a 404 status code being sent by Elasticsearch), despite the response actually containing some useful details.

This means you have to compare the `error.message` with the string `"Not Found"`, which makes error handling logic brittle and difficult to make generic.

(this is compounded by the fact that all errors share a default type, rather than the "not found" error being comparable as `error instanceof NotFoundError`)

For now, I'm working around with issue by just using the Search endpoint with a match query, which I know is less than ideal for getting a specific document by id.

**Comment by spalger** [comment]
There is actually an error property exported by the elasticsearch module which includes all of the errors that the client sends back. In the case of 404 responses you can use either the `404` or `NotFound` class:

```js
var elasticsearch = require('elasticsearch');

var NotFoundError = elasticsearch.errors[404];
// or
var NotFoundError = elasticsearch.errors.NotFound;
```

The error objects all expose their status code as well, so you can also check for 404's with that property
```js
client.get(...)
.catch(function (err) {
  if (err.status === 404) {
    // do something
  } else {
    throw err;
  }
});
```

**Comment by miksago** [comment]
Is this even the case if you get a ENOMEM type system call error from node.js?

**Comment by spalger** [comment]
Hmm, not sure what the "ENOMEM" system call error is, but this is specifically for HTTP errors/responses. I'm not sure what happens for "ENOMEM".

**Comment by miksago** [comment]
basically a system call failed to allocate memory — it's a frivolous example there though; my main point is, `err` happens, and I just want to know how they're handled.

**Comment by spalger** [comment]
Well, in an exceptional case like that here is what would happen:

 1. the host/es node that the request was directed at would be removed from the connection pool
 1. other nodes would be tried until:
    - a request succeeds (aka, a response was received, even 404 is considered a success at this point)
    - the connection pool is exhausted
    - the maxRetry count is reached
  1. if a request was successful
    1. the response is converted to either a user response or error based on the status code and response body
  1. if a request could not be completed
    1. the final error received is wrapped in a `ConnectionFault` error and passed back to the caller

All of this logic is implemented by the [`Transport`](http://github.com/elastic/elasticsearch-js/blob/master/src/lib/transport.js) class and more details can be found there.
