### ISSUE TITLE
Question about bulk() method return value?

### ISSUE THREAD

**Issue by yuz11** [elastic/elasticsearch-js#342]
I'm Using Elasticsearch 2.1.1 and use elasticsearch-js to write my nodejs program to store index to es.

code is like below:
```
...
        //Data Init
        msgArr.push({"index":
            {
                _index:message.service,
                _type:message.logtype,
                _id:message._id
            }
        });
        msgArr.push(message);
...
        //Bulk Method
        esClient.bulk({
            body:msgArr.slice(0,4)
        },function(err, resp){
            if(err){
                console.log(err);
            }
            else{
                console.log(resp);
            }
        });
...
```

Somehow I get this return value

```
{ took: 1,
  errors: true,
  items: [ { index: [Object] }, { index: [Object] } ] }
```

while my data is

```
[ { index: 
     { _index: 'bt_svc_ap',
       _type: 'event',
       _id: '569cc7851d41c8f28d5a38f1' } },
  { _id: 569cc7851d41c8f28d5a38f1,
    id: 'tOmaYr3TEeWkrvgPQf27uw',
    service: 'bt_svc_ap',
    pid: 6755,
    groupId: 57,
    ip: '183.232.30.211:MOB',
    logtype: 'event',
    function: 'joinUserGroup',
    line: 167,
    msg: 'uid:2105377717, ugId:2_2330849298, action:joinUg',
    '@timestamp': '"2016-01-18T11:07:47.000Z"' },
  { index: 
     { _index: 'bt_svc_ap',
       _type: 'event',
       _id: '569cc7851d41c8cff15a3c85' } },
  { _id: 569cc7851d41c8cff15a3c85,
    id: 'tNHMor3TEeWkrvgPQf27uw',
    service: 'bt_svc_ap',
    pid: 6755,
    groupId: 57,
    ip: '183.232.30.211:MOB',
    logtype: 'event',
    function: 'OnSubServiceTypes',
    line: 398,
    msg: 'action:subSt, uid:2104828824, serviceType:15013; ',
    '@timestamp': '"2016-01-18T11:07:47.000Z"' } ]
```

So What is going on?It seems that index is recognized as an array.But I obviously using a JSON.

**Comment by spalger** [comment]
The bulk response says `errors: true`, can you please print them out so we can see what elasticsearch says is happening? You may need to use `JSON.stringify(resp, null, '  ');` to get print the nested values.

**Comment by yuz11** [comment]
Thx for the comment. I got the error and then fix it. It's because the document got an _id.
  {
   "index": {
    "_index": "bt_svc_ap",
    "_type": "event",
    "_id": "6jVwoWY2Qkq6XfXcpUHSjQ",
    "status": 400,
    "error": {
     "type": "mapper_parsing_exception",
     "reason": "Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters."
    }
   }

I delete the _id then it seems that document is inserted to the index as it replys:
{
 "took": 2,
 "errors": false,
 "items": [
  {
   "index": {
    "_index": "bt_svc_ap",
    "_type": "event",
    "_id": "TcINqL5YEeWQofgPQf2AyQ",
    "_version": 1,
    "_shards": {
     "total": 1,
     "successful": 1,
     "failed": 0
    },
    "status": 201
   }
  }
But new question, I can't see it in my kibana.Why?I use the count() method ,the document number is increasing.
{ count: 7343634,
  _shards: { total: 18, successful: 18, failed: 0 } }

**Comment by yuz11** [comment]
Must specify timestamp data type first...
