### ISSUE TITLE
Wrong score and results 

### ISSUE THREAD

**Issue by maqboolkhan** [elastic/elasticsearch-js#347]
I want search `clash of clans` on my `apps` document type and my index is `indexer`!
here is my query
```
{
"query": {
        "match": {
              "_all": "clas of clan"
          }
 }
}
```

when i run this query via elasticsearch's nodejs module i got wrong results and `max_score` and `score` is 1 but when i try this query on Python `elasticsearch` module then its returning correct results :cry: 
m using ES 1.7 ES.js 1.7 ES.py 1.7 kindly help

**Comment by RXminuS** [comment]
Was this ever resolved?
