### ISSUE TITLE
filter_path parameter

### ISSUE THREAD

**Issue by pgherveou** [elastic/elasticsearch-js#377]
Hi I was wondering if the **[filter_path](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/common-options.html#_response_filtering)** parameter could be specified when building query, to avoid parsing huge elasticsearch responses

Here is my use case: I have the following query where

- I execute a first term aggregation that returns a large number of buckets
- then execute a metric aggregation on this bucket (avg in this example)
- and finally a sum_bucket aggregation
- When I run this query, the output contains all the intermediary my_huge_bucket.my_huge_bucket_metric results but I am only interested by the sum_bucket metric.

Is there a way to strip the intermediary aggregation from the result?

```json
{
  "size": 0,
  "aggs": {
    "my_sum_bucket": {
      "sum_bucket": {
        "buckets_path": "my_huge_bucket.my_huge_bucket_metric"
      }
    },
    "my_huge_bucket": {
      "terms": {
        "field": "some_field",
        "size": 0
      },
      "aggs": {
        "my_huge_bucket_metric": {
          "avg": {
            "field": "some_field"
          }
        }
      }
    }
  }
}
```

**Comment by ilovett** [comment]
I would think that

```
client.search({
  index: 'myindex',
  q: 'filter_path=aggs.**.sum_bucket',
  body: {
    size: 0,
    aggs: { ... }
  }
})
```

would do the trick, but I am having trouble adding to the query string with the search function

**Comment by spalger** [comment]
@ilovett the `q` parameter is actually the lucene query string, not a url query string.

To specify arbitrary query string parameters all you need to do is add them to the root of the object passed to any api method. So @ilovett 's example would become:

```js
client.search({
  index: 'myindex',
  filter_path: 'aggs.**.sum_bucket',
  body: {
    size: 0,
    aggs: { ... }
  }
})
```

---

That said, I would also like to add actual support for this and get it listed in the [api conventions](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-conventions.html), so I'll leave this open

**Comment by spalger** [comment]
Correction, it already is supported and documented in the [api conventions](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-conventions.html)!

**Comment by ilovett** [comment]
Excellent, thanks, yes I also just spotted on [this page](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/quick-start.html#_ping_the_cluster) that any "undocumented params are appended to the query string"

**Comment by ilovett** [comment]
I do think that an additional note about that could be added to the [api reference](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html) as it wasn't so easy to find.  I normally `ctrl+f` for these types of things.

**Comment by spalger** [comment]
Yeah, that's a fair point. Thanks for the tip. I'll probably update the api docs to have the api conventions at the top of each page, rather than on a new page. Unfortunately they are already so big :/
