### ISSUE TITLE
how do i mention multiple url in host

### ISSUE THREAD

**Issue by sandeepn9494** [elastic/elasticsearch-js#382]
i want to mention multiple elastic nodes in host .so that when one node is down searching will happen from another node.
i tried this approach didn't work  : http://stackoverflow.com/questions/25763811/node-js-elasticsearch-multiple-hosts
how do i do that any suggestions .Thanks

**Comment by spalger** [comment]
This is definitely supported:

```js
const elasticsearch = require('elasticsearch');
const client = new elasticsearch.Client({
  hosts: [
    {  host: 'localhost', port: '9200' },
    'https://localhost:9201'
  ]
});
```
