### ISSUE TITLE
Get total bucket count per aggregation

### ISSUE THREAD

**Issue by henninga** [elastic/elasticsearch-js#383]
When getting a size limited aggregation (say 5 items), is it possible to ask for the total number of matching results per aggregation given the specified filter/query?

Pretty much exactly the same thing that you get total property under hits but for aggregations

**Comment by spalger** [comment]
Yes, every bucket bucket includes a `doc_count` property

![image](https://cloud.githubusercontent.com/assets/1329312/14287973/bbdaeace-fb09-11e5-9407-9084c735fc56.png)
