### ISSUE TITLE
No way to put and overwrite existing document

### ISSUE THREAD

**Issue by scmorse** [elastic/elasticsearch-js#388]
`client.create` throws an error if the document already exists. It would be nice if there were a way to PUT a document, overwriting it if it already exists and writing it if it doesn't, just like the PUT `/index/type/id` endpoint of the ES server.

Could maybe add a config option to `client.create`? Or another method `client.putDocument`?

**Comment by spalger** [comment]
I think you're looking for the `client.index()` method.
