### ISSUE TITLE
Don't include all API versions with very npm version

### ISSUE THREAD

**Issue by aaronshaf** [elastic/elasticsearch-js#389]
The current version includes a folder for very ElasticSearch version in `src/lib/apis`. This is unnecessarily large (2.3M). Perhaps different versions of the module could be released for every API?

**Comment by spalger** [comment]
This is a lot easier for me to manage, and 2.3mb really isn't that big in my opinion. I'm open to better solutions, but until this is causing an actual issue I don't think it's worth the time to change.

**Comment by delvedor** [comment]
Hi! We are working on this! :)
Closing for now, feel free to reopen!
