### ISSUE TITLE
Client-side: Logger is not a constructor

### ISSUE THREAD

**Issue by anault** [elastic/elasticsearch-js#392]
Server-side is working flawlessly, but on the client side, I get this error when I run `new elasticsearch.Client(...)`.

```
Uncaught TypeError: Logger is not a constructor
```

Located here in the package :
```
  // ...
  config.levels = Log.parseLevels(config.levels || config.level || 'warning');
  delete config.level;

  var Logger = _.funcEnum(config, 'type', Log.loggers, process.browser ? 'console' : 'stdio');
  return new Logger(this, config);
};  
// ...
```
Logger in undefined.

I need help please :)

**Comment by jargot** [comment]
I don't think you're supposed to run this client-side, see [the elastic official docs.](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/browser-builds.html)

But I might be wrong!

**Comment by anault** [comment]
This is quite confusing:
> Check out the [Browser Builds doc page](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/browser-builds.html) for help downloading and setting up the client for use in the browser.

I wouldn't be surprised if it was impossible to setup client-side though haha

**Comment by dubielzyk** [comment]
How'd you fix this. I'm getting this issue

**Comment by spalger** [comment]
When you are running into issues using the generic `elasticsearch` npm module with your build system/front-end framework I suggest using the `elasticsearch-browser` one.
