### ISSUE TITLE
Override request method for search

### ISSUE THREAD

**Issue by claygorman** [elastic/elasticsearch-js#395]
Is there a way I can tell my client.search() to use GET instead of the default POST?

**Comment by spalger** [comment]
Yep, every API method supports these [generic request parameters](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-conventions.html#_generic_parameters), including `method`.

**Comment by claygorman** [comment]
wow somehow I missed that... thank you very much!
