### ISSUE TITLE
How to index to 1 shard

### ISSUE THREAD

**Issue by jloveric** [elastic/elasticsearch-js#397]
Hi, is it possible to index to a single shard using this elasticsearch interface?  Right now I use this command for indexing

```
client.index({
  index: "someIndex",
  type: "pub",
  id: count,
  body: item,
  settings: { index: { number_of_shards: 1 } }
  }, (error, response) => {
  //do something
}) 
```

Which creates the index just fine, but seems to be using 5 shards instead of 1.  Running the count command on the resulting index gives 
`http://localhost:9200/someIndex/_count {"count":73,"_shards":{"total":5,"successful":5,"failed":0}}`

which implies there are 5 shards.  What is the correct way to write to 1 shard?  I'm using elasticsearch 2.3 and the node elasticsearch interface version 11.  Thanks!

**Comment by spalger** [comment]
The settings you are passing int he `client.index()` call actually need to be sent in a `indices.create()` request before you start indexing. Check out https://www.elastic.co/guide/en/elasticsearch/reference/2.1/indices-create-index.html for more info
