### ISSUE TITLE
client.close() does not release elasticsearch connection until maxKeepAliveTime elapses

### ISSUE THREAD

**Issue by aaronyo** [elastic/elasticsearch-js#40]
Even when there are no pending requests, client.close() does not release an elasticsearch connection until maxKeepAliveTime elapses (which is defaulted to 5 min).

Expected: the connection closes immediately so that, for example, your node process can terminate immediately.

I'm using version 1.4.0

**Comment by rash805115** [comment]
I am using the latest version `~0.7.5`, and I am not able to close the connection using `client.close()` method. I am assuming that the `keepAlive` option is forcing the client to be forever open, but for testing in local/pipeline I need the connection to be closed after the test ends. How should I go about solving this problem?

**Comment by vanthome** [comment]
A `close()` method does not exist in the most recent version `15.2.0` but I think it's needed.
