### ISSUE TITLE
Rx / observable support for elasticsearch-js

### ISSUE THREAD

**Issue by templth** [elastic/elasticsearch-js#406]
I wonder if there is a support of reactive programming (rxjs) / observables in the library. This would allow me to integrate requests on ElasticSearch within an asynchronous data flow and leverage of advantages of observables (lazy initialization, cancellation, observable operators).

It's something interesting specially when using the library within an Angular2 application.

**Comment by spalger** [comment]
Not yet, but I would be interested in seeing how that might look! I haven't had time to play with observables much, though I would like to learn more.

**Comment by templth** [comment]
Great! Pleased to hear that ;-)

In fact, it's a bit similar to promises. Here is the way to create a raw observable with Rxjs:

```
let obs = Observable.create((observer) => {
  let id = setInterval(() => {
    // A message is sent each 2s
    observer.next({ message: 'some message' });
  }, 2000);

  // clear setInterval when the subscription is deleted (unsubscribe)
  return () => {
    clearInterval(id);
  };
});
```

You can subscribe on the observable using the `subscribe` method. The latter returns a subscription that can be canceled using the `unsubscribe` method. Here is a sample:

```
let subscription = obs.subscribe(
  (obj) => {
    // obj provided in the next method above
  },
  (err) => {
    // obj provided in the error method (if called instead of next)
  },
  () => {
    // obj provided in the complete method that finalize the observable
  }
);

subscription.unsubscribe();
```

**Comment by spalger** [comment]
Interesting, would you expect any of the current methods to emit/provide/send(?) more than a single value?

**Comment by templth** [comment]
I'm not sure to understand what is `emit/provide/send` but observables are event-drive. This means that you can call several times the `next` method unlike promises. When you resolve a promise you can use it anymore...

Otherwise I'd be really pleased to contribute / discuss such support in the library ;-)

**Comment by spalger** [comment]
> I'm not sure to understand what is emit/provide/send

I was guessing at the verb people use to describe "call the next method with a value'"

Let me restate my question: wouldn't all of the observables created by elasticsearch-js only result in a single value? What type of API would you imagine benefitting from the ability to provide multiple values?

On I can think of is the ability to scan over results, similar to how [elasticsearch-scrolltoend](https://www.npmjs.com/package/elasticsearch-scrolltoend) works, but in that case it feels better implemented outside of the client.

Another option is to support an observables returning API in the angular version of the client, and potentially others if we can find a nice way to do it. This way people can use the client with angular 2 without "observable-ify"-ing it like you regularly have to do in the promise world.

**Comment by dotfold** [comment]
@spalger I agree, adding support for observables inside the client is not the right place - the internals of elasticsearch-js would need to understand the concept of a query being a producer that will send 0 or more values over time. This would be a fairly drastic change to the intent and API surface of this library.

@templth Wouldn't it be cleaner to just use `Rx.Observable.fromPromise` in your consumer code? https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/frompromise.md

**Comment by templth** [comment]
@dotfold Sure you could leverage the `fromPromise` method as a shortcut. This approach has however some drawbacks. You need to be aware that promises are wrapped into observables with this approach. This means that they aren't lazy and you can't cancel it.

Let's take a sample. You want to link an ElasticSearch request with an input to implement an auto complete feature. Rx allows you to handle this efficiently with operators like `switchMap` (cancel the in-progress observables) or `debounceTime` / `distinctUntilChanged`. With `switchMap`, when the user enters a character, a request is executed. If a request is in progress regarding the previous entered character, it will be canceled. Using `fromPromise`, the request can't be canceled since the underlying promise can't be canceled.

This feature is interesting since this ensures that the correct / last result is actually handled. For example, if the response for the first request is received after the result of the second one.

Such approach can be used (for example within Angular2) this way:

```
this.items = this.term.valueChanges
                 .debounceTime(400)
                 .distinctUntilChanged()
                 .switchMap(term => {
                   return Observable.fromPromise(client.search({
                     q: 'pants'
                   }).then((body) => {
                     return body.hits.hits;
                   });
                 });
```

`term` is a control associated with an input. Something like that:

```
@Component({
  (...)
  template: `
    <input [ngFormControl]="term"/>
    <ul>
      <li *ngFor="let item of items | async">{{item.name}}</li>
    </ul>
  `
})
export class SomeComponent {
  constructor() {
    this.term = new Control();
    this.items = this.term.valueChanges
                           (...)
  }
}

**Comment by templth** [comment]
@spalger unless you want to have some kind of streaming for requests, I agree with you that only a single value will be return through the observable.

I had a look at the elasticsearch-scrolltoend regarding the "call the next method with a value". I think that it's possible to implement this by combining two observable / observer.

In the `ScrollableService` class, I use the `scrollSubject` (FYI a subject is both observable and observer) to trigger the retrieval of next data.

This service uses fake data so it could be easily improved ;-) It's to describe how to implement things.

```
export class ScrollableService {
  executeRequest(observer, scrollSubject, index) {
    setTimeout(() => {
      observer.next({
        data: [ { id: index+1 }, { id: index+2 }],
        nextObserver: scrollSubject
      });
    }, 2000);
  }

  getData() {
    return Observable.create(observer => {
      var scrollSubject = new Subject();
      
      let index = 0;
      
      this.executeRequest(observer, scrollSubject, index);
      index += 2;

      scrollSubject.subscribe(() => {
        this.executeRequest(observer, scrollSubject, index);
        index += 2;
      });
    });
  }
}
```

For the user of this service, you can leverage the `nextObserver` that allows you to scroll. This observer can be extract from the response using the `map` operator. The `scan` operator allows to aggregate the result to the previous one. You can this way leverage the async pipe of Angular2...

```
// Call this method to get initial data and the next observer
loadData() {
  this.data = this.scrollableService.getData().map((result) => {
    this.nextObserver = result.nextObserver;
    return result.data;
  })
  .startWith([])
  .scan((acc,value) => acc.concat(value));;
}

// Scroll to the next data
scroll() {
  this.nextObserver.next();
}
```

See this plunkr as a sample: https://plnkr.co/edit/HrG6sD4QH1KkD35gm5M0?p=preview. The code related to this is located into files `src/scrollable.ts` and `app.component.ts`.

Otherwise as described in my previous comment, a key difference with promise is the ability of observables to be lazy and canceled.

**Comment by delvedor** [comment]
https://github.com/elastic/elasticsearch-js/issues/406
