### ISSUE TITLE
Running new elasticsearch.Client(...) on the client

### ISSUE THREAD

**Issue by dubielzyk** [elastic/elasticsearch-js#407]
I'm using Meteor and I've installed _elasticsearch_ via npm.

When I run `new elasticsearch.Client(...)` I get  `Logger is not a constructor` in my console.

Help?

**Comment by spalger** [comment]
This is probably because the config option for log is not valid. Can you include what you can from your configuration?

**Comment by dubielzyk** [comment]
I'm using ElasticSearch Cloud. I pass
```
var elasticsearch = require('elasticsearch');
var client = new elasticsearch.Client({
  host: hostnameFromCloud,
  log: 'trace'
});
```

**Comment by spalger** [comment]
You probably need to use the `elasticsearch-browser` module. Certain systems will use the `"browser"` configuration in the package.json file (like webpack and browserify) but others don't, so they might not get the right modules when building `elasticsearch` for the browser.

**Comment by nengine** [comment]
I have meteor-augular 1.4 application and was getting an error after importing elasticsearch module on  the client side.  Any help is greatly appreciated.

```js
import elasticsearch from 'elasticsearch-browser';
export default angular.module(name, [
  angularMeteor,
  uiRouter,
  'elasticsearch'
])
```


[$injector:nomod] Module 'elasticsearch' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
