### ISSUE TITLE
esFactory is not sending Content-Type header on Firefox

### ISSUE THREAD

**Issue by lourenco** [elastic/elasticsearch-js#412]
The elasticsearch client version to angular is not sending Content-Type header

https://jsfiddle.net/app40wLp/4/

**Comment by RogerGMartins** [comment]
Hosts object is an array. you have an object.


`var client = esFactory({
    host:[ {
      
        protocol: 'https',
        host: 'demo7672770.mockable.io',
        port: '443',
        path: '',
        headers: {
          'Content-Type': 'text/plain',
          'Other-Header': true
        }
      
    }]
  })`
