### ISSUE TITLE
How to push  data to elasticsearch using NodeJS

### ISSUE THREAD

**Issue by Git-Rajkumar** [elastic/elasticsearch-js#413]
I am working on creating live chat application using nodejs and socket.io,  i need to push  chat information to elasticsearch  using node.js.

I follow this link  https://www.npmjs.com/package/elasticsearch    to connect elasticsearch. But, I don't know How to push chat information to elasticsearch. Where to set configuration and push to elastic search Suggest me how to do this?.

**Comment by spalger** [comment]
I'm not sure what to suggest beyond the [examples](https://www.npmjs.com/package/elasticsearch#examples), but perhaps you should ask your question in the [user forums](https://discuss.elastic.co/). The issue track is for bugs and feature requests.
