### ISSUE TITLE
Querying multiple indices?

### ISSUE THREAD

**Issue by fikse** [elastic/elasticsearch-js#414]
Hi, is there a way to tell the client to query multiple indices, maybe using regex? In this post, 
https://discuss.elastic.co/t/failing-to-create-mappings-logstash-elasticsearch/52540
, I show how I would query multiple indices if the client doesn't allow this, but I'm hoping there's a better way to do this. I'm noticing there's a way to tag indices with aliases, maybe this is what I'm needing?

**Comment by spalger** [comment]
Yeah, you can use a wildcard or an array of index names if you want:

```js
```

**Comment by fikse** [comment]
Thank you!
