### ISSUE TITLE
How is update_all_types param on putMapping supposed to be passed?

### ISSUE THREAD

**Issue by gabrielpjordao** [elastic/elasticsearch-js#421]
Hey there,

I'm trying to update a mapping for an index passing `update_all_types` get param, as in https://www.elastic.co/guide/en/elasticsearch/reference/2.2/indices-put-mapping.html#CO114-4

I'm using the following code:

``` javascript
esClient.indices.putMapping({
  index: ...,
  type: ...,
  updateAllTypes: true,
  body: {
      properties: {
         ...
      }
  }
});
```

I'm using `updateAllTypes` param from https://github.com/elastic/elasticsearch-js/blob/v8.2.0/src/lib/apis/2_x.js#L3422 (using v8.2.0 with ES 2.2.0)

From what I can see from the stack trace, it is not using the correct params. It says the path is `/my-idx/_mapping/my-type` rather than the expected `/my-idx/_mapping/my-type?update_all_types` (Not sure if it would display the actual url with params there, though).

Is this a versioning issue, am I using it the right way or is it really bugged?

Thanks!

**Comment by kamalkech** [comment]
some issue here THEME ELASTIC SEARCH !!

**Comment by spalger** [comment]
Hope you got this working, the `updateAllTypes` parameter is definitely supported and works. I recommend turning on trace logging to see the actual requests that are being sent. The path alone will not include the query string.
