### ISSUE TITLE
How to setup Basic Auth on cross domain with AngularJS ?

### ISSUE THREAD

**Issue by Emidomenge** [elastic/elasticsearch-js#424]
According [this doc](https://www.elastic.co/guide/en/shield/current/_using_elasticsearch_http_rest_clients_with_shield.html) I need to setup `Authorization: Basic <TOKEN>` somewhere in my code but I don't know where to do it because I'm using AngularJS.

My service looks like this. Should I put the basic token here ?
```

angular.module('myModule')
  .service('testElastic', function (esFactory) {
    return esFactory({
      //host: [
      //  {
      //    host: 'myurl.com',
      //    auth: 'elalogin:elapass'
      //  }
      //]
      host: 'http://elalogin:elapass@myurl.com:9200'
    });
  });
```
In my controller : 
```
testElastic.cluster.state({
        metric: [
          'version'
        ]
      })
      .then(function (resp) {
        $scope.clusterState = resp;
        $scope.error = null;
      })
      .catch(function (err) {
        $scope.clusterState = null;
        $scope.error = err;
        // if the err is a NoConnections error, then the client was not able to
        // connect to elasticsearch. In that case, create a more detailed error
        // message
        if (err instanceof esFactory.errors.NoConnections) {
          $scope.error = new Error('Unable to connect to elasticsearch. ' +
            'Make sure that it is running and listening at http://localhost:9200');
        }
      });
```
then I receiving a deny access : 
`XMLHttpRequest cannot load http://myurl.com:9200/_cluster/state/version. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.`

**Comment by lowenzachn** [comment]
+1
I've stucked with the same problem

**Comment by Emidomenge** [comment]
Well, I found a solution that worked for me : 
http://stackoverflow.com/questions/33051405/elasticsearch-js-client-connection-refused-access-control-allow-origin-not-reco?answertab=votes#tab-top

Hope it's help ! :+1:
