### ISSUE TITLE
Full update of document

### ISSUE THREAD

**Issue by HainPalaxo** [elastic/elasticsearch-js#425]
Current API (11.0.1) only allows to do partial update of documents. For my application I would like to have ability to use "full" update of document like in ElasticSearch REST API. Something like this:

```
PUT localhost:9200/test/type1/1 
{
    "counter" : 1,
    "tags" : ["red"]
}
```

Any ideas, how could it be done with current API, or is this really not supported?

**Comment by spalger** [comment]
You are correct, the update API is only for modifying documents. The index API is for replacing them.
