### ISSUE TITLE
Huge degradation in search performance btw elasticsearchjs and REST endpoint

### ISSUE THREAD

**Issue by ganarajpr** [elastic/elasticsearch-js#426]
We have been using the elasticSearch.js in our production version and while doing a refactor one of the things I noticed was that there is a huge difference in performance when making the same query through elasticSearch.js and through the REST endpoint.

The REST Endpoint takes close to `~50ms` to do the same search ( the same query ) while elasticSearch.js takes `1.5-2.5 seconds`.. This is a huge performance hit and is probably not acceptable to most use cases. ( I just want to note that its for the same database - with the same query ). 

I want to know if its just me ( am I doing something wrong ? )

Here is the nodejs code I am using to run the same query through the rest endpoint. 

```javascript
function doSearch(postBody) {
    var http = require('http');

    return new Promise( function (resolve) {
        var request = http.request({
            host: 'localhost',
            path: '/catalog/_search',
            port: 9200,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Content-Length': postBody.length
            }
        }, function(response) {
            var reply = '';
            response.on('data', function(chunk) {
                reply += chunk;
            });

            response.on('end', function() {
                resolve(reply);
            });
        });

        request.write(postBody);
        request.end();
    });

}

```

The equivalent code through this sdk / library is:

```javascript

function search(queryBody) {
    var searchParams = {
        index: 'catalog',
        type: 'product',
        body: queryBody,
        size: 10000
    };
    return client.search(searchParams);
}

```

We have a catalog of around 92k products. 
The query that I am running is just an aggregation query ( size: 0 ).

**Comment by spalger** [comment]
The plain rest call isn't requesting 10000 documents, I bet that's what is
causing the slowdown.

**Comment by ganarajpr** [comment]
Thanks that seems to be the difference :)
