### ISSUE TITLE
How to use aggregation in angularjs?

### ISSUE THREAD

**Issue by harinathcse** [elastic/elasticsearch-js#427]
I downloaded the sample application from https://github.com/spalger/elasticsearch-angular-example.
I was able to connect and perform basic query inside the app but could not perform the aggregation in client

`
// Create the es service from the esFactory
logbarfApp.service('elasticClient', function (esFactory) {
  return esFactory({ host: 'localhost:9200' });
});

// We define an Angular controller that returns query results,
// Inputs: $scope and the es service

logbarfApp.controller('MyController', function($scope, $document, elasticClient, esFactory) {

// search for documents
  $scope.newresult = function(){

    elasticClient.search(
      {
        "size": 1,
        body:{
      "sort": [
        {
          "logtimestamp": {
            "order": "desc"
          }
        }
      ],
      "fields": [
      "logtimestamp",
      "body"
    ],
      "query": {
        "filtered": {
          "filter": {
            "bool": {
              "must": [
                {
                  "range": {
                    "logtimestamp": {
                      "gte": 1466121600000,
                      "lte": 1466123400000,
                      "format": "epoch_millis"
                    }
                  }
                }
              ],
              "must_not": []
            }
          }
        }
      }
    },
    "aggs": {
      "corrid_agg": {
        "terms": {
          "field": "color",
          "size": 1000
        }
      }
    }
	}).then(function (response) {
      $scope.hits = response.hits.hits;
    });

  };
});`

When I run the above query, it does not return result for aggregation. Any help would be great.
Thanks in advance.

**Comment by harinathcse** [comment]
@spalger Can you please have look into the issue?

**Comment by spalger** [comment]
@harinathcse this issue tracker is intended for bug reports and feature requests. In the future please ask your questions on IRC or the https://discuss.elastic.co forums.

This seems like it may be an issue with the way you are readying the response. The aggregations are on the response at `response.aggregations`

**Comment by harinathcse** [comment]
Thanks a lot @spalger.

**Comment by hari-kris** [comment]
@hadihonarvar 
As @spalger  said
This seems like it may be an issue with the way you are reading the response. The aggregations are on the response at response.aggregations
