### ISSUE TITLE
Node.js search method not working.

### ISSUE THREAD

**Issue by mastayoda** [elastic/elasticsearch-js#430]
Hello everyone,

I'm trying to make a simple search using elasticsearch using the Node.js driver.

The problem is the following:

I have several documents stored in the engine, some look like:

```
{
    index: 'mygraph',
    type: 'edge',
    id: '1',
    body: {
        relation: 'knows',
        source: 1,
        target: 2
    }
}
```

If I go to the browser and execute this URL: [](http://localhost:8004/mygraph/edge/_search?q=relation:knows)

I get:

```
{
    "took": 5,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 1,
        "max_score": 1.0,
        "hits": [{
            "_index": "mygraph",
            "_type": "edge",
            "_id": "1",
            "_score": 1.0,
            "_source": {
                "relation": "knows",
                "source": 1,
                "target": 2
            }
        }]
    }
}
```

Then if I do the same in the Node.js driver(which is the same POST request shwoing in the trace):

Elasticsearch TRACE: 2016-07-26T15:00:01Z
-> POST http://localhost:8004/mygraph/edge/_search?q=relation%3Aknows

I get:
```

{
    "took": 2,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 0,
        "max_score": null,
        "hits": []
    }
}
```

Somebody can tell me what is wrong?

Here is the class file: [http://pastebin.com/cc1GgNAx](url)
Here is the test script: [http://pastebin.com/VsGY3CuL](url)

Info: 
- I'm on OSX Mavericks 
- Using Node.js 6.2
- Javascript driver is 11.0.1
- Elasticsearch 2.3.4

Thanks in advanced!

**Comment by mastayoda** [comment]
Ok, I think I now see the problem, I'm not giving time for the indexes to be refreshed... if I specify the refresh flag in the index method, it yields correct results. Is this correct?

**Comment by spalger** [comment]
You are correct, indexing a document only makes them available for search after the next refresh, and elasticsearch refreshes about once per second by default. It's generally considered a bad idea to set the `refresh` flag, but rather let elasticsearch take care of the refreshing for you and deal with the delay some other way.

**Comment by kvelaro** [comment]
> Ok, I think I now see the problem, I'm not giving time for the indexes to be refreshed... if I specify the refresh flag in the index method, it yields correct results. Is this correct?

Could you please provide your solution. We have ES6.2, and in documentation it seems that indices.create promise does not have `refresh` option.
