### ISSUE TITLE
Bluebird integration without using `defer`

### ISSUE THREAD

**Issue by daedalus28** [elastic/elasticsearch-js#431]
The official way to use bluebird with this library is to [pass in the `defer` function](https://github.com/elastic/elasticsearch-js/blob/bc238288f6a49cfbf55946e98c598526da5347eb/scripts/generate/templates/configuration_docs.tmpl#L222), but bluebird has [deprecated the `defer` function](http://bluebirdjs.com/docs/api/deferred-migration.html) and throws warnings in v3 when you use it.

Any chance elasticsearch-js can take the actual Promise constructor?

**Comment by spalger** [comment]
While esjs could/should be updated to support the Promise constructor, creating a defer object is super simple and I suggest just doing that for now.

```js
client = new Client({
  defer() {
    const defer = {}
    defer.promise = new Bluebird((resolve, reject) => {
      defer.resolve = resolve
      defer.reject = reject
    })
    return defer
  }
})
```

**Comment by spalger** [comment]
Bluebird was removed in 10.0, and in 13.0 we will move to actual native promises (no shim)
