### ISSUE TITLE
index type source field value big number lose precision

### ISSUE THREAD

**Issue by XueseGhost** [elastic/elasticsearch-js#432]
the source like this:
_source":{"join_time_unix_timestamp":1470380067000,"location":"","leave_reason":0,"leave_time":"2016-08-05T07:45:24.000Z","leave_time_unix_timestamp":1470383124000,"conf_id":"304edbe1e5f340ea8f0957475fdd0428","user_nickname":"fdfdf","site_id":1,"join_type":0,"user_ip":"221.12.175.78","user_data":" ","duration":3057,"area":" ","join_time":"2016-08-05T06:54:27.000Z","user_id":1524753829371840599}

client get the result and parse json, but the filed user_id value is '1524753829371840500' #lose precision

**Comment by spalger** [comment]
Sorry, but this is a limitation of JavaScript. https://en.wikipedia.org/wiki/Double-precision_floating-point_format
