### ISSUE TITLE
Create index: [parse_exception]  unit is missing or unrecognized

### ISSUE THREAD

**Issue by orinciog** [elastic/elasticsearch-js#435]
Hello,

I want to create an index using **indices.create** function and I want to specify the **masterTimeout**.
The problem is that no matter how I define this property, elastic throws one error:
- masterTimeout: 120 (number). Error: [parse_exception] Failed to parse setting [master_timeout] with value [120] as a time value: unit is missing or unrecognized
- masterTimeout: "120" (string):  Error: [parse_exception] Failed to parse setting [master_timeout] with value [120] as a time value: unit is missing or unrecognized

I'm using ES 2.3.4 and elasticsearch.js 11.0.1

Update: It worked with masterTimeout: "120s", you should change the documentation for this property. masterTimeout in ES 2.X is not anymore a number, is a string with units inside.

Thank you,

**Comment by spalger** [comment]
This was fixed in v12.1.0
