### ISSUE TITLE
Not using template while indexing data

### ISSUE THREAD

**Issue by rohit-raj** [elastic/elasticsearch-js#443]
I have encountered another problem, I dont know its only me who is getting this issue.

When I store the templates for different indices.
template name being the name of the ElasticSearch type.

the template looks like:
```
{
  "template": "account*",
  "settings" : {
      "number_of_shards" : 1
  },
  "mappings" : {
    "account" : {
      "properties" : {
        "email" : {
          "type" : "string"
        }
      }
    }
  }
}
```

but when i use
```
this.eSClient.index({
  index: this.index,    // index = accounts
  type: this.type,      // type = account
  id: key,
  body: data }, (error, response) => {
  if (callback) {
    callback(error, response);
  }
});
```
the template that I just saved is not getting used.

i have set `index.mapper.dynamic : false`

the issue that I get:
`failed to index accounts/account/ffdcbfc6-0643-44f1-b1b7-8c93f2c266e0: [index_not_found_exception] no such index, with { resource.type=index_expression resource.id=accounts index=accounts }
"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_expression\",\"resource.id\":\"accounts\",\"index\":\"accounts\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_expression\",\"resource.id\":\"accounts\",\"index\":\"accounts\"},\"status\":404}" `
Please suggest some inputs to this.

**Comment by spalger** [comment]
I suggest you ask the community at the elasticsearch forums, this issue tracker is for bugs and feature requests

https://discuss.elastic.co/c/elasticsearch
