### ISSUE TITLE
Watchers management

### ISSUE THREAD

**Issue by albertvp** [elastic/elasticsearch-js#450]
Hi there,

I'm using this NPM as a NodeJS client, working fine for creating indices and making searches...

I'd like to use the [watcher plugin](https://www.elastic.co/guide/en/watcher/2.4/index.html) to execute actions with a web hook when my data changes.

It seems to me that this feature is not available with this client, is there any lib or tool to manage elasticsearch watchers? I mean, should I use a custom http request to create/remove the watchers and setup a http server to receive the trigger?

Do you plan to add it to this client?

**Comment by spalger** [comment]
I do plan to add it to the client, just haven't gotten there quite yet. Stay tuned!

**Comment by gpestana** [comment]
This would be a super nice feature to have. @spalger need help on this one?
