### ISSUE TITLE
Release v12 plan/schedule?

### ISSUE THREAD

**Issue by bengourley** [elastic/elasticsearch-js#451]
Hi, sorry if this is documented elsewhere, I can't find any information relating to the release schedule.

I'd like to upgrade to v12 (as of writing you're on 12.0.0-rc5) in order to get support for API version 2.4 (and the removal of the lodash-compat dependency), just wondering if there is a date in the pipeline of when v12 will be published to npm, or if there is something blocking it from being released?

Cheers 🔍

**Comment by spalger** [comment]
My plan was to release v12 with elasticsearch 5.0, but as that hasn't happened yet I'm considering pushing up v12 now and using v13 to change the default api to 5.0. In the meantime, feel free to use the rc, the only "breaking change" is the new default `apiVersion`
