### ISSUE TITLE
Client.create error on elastic:5.0.0-rc1

### ISSUE THREAD

**Issue by fcrisciani** [elastic/elasticsearch-js#453]
A simple:
`client.create({
              index: index_name,
              type: doc_type,
              timestamp: elem.date,
              body: elem
          },function (error_els, response) { [..] })`

returns the following error is the post is done to Elastic:5.0.0-rc1:
Validation Failed: 1: an id must be provided if version type or value are set

The condition in elastic that is being hit is the following:
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/index/IndexRequest.java
`if (id == null && (versionType == VersionType.INTERNAL && version == Versions.MATCH_ANY) == false) {
            validationException = addValidationError("an id must be provided if version type or value are set", validationException);
        }`

My objective is to do a POST so that the id is automatically generated by elastic. The call works fine till elastic:5.0.0-alpha5

**Comment by spalger** [comment]
That sounds like a possible bug, If you could provide a reproducible example (in a gist or something) it would be very helpful.

**Comment by fcrisciani** [comment]
here you are: https://gist.github.com/fcrisciani/85da15fc79d1212d9623cd38b2dc1dd6

**Comment by fcrisciani** [comment]
it's a simple node.js program. Just change the elastic IP and run it: node test.js
The output is the one that I mention in the GIST.
To run elastic I use a docker container:
docker run --name elasticsearch -d -p 9200:9200 -p 9300:9300 elasticsearch:5.0.0-rc1

**Comment by fcrisciani** [comment]
If the id instead is set the call goes through

**Comment by spalger** [comment]
I just got word from the elasticsearch team that `client.create()` actually requires an id now, but if you use `client.index()` instead it will auto-generate the id. Time to upgrade the API docs. Good catch!

**Comment by fcrisciani** [comment]
ok sounds good, thanks for the quick turnaround! Will try with 'client.index()' then!

**Comment by mariotacke** [comment]
Just ran into this myself. I think the docs for `create` could use a link to the `index` method to clarify this behavior. I was used to the curl `PUT` and `POST` behavior and IMO `create` seemed to be the most idiomatic way to express creating a document/index (with or without an id).
