### ISSUE TITLE
indices.create is using method 'POST' instead of 'PUT'

### ISSUE THREAD

**Issue by w4-sglim** [elastic/elasticsearch-js#456]
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-create-index.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/indices-create-index.html

Recent document using 'PUT' and 'POST' is not supported over 5.0.

https://github.com/elastic/elasticsearch-js/blob/67c931c5de3a8a0a6e7e7c8bac19b7c77d379380/src/lib/apis/2_4.js#L2326

current workaround is using 'PUT' forcefully.
esClient.indices.create.spec.method = 'PUT';

**Comment by spalger** [comment]
This was fixed in v12.0.1
