### ISSUE TITLE
Changelog was really hard to find

### ISSUE THREAD

**Issue by aredridel** [elastic/elasticsearch-js#458]
starting with updating to v12, I chased for about ten minutes before I found the changelog explaining what the breaking change was in the repo.

It'd be great if this was in the documentation on your site, or otherwise more accessible.

**Comment by spalger** [comment]
:+1: thanks for pointing that out

**Comment by spalger** [comment]
Changelog is now discoverable at [elastic.co](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/12.0/changelog.html)

**Comment by aredridel** [comment]
Oh you are the best!
