### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by xtuc** [elastic/elasticsearch-js#459]
This is related to issue #313.

I encounter the same issue with Node `v6.9.1` and elasticsearch-js `v11.0.1`.

Node options : `--expose-gc` `--max-old-space-size=8192` `--max-semi-space-size=1024`.
_I increased the young space hopping that it will fix the problem._

ElasticSearch response is about 77Mb.

Error details:
```
error RangeError: Invalid string length
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/elasticsearch/src/lib/connectors/http.js:181:19)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at IncomingMessage.Readable.push (_stream_readable.js:134:10)
    at HTTPParser.parserOnBody (_http_common.js:123:22)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

I also got these errors:
```
2016-10-31T16:12:06.567Z - error: [ELASTICSEARCH] Request error, retrying
POST http://xx.xx.xx.xx:9200/_msearch => Parse Error
Unhandled rejection Error: Request Timeout after 180000ms
    at /usr/src/app/node_modules/elasticsearch/src/lib/transport.js:336:15
    at Timeout.<anonymous> (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:365:7)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

Since the request timed out I thought the client got an invalid chunk.
I made a trace :
```
[…]
[pid 27313] read(10, "[…]"..., 65536) = 65536
[pid 27313] read(10, "[…]"..., 65536) = 65536
[pid 27313] read(10, "[…]"..., 65536) = 52824
[pid 27313] read(10, "[…]"..., 65536) = 65536
[pid 27313] read(10, "[…]"..., 65536) = 65536
[pid 27313] read(10, "[…]"..., 65536) = 47032
[pid 27313] read(10, "[…]"..., 65536) = 65536
[pid 27313] read(10, "[…]"..., 65536) = 65536
[pid 27313] read(10, "[…]"..., 65536) = 47032
[pid 27313] read(10, "[…]"..., 65536) = 65536
[pid 27313] read(10, "[…]"..., 65536) = 65536
[pid 27313] read(10, "[…]"..., 65536) = 42688
[pid 27313] read(10, "[…]"..., 65536) = 65536
[pid 27313] read(10, "[…]"..., 65536) = 41616
[pid 27313] read(10, "[…]"..., 65536) = 65536
[pid 27313] write(2, "/usr/src/app/node_modules/elasticsearch/src/lib/connectors/http.js:180\n    incoming.on('data', func"..., 811) = 811
[…]
```

The write operation is the beginning of the exception.
It seems that the chunks have the same length.

I had to cut out the content but there was nothing special. Partial JSON objects as string.

Any ideas ?

Thanks in advance,
Sven.

**Comment by spalger** [comment]
Hmm, I don't imagine the `JSON.parse()` function handling 77Mb of text very well. I've been thinking about updating the client to support streaming the responses back, but it will take some serious work. If I was in your shoes I would either make smaller, paginated, requests or switch to a raw http request and use a streaming JSON parser ([oboe](http://oboejs.com/) comes to mind) that could handle massive responses like that.

**Comment by xtuc** [comment]
Parsing a 77Mb response is not a big deal. It's a question of time and memory.

The issue occurs before parsing, during the downloading of the response.

My query has many aggregations. I don't know if I would benefit much from "in real time" parsing since the response has a lot of nested elements.
But it's is still a good point.

It seems to be a good idea to concatenate incoming data using a `Buffer` _which store data outside of the V8 heap_.
Source: [stackoverflow.com](https://stackoverflow.com/questions/24153996/is-there-a-limit-on-the-size-of-a-string-in-json-with-node-js/24154610#24154610).

I only encounter this issue in a subset of my data. I suspect a bad character in the response.

What about catching the exception as soon as possible and directly dump the bad chunk of data ? If this will help me, I will make a PR.

**Comment by spalger** [comment]
I'd be open to using `Buffer` objects instead of strings, but I feel like "Invalid string length" means that node.js won't be able to convert that `Buffer` back into a string so that `JSON.parse()` can do it's magic. 

This is why I suggested something like oboe. Not because it's "real time" but because it can parse the chunks of the response without needing a single string to represent all 77mb of response data.

**Comment by xtuc** [comment]
Paginating the request fixed this issue. Thanks.

**Comment by liorg2** [comment]
i get this issue on aggregation, which cannot be Paginated. it will be nice to at least wrap with try/catch

incoming.on('data', function (d) {
      **response += d;**
    });

**Comment by dimfeld** [comment]
I hacked up an Oboe-based parser that works within this library. There are a bunch of caveats here:

1. The CustomConnector class returns a Buffer into a part of the client that is expecting a string. This happens to work as of now, but isn't guaranteed to continue working.
2. The deserializer sometimes returns a promise into a part of the client that isn't actually expecting one. This just happens to work when using the ES client in promise mode, but of course that could break with any future release. It doesn't work with callbacks unless you're ok with your callback's result parameter sometimes being a promise. It probably also breaks this library's ability to detect error responses, but I haven't checked.
3. With a 300+ MB response (tens of thousands of nested objects) it got past the HTTP response collection phase, but then Node ran out of V8 heap anyway during deserialization.
4. It's slow since Oboe is parsing a ton of data with a JS-based parser.

@spalger's suggestion to paginate or bypass the library completely and stream it through Oboe is  a better one if you really need to do something with a giant response, since you can actually stream the objects through whatever processing needs to be done and maybe not have to keep them all in memory.

All that said, if you do still want to try it, the code is below. I offer no support for this and release it  under the Apache 2.0 license, same as this package.

```
var _ = require('lodash');
var zlib = require('zlib');
var oboe = require('oboe');
var elasticsearch = require('elasticsearch');
var Readable = require('stream').Readable;

// The actual value is more like 256MB, but Node doesn't expose it anywhere.
const MAX_STRING_LENGTH = 128 * 1024 * 1024;

var EsJsonSerializer = elasticsearch.Transport.serializers.json;
var EsConnector = elasticsearch.ConnectionPool.connectionClasses.http;

function bufferStream(buf) {
  const readable = new Readable();
  let startIndex = 0;

  readable._read = function(size) {
    let keepGoing = true;
    while(keepGoing && startIndex < buf.length) {
      let remaining = buf.length - startIndex;
      let sliceSize = Math.min(remaining, MAX_STRING_LENGTH);
      keepGoing = this.push(buf.slice(startIndex, startIndex + sliceSize));
      startIndex += sliceSize;
    }

    if(startIndex >= buf.length) {
      this.push(null);
    }

  };

  return readable;
}

function streamJsonResponse(data) {
  return new Promise((resolve, reject) => {
    oboe(bufferStream(data))
      .on('done', resolve)
      .on('error', reject);
  });
}


class CustomSerializer extends EsJsonSerializer {
  deserialize(str) {
    if(typeof str === 'string') {
      try {
        return JSON.parse(str);
      } catch(e) {}
    } else if(_.isBuffer(str)) {
      if(str.length < MAX_STRING_LENGTH) {
        try {
          return JSON.parse(str);
        } catch(e) {}
      } else {
        return streamJsonResponse(str);
      }
    }

    return null;
  }
}

class CustomConnection extends EsConnector {
  // This is a modified version of the code from Elasticsearch.js, but uses a Buffer instead of a string.
  request(params, cb) {
    var incoming;
    var timeoutId;
    var request;
    var status = 0;
    var headers = {};
    var log = this.log;
    var response;
    var responseLength = 0;

    var reqParams = this.makeReqParams(params);

    // general clean-up procedure to run after the request
    // completes, has an error, or is aborted.
    var cleanUp = _.bind(function(err) {
      clearTimeout(timeoutId);

      request && request.removeAllListeners();
      incoming && incoming.removeAllListeners();

      if((err instanceof Error) === false) {
        err = void 0;
      }

      response = Buffer.concat(response, responseLength);

      log.trace(params.method, reqParams, params.body, response, status);
      if(err) {
        cb(err);
      } else {
        cb(err, response, status, headers);
      }
    }, this);

    request = this.hand.request(reqParams, function(_incoming) {
      incoming = _incoming;
      status = incoming.statusCode;
      headers = incoming.headers;
      response = [];

      var encoding = (headers['content-encoding'] || '').toLowerCase();
      if(encoding === 'gzip' || encoding === 'deflate') {
        incoming = incoming.pipe(zlib.createUnzip());
      }

      incoming.on('data', function(d) {
        response.push(d);
        responseLength += d.length;
      });

      incoming.on('error', cleanUp);
      incoming.on('end', cleanUp);
    });

    request.on('error', cleanUp);

    request.setNoDelay(true);
    request.setSocketKeepAlive(true);

    if(params.body) {
      request.setHeader('Content-Length', Buffer.byteLength(params.body, 'utf8'));
      request.end(params.body);
    } else {
      request.setHeader('Content-Length', 0);
      request.end();
    }

    return function() {
      request.abort();
    };
  };
}

var client = new elasticsearch.Client({
  serializer: CustomSerializer,
  connectionClass: CustomConnection,
});
```
