### ISSUE TITLE
unknown setting [index.similarity]

### ISSUE THREAD

**Issue by jloveric** [elastic/elasticsearch-js#461]
I recently upgraded to elasticsearch 5.0 and am trying to get things working on a code that worked fine with elasticsearch 2.x, I'm trying to track down the problem...  The elasticsearch.js code where the error is thrown looks like this

```
client.indices.create({
  index: indexName,
  body: {
    settings: { 
      number_of_shards: 1,
      similarity :  "norm_bm25"
    } 
  },
  ... error stuff
```

Also, I'm trying to set the default index settings using

```
curl -XPUT 'http://localhost:9200/_template/template1' -d '{
  "template" : "*",  
  "settings.number_of_replicas" : "1",
  "settings.number_of_shards" : "1",
  "settings.similarity.default.type" : "BM25",
  "settings.similarity.default.b" : "0.0",
  "settings.similarity.default.k1" : "1.2",
  "settings.similarity.norm_bm25.type" : "BM25",
  "settings.similarity.norm_bm25.b" : "0.75",
  "settings.similarity.norm_bm25.k1" : "1.2"
}'
```

These values were set in the elasticsearch.yml in elasticsearch 2.x (but you can no longer do that in elasticsearch 5.0)

The error I receive is 

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "unknown setting [index.similarity] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "unknown setting [index.similarity] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
  },
  "status": 400
}
```

Any ideas as to why this is happening?  I don't seem to be able to find the documentation about how to set similarity in an index template, or how to do it in indices.create...

Thanks for any help.

**Comment by Mo-k-tec** [comment]
Any news? I have a similar issue within PHP

**Comment by PaulSodimu** [comment]
Same issue. Check this out. https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_settings_changes.html#_node_attribute_settings

**Comment by Mo-k-tec** [comment]
Could u maybe explain, kinda new to it.
I just created a cluster and want to add a index and i get this error.

Thanks for fast replies
Mo

**Comment by PaulSodimu** [comment]
As part of my code, I was setting a custom setting on the index using elasticsearch 2.x. I then upgraded to elasticsearch 5.x then started getting the same message the original poster was getting. The [breaking changes] (https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_settings_changes.html#breaking_50_settings_changes) state 
> ...only selected settings like for instance index.codec can be set on the node level.

Also @jloveric the similarity setting has been renamed to classic. [See here] (https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_settings_changes.html#_similarity_settings

**Comment by mahesh1104** [comment]
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "unknown setting [index.performanceendpointslatency.endpoints_data.uri.fielddata] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "unknown setting [index.performanceendpointslatency.endpoints_data.uri.fielddata] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
  },
  "status": 400
}

**Comment by mahesh1104** [comment]
I have used this in the dev tools , kibana.

PUT performanceendpointslatency
{
  "performanceendpointslatency": {
    "endpoints_data.uri": { 
      "type":     "text",
      "fielddata": true
    }
  }
}
I am getting this error.
{
"error": {
"root_cause": [
{
"type": "illegal_argument_exception",
"reason": "unknown setting [index.performanceendpointslatency.endpoints_data.uri.fielddata] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
}
],
"type": "illegal_argument_exception",
"reason": "unknown setting [index.performanceendpointslatency.endpoints_data.uri.fielddata] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
},
"status": 400
}

can you explain me, how to solve this issue.

**Comment by lgmaxim31** [comment]
same problem 
![image](https://user-images.githubusercontent.com/35067717/35343113-124a18b2-012a-11e8-9f06-f5682a6f1425.png)

**Comment by RymMichaut** [comment]
Same problem here too :(
Could anyone help please?
```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"unknown setting [index.data] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"}],"type":"illegal_argument_exception","reason":"unknown setting [index.data] please check that any required plugins are installed, or check the breaking ch
```

![error_es](https://user-images.githubusercontent.com/31435778/35518355-9c4d8b6c-0511-11e8-984d-ea0d6f4f0f31.png)

**Comment by lgmaxim31** [comment]
I wish help you, but i dont remember when i had this error... i can show your my PHP code if you need

**Comment by abhi-infrrd** [comment]
Did anybody solve this issue? Apparently creating->deleting->creating the same index throws this error.

**Comment by nomi-ramzan** [comment]
You need to set it inside body property. like

```
client.indices.create({
    index: 'test_ind',
    body: {
      'index.settings.number_of_shards': 5,
      'index.settings.number_of_replicas': 10
    }
})
```
Of in object form 

```
client.indices.create({
    index: 'test_ind',
    body: {
      index: { settings: { number_of_shards: 5, number_of_replicas': 10 } }
    }
})
```

**Comment by nishant260190** [comment]
I am also facing the same issue. If I am providing _type & 
-id in url like http://localhost:9200/product/electronics/8 than it is working and if I will not provide it than it is giving the same error.

**Comment by skmc1976** [comment]
I am also faceing that issue,I paste [curl -X PUT "localhost:9200/customer?pretty"] in my terminal and is ok
