### ISSUE TITLE
getting "mapper_parsing_exception

### ISSUE THREAD

**Issue by sundarapandian18** [elastic/elasticsearch-js#465]
Hi ,

i'm getting the below error

`"mapper_parsing_exception :"analyzer [autocomplete_analyzer] not found for field [name]"}],"type":"mapper_
parsing_exception","reason":"analyzer [autocomplete_analyzer] not found for fiel
d [name]"},"status":400}',`

```
var mappings = {
    type: "business_locations",
    body: {
        properties: {
          business_id: { type: "string" },
          name: {
                type: "string",
                index: "analyzed",
                analyzer: "autocomplete_analyzer"
          }
        }
    }
  }
```

```
var analyzerSettings= {
    "index" : {
      "analysis" : {
        "analyzer" : {
          "autocomplete_analyzer" : {
            "type" : "custom",
            "tokenizer" : "lowercase",
            "filter"    : ["asciifolding", "title_ngram"]
          }
        },
        "filter" : {
          "title_ngram" : {
            "type" : "nGram",
            "min_gram" : 3,
            "max_gram" : 5
          }
        }
      }
    }
  }

```

  function initIndex() {

      return elasticClient.indices.create({
          index: indexName,
          body:{"settings": analyzerSettings}

      });
  }`

when i do put Mapping 
 ` elasticClient.indices.putMapping(mappings);`

i get this error.. 

How to get rid of this `"mapper_parsing_exception :"analyzer [autocomplete_analyzer] not found for field [name]"}],"type":"mapper_
parsing_exception","reason":"analyzer [autocomplete_analyzer] not found for field
d [name]"},"status":400}',`

Thanks in advance for your help
Sundar

**Comment by spalger** [comment]
Hey @sundarapandian18, sorry for letting this sit for so long. This issue tracker is for bugs and feature requests for the elasticsearch.js client. You will find much better help with elasticsearch usage at our forums: https://discuss.elastic.co/c/elasticsearch
