### ISSUE TITLE
Potential issue with query syntax differences between curl and JS client

### ISSUE THREAD

**Issue by fyaconiello** [elastic/elasticsearch-js#466]
When I send the following json to my elasticsearch using curl

GET request to: http://localhost:9200/analytics/document/_search
```
{
    from: 0,
    size: 10000,
    query: {
        filtered: {
            query: {
                term: {
                    twilio_number: "1888888888"
                }
            },
            filter: {
                range: {
                    datetime: {
                        lt: "2016-10",
                        gte: "2016-09",
                        format: "yyyy-MM"
                    }
               }
           }
        }
    }
}
```

I get the proper response

when I send the same json through the search api exposed via the elasticsearch node module the range filter appears to be ignored.

at a basic level I'm sending the above json like this:
```
        elastic.search(params).then(function(success) {
            res.send(JSON.stringify(success.hits.hits));
        }, function(error) {
            res.status(500).send(JSON.stringify(error));
        });
```

but with additional 

```
            "index": "analytics",
            "type": "document",
```

Is this an issue with how I am formatting my query, the js implementation, or something else?

**Comment by spalger** [comment]
Are you passing what should be included in the body of the request under the `body:` key of the params?

Checkout https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-conventions.html, but I suspect you need to change your params to look like this:

```js
elastic.search({
  index: 'analytics',
  type: 'document',
  body: {
    from: 0,
    size: 10000,
    query: { ... }
  }
})
```

**Comment by fyaconiello** [comment]
That was it, I missed something pretty basic. Thanks for the help!
