### ISSUE TITLE
_update endpoint incorrectly throws illegal_argument_exception error

### ISSUE THREAD

**Issue by jtveritone** [elastic/elasticsearch-js#468]
_update endpoint appears to incorrectly wrap parameters inside a "query":{} object.
For example, if I call client.update() with
```
{
  "script": {...}
}
```
I'd get
>illegal_argument_exception ... contains unrecognized parameters: [script] ...
>{"query": {"script": {...}}}

(Note "script" object is wrapped inside a "query" object)

**Comment by spalger** [comment]
Hmm, esjs doesn't touch the body of the request. Can you share the code that is calling the client?
