### ISSUE TITLE
percolate 5.x

### ISSUE THREAD

**Issue by cadebward** [elastic/elasticsearch-js#469]
Im trying to wrap my head around the percolator in 5.x, so forgive me if I'm totally wrong, but has the percolator API been updated in this library to match ES 5.x?  Seems like a few things are missing, like `document_type` and `field`.

If not, I'd love to help, just thought I'd ask before diving in.

**Comment by spalger** [comment]
In 5.x percolation is accomplished with the percolate query via the search api, so you will use `client.search()` along with a body similar to [the examples in the es docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/query-dsl-percolate-query.html).

The `percolate` method available on the client is for the now deprecated [percolator api](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/search-percolate.html)

Sorry for the confusion. I'll add a deprecation warning to the docs and remove the examples.

**Comment by cadebward** [comment]
Ah, that makes sense. Thanks for the clarification!

**Comment by spalger** [comment]
reopening as a reminder to deprecate the percolator docs
