### ISSUE TITLE
ElasticSearch JS Browser Angular NGINX Scoll Issue

### ISSUE THREAD

**Issue by whittssg** [elastic/elasticsearch-js#470]
Hello, I am trying to route all elasticsearch _search queries through NGINX to my local sever. I currently have my browser app querying the ip of elastic search directly which works fine but id like to route it through NGINX so that i can enable HTTPS.

For testing i have this in my elasticsearch 5.0 config:
network.host: [127.0.0.1, 10.11.12.13]
http.cors.enabled: true
http.cors.allow-origin: "*"

And in my NGINX i have this:

 location ~ ^/.*/_search$ {
 proxy_pass http://127.0.0.1:9200;
 }

If i do a search under my scroll limit (1000) then the query will work fine but as soon as the query needs to scroll i get an error:

Request URL:https://mysite.mydomain.com/_search/scroll?scroll=30s
Request Method:POST
Status Code:400 Bad Request
Remote Address:serverIP:443

Is there a special NGINX setting that i need to do to allow scroll when routing through NGINX?

Thanks,

**Comment by cblanc** [comment]
As far as I can tell, the regex provided to the location directive does not match the scroll url

`_search$` requires $uri to end within `_search`, however scroll requests end with `_search/scroll`

Might want to consider relaxing the regex or adding an optional `(/scroll)?`

**Comment by whittssg** [comment]
@cblanc That was it, face palm to me - thanks for your help.
