### ISSUE TITLE
startting elasticsearch

### ISSUE THREAD

**Issue by NiLeShpatil777** [elastic/elasticsearch-js#474]
Hello,
         I installed elastic search by command "sudo npm install elasticsearch --save".and created client of elasticsearch and was checking cluster health but it is refusing to connect to 9200port.But when i start elasticsearch 5.0.1 which i have downloaded from elasticsearch's official site on port 9200 then am getting cluster health.Is it really needed to do so? .I was assuming that ,the following connect.js starts port9200 automatically.Is it needed to use npm installed elasticsearch & elasticsearch 5.0.1 at a time?
is there any way to  auto integrate these 2.
-----------------------------connect.js    [START]----------------------------------------------
var elasticsearch = require('elasticsearch');

var elasticClient = new elasticsearch.Client({  
    host: 'localhost:9200',
    log: 'info'
});
module.exports = elasticClient;
------------------------------------------------------------------connect.js [END]------------------------

------------------------------------------------info.js  [START]----------------------------------

var elasticClient = require('./connection');

elasticClient.cluster.health({},function(err,resp,status) {
  console.log("-- Client Health --",resp);
});
-------------------------------------------------------info.js  [END]---------------------------------------------

im working on ubuntu 16.04
npm version 3.10.8
node version 3.10.8
elasticsearch version 12.1.0

**Comment by spalger** [comment]
Yep, the elasticsearch module on npm is just the client for elasticsearch. You will need to run the elasticsearch server separately.
