### ISSUE TITLE
Try out agentkeepalive module

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch-js#476]
`13.0.0-beta2` is the new build including the agentkeepalive module. To use this version install with `npm install --save elasticsearch@beta`

---

I just published version `12.1.0-agentkeepalive` of elasticsearch-js that includes the keep alive implementation that [many people](https://github.com/elastic/elasticsearch-js/issues/196#issuecomment-142384403) have identified works well for them. Please give it a shot and report any issues/successes here.

Until I/someone produce an automated test proving that it works and that the current implementation doesn't I'm not comfortable releasing it as the default.

---
Even if you are a few major-version numbers away, you shouldn't have any issue upgrading to 12.1 as long as you as setting your [`apiVersion`](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html#config-api-version)

**Comment by Toktik** [comment]
After upgrade from `12.1.3` to `13.0.0-beta1` my connections are never revived.

**Comment by spalger** [comment]
@Toktik can you please open an issue with some more details?

**Comment by mbifulco** [comment]
@spalger I'm a bit confused as to what I should be doing to test this.  Maybe you can answer some questions:

- what version should my package.json file be pointing to? 
  - I see `13.0.0.beta-2` listed as the most recent release [here](https://github.com/elastic/elasticsearch-js/releases).  
  - GitHub has `12.1.1` listed as the "Latest Release"
  - [npmjs.çom](https://www.npmjs.com/package/elasticsearch) points to `12.1.3` as the Latest Release.  
  - In this issue, you suggest `12.1.0-agentkeepalive`. 

- I'm using ElasticSearch hosted on Elastic's cloud - an instance I created about a week ago.  Can you confirm that my configuration is correct?
```es6
const elasticSearchConfig = {
  hosts: [
    'https://[USER]:[PASSWORD].us-east-1.aws.found.io:[PORT]',
  ],
  log: 'warning',
  index: '[INDEXNAME]',
  apiVersion: '5.0',
}

onst esclient = new elasticsearch.Client(elasticSearchConfig);
```

I can't seem to find a combination of the above that returns a query from an index as a part of a Node project.  I get `Unable to revive connection:` and `No living connections` no matter what package I use.

**Comment by spalger** [comment]
@mbifulco updated the description to point to 13.0.0-beta2.

Your host looks incorrect, the user/password bit should be followed by a `@` and then be followed by the host for your es cluster on cloud. That hostname should have a long alpha-numeric subdomain at the front of it.

**Comment by lbdremy** [comment]
@spalger the minSockets option is not used by keepaliveagent https://github.com/node-modules/agentkeepalive#new-agentoptions, this mean that no minimum of socket are not kept around anymore, this could have an important impact.

**Comment by spalger** [comment]
@lbdremy I definitely like the idea that it will close all sockets when there isn't any activity for `freeSocketKeepAliveTimeout`. What would be the benefit of keeping sockets around if nothing is using them?

**Comment by lbdremy** [comment]
I suppose you don't see much difference if the number of requests is stable and continuous (coz you always have freeSocket hanging there to serve you) but in a case you have a burst every 5 minutes for example, if you have no connection waiting to be used at any time, you have to create one or many connections to serve the requests which can cost some extra time particularly if it's over https. From my experience it can save 20/30 ms per request if you don't have to open a new connection. Well, it is all about the situation and the right configuration of the keepaliveagent to get the most of the keep alive feature.

**Comment by spalger** [comment]
> in a case you have a burst every 5 minutes 

I think it would make sense for a client there to set their `freeSocketKeepAliveTimeout` to something like 10 minutes then

**Comment by lbdremy** [comment]
Yes sure, you have to understand how to configure correctly the keepaliveagent, considering the usage.
