### ISSUE TITLE
cat.indicies().then assumes response is json

### ISSUE THREAD

**Issue by jitcoder** [elastic/elasticsearch-js#477]
Steps to reproduce:
```
'use strict';

const elasticsearch = require('elasticsearch');

const client = new elasticsearch.Client({
  host: 'localhost:9200',
  log: 'trace'
});

client.cat.indices().then((data) => {
  
})
```

The results returned by _cat/indices is not a JSON response from elasticsearch server, however the client assumes it is and attempts to JSON.parse which throws exception

**Comment by jitcoder** [comment]
recommend checking content-type on responses

**Comment by jitcoder** [comment]
Sorry, I assumed it was the client code, the exception is actually being thrown by the lib/logger.js:174 module,

```
LoggerAbstract.prototype._prettyJson = function (body) {
  try {
    if (typeof body === 'string') {
      body = JSON.parse(body);
    }
    return JSON.stringify(body, null, '  ').replace(/'/g, '\\u0027');
  } catch (e) {
    return typeof body === 'string' ? body : '';
  }
};

module.exports = LoggerAbstract;
```

**Comment by spalger** [comment]
Huh, can you show the error that you are getting? The `JSON.parse()` in the code you linked is wrapped in a `try {} catch (e) {}` for the exact purpose of handling the scenario that the body isn't JSON and should cause the plain body to be returned.

**Comment by jitcoder** [comment]
nvm I'm smoking crack. I had a "break on all exceptions" enabled in my editor.
Sorry about that!
