### ISSUE TITLE
ping() not working with 5.0

### ISSUE THREAD

**Issue by celesteking** [elastic/elasticsearch-js#478]
`es.ping()` sends a HEAD request, which is not supported on ES 5.0, it seems. There should be a way to check cluster health.

```
curl -D- -XHEAD  'http://127.0.0.1:9200/?hello=elasticsearch'
HTTP/1.1 400 Bad Request
content-type: text/plain; charset=UTF-8
content-length: 0
```

Thanks.

**Comment by spalger** [comment]
`HEAD` is still supported, but unexpected query string parameters cause 400 responses now. If you drop the `?hello` parameter it comes back with a 200

```
$ curl -I -XHEAD 'http://127.0.0.1:9200/'
HTTP/1.1 200 OK
Date: Fri, 09 Dec 2016 23:26:44 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 340
Connection: keep-alive
```

**Comment by celesteking** [comment]
Documentation should be updated accordingly, then.

**Comment by spalger** [comment]
Done, thanks
