### ISSUE TITLE
TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by aabanaag** [elastic/elasticsearch-js#480]
```
const query = new BodyBuilder()
      .query('match', 'user_id', id)
      .query('match', 'type', 'deposit')
      .aggregation('avg', 'amount')
      .build('v2');

const Search = Meteor.wrapAsync(ES.search);

let result = Search({
   index: 'transactions',
   type: 'lla',
   body: query
});

console.log(result);
```

But I got an error of `TypeError: Cannot read property 'request' of undefined`

**Comment by spalger** [comment]
The search method requires the `this` context it would normally have if is was still being called as a property of `ES`. Change the line defining `Search` to read like below and it should work

```js
// tells meteor to use the ES object as the context for the function
const Search = Meteor.wrapAsync(ES.search, ES);
```

**Comment by aabanaag** [comment]
oh. nice! I was reading about the context. I thought I needed to add `this` Thank you for the speedy response.
