### ISSUE TITLE
Silent (no logging at all)

### ISSUE THREAD

**Issue by Mayhem93** [elastic/elasticsearch-js#481]
Hello,

I have a simple question: is it possible to completely disable any logging (or at least cancel the retrying thingy).

I'm making some unit tests on a Database adapter I've built and I have a test in which I must connect to a unavailable host (either timed out, or conn refused). The thing is, I don't know how to make him shut up or at least cancel the auto retry.

**Comment by spalger** [comment]
Yep, passing `log: false` to the client constructor should do the trick.
