### ISSUE TITLE
Elastic Search HTTP_PROXY - Connection behind a Proxy 

### ISSUE THREAD

**Issue by NickLiffen** [elastic/elasticsearch-js#483]
Hello,

Is their any native or suggestions on how to connect to a hosted Bonsai Instance behind a proxy? My current implementation looks like this: 

```
const elasticsearch = require('elasticsearch');
const proxy = require('proxy-agent');
const bonsaiUrl = process.env.BONSAI_URL;

// Creating the bonsai client
const client = new elasticsearch.Client({
  host: bonsaiUrl,
  log: 'trace',
  createNodeAgent: () => { return proxy(process.env.HTTP_PROXY); },
});

```
And then in my .env I have my proxy under HTTP_PROXY

However when I ping the bonsai instance it still doesn't connect? Any inbuilt proxy?

**Comment by spalger** [comment]
Hey @NickLiffen, sorry for letting this sit for months. elasticsearch.js doesn't support HTTP_PROXY it self, but support for `createNodeAgent` was added in 10.1 and will use whatever agent you provide. Not able to help with issues using `proxy-agent` though.
