### ISSUE TITLE
I'm not willing to sign the CLA document for a 2 character documentation change.

### ISSUE THREAD

**Issue by TonyApuzzo** [elastic/elasticsearch-js#489]
JavaScript API documentation for clearScroll mentions "scrollId" but it should be "scroll_id".  

PR If not for the CLA BS. -- https://github.com/elastic/elasticsearch-js/pull/488

**Comment by spalger** [comment]
Thanks, but the api parameters are all camelCased and transformed into snake_case before sending to es. It's a decision I somewhat regret but will live with for some time. Thankfully, snake_case versions work too.

**Comment by TonyApuzzo** [comment]
The thing is scrollId does not work -- if it is supposed to work then that is a different error.
