### ISSUE TITLE
Library Size

### ISSUE THREAD

**Issue by aequasi** [elastic/elasticsearch-js#490]
I've been messing around with shrinking the size of my webapp's bundle size, and I've noticed that the elasticsearch library is the largest library in my project by at least 3 times the next project (react-dom). Is there any way to mitigate the size of this? Seems like it might be loading the API for each version in the bundle, which seems kinda silly.... But i could be wrong.

**Comment by spalger** [comment]
Yeah, it really is silly how big this library is.

I've experimented with different strategies, but if you're using webpack then you could build elasticsearch-js from npm and tell webpack to exclude the api versions you're not using. You could also forgo the api files entirely and use a custom api that has either just the methods you use or no api at all and simply rely on `client.transport.request({ path, method, etc.. })`, but at that point you might as well use any standard ajax library.

Sorry I don't have a better answer, but I'm not convinced that reducing the size of esjs is worth the effort it would take (or the impact it would have in terms of breaking changes). The size of the library is more reasonable when gzipped (in comparison to an image for instance) but in most cases elasticsearch-js shouldn't be used in webpages where an extra 100k is that big of a deal.

**Comment by draeron** [comment]
make a fork and delete all API versions you don't need then include your fork. takes 5 min and saves a lot of space. You can always update your fork with the latest fix if you need to.

**Comment by aequasi** [comment]
Just forwent the whole lib and used fetch to make my own client.

**Comment by MadDeveloper** [comment]
@draeron can you explain how you clean properly unused apis? 
I did it but when I try to build my angular 4 project for production with `ng build --prod`, an error occurs in my vendor bundle file (but I don't have any problems when I juste use `ng serve`)

`ERROR in vendor.c2a5f232c289cfd8420c.bundle.js from UglifyJs
Unexpected token: name (index) [vendor.c2a5f232c289cfd8420c.bundle.js:1189,6]`

**Comment by draeron** [comment]
@MadDeveloper 

This what i did to only leave ES 1.5 in the client lib.

https://github.com/draeron/elasticsearch-js/commit/5befd6121bd712dce8a1aa64cd341ecd16ff8033

**Comment by MadDeveloper** [comment]
Thank's, but that is exactly what i did.... [https://github.com/MadDeveloper/elasticsearch-js/commits/master](MadDeveloper/elasticsearch-js/commits/master), and i still have the error above when i build for prod.

**Comment by mfellner** [comment]
Here's another idea: use webpack aliases to replace unnecessary modules with a dummy file.

```js
{
  resolve: {
    alias: {
      "./0_90": path.resolve(__dirname, "empty.js"),
      "./1_7": path.resolve(__dirname, "empty.js"),
      "./2_4": path.resolve(__dirname, "empty.js"),
      "./5_0": path.resolve(__dirname, "empty.js"),
      "./5_1": path.resolve(__dirname, "empty.js"),
      "./5_2": path.resolve(__dirname, "empty.js"),
      "./5_3": path.resolve(__dirname, "empty.js"),
      "./5_4": path.resolve(__dirname, "empty.js"),
      "./5_5": path.resolve(__dirname, "empty.js"),
      "./5_6": path.resolve(__dirname, "empty.js")
    }
  }
}
```
