### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by fred2H0TSavoie** [elastic/elasticsearch-js#491]
I'm looking for a way to login/logout users. 
Login is ok, but how to make a clean logout ?
tk.

**Comment by spalger** [comment]
Not sure what you're looking for. The elasticsearch-js client doesn't offer any login/logout functionality

**Comment by fred2H0TSavoie** [comment]
your right is not a login/logout but we can authenticate using the api. 

module.service('client', function (esFactory) {
var config = {
    host: 'joe@pass:localhost:9200',
    // ...
  }
  return esFactory(config);
});

So if we authenticate for a user and want to switch user then the api send : 

'Do not reuse objects to configure the elasticsearch Client class'

so what is the best way to manage this ?

**Comment by spalger** [comment]
If you want to change the username and password for the request you will either need to close the client and create a new one:

```js
let client
$scope.$watch('user', (user) => {
  if (client) {
    client.close();
    client = null;
  }  

  if (user) {
    client = esFactory({
      host: {
        host: 'localhost',
        port: 9200,
        auth: `${user.username}:${user.password}`
      }
    });
  }
});
```

or you can leave the client unauthenticated and send the credentials in the header of each request:

```js
const client = esFactory();

client.search({
  body: {
    query: { match_all: {} },
  },
  headers: {
    Authorization: `Basic ${atob(`${user.username}:${user.password}`)}`
  }
})
```
