### ISSUE TITLE
Error "Unable to parse/serialize body" when filterPath used and aggregation keys contain quote characters

### ISSUE THREAD

**Issue by ferranmunoz** [elastic/elasticsearch-js#492]
When I perform a terms aggregation calling the method `search` of the client with the `filterPath` parameter I get the error "Unable to parse/serialize body" if the keys of the aggregation contain the quote character (").

Example of query:
```
{
  "size": 0,
  "aggs": {
    "chapter": {
      "terms": {
        "field": "name"
      }
    }
  }
}
```

The `filterPath` specified is `aggregations.chapter.buckets.key`.
Example of document:
```
{
  "name": "This is a "quoted" text."
}
```

I don't get any error if I do not add `filterPath` to the parameters used to call `search`.
I think that it is an issue with elasticsearch.js because I have tested the same using curl and I don't  get any error.

**Comment by spalger** [comment]
The JSON parser that elasticsearch uses is pretty loose and allows invalid JSON like this, but JavaScript does not. If you index your documents and escape the quotes with a `\` this should work fine:

```
{
  "name": "This is a \"quoted\" text."
}
```

**Comment by ferranmunoz** [comment]
Thanks  @spalger. I thought that it was stored escaped internally. I will escape the quotes.
