### ISSUE TITLE
client.indices.putAlias isn't documented anywhere

### ISSUE THREAD

**Issue by shawninder** [elastic/elasticsearch-js#493]
I was trying to add an alias for an index using this module, but I couldn't find any documentation about how to do this anywhere. I ended up finding `client.indices.putAlias` by looking through the source code, but I would rather find it in the documentation to make sure I can expect this function to continue working in the future, and to know what my options are when using it...

Actually, what I'm really trying to do is remove an alias and add another one in an "atomic" fashion (following the advice here: https://www.elastic.co/blog/changing-mapping-with-zero-downtime), but although I found `putAlias` and `deleteAlias` in the source code, that doesn't help me with doing both in a single request using this module.

Am I missing something obvious?

**Comment by spalger** [comment]
This is documented now, the docs might not have been updated at this time.

**Comment by mdjaman** [comment]
@spalger Is it return Promise?

**Comment by spalger** [comment]
@mdjaman yes, every method on the client returns a promise unless a callback is passed as the second argument.
