### ISSUE TITLE
Client doesn't sniff cluster ES5

### ISSUE THREAD

**Issue by serega-k** [elastic/elasticsearch-js#496]
Hi,

`Client` doesn't work on ES5.* if it was created with using "sniffing" properties.
The reason is missing of “http_address” field in the response `host:port/_nodes/_all/clear`

Could you please fix it for `JS` the same way it is done in `python` or `go`

**Comment by kwizzn** [comment]
This is an issue and it was fixed on Feb 9 in https://github.com/elastic/elasticsearch-js/commit/630942595175d3a8bb9ec865f8db1d80a1bb3206 for v13.0.0. Really looking forward to the release...

**Comment by kwizzn** [comment]
I believe we could close this.

**Comment by spalger** [comment]
Yep, thanks @kwizzn

**Comment by serega-k** [comment]
Thanks a lot 👍
