### ISSUE TITLE
What node version do you use with elasticsearch-js?

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch-js#499]
Master is using the agentkeepalive module that members of the community have had great success with for some time, but the library just updated to 3.0 and dropped support for Node.js version less than 4.0. I too would like to make that jump in elasticsearch-js, but I wonder how many people are using older versions. 👍 the version you use?

**Comment by spalger** [comment]
0.10

**Comment by spalger** [comment]
0.12

**Comment by spalger** [comment]
4.x

**Comment by spalger** [comment]
6.x

**Comment by spalger** [comment]
7.x

**Comment by mindnuts** [comment]
6.9.5

works like a charm

**Comment by gpestana** [comment]
v6.4.0 and no problem so far

**Comment by spalger** [comment]
Thanks for the feedback everyone, plan for now is to make 14.0 require 6.0
