### ISSUE TITLE
ping timeout but es is live and well

### ISSUE THREAD

**Issue by robomotic** [elastic/elasticsearch-js#500]
Hello guys,
I am having troubles using this library to query my ES instance (version 5.2 single node cluster with X-Pack instaleld), running Node 6.9.3 and:

> 
> `-- elasticsearch@12.1.3
>   +-- chalk@1.1.3
>   | +-- ansi-styles@2.2.1
>   | +-- escape-string-regexp@1.0.5
>   | +-- has-ansi@2.0.0
>   | | `-- ansi-regex@2.1.1
>   | +-- strip-ansi@3.0.1
>   | `-- supports-color@2.0.0
>   +-- forever-agent@0.6.1
>   +-- lodash@4.17.4
>   `-- promise@7.1.1
>     `-- asap@2.0.5
> 

Test code below:
```
var elasticsearch = require('elasticsearch');
var client = new elasticsearch.Client({
  host: 'ec2-xx-xx-xx-xx.compute-1.amazonaws.com',
  httpAuth: 'elastic:xxxxxxxx',
  protocol: 'http',
  port: 9200,
  log: 'trace',
  apiVersion: '5.0'
});

client.ping({
  // ping usually has a 3000ms timeout
  requestTimeout: 3000
}, function (error) {
  if (error) {
    console.trace('elasticsearch cluster is down!');
  } else {
    console.log('All is well');
  }
});
```

I am currently using python django elasticsearch to connect to that instance in the same manner so I would like to understand why the ES node library is not able to do so.

The output is a bit strange:

> Trace: elasticsearch cluster is down!
>     at C:\Users\ddiprod\Documents\RawEdgar\server.js:16:13
>     at respond (C:\Users\ddiprod\Documents\RawEdgar\node_modules\elasticsearch\src\lib\transport.js:308:9)
>     at C:\Users\ddiprod\Documents\RawEdgar\node_modules\elasticsearch\src\lib\transport.js:336:7
>     at Timeout.<anonymous> (C:\Users\ddiprod\Documents\RawEdgar\node_modules\elasticsearch\src\lib\transport.js:365:7)
>     at ontimeout (timers.js:365:14)
>     at tryOnTimeout (timers.js:237:5)
>     at Timer.listOnTimeout (timers.js:207:5)
> Elasticsearch TRACE: 2017-02-13T12:39:55Z
>   -> HEAD http://ec2-xxxxxxxx.compute-1.amazonaws.com:80/
> 
>   <- 0

I was expecting the HEAD to be connecting to port 9200 not 80?

Any help is welcome!

**Comment by robomotic** [comment]
Ops it seems to be that the port parameter is totally ignored.... in fact if I do:

  host: 'ec2-xxxxxx.compute-1.amazonaws.com:9200',

is working .

**Comment by spalger** [comment]
@robomotic sorry I let this sit for so long. if you want to specify the host and port separately they should be wrapped in an object under the top level `host:` key, like so:

```js
var client = new elasticsearch.Client({
  host: {
    host: 'ec2-xx-xx-xx-xx.compute-1.amazonaws.com',
    protocol: 'http',
    port: 9200,
    auth: 'elastic:xxxxxxxx',
  },
  log: 'trace',
  apiVersion: '5.0'
});
```

See https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/host-reference.html for more details
