### ISSUE TITLE
_count request failing with 404

### ISSUE THREAD

**Issue by danwhitacre** [elastic/elasticsearch-js#502]
I am currently in the middle of developing a plugin for kibana 5.1. Without going into all the details, I am using the ES client to make sure an index exists (ie. es.indices.exists(params)) and that works just fine. However, shortly thereafter, I am trying to check the number of documents on said index (ie. es.count(params)) and am getting a 404 returned on the request. It seems the request being made (no matter the params passes) is a POST request. When testing just using Postman and using a GET request, the request returns just fine. It seems in the docs it should be a GET rather than a POST. https://www.elastic.co/guide/en/elasticsearch/reference/5.x/search-count.html

**Comment by danwhitacre** [comment]
Ok so if I just install the current version of the module directly and run count() on the client it seems to work just fine.. even with the POST. Maybe this is a kibana issue?

**Comment by spalger** [comment]
Perhaps, but it could be something else. I would recommend trying to do the count without the  `.exists()` check, and then just retry the count when you get a 404 (or whatever you are doing if the index doesn't exist).

**Comment by danwhitacre** [comment]
The _count call is always 404ing through the kibana plugin though. Some on the irc channel mentioned it could be related to the proxy in kibana? It is a client side plugin.

**Comment by spalger** [comment]
Ah, yes, that is probably the issue. The elasticsearch proxy provided to the front-end only supports a very limited subset of the API. I suggest creating a rest endpoint and doing your communication with elasticsearch there

**Comment by danwhitacre** [comment]
Ok yea. That seems to be the route to go down. Thanks!
