### ISSUE TITLE
CONTRIBUTING.md could use additional info on dev. environment requirements.

### ISSUE THREAD

**Issue by WesTyler** [elastic/elasticsearch-js#503]
I am trying to add some tests around the serialization functions (may PR if I can replicate behavior).

I followed the guidelines in [CONTRIBUTING.md](https://github.com/elastic/elasticsearch-js/blob/master/CONTRIBUTING.md#3-when-you-are-ready-run-the-test-suite) and have so far run into the following roadblocks that were not readily apparent:
  1. Must be in Node version >=5.x OR be using Node v4.x with the `--harmony` flag
  ```bash
  wtyler:elasticsearch-js (master *)$ node --version
  v4.5.0
  wtyler:elasticsearch-js (master *)$ grunt test
  Loading "Gruntfile.js" tasks...ERROR
  >> SyntaxError: Unexpected token ...
  Warning: Task "test" not found. Use --force to continue.

  Aborted due to warnings.
  ```

2. Must have JDK installed to utilize `java` command-line tool. (Semi-related side note, the dialogue box that pops up in this case does not correctly direct you to the JDK install page...)
```bash
Warning: Command failed: /.../.../elasticsearch-js/esvm/branch-5.2/bin/elasticsearch -h
No Java runtime present, requesting install.
 Use --force to continue.

Aborted due to warnings.
```

Would you be open to a documentation-only PR to amend the CONTRIBUTING.md with the below information?

### 3. When you are ready, run the test suite

1. Install dev dependencies.

  ```sh
  npm install
  ```

2. Ensure that your development environment meets the below minimum requirements.
  - Node version >=5.x, or Node version 4.x with `--harmony` flag.
  - Java Developer Kit. Tests make use of the `java` command-line tool.
  - Global install of Grunt command-line tool:
    ```sh
    npm install -g grunt-cli
    ```

3. Run the tests.

**Comment by spalger** [comment]
Yeah, I'd totally be interested in a PR. I'd call out [`nvm`](https://github.com/creationix/nvm), [`avn`](https://github.com/wbyoung/avn) and [`jabba`](https://github.com/shyiko/jabba) and would probably structure it similar to the [kibana contributing doc](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#setting-up-your-development-environment).

**Comment by delvedor** [comment]
Closed in https://github.com/elastic/elasticsearch-js/commit/f260549a4fcd7ce460f2f2688d57666a8d891e61 and https://github.com/elastic/elasticsearch-js/pull/794.
