### ISSUE TITLE
 strict match

### ISSUE THREAD

**Issue by shivshankar3578** [elastic/elasticsearch-js#506]
can anyone tell me how to strict match in elasticsearch-js. here is my search

```
client.search({{
  index: 'hash_tag',
  type: 'hash_tag',
  lenient:false,
  body: {
    query: {
      match: {
        tag_name: 'hash tag 1'
      }
    }
  }
}).then(function (body) {
    console.log("body", JSON.stringify(body));
  }, function (error) {
    console.trace(error.message);
})
```

this query search either **hash, tag ,1** i'm looking for exact whole string match.here is my example index style.
```

{
  "_index": "hash_tag",
  "_type": "hash_tag",
  "_id": "3483",
  "_score": 0.019691018,
  "_source": {
    "id": "3483",
    "labels": [
      "hash_tag"
    ],
    "tag_name": "hash tag 2"
  }
}
```

**Comment by spalger** [comment]
Looks like you need to create a `keyword` type field, but I'm closing this because this issue tracker is for bugs and https://discuss.elastic.co/c/elasticsearch is more appropriate for support/help.
