### ISSUE TITLE
documents Indexed

### ISSUE THREAD

**Issue by Muneem** [elastic/elasticsearch-js#509]
How to know how many documents are indexed?I have used client.count method but it s giving me wrng answer in total field. So i am confused how should i know how many documents are indexed?

**Comment by spalger** [comment]
Please reserve this issue tracker for bugs and feature requests :)

Perhaps this will help: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html

**Comment by spalger** [comment]
Please use https://discuss.elastic.co/c/elasticsearch for questions/support
