### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by avgalon** [elastic/elasticsearch-js#510]
Hi all,
I have an angular 2 application.
The angular2 application is using elasticsearch.js version 12.1.3
I use webpack 2 for bundling.

After i bundle the project i get:
ReferenceError: process is not defined
The only place the parameter process exist is in log.js located in elasticsearch lib fiolder line 212:

"var Logger = _.funcEnum(config, 'type', Log.loggers, process.browser ? 'console' : 'stdio');"

Please advise...

**Comment by sxmon** [comment]
Same issue here. With angular 2 and webpack.

**Comment by spalger** [comment]
Please use the `elasticsearch-browser` when you're trying to load elasticsearch.js along with npm and bundlers like webpack or browserify (related https://github.com/elastic/elasticsearch-js/issues/527)
