### ISSUE TITLE
Validation Failed: 1: scrollId is missing

### ISSUE THREAD

**Issue by craigvantonder** [elastic/elasticsearch-js#512]
Using:
 - v5.1 in Amazon Elastic Search Service
 - Ubuntu 16.04 running Node 7.4
 - elasticsearch 12.1.3 and also tried 13.0.0-beta2

Going by the Javascript API documentation for scroll I have:

    var allPeople = [];

    // Initialise the connection
    var elasticsearch = require('elasticsearch');
    var client = new elasticsearch.Client({
      host: config.eshost,
      log: 'trace'
    });

    // Having to stringify this or get "Failed to derive xcontent"
    var options = JSON.stringify({
      index: 'people',
      type: 'person',
      size: 100,
      scroll: '30s', // keep the search results "scrollable" for 30 seconds
      source: ['parent_id'], // filter the source to only include the parent_id field
      q: 'parent_id:1'
      // body: {
      //   query: {
      //     term: {
      //       parent_id: 1
      //     }
      //   }
      // }
    });

    // first we do a search, and specify a scroll timeout
    client.search(options, function getMoreUntilDone(error, response) {
      // collect the _id value of each document
      response.hits.hits.forEach(function (hit) {
        allPeople.push(hit._id); 
      });

      if (response.hits.total > allPeople.length) {
        console.log("##########");
        console.log(response);
        console.log("##########");
        // ask elasticsearch for the next set of hits from this search
        client.scroll({
          scrollId: response._scroll_id,
          scroll: '30s'
        }, getMoreUntilDone);
      } else {
        console.log('every "test" person', allPeople);
      }
    });

Which produces: 

    ##########
    { took: 1,
      timed_out: false,
      _shards: { total: 3, successful: 3, failed: 0 },
      hits:
       { total: 1995,
         max_score: 1,
         hits:
          [ [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object] ] } }
    ##########

    Elasticsearch DEBUG: 2017-03-01T08:28:35Z
      starting request {
        "method": "POST",
        "path": "/_search/scroll",
        "query": {
          "scroll": "30s"
        }
      }

    Elasticsearch TRACE: 2017-03-01T08:28:36Z
      -> POST https://myawsdomainendpoint:443/_search/scroll?scroll=30s
      
      <- 400
      {
        "error": {
          "root_cause": [
            {
              "type": "action_request_validation_exception",
              "reason": "Validation Failed: 1: scrollId is missing;"
            }
          ],
          "type": "action_request_validation_exception",
          "reason": "Validation Failed: 1: scrollId is missing;"
        },
        "status": 400
      }

I guess the issue here is that it expects the response to contain `_scroll_id` but the `console.log(response)` output does not contain it. 

This being said, when I try to make the request with PostMan:

    POST https://myawsdomainendpoint/people/person/_search?scroll=1m
    {
      "size": 100,
      "query": {
        "term" : {
          "parent_id" : 1
        }
      }
    }

Then I get the `_scroll_id` in the output. 

So, is this a bug in the JS API or have I done something wrong here or is it maybe on the AWS side?

Also noting that I get back 10 results from the JS API even though I defined a size of 100 as is given in PostMan?

**Comment by craigvantonder** [comment]
As it turns out, I was using version 2.3 of Elastic Search (facepalm) Please close this..

**Comment by spalger** [comment]
Glad you got things working!
