### ISSUE TITLE
Extending elasticsearch.Client on an ES6 code

### ISSUE THREAD

**Issue by ThiagoMiranda** [elastic/elasticsearch-js#516]
Hi..

Probably I'm doing something wrong ( or getting the wrong idea on the extends implementation ) but why can't I add methods extending the `elasticsearch.Client` class?

```javascript
class MyClass extends elasticsearch.Client {
    
    constructor(config) {
        super(config);       

       this.testConnection(); //-> gives an this.testConnection is undefined
    }

    testConnection() {
        this.ping({
            requestTimeout: 30000,
        }, (error) => {
            if(error) console.error('Elastic search is out');
            if(!error) {
                console.log('Conected');
            }
        });
    }
}

const client = new MyClass({
    host: 'my_host', 
    log: 'info'
});

MyClass.testConnection(); //also an "undefined" error
```

Ps: The super method is called since I have a "Elastic info connected" message

**Comment by Mattchewone** [comment]
@ThiagoMiranda don't you need to call `client.testConnection()` as opposed to `MyClass.testConnection()`?

**Comment by ThiagoMiranda** [comment]
@Mattchewone sorry I've changed some of the code variables name but it gives me the same error

**Comment by spalger** [comment]
Sorry, but the `elasticsearch.Client` constructor isn't inheritable. It actually creates a new constructor inside itself (based on the chosen apiVersion) and then returns an instance of that constructor (see https://github.com/elastic/elasticsearch-js/blob/master/src/lib/client.js#L101).

To extend the API I suggest using a plugin, like so:
```js
const customApiPlugin = Client =>
  class CustomClient extends Client {
    testConnection() {
      this.ping({
        requestTimeout: 30000,
      }, (error) => {
        if(error) console.error('Elastic search is out');
        if(!error) {
          console.log('Conected');
        }
      });
  }

const client = new elasticsearch.Client({
  plugins: [customApiPlugin]
});

client.testConnection();
```

**Comment by ThiagoMiranda** [comment]
@spalger thanks I'll try that
