### ISSUE TITLE
How to send data to external data storage e.g. elastic search using NodeJS?

### ISSUE THREAD

**Issue by JenifferWuUCLA** [elastic/elasticsearch-js#517]
How to send web form's data to external data storage e.g. elastic search using NodeJS? Would you pls help to give me some code demos to follow?

Thanks!

**Comment by spalger** [comment]
@JenifferWuUCLA this issue tracker is for bugs and feature requests. For general questions and help using elasticsearch I suggest starting a topic at https://discuss.elastic.co/c/elasticsearch
