### ISSUE TITLE
Index contain "*" will error out or crash

### ISSUE THREAD

**Issue by xiaoanhou** [elastic/elasticsearch-js#520]
For example, I have:
c:\develop\accaella\test\aella_full_stack_mgr>curl http://192.168.1.23:9200/_cat/indices
   yellow open ade_register-2017.03.24 P460kuyfRX2XwZev_bK7ug 5 1   207 0   190kb   190kb
   yellow open ade_monitor-2017.03.24  Hfmip7itSbmd0jOVO5LKcA 5 1 19673 0  11.2mb  11.2mb
   yellow open ade_monitor-2017.03.25  EiNaMiYyRgab247AD8u-Wg 5 1  9595 0  20.2mb  20.2mb
   yellow open ade_register-2017.03.25 XC6-jQoxSKa0A5tOTP1UHA 5 1   606 0 472.2kb 472.2kb

If I search Index 'ade*' as shown below, the elasticsearch-js will error out or crash.
client.search({
  index: 'ade*',
  type: 'tweets',
  body: {
    query: {
      match: {
        body: 'something'
      }
    }
  }
}).then(function (resp) {
    var hits = resp.hits.hits;
}, function (err) {
    console.trace(err.message);
});

**Comment by spalger** [comment]
What's the error?

**Comment by xiaoanhou** [comment]
Sorry. Looks like something else caused the server crash. I cannot reproduce the issue anymore. Here I am closing Issue 92. Thanks for the prompt reply.
