### ISSUE TITLE
Is it possible to do an Sliced Scroll?

### ISSUE THREAD

**Issue by antonvs2** [elastic/elasticsearch-js#524]
I want to do an [Sliced Scroll](
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#sliced-scroll), but I checked the source code and the documentation and did not find anything about it.

Tried adding it to the body as well but no luck.

Is there any way to use it?

**Comment by spalger** [comment]
Sure, looks like you use the same scroll api methods, but pass the slice information in the body of the request with the query.

**Comment by antonvs2** [comment]
Thanks for your answer!

Sorry, I was checking it in version 2.x, that's why it was failing even adding it to the body.
