### ISSUE TITLE
appended localhost resulting in no living connection 

### ISSUE THREAD

**Issue by ChrisCPO** [elastic/elasticsearch-js#525]
lets say my computer's name is "foo labtop" 

I'm getting these errors when running the server: 

```
Elasticsearch WARNING: 2017-04-06T17:28:41Z
  Unable to revive connection: http://foo-labtop/127.0.1.1:9200/

Elasticsearch WARNING: 2017-04-06T17:28:41Z
  No living connections
```
The host is being set to localhost:9200.
```
    this._connectionOptions = {
      hosts: config.hosts, // => "localhost:9200"
      sniffOnStart: true, // search for the rest of the cluster on boot
      sniffInterval: 15000, // update cluster config every 15 seconds
      sniffOnConnectionFault: true,
      keepAlive: true,
      apiVersion: '2.1'
    };

    this._client = new Elasticsearch.Client(this._connectionOptions);
```

 I can't figure out where this appended DNS is coming from I have looked through system settings, asked other developers. Note I do not have issues with other libraries, I have a rails app that works fine with my local ES server. 

anyone have a idea's, my OS is Ubuntu 14.04

**Comment by spalger** [comment]
`"localhost:9200"` parses to a path using node's standard url parser. Include the protocol in there and it should be fine (eg. `"http://localhost:9200")
