### ISSUE TITLE
client.indicies.create uses POST method instead of PUT method

### ISSUE THREAD

**Issue by carltierney** [elastic/elasticsearch-js#529]
HTTP POST is no longer supported by elastic search server as a valid method for creating an index

"No handler found for uri [/<index name>] and method [POST]"

**Comment by spalger** [comment]
Recent versions of the client shouldn't have that issue https://github.com/elastic/elasticsearch-js/blob/f31aa27b6efa3b29744ed8e709931057f0f79789/src/lib/apis/5_3.js#L2939
