### ISSUE TITLE
elasticsearch-js is initiating JqueryConnector inside $ or jQuery

### ISSUE THREAD

**Issue by fnfilho** [elastic/elasticsearch-js#530]
on console, when I request for $ ou jQuery, this is what I get:
```
function JqueryConnector(host, config) {
  ConnectionAbstract.call(this, host, config);
}
```

My code is simply importing `import elasticsearch from 'elasticsearch'` as defined on the docs. When I comment this line, $ and jQuery goes back to the correct object.

This is creating some inconsistencies with other libraries that request jQuery

**Comment by spalger** [comment]
Are you installing elasticsearch from npm? Please use the `elasticsearch-browser` module if so. As you can see in [we are not replacing jquery](https://github.com/elastic/elasticsearch-js/blob/f31aa27b6efa3b29744ed8e709931057f0f79789/src/elasticsearch.jquery.js#L14) in the jquery version of the client, but it seems you are probably importing the [jquery connector](https://github.com/elastic/elasticsearch-js/blob/f31aa27b6efa3b29744ed8e709931057f0f79789/src/lib/connectors/jquery.js#L8) (connectors are for http/ajax connections, not for connecting to the library)
