### ISSUE TITLE
Deleted documents show up in completion suggestions

### ISSUE THREAD

**Issue by Ebrahim-Yewno** [elastic/elasticsearch-js#531]
I have deleted documents from an index, but still see them in suggestions. I have tried explicit refresh, but it also doesn't help. 
I could track this problem back in[ 2014 in earlier versions](https://github.com/elastic/elasticsearch-js/issues/117), but it sounds that it is solved in current version, but I'm facing the same problem.

Is there any way to purge a document from an index including suggestions?

**Comment by spalger** [comment]
@Ebrahim-Yewno please take your question about elasticsearch (not the client) to the [elasticsearch forums](https://discuss.elastic.co/c/elasticsearch).
