### ISSUE TITLE
listen connection events

### ISSUE THREAD

**Issue by akulnurislam** [elastic/elasticsearch-js#532]
Hello guys is there any listen connection from elasticsearch.

example like this [events redis](https://github.com/NodeRedis/node_redis#connection-and-other-events)

needed when elasticsearch `disconnected` so I'm able to reconnecting.

**Comment by spalger** [comment]
Not yet, but we're looking into such events starting with https://github.com/elastic/elasticsearch-js/issues/526

**Comment by akulnurislam** [comment]
ah ok @spalger thanks
