### ISSUE TITLE
What's the elasticsearch-js equivalent of GETting `/_aliases`?

### ISSUE THREAD

**Issue by shawninder** [elastic/elasticsearch-js#533]
I need is a list of all the indices I have along with any aliases they may have. I found a way to get exactly the data I want out of elasticsearch via curl (`GET /_aliases?format=json`), but I can't find the elasticsearch-js equivalent (`esClient.<something>().then(...)`).

So I guess there are 2 questions here:

1. What is the equivalent for `GET /_aliases?format=json` in the `esClient.<something>` format?
2. In general, if I have a working http "command", how can I find its elasticsearch-js equivalent?

**Comment by spalger** [comment]
You're looking for `getAlias()`. I suggest starting by searching through the [api reference](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html), most API's an named very similar to their elasticsearch equivilent
