### ISSUE TITLE
Ignore expires header for client requests

### ISSUE THREAD

**Issue by flyweight** [elastic/elasticsearch-js#536]
Currently, I have my ES instance behind an nginx proxy that sends an expires header with a cache-control value of public.

I want to be able to bypass this cache while using the elasticsearch.Client.  Is there a configuration that I can change in the client to make it not respect the expires header?

```
const client = new elasticsearch.Client({                                                                                                   
  host: "https://myhost/search",                                                                                                    
  requestTimeout: 30000,                                                                                                                    
  deadTimeout: 1000                                                                                                                         
});
```

Thanks

**Comment by spalger** [comment]
The client doesn't do any caching, and if you're doing this in the browser the client can't tell the browser to not respect the cache headers. You should fix your proxy configuration.
