### ISSUE TITLE
min_score not available on .search()

### ISSUE THREAD

**Issue by Unibozu** [elastic/elasticsearch-js#540]
ElasticSearch supports providing a `min_score` property within the search body https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-min-score.html

It seems the ElasticSearch JS client allows `minScore` in the `.count()` method but not `.search()`.

Is there a specific reason this is not available?

Thanks

**Comment by spalger** [comment]
The arguments available in the body of any request are not described in the elasticsearch-js docs. Because of this my assumption is that the count API supports sending the `min_score` via the query string, but the search API does not.

**Comment by Unibozu** [comment]
Not sure I understand what to do with that. Is it supposed to work despite not being in the documentation?

**Comment by Unibozu** [comment]
No worries I've done some testing and found what you meant by that. I couldn't find any documentation about the count API supporting `min_score` via query string, but passing `min_score` in the search API body works as expected.
