### ISSUE TITLE
Pipeline isn't supported on update.

### ISSUE THREAD

**Issue by Asheboy** [elastic/elasticsearch-js#542]
Is there a reason why this API doesn't support the pipeline property on updates? The property I'm refering to on create is https://github.com/elastic/elasticsearch-js/blob/master/src/lib/apis/5_3.js#L1846-L1848.

**Comment by spalger** [comment]
The API in the elasticsearch client is defined based on the rest-api-spec from elasticsearch: https://github.com/elastic/elasticsearch/blob/5.3/rest-api-spec/src/main/resources/rest-api-spec/api/update.json

If there is a missing parameter we should add it up stream.
