### ISSUE TITLE
Typescript - Property 'catch' does not exist on type 'PromiseLike

### ISSUE THREAD

**Issue by ericzon** [elastic/elasticsearch-js#544]
I've just installed your last version + @types/elasticsearch. At this moment it works ok calling .then method but it raises this error on calling .catch. 

Thanks

**Comment by spalger** [comment]
Sorry @ericzon, but those type definitions are not a part of this repo: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/elasticsearch
