### ISSUE TITLE
Ping spec requestTimeout overrides client requestTimeout

### ISSUE THREAD

**Issue by jbudz** [elastic/elasticsearch-js#547]
It looks like the requestTimeout at https://github.com/elastic/elasticsearch-js/blob/master/src/lib/apis/master.js#L5557 overrides the requestTimeout when initializing a client.

Not sure if it's intentional, if it is we should to override this in the kibana health check.

**Comment by tylersmalley** [comment]
Test:

```
const elasticsearch = require('elasticsearch');

const client = new elasticsearch.Client({
  host: 'localhost:9200',
  log: 'trace',
  requestTimeout: 30000,
  pingTimeout: 30000
});

client.ping();
```

Log:
```
Elasticsearch INFO: 2017-05-19T16:50:41Z
  Adding connection to http://localhost:9200/

Elasticsearch DEBUG: 2017-05-19T16:50:42Z
  starting request {
    "method": "HEAD",
    "requestTimeout": 3000,
    "castExists": true,
    "path": "/",
    "query": {}
  }


Elasticsearch TRACE: 2017-05-19T16:50:42Z
  -> HEAD http://localhost:9200/

  <- 200


Elasticsearch DEBUG: 2017-05-19T16:50:42Z
  Request complete
```

**Comment by bohyun-e** [comment]
@jbudz @tylersmalley Any updates on this issue?

**Comment by amiram** [comment]
This bug seems simple. There is a hard-coded value for timeout in ping function in each api. For example here: https://github.com/elastic/elasticsearch-js/blob/master/src/lib/apis/6_0.js#L5515
Is it there for a reason?
