### ISSUE TITLE
Content-Type header in configuration doesn't change network request

### ISSUE THREAD

**Issue by CailinPitt** [elastic/elasticsearch-js#553]
I'm currently using elasticsearch-js in an Angular 1.6 app I am developing. When I post to my ElasticSearch instance, it generates preflight requests (because the Content-Type is `application/json`). I want to modify my POST requests to ElasticSearch so it doesn't generate preflight requests.

I found this old issue (#98) where someone needed to change the Content-Type of requests to their ElasticSearch instance, so I tried using the suggestion made and adding the header configuration to change the Content-Type:

```
(function() {
    'use strict';

    angular
        .module('myApplication')
        .service('elasticSearchClient', function(esFactory) {
          return esFactory({
            method: "POST",
            host: '<host>',
            headers: {
              'Content-Type': 'text/plain'
            }
            //log: 'trace' //Prints Rest call details to console
          });
        });
})();
```

However when I inspect the network events in Chrome, my POST requests are still of Content-Type `application/json`, thus generating preflight requests. Thank you for the help in advance!

**Comment by RogerGMartins** [comment]
I'm having the same issue.

I'm connecting like this:
`_esClient = esFactory({
        host: 'http://localhost:8888/backend/mit/elasticsearch',
        apiVersion: '2.4',
        log: 'trace',
        headers: {
          'Accept': 'application/json;charset=utf-8',
          'Accept-Charset': 'charset=utf-8'
        },
      });`

and this is being sent :
Accept: application/json, text/plain, */*
without the accept-charset.

I'm proxying the requests, so i guess i will just inject there.

**Comment by spalger** [comment]
I'm not convinced that this is going to prevent pre-flight requests. I'm pretty sure that's happening because the request is cross-origin, but there is a problem with your config. the [client does't have a headers option](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html), that option belongs inside a [host object definition](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/host-reference.html).

```js
(function() {
    'use strict';

    angular
        .module('myApplication')
        .service('elasticSearchClient', function(esFactory) {
          return esFactory({
            method: "POST",
            host: {
              host: '<host>',
              headers: {
                'Content-Type': 'text/plain'
              }
            }
            //log: 'trace' //Prints Rest call details to console
          });
        });
})();
```
