### ISSUE TITLE
Config option to set sniff filter_path param

### ISSUE THREAD

**Issue by cawalch** [elastic/elasticsearch-js#554]
The current `filter_path` [param](https://github.com/elastic/elasticsearch-js/blob/master/src/lib/transport.js#L406) should be configurable to allow for custom node attributes.

**Comment by spalger** [comment]
I think that's a reasonable idea, mind trying out https://github.com/elastic/elasticsearch-js/pull/559?

**Comment by cawalch** [comment]
Perfect. Thanks!
