### ISSUE TITLE
callback function called multiple times

### ISSUE THREAD

**Issue by sharadendu-sinha** [elastic/elasticsearch-js#558]
While trying to invoke bulk API, we found that callback function is getting invoked multiple times. Not sure if this is by design ???
As cb is called multiple times it makes it impossible for the library to be combined with other control flow modules like async or wait.for or for that matter any library that depends on cb invocation to detect completion. 

The issue is originally in transport.js and should be fixed, if not there should be proper documentation stating that there can be multiple cb invocations. 

Also its the tranport module causing the issue, I am confident that all other APIs (excluding bulk) suffer from the same fate.

**Comment by spalger** [comment]
Can you please provide reproduction steps? This is a serious bug if it's reproducible

**Comment by sharadendu-sinha** [comment]
I was trying to move data from one data source to a new ES cluster. 
So, I had implemented my own node based utilty to do the same. The utility reads the original data store and in chunks of 500 dumps new docs to new ES cluster. 

So, basically its a long running bulk index operations. 
The easiest way to reproduce this is introduce network fluctuations. Lets say i disconnect network momentarily. My utilty was designed to handle such network failures by using retry on with exponential backoff. Now, when I turned my network I was expecting the process to resume, but it kept failing because async.js kept complaining "callback already called". 

I added a few loggers to confirm that number of callbacks received and number of calls made to es client were same. But found that number of callbacks were more.

So, as a fix I am using npm 'once' before I call async js callback. 

I had to spend a good day and a half trying to debug the issue and get my data exported to work. 

Hope the above helps. 

Having said that I have also observed the issue without network outages, but sure about the reproduction steps there.

Also, I do not see any checks in transport to ensure callbacks are invoked a single time. This can be seen by simple code reviews.

**Comment by godber** [comment]
I think it might be possible you are experiencing the issue outlined in #521.

In the case of that issue, when the socket times out, the retry logic kicks in and retries the request I think.

Are you seeing any socket hangup errors?

**Comment by spalger** [comment]
While I try tracking down the cause of this, consider using promises instead. They are garunteed to only be resolved/rejected once.

**Comment by sharadendu-sinha** [comment]
I am of the opinion, be it with or without retry, the API contract is based on cb which needs to get invoked just once. 
So, if the same cannot be handled in library , I request you guys to please add documentation that cb may get called multiple times, it will help save debugging nightmares and enormous amount of time for all of the libs consumers

**Comment by sharadendu-sinha** [comment]
Why is the status still marked as feedback required. I have provided my feedback. Request you guys to change the status appropriately, else I am afraid this will not be picked up.
