### ISSUE TITLE
Call to index never returns

### ISSUE THREAD

**Issue by seanlindo** [elastic/elasticsearch-js#561]
I'm using 3 queue workers to process messages of 20 in a loop, indexing one at a time. I'm creating the connection only once per application instance as well.

For some reason, the connection appears to die and queue workers stop processing messages. There are no errors and no clues. I've turned on the debugging level for the logs but there is nothing of note, the last logged message is a successful index operation, but then nothing. The entire operation is surrounded by a top level `try/catch`, but that never trips anything either. Are there additional configuration options I should be using?

## Code

    import config from 'config'
    import elasticsearch from 'elasticsearch'

    const connString = config.get('ES.connectionString')
    const es = new elasticsearch.Client({ host: connString, log: 'debug' })

    module.exports = es

## Indexing Code

    for (let document of documents) {
            await client.index({
                index: 'document',
                type: 'compliance',
                id: document.id,
                body: document
            })
        }

**Comment by spalger** [comment]
Everything looks normal to me. I'm almost certain this has nothing to do with the library so I'm going to close the issue, but I'd be happy to take a look at the code if you want to link to a repo, or share more
