### ISSUE TITLE
Get method instead of Post in search api

### ISSUE THREAD

**Issue by matt212** [elastic/elasticsearch-js#569]
Hi , 
is there a way to search elastic using get rather than post method , since i can do this in curl

```
curl -XGET 'localhost:9200/tvseries/internindex/_search?size=5&from=5&pretty' -H 'Content-Type: application/json' -d'
{
  "query": {
    "bool": {
      "should": [
        { "match": { "showname":  "Family guy" }},
        { "match": { "content": "sex"   }}
      ]
    }
  }
}
'
```
and it works , how can i do the same using elasticsearch.js !

**Comment by spalger** [comment]
Node.js doesn't support sending http bodies with the GET method. As I understand it, the spec is a little hazy on this topic, but that's the reality in both the browser and node.js so there is no way to do it in the js client.
