### ISSUE TITLE
Missing search_after parameter

### ISSUE THREAD

**Issue by marcvdm** [elastic/elasticsearch-js#571]
According to the elasticsearch docs i can use the search_after parameter to paginate/scroll through the data.
https://www.elastic.co/guide/en/elasticsearch/reference/5.1/search-request-search-after.html

But i cannot find any reference in this js sdk.

When i try to use it i get the following exception
```
[illegal_argument_exception] request [/_search] contains unrecognized parameter: [search_after] -> did you mean [search_type]?
```

Is this intended or just missing?

**Comment by spalger** [comment]
Search after belongs in the body of the request, and the elasticsearch-js api only documents the query string parameters. All of the body parameters are passed within the `body: {}` accepted by almost every method that isn't a pure `GET`.

**Comment by devagirir** [comment]
I tried same approach, but I print that query..it like this
{"index":"sampleindex","size":1000,"sort":"vvvv.keyword:asc","body":{"search_after":"00D1I000003nRMaUAM_000d7fe1-2a91-11e9-bd8f-4f1e395f9c1c"}}
it still gives me error "contains unrecognized parameter: [search_after] -> did you mean [search_type]?"

**Comment by olegkleiman** [comment]
Try something like this:
 ``` javascript
       const response = await elasticClient.search({
          index: <indexName>,
          size: pageSize,
          sort: 'id:asc',
          body: {
            search_after: [after]
          }
        });
```
