### ISSUE TITLE
Scroll api 5.0, 5.1, 5.2 throwing error against elastic search 5.3+

### ISSUE THREAD

**Issue by kjg** [elastic/elasticsearch-js#573]
When I use the 5.0, 5.1, 5.2 scroll API from elasticsearch-js 13.1.1 or 13.2.0 against elasticsearch versions 5.3 and up I get the error

` Error: [illegal_argument_exception] Failed to parse request body`

In this case the request body is just a plain string which is the scroll id, not a json payload of form `{scrollId: scrollId}`

Does elasticsearch 5.3 not allow for requests via API 5.0, 5.1, 5.2, or do those API definitions need to be updated, or any idea what I might be doing wrong here?

**Comment by kjg** [comment]
Wait, is the apiVersion we set in the client supposed to always match the version of elasticsearch you're connecting to? If so, does upgrading elasticsearch always require a version bump in the config of the client code and downtime of the app?

**Comment by kjg** [comment]
As far as I can tell, the string only body was last in the docs on [version 1.7](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-request-scroll.html), all newer versions show using the json body.

Maybe all the api specs need to be updated then? Do we need to update

- https://github.com/elastic/elasticsearch-js/blob/e2897da71f1d152ca107e6662c9be1f84daa3907/src/lib/apis/5_0.js#L5715-L5740
- https://github.com/elastic/elasticsearch-js/blob/e2897da71f1d152ca107e6662c9be1f84daa3907/src/lib/apis/5_1.js#L5848-L5873
- https://github.com/elastic/elasticsearch-js/blob/e2897da71f1d152ca107e6662c9be1f84daa3907/src/lib/apis/5_2.js#L5848-L5873

to match

https://github.com/elastic/elasticsearch-js/blob/e2897da71f1d152ca107e6662c9be1f84daa3907/src/lib/apis/5_3.js#L5836-L5864

**Comment by kjg** [comment]
After much digging, I think this is the change that needs to be made (followed by a `npm run generate`)

```diff
diff --git i/scripts/generate/overrides.js w/scripts/generate/overrides.js
index fd8aa9c..2607852 100644
--- i/scripts/generate/overrides.js
+++ w/scripts/generate/overrides.js
@@ -252,7 +252,7 @@ function (spec) {
     }
   },
   {
-    version: '>=5.3',
+    version: '>=2.0',
     paramAsBody: {
       scroll: {
         param: 'scrollId',
```

What do you think @spalger? Do you happen to remember why you had it as 5.3+ [before](https://github.com/elastic/elasticsearch-js/commit/d4522941243c2d0575915f377900bdc3b7a473f4)

**Comment by spalger** [comment]
I did that as 5.3+ because https://github.com/elastic/elasticsearch/pull/22691 went into 5.3, but that's unfortunate that this doesn't work in 5.0+... I really need to get the functional tests for the client up and running again

**Comment by spalger** [comment]
Are you sure that should be `>=2.0`? Wouldn't `>=5.0` be more appropriate?

**Comment by kjg** [comment]
@spalger I went with `>=2.0` because the [1.7 docs](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-request-scroll.html) show the body as just the requestId value 

```
curl -XGET  'localhost:9200/_search/scroll?scroll=1m'   \
     -d       'c2Nhbjs2OzM0NDg1ODpzRlBLc0FXNlNyNm5JWUc1' 
```

and the [2.0 and up docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-request-scroll.html) all support the json version

```
curl -XGET  'localhost:9200/_search/scroll'  -d'
{
    "scroll" : "1m", 
    "scroll_id" : "c2Nhbjs2OzM0NDg1ODpzRlBLc0FXNlNyNm5JWUc1" 
}
'
```
<img width="758" alt="screen shot 2017-07-28 at 12 28 36 pm" src="https://user-images.githubusercontent.com/2205/28728968-57aed2ee-7390-11e7-9596-7f97096c71c8.png">

And the note about for backwards compatibly `scroll_id can be passed in the request body` was removed in the 5.0 docs

My opinion is 2.0 -> 2.4 should use the json body version instead of the backwards compatible version since they support both styles, but you are obviously much closer to the project, so I'll defer to your expertise.

Would you like me to make the PR for this change? If so should I use `>=2.0` or `>=5.0` after the above consideration? And also, should I include the new output of `npm run generate` in the PR or does that always get updated after merge into master?

Thanks so much for taking a look at this!

**Comment by spalger** [comment]
Nice, sounds like a valid reason to me! A PR would be very helpful, and `>=2.0` sounds great

**Comment by kjg** [comment]
Should I include the output of `npm run generate` in the PR or does that always get updated after merge into master?

**Comment by spalger** [comment]
@kjg I actually run it manually but like to keep it separate from the PRs. Thanks again!
