### ISSUE TITLE
TypeError:cannot read property 'requst' of undfined

### ISSUE THREAD

**Issue by offlineError** [elastic/elasticsearch-js#574]
Hi there,
I'm using your package, to add a log into kibana, and I get this error:

TypeError cannot read property 'request' of undefined
at exec ...node_modules/elasticsearch/src/lib/client_action.js : 364:19
at action ... node_modules/elasticsearch/src/lib/client_action.js : 61:16
and the rest of the stack is mine.

I use the index function within the client object.

elasticsearch:13.2
node: 8.1.2

hope to solve it. thanks!

**Comment by AlexandruSimandi** [comment]
i have the exact same issue

**Comment by mdelorimier** [comment]
Same here

**Comment by spalger** [comment]
the only `request` property in the client_action is `this.request`, which means the function that you're accessing has probably lost `this` context. Are you calling the method like `client.index()` or have you assigned `index` to a separate value and called it directly, like

```js
var index = client.index;
index()
```

If it's the later then you need to bind the `this` context to the `index` function with something like the `.bind()` method:

```js
var index = client.index.bind(client);
index()
```
