### ISSUE TITLE
Support `PUT <index>/<type>/<id>`

### ISSUE THREAD

**Issue by nyurik** [elastic/elasticsearch-js#577]
The core ElasticSearch API supports `PUT` verb - `PUT <index>/<type>/<id>` -- which functions as an UPSERT command - if the document does not exist, PUT creates it, otherwise it replaces the document with the new version.  Does the elasticsearch-js have corresponding functionality?

**Comment by spalger** [comment]
You're looking for [`client.index()`](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-index)
