### ISSUE TITLE
React Native?

### ISSUE THREAD

**Issue by Sundin** [elastic/elasticsearch-js#578]
Has anyone tried this library out with react native? I tried adding it to my project, but I get a lot of errors of the following sort:

https://github.com/facebook/react-native/issues/4968

**Comment by renehauck** [comment]
For reasons of safety, i wouldn't do this. Use a Api.

**Comment by YasirPanjsheri** [comment]
@renehauck Hi, can you explain more regarding the Api ? I am trying to build a react native app with faceted search capability in Firebase. I am really confused regarding this.

**Comment by renehauck** [comment]
Sure, for using ElasticSearch(or other databases,...) on mobile devices, you have to store the username (key or whatever) and the password on your device. 
And that's the reason, you can not store this authentication data **secure** on a device. 
For example in android, you can simple decompile the app-apk. With a api, you can make this "securer", and only deliver the data, you want.
