### ISSUE TITLE
Provide TypeScript type definitions for ElasticSearch

### ISSUE THREAD

**Issue by keyle** [elastic/elasticsearch-js#59]
As TypeScript has hit 1.0RC1, the language should be stable.

It'd be really useful (and powerful) if you could provide the type defs for ElasticSearch as elasticsearch helps solve enterprise problem, and typescript is the answer to scaling javascript apps (front and back).

TypeScript definition are similar to header files that help a statically typed language such as TypeScript making sense of an api.

See this repo https://github.com/borisyankov/DefinitelyTyped containing many defs.

**Comment by jmkgreen** [comment]
This was closed but to what end? I'm not seeing an entry in the referenced repo. I am trying to get Intellij to recognise this library and this seems to be the missing link.

**Comment by spalger** [comment]
I'll reopen and reinvestigate. At the time I had doubts about the longevity of the TypeScript project.

**Comment by jmkgreen** [comment]
Intellij has a window to download from the above repository and I am seeing more adoption of Typescript "out there" so this likely to be of value IMHO.

**Comment by djnelson9715** [comment]
+1 for Typescript support.  For large scale enterprise development, Typescript is essential.

**Comment by StanleyGoldman** [comment]
+1

**Comment by samalbert** [comment]
+1

**Comment by mgilliganrca** [comment]
+1

**Comment by andreimatusevich** [comment]
+1

**Comment by andreimatusevich** [comment]
BTW Angular 2 is going to be build on TypeScript

**Comment by gslsouza** [comment]
+1

**Comment by styfle** [comment]
+1

**Comment by sdnetwork** [comment]
+1

**Comment by lazutkin** [comment]
+1

**Comment by khaines** [comment]
+1

**Comment by zhutony** [comment]
+1

**Comment by PLEEROCK** [comment]
+1

**Comment by siman** [comment]
I have found these type defs (may be outdated):
https://github.com/peeriodproject/core/blob/master/ts-definitions/elasticsearch/elasticsearch.d.ts

**Comment by zivni** [comment]
+1

**Comment by soramusoka** [comment]
+1

**Comment by moufatich** [comment]
+1

**Comment by wongwideweb** [comment]
+1

**Comment by jordanburke** [comment]
+1

**Comment by darthtrevino** [comment]
+1

**Comment by achaussende** [comment]
+1

**Comment by coreyog** [comment]
+1

**Comment by arbh89** [comment]
+1

**Comment by kouki-o** [comment]
+1

**Comment by JornPalsenbarg** [comment]
+1

**Comment by gyllen** [comment]
+1

**Comment by MannikJ** [comment]
+1

**Comment by alexweber** [comment]
👍

**Comment by terodox** [comment]
+1

**Comment by sayuloveit** [comment]
+1

**Comment by n4nagappan** [comment]
+1

**Comment by jppellerin** [comment]
Started something here that is functional and works for search.

https://github.com/jppellerin/typed-elasticsearch

**Comment by CasperSkydt** [comment]
Got this merged to definitelytyped today: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/elasticsearch/elasticsearch.d.ts

Its a start...

**Comment by spalger** [comment]
Thank you @CasperSkydt!

**Comment by sxmon** [comment]
@CasperSkydt  Thank you. What is a quickstart to use elasticsearch in typescript ?

**Comment by Kangmo** [comment]
Hi @CasperSkydt , Thanks for type type definition. 

1. I have two questions about the type definition. PromiseLike seems to be missing catch. Is this ok?
2. Looks like the type definition file is based on ElasticSearch 5.0. Do you have any plan to support the latest 5.4 version?

Thanks,
Kangmo

**Comment by kareljuricka** [comment]
When I try to connect to elasticsearch with node.js in typescript using this type definition file, I got error - ReferenceError: navigator is not defined.

I understand that it wants to run in browser but what if I want to use it in node.js?

**Comment by kareljuricka** [comment]
I facing thix problem with typescript compilation with this code:
```
import { Client } from 'elasticsearch';

let client = new Client({
	host: 'localhost:9200'
})
```

When I transpile it with typescript compiler (command tsc), everything works ok. But when I use webpack to build same project, it generates big bundle where is line with using Navigator object. Because I want to use it for backend node.js and run it in console, I get ReferenceError: navigator is not defined. 

Does someone know solution?

**Comment by tleveque** [comment]
+1

**Comment by delvedor** [comment]
The new version of the client provides types definitions with the code 🎉
