### ISSUE TITLE
Old lodash is adding ~1mb of JS

### ISSUE THREAD

**Issue by dougmoscrop** [elastic/elasticsearch-js#592]
We're using AWS Lambda and the amount of JavaScript included in your deployment impacts things like startup time. 

lodash 2.x is around 1MB uncompressed and 300kb compressed. It would be awesome to maybe not depend on it anymore or to move up to a later version. I understand this was tried before and there were memory leak concerns. I also notice that you now target Node v6+ on master - would you accept PRs removing lodash in some areas where ES6 native functionality exists? Or would you prefer to migrate to 4.x and see about the leaks again? 

(A side note, this module is almost always the largest in all deployments!)

**Comment by doug-numetric** [comment]
Can you cherry-pick your lodash dependencies?

**Comment by dougmoscrop** [comment]
The new client looks like it has minimal dependencies! 👍

**Comment by delvedor** [comment]
Indeed :)
We are planning to publish it soon, at the moment on npm you can find the beta version that works with Elasticsearch 7-beta1.
Feel free to try it! :)

**Comment by dougmoscrop** [comment]
Sounds good, is there plans to have it work with 5 or 6?

**Comment by delvedor** [comment]
Yes, the plan is to support Elasticsearch 5, 6 and 7.
