### ISSUE TITLE
how to detect when Client.bulk did not add documents to type due to duplicate _id

### ISSUE THREAD

**Issue by nxmohamad** [elastic/elasticsearch-js#596]
in the situation where bulk is trying to add documents into a type, but doesn't because the _id specified already exists, how can I detect that?

currently it just returns a 200 even though before and after the action, the number of documents in my type remains the same.

**Comment by nxmohamad** [comment]
my bad. just re-read the docs. I should just change the action type from index to create.

**Comment by wingleungchoi** [comment]
@nxmohamad what is the behaviour `create` is?  upsert or  duplicate documents with the same _id?

**Comment by wingleungchoi** [comment]
checked in document.
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference-5-3.html#api-index-5-3
`When you specify an id either a new document will be created, or an existing document will be updated.`
