### ISSUE TITLE
how to create a document without id?

### ISSUE THREAD

**Issue by doukai** [elastic/elasticsearch-js#597]
client.create({
  index: 'myindex',
  type: 'mytype',
  **id: '1',**
  body: {
    title: 'Test 1',
    tags: ['y', 'z'],
    published: true,
    published_at: '2013-01-01',
    counter: 1
  }
}, function (error, response) {
  // ...
});

how to create a document without id(elasticsearch generate)?

**Comment by shzcore** [comment]
@doukai 

client.index()

This should resolve the problem

**Comment by doukai** [comment]
@shzcore thank you!
