### ISSUE TITLE
Different results between direct HTTP Call and using NodeJS client

### ISSUE THREAD

**Issue by champloo11** [elastic/elasticsearch-js#604]
POSTing a search query via a REST client yield different results, it appears that the node client rounds off floating point numbers somewhere. 

Via a REST Client (returns exactly one hit):
```
POST /search-index/sitter-digest/_search?from=0&size=50 HTTP/1.1
Content-Type: text/plain; charset=utf-8
Host: localhost:9200
Connection: close
User-Agent: Paw/3.1.5 (Macintosh; OS X/10.12.6) GCDHTTPRequest
Content-Length: 163

{
  "query": {
    "range": {
      "rank": {
        "gte": 4.5
      }
    }
  },
  "sort": [
    {
      "rank": {
        "order": "desc"
      }
    }
  ]
}
```

Results:
```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "hits":[...],
 }
}
```

Via *node* (note that changing the `gte` field to 4.4 yields results. Which leaves me to believe that this is a rounding/casting issue):

```javascript
const sitterData = await elasticsearch.search({
    index: 'search-index',
    type: 'sitter-digest',
    size: 50,
    from: 0,
    body: {
        query: {
            range: {
                rank: {
                    gte: 4.5,
                },
            },
        },
        sort: [
            {
                rank: {
                    order: 'desc',
                },
            },
        ],
    },
});
```

Results:
```{ took: 0,
  timed_out: false,
  _shards: { total: 5, successful: 5, skipped: 0, failed: 0 },
  hits: { total: 0, max_score: null, hits: [] } }```

**Comment by 0x13a** [comment]
if you provide a dump of the request being sent by the node.js could be helpful to discover the issue
using [ngrep](https://github.com/jpr5/ngrep) for example

```sh
sudo ngrep port 9200
```

**Comment by sgn95** [comment]
hello!  Is the problem solved? how to solve?

**Comment by delvedor** [comment]
Hello!
Is this problem still an issue? If so, can you please upload a full example to reproduce it? *(which client are you using and which version, same for elasticsearch and some fake data that will replicate the issue)*

**Comment by sgn95** [comment]
I used version 15.3.1, I cleaned up the es cache, it is ok ， but, I use HTTP normally

log: {"took":79,"timed_out":false,"_shards":{"total":2,"successful":1,"skipped":0,"failed":1,"failures":[{"shard":1,"index":"ytborder_2019","node":"oov7JSMAQqm13n4cLDDYfg","reason":{"type":"exception","reason":"java.util.concurrent.ExecutionException: CircuitBreakingException[[parent] Data too large, data for [_id] would be [2240955167/2gb], which is larger than the limit of [2230452224/2gb]]","caused_by":{"type":"execution_exception","reason":"CircuitBreakingException[[parent] Data too large, data for [_id] would be [2240955167/2gb], which is larger than the limit of [2230452224/2gb]]","caused_by":{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [_id] would be [2240955167/2gb], which is larger than the limit of [2230452224/2gb]","bytes_wanted":2240955167,"bytes_limit":2230452224}}}}]},"hits":{"total":1,"max_score":null,"hits":[{"_index":"ytborder_2019","_type":"2019","_id":"5c8c8a7cee3f14128bfce799","_score":null,"_source":{"id":"5c8c8a7cee3f14128bfce799","ordernum":"M20190316133231109927","no3":"","ordertype":2,"mcode":"48918421eef590","imei":"868575021337458","sn":"8601709250999","client":1,"cardno":1010000098163460,"openid":"osENwwNSQ1HCF3KIKJ0T4C-ohPeo","fee":700,"charge":0,"balance":0,"accountnumber":10017885,"poolamount":1598650,"createTime":"2019-03-16 13:32:44"},"sort":[1552743164000,"5c8c8a7cee3f14128bfce799"]}]},"aggregations":{"ordertype":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":2,"doc_count":1,"sumcharge":{"value":0},"sumfee":{"value":700}}]}}}

**Comment by delvedor** [comment]
Can you please upload a full example to reproduce it? *(which client are you using and which version, same for elasticsearch and some fake data that will replicate the issue)*

Something like the following would be awesome:
```js
'use strict'

const { Client } = require('elasticsearch')
const client = new Client({ ... })

client.index({ some data })
client.search({ query that you are using })
```
And finally the `curl` command.

Have you got a custom mapping or are you using the default?

**Comment by sgn95** [comment]
i  used default mapping .
use NodeJS Client: 
const { Client } = require('elasticsearch')
const client = new Client({
host: 'localhost:9200'
})
query Object:
{"query":{"bool":{"must":[{"match":{"ordernum":"M20190316133231109927"}}]}},"aggs":{"ordertype":{"terms":{"field":"ordertype"},"aggs":{"sumfee":{"sum":{"field":"fee"}},"sumcharge":{"sum":{"field":"charge"}}}}}}

use http call: 
curl 'http://localhost:9200/_search?pretty -H  "Content-Type: application/json" -d '{"query":{"bool":{"must":[{"match":{"ordernum":"M20190316133231109927"}}]}},"aggs":{"ordertype":{"terms":{"field":"ordertype"},"aggs":{"sumfee":{"sum":{"field":"fee"}},"sumcharge":{"sum":{"field":"charge"}}}}}}'

**Comment by delvedor** [comment]
As said, I also need some fake data to reproduce the issue.
I also suggest you take a look at https://guides.github.com/features/mastering-markdown/.
