### ISSUE TITLE
Elasticsearch 6.0 Release - When will the API full support the new version?

### ISSUE THREAD

**Issue by lmemmott** [elastic/elasticsearch-js#606]
With Elasticsearch 6.0 being released today, can anyone tell us when this API will be updated to fully support it?

Thanks in advance!

**Comment by spalger** [comment]
I'll release a new version today

**Comment by lmemmott** [comment]
Awesome!  That would be great!

**Comment by spalger** [comment]
Done, enjoy es 6.0!

**Comment by lmemmott** [comment]
Should I be seeing the changes in the master branch or a different one?

**Comment by spalger** [comment]
14.x, master is kind of in flux and might get ripped out (I don't have time to complete the big refactoring I was working on)
