### ISSUE TITLE
socket hangups

### ISSUE THREAD

**Issue by measwel** [elastic/elasticsearch-js#609]
I am using the elasticsearch driver to automatically create an index based on a cassandra table. 
The connnections keeps dropping. Sometimes when pinging with HEAD, sometimes when putting the index in place.

```
HEAD http://localhost:9200/index => socket hang up
PUT http://172.19.0.2:9200/index/_mapping/post => socket hang up
```

Can somebody please help me to diagnose and remedy this problem?

**Comment by rpedela** [comment]
PR #600 fixes the socket hang up problem for me, but I am doing a large bulk request. You may have a different problem. Can you provide a small but complete example so that others can reproduce your problem?
