### ISSUE TITLE
`.bulk()` operation fails silently

### ISSUE THREAD

**Issue by leftmostcat** [elastic/elasticsearch-js#620]
When using the bulk API, even if the callback response param would have `"errors": true`, the returned promise is not rejected and the error param is undefined. Further, this is not clearly documented, making responding to errors from the bulk API confusing and difficult.

JS release is 13.3.1, elasticsearch is 5.6.5, apiVersion is 5.5.

**Comment by spalger** [comment]
I agree that it's confusing how bulk doesn't reject when some of the requests fail, but the elasticsearch-js client focuses on exposing the elasticsearch API, which responds with a 200 OK status code in such scenarios.
