### ISSUE TITLE
How to configure client with X-pack plugin?

### ISSUE THREAD

**Issue by parthpatwala** [elastic/elasticsearch-js#622]
This is not a bug but just need information. After installing elasticsearch 5.5 i performed this query which is running perfectly. After that i installed x-pack plugin for authentication and result i got is 'missing authentication token for REST request' . So how can i authenticate client to perform search? Thanks.

```
var elasticsearch = require('elasticsearch');

var client = new elasticsearch.Client({
  host: 'localhost:9200',
  log: 'trace'
});

client.search({
    index: 'twitter', // index name
    type: 'posts', // index type
    size: req.body.size, // page size
    from: req.body.from, // page index
    body: {
        query: {
            match_all: {} // get all records
        };
    }
}, function (error, response) {
    res.json({ data : response }); //  print response
});
```

**Comment by spalger** [comment]
The host can be updated to include your username and password in the URL, or you can specify the `httpAuth` config parameter as a string: 

```js
client = new elasticsearch.Client({
  // ...
  httpAuth: `${username}:${password}`
});
``` 

See https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html for a couple other options.
