### ISSUE TITLE
`client.search()` vague suggest documentation

### ISSUE THREAD

**Issue by SaltyQuetzals** [elastic/elasticsearch-js#626]
In the [client.search()](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-search) documentation, when I attempt to use the parameters `suggestionField` and `suggestionText`, I get error messages that indicate that my input string is null. However, I thought that `suggestionText` was supposed to be the key to my input string? Trying to get suggestions based on a user's query isn't clearly defined anywhere in the documentation or examples. 
```
{
        index: 'random_index',
        suggestField: 'suggest',
        suggestText: 'query'
}
```
Error:
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: [null_pointer_exception] Input string is null
```

**Comment by harscoet** [comment]
👍

**Comment by dawnerd** [comment]
Same problem... Documentation isn't clear at all.

**Comment by mallekbh** [comment]
+1

**Comment by seanlindo** [comment]
So does this just not work?

**Comment by flyinghawker** [comment]
this issue still exists and as I understand, suggester is very important, right?

**Comment by flyinghawker** [comment]
Complement suggest is different scenarios from normal suggesters. Here I try in another way which may not work as expected but at least produce certain reasonable result.
`
{
      index: 'title',
      size:1, 
      from:0,
      body: {
        "query" : {
          "match": {
            "title": 'dolo'
          }
        },
        "suggest" : {
          "my-suggestion" : {
            "text" : 'dolo',
            "term" : {
              "field" : "title"
            }
          }
        }
      }
    }
`

**Comment by SaltyQuetzals** [comment]
This issue is over a year old, and though the field names have changed, the documentation still doesn't lend any information as to how to use this functionality.
