### ISSUE TITLE
Elasticsearch: Uncaught TypeError: Cannot read property 'Client' of undefined

### ISSUE THREAD

**Issue by rolfrennemo** [elastic/elasticsearch-js#629]
I'm running version 5.6.7 and have an issue I can't solve. See enclosed screenshots.
![image](https://user-images.githubusercontent.com/24465823/36178740-b94ddc30-10ce-11e8-97e5-bbf1a4a31fe6.png)
![image](https://user-images.githubusercontent.com/24465823/36178757-c9149a96-10ce-11e8-9c20-bdd89647b0f4.png)
Apreciate if someone has a tip for me.

Regards
Rolf

**Comment by nihar4276** [comment]
Hey, I am getting the same error, did you find a solution?

**Comment by nihar4276** [comment]
@rolfrennemo Reinstall the module and that should fix the issue

**Comment by stevensuting** [comment]
@nihar4276 How do you reinstall the module? The demo mentions nothing about it in the first place.

@rolfrennemo Did you find a solution for this?
