### ISSUE TITLE
Missing abort()

### ISSUE THREAD

**Issue by that1guy** [elastic/elasticsearch-js#633]
My app has potential to fire multiple requests to Elasticsearch and therefore I'd like to be able to abort some of the extra requests while in flight and only handle the promise of the most recent request.

Per the [documentation](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-conventions.html#api-conventions-cb), I'm expecting an `abort` method in the promise, but I don't see one.

Here is my Elasticsearch angular factory

```
app.factory('elasticsearch', ['esFactory', 'THEME', function (esFactory, THEME) {

  var factory = {};

  //client to connect to property api via ES
  factory.propertiesClient = esFactory({
    host: THEME.apiEndpoints.propertiesApi,
    log: 'error'
  });


  factory.areasClient = esFactory({
    host: THEME.apiEndpoints.areasApi,
    log: 'error'
  });


  factory.buildingsClient = esFactory({
    host: THEME.apiEndpoints.buildingsApi,
    log: 'error'
  });

  factory.metricsClient = esFactory({
    host: THEME.apiEndpoints.metricsApi,
    log: 'error'
  });

  return factory;

}]);
```

And here is my controller sending using the Elasticsearch `.search` method which should return my promise with the `abort` method;

![image](https://user-images.githubusercontent.com/1218940/36459883-a5424004-166a-11e8-8579-f72db9b7bec2.png)

Here's the contents of the `requestInFlight` promise:

![image](https://user-images.githubusercontent.com/1218940/36460016-69839c7e-166b-11e8-8f62-a45f54f33c62.png)

_Note:_ I have no errors as of this moment, everything is working fine.  But I can't figure out how to abort these extra requests.

**Comment by spalger** [comment]
This is because you're calling `.then()` on the promise returned by the es client, which returns a new promise that won't have the `.abort()` method. You need to capture the actual promise from the client like so:

```js
var esPromise = elasticsearch.propertiesClient.search(esQuery);
var requestInFlight = esPromise.then(function (body) {
 ...
```

Then you'll be able to call `esPromise.abort()`
