### ISSUE TITLE
Sporadic timeouts when using an Ubuntu container

### ISSUE THREAD

**Issue by amiram** [elastic/elasticsearch-js#634]
There are some issues that claim that sometimes you get timeout when connecting to elastic. I did some tests that you can find and do yourself [here](https://github.com/amiram/es-test).
I short, I found out that when using an Ubuntu container, requests can take around 5500ms several times per hour. It doesn't happen with alpine.
I guess this problem is not an issue with this package. Since default timeout is 3000ms, make sure you increase it with config. BTW, currently ping timeout in config is discarded and you have to pass it explicitly to the ping call.

**Comment by Verkurkie** [comment]
i am having timeout issues even when passing ping timeout explicitly like this:
`client.ping({ pingTimeout: 60000 })` - the call times out almost immediately with ECONNREFUSED error ... any thoughts? i also tried `requestTimeout` and `timeout` but all with the same result (tried them in both the config and explicitly in the call)
