### ISSUE TITLE
Elasticsearch - No handler found for uri [*****] and method [POST]

### ISSUE THREAD

**Issue by Kannaj** [elastic/elasticsearch-js#636]
**NOTE** - previous related answers havent solved my problem

I have an elastic-cluster set up in the below way

1. Elastic nodes are behind a VPN
2. Kibana server is also in the VPN but has a public api. NGINX is also in this server doing a reverse proxy.

this is my nginx.conf file

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;

    location / {
        proxy_pass http://10.X.X.8:5601;
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/conf.d/elastic.htpasswd;
    }

    location /elastic {
        return 302 /elastic/;
    }

    location /elastic/ {
        proxy_pass http://10.X.X.4:9200;
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/conf.d/elastic.htpasswd;
    }
    }

As you can see , requests to `hostname.com` will be rerouted to kibana and requests to `hostname.com/elastic` will be redirected directly to the elastic cluster

I'm using Nodejs as the client to elastic here

    var elasticsearch = require('elasticsearch');
    var environment      = require('../environment')
    
    var client = new elasticsearch.Client({
      host: https://hostname.com/elastic,
      httpAuth: environment.config.ELASTIC.PASS,
      apiVersion: '5.6'
    });
    
    client.ping({
        // ping usually has a 3000ms timeout
        requestTimeout: 5000
      }, function (error) {
        if (error) {
          console.trace('elasticsearch cluster is down!');
        } else {
          console.log('All is well');
        }
      });

`client.ping` seems to work well as i get a 200 response from elastic.

however , doing an operation like this

 

           elastic.index({ index: 'xxx-logs-4', type: 'logs', id: 1, body: messageData}, function(err, resp, status){
                if(err){
                    return logger("warn", "log", "error writing message to elastic", session, {"err": err});   
                }

            })

I get the below error

    path:"/chat-logs-4/logs/1"
    response:"No handler found for uri [/elastic/chat-logs-4/logs/1] and method [POST]"

the same error occurs for client.create(***)

**Comment by zackhorvath** [comment]
Hi @Kannaj, did you ever figure this out? Having a similar issue.
