### ISSUE TITLE
Problem adding multiple documents to the index

### ISSUE THREAD

**Issue by houriaMad** [elastic/elasticsearch-js#637]
I have a json file, it looks like this schema as-follows:

```
{
  "object": [
    {
      "id_a": "1",
      "n_s": "1",
      "name": "first",
      "num_a": "1",
      "verset": "Bonjouuuuùùùùùr"
    },
    {
      "id_a": "2",
      "n_s": "1",
      "name": "الفاتحة",
      "num_a": "2",
      "content": "Bonsoiiiiiir"
    },
...
    {
      "id_a": "6236",
      "n_s": "114",
      "name": "last",
      "num_a": "1",
      "content": "C'est le contenu que je veux"
    },
    {
      "id_a": "6237",
      "n_s": "114",
      "name": "last",
      "num_a": "2",
      "content": "Il était très difficile"
    }
  ]
}
```

---------------------------------------------------------------

I work with nodejs and elasticsearch and files with the same form but in 3 Arabic, French and English languages that are separated, 
I create my index with:
```js
    client.indices.create({
        index: "my_index_fr",
        body: {
            mappings: {
                "my_type_fr": {
                    properties: {
                        "object": {
                            type: 'nested',
                            properties: {
                                "id_a": { type: "integer" },
                                "n_s": { type: "integer" },
                                "name": { type: "text" },
                                "num_a": { type: "integer" },
                                "content": { type: "text", "analyzer": "french", "search_analyzer": "simple" },
                            }
                        }
                    }
                }
            }
        }
    }).then((success) => {
        console.log("Index created with succes !");
        res.json(success);
    });
```

--------------------------------------------------------------------------

I put my file with this:

```js
    var fileFr = require('./data/file_fr.json').object;

    let ret = [];
    console.log(fileFr .length);
    let count = 0;
    for (let index = 0; index < fileFr .length; index++) {
        const object= fileFr [index];
        if (object.id_a && object.n_s && object.name && object.num_a && object.content) {
            client.index({
                index: 'my_index_fr',
                type: 'my_type_fr',
                id: object.id_a,
                body: object

            }, function (error, resp) {
                if (error) {
                    ret.push(error);
                    console.log(error);
                    return;
                } else {
                    ret.push(resp);
                    console.log(resp);
                    count++;
                }

            });

        } else {
            console.log(object);
            break;
        }
    }

    if(count===fileFr.length) {
        res.json(ret);
    }else {
        res.json({errors:'there is errors',ret:ret});
    }
    console.log(count);
```

--------------------------------------------------

I have 2 question: 

1. how to add my whole file with bulk without having a problem of time, with nodejs, I do not know how to do the same method of push, but with bulk (i don't want the : curl -XPOST .....)

2. the second, if I leave the program as it is I'm receiving problems of filling documents, there are still several documents that are not added, that is to say it does not add it entirely and it me also returns:
"Request Timeout after 30000ms"

**Comment by spalger** [comment]
1. The `client.bulk()` api is documented here: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-bulk

2. When you send each document in their own request, and all at the same time, some requests are going to be queued until earlier ones finish. If you have a lot of documents then the queues could get pretty backed up and cause some documents to wait for over 30 seconds, which is the default timeout. I think that you are on the right path and using bulk requests will prevent the errors you're seeing. I also think you should wait for the response before sending the next bulk request, rather than doing them all at once.
