### ISSUE TITLE
Unable to recover after an Internal Server Error

### ISSUE THREAD

**Issue by mlucool** [elastic/elasticsearch-js#652]
If I send a malformed query then I cannot send another query ever again without closing and reconnecting.

Example bad query:
```
{
    body: {
        query: {
            bool: {
                must: [
                    {
                        prefix: {
                            user: ['myuse']
                        }
                    }
                ]
            }
        }
    }
});
```

Here `[` is invalid after `user` (it expect a string string) and is causing my server to return 
```
Elasticsearch ERROR: 2018-04-18T16:15:57Z
  Error: Request error, retrying
  POST https://myurl.com/_search => Internal Server Error
```
And elastic warns:
```
Elasticsearch WARNING: 2018-04-18T16:15:57Z
  Unable to revive connection: https://myurl.com

Elasticsearch WARNING: 2018-04-18T16:15:57Z
  No living connections
```

Is there some way to avoid this required disconnect/reconnect?

**Comment by spalger** [comment]
@mlucool I don't get an "Internal Server Error" like you are, I see the following response when I send that query directly to elasticsearch:

```
Elasticsearch TRACE: 2018-04-18T20:29:08Z
  -> POST http://localhost:9200/_search?size=1
  {
    "query": {
      "bool": {
        "must": [
          {
            "prefix": {
              "user": [
                "myuse"
              ]
            }
          }
        ]
      }
    }
  }
  <- 500
  {
    "error": {
      "root_cause": [
        {
          "type": "illegal_state_exception",
          "reason": "Can\u0027t get text on a START_ARRAY at 1:45"
        }
      ],
      "type": "illegal_state_exception",
      "reason": "Can\u0027t get text on a START_ARRAY at 1:45"
    },
    "status": 500
  }
```

Also, after receiving that response valid requests are processed just fine.

That leads me to believe that you're using some sort of proxy between node.js and elasticsearch that is probably breaking when elasticsearch responds with a 500 response.

**Comment by mlucool** [comment]
FTR it was caused by https://github.com/elastic/elasticsearch-js/issues/676#issuecomment-401432612
