### ISSUE TITLE
🎉 Looking for a full-time contributor

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch-js#653]
We just opened up a position for someone to work on the JavaScript client full time here at Elastic. Checkout the job listing for more details and to apply. Your help spreading the word is also appreciated!

https://www.elastic.co/about/careers/engineering/jobs/1116390

**Comment by welkie** [comment]
I hope whoever ended up in this role knows about TypeScript. I'd love to see more of the libraries I regularly use switch to TypeScript so that there's no need for DefinitelyTyped to create types for them. The experience with libraries that bundle their own types is great. :)

**Comment by kblcuk** [comment]
Wonder if this is still valid, since that job posting points to 404.

**Comment by delvedor** [comment]
Hi! I'm the new maintainer of this module :)

@kblcuk you are right, this can be closed :)
@welkie the library will be written in plain js, but I do agree that we should provide typings along the client instead of relying on DefinitelyTyped.
