### ISSUE TITLE
Suggestion: option to disable custom client logging

### ISSUE THREAD

**Issue by Mayhem93** [elastic/elasticsearch-js#672]
Hello guys,

I've been using the ES client library since ES 1.7 and I've always wanted to know why can't you just make the library silent and not log out errors.

For example i'm using this client in my https://github.com/Mayhem93/telepat-models/tree/improvement/functional-tests repo and it has its own logging format and error messages.

I am already receiving error messages, which is enough for my application to handle them and display accordingly.

**Comment by spalger** [comment]
If you set the `log` config value to something falsey it won't log.

```js
const client = new elasticsearch.Client({
  log: false
})
```
