### ISSUE TITLE
Type error elasticsearch.client.suggest not a function on 15.0

### ISSUE THREAD

**Issue by laxmipsarva** [elastic/elasticsearch-js#674]
Recently we upgraded elastic search to 6.x and node module to 15.0. one of the function elasticsearch.client.suggest which used to work on elasticsearch-js@11.0 is not working on elasticsearch-js@15.0.

**Comment by spalger** [comment]
Elasticsearch-js 15 has a default apiVersion of 6.2, which doesn't have the `suggest` method anymore. Make sure you include the [`apiVersion`](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html#config-api-version) in your config to specify what version of the API you need based on your elasticsearch version.
