### ISSUE TITLE
No living connections to Elastic Cloud GCP cluster from firebase cloud function

### ISSUE THREAD

**Issue by sophiaxu8** [elastic/elasticsearch-js#675]
User try to use elasticsearch.js from Google Cloud Functions firebase  to connect to Elastic cloud cluster xxxxxx on GCP and got "No Living connection" error.

 Try  `curl -k -u ""prod_db:<pwd of the user>" https://<user- instance>.us-west1.gcp.cloud.es.io:9243`  and that is working fine.
User would like to confirm if the elasticsearch.js he use is correct: (firebase support tell him this is not a firebase issue )

Here is the code he used from Firebase:
```javascript
ES Properties set in env of Firebase Cloud

"elasticsearch": {
"es_hosturls_0": "https://<bizrec instance>.us-west1.gcp.cloud.es.io",
"api_version": "6.2",
"es_auth": "prod_db:<pwd of the user>",
"es_port": "9243",
"es_protocolt": "https",
"es_log": "trace"
},

The initialising connection using Elasticsearch.js in index.js of Firebase cloud functions:

/***** ELASTICSEARCH SERVER CLIENT Settings using Firebase config:set Env params ***********/
const auth = functions.config().elasticsearch.es_auth;
const port = functions.config().elasticsearch.es_port;
const protocol = functions.config().elasticsearch.es_protocolt;
const log = functions.config().elasticsearch.es_log;
const api_version = functions.config().elasticsearch.api_version;
const hostUrls = [
functions.config().elasticsearch.es_hosturls_0
//functions.config().elasticsearch.es_hosturls_1,
//functions.config().elasticsearch.es_hosturls_2,
//functions.config().elasticsearch.es_hosturls_3
];
const hosts = hostUrls.map(function(host) {
return {
protocol: protocol,
host: host,
port: port,
auth: auth,
log: log,
apiVersion: api_version
};
});

const esClient = new elasticsearch.Client({
hosts: hosts
});`
```

**Comment by spalger** [comment]
Based on the example the `elasticsearch.es_hosturls_0` config includes the protocol information, but then they are transforming that into an object and specifying it as purely a host id (which would be just the `<bizrec instance>.us-west1.gcp.cloud.es.io` part). Removing the lines that map the `hostUrls` and just passing that as the `hosts` config to `elasticsearch.Client()` should fix the problem.

**Comment by sophiaxu8** [comment]
Thanks @spalger
