### ISSUE TITLE
Connector Callback

### ISSUE THREAD

**Issue by mlucool** [elastic/elasticsearch-js#676]
Hi,

The documentation doesn't say exactly what the [request callback](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/transport-reference.html#_request_params_callback) should expect. In my extension, superagent-elasticsearch, I only returned [cb(err, text)](https://github.com/mlucool/superagent-elasticsearch/blob/master/src/SuperagentConnector.js#L76), but I see [elsewhere](https://github.com/elastic/elasticsearch-js/blob/master/src/lib/connectors/http.js#L165) it can take cb(err, text, status, headers). 

When should the err parameter be defined? If the request was invalid (i.e. status 400 or 500 [example](https://github.com/elastic/elasticsearch-js/issues/652#issuecomment-382519403)), but elastic did return something, should err be defined? If not, under what conditions is it defined?

Also, can the expected types for status and headers be clarified somewhere.

Thanks!

**Comment by spalger** [comment]
The callback that the connections receive is defined here: https://github.com/elastic/elasticsearch-js/blob/9c98262b871f860afccc04f8025c35c45aea2281/src/lib/transport.js#L230

If the connection responds with an error it is assumed that the connection was unable to talk to elasticsearch. If a response from elasticsearch is received, regardless of the status code, it should not be converted into an error. The client does additional error checking and will format a unified error format when the status code indicates an error.

Errors from connections also trigger retries in certain cases and will cause the connection to be put in the "dead connection" pool until it is needed again or responds correctly to a ping.

The status should be a number if defined, and the headers a map of header names to values with all the header names lower-cased, like node's `'http'` module does.

I realize this information isn't really documented anyway, does it make sense to you? If you wouldn't mind I'd be happy to work with you on a PR to better explain this in the docs somewhere.

**Comment by mlucool** [comment]
Thanks - this is much clearer. I'll update [superagent-elasticsearch](https://github.com/mlucool/superagent-elasticsearch) with this. Please update the docs and I can comment if that is clearer to an end user.
