### ISSUE TITLE
Angular 6 process.nextTick is not a function

### ISSUE THREAD

**Issue by fercaveri** [elastic/elasticsearch-js#681]
Hi there, i'm using a proyect with angular 6 and elasticsearch.

When i call some of the elasticsearch functions (search, index) it's trhowing me a console error
![image](https://user-images.githubusercontent.com/26494305/42658573-1565af6e-85fc-11e8-9f34-b756dbd4951d.png)

With angular 5 it's working fine

{
  "name": "ecs-s3-ui",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build-prod": "ng build --base-href=/pierpoc/ --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "jasmine": "jasmine-ts \"spec/**/*.spec.ts\""
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/core": "^0.6.3",
    "@angular/animations": "^6.0.9",
    "@angular/cdk": "^6.0.9",
    "@angular/common": "^6.0.9",
    "@angular/compiler": "^6.0.9",
    "@angular/core": "^6.0.9",
    "@angular/forms": "^6.0.9",
    "@angular/http": "^6.0.9",
    "@angular/material": "^6.3.3",
    "@angular/platform-browser": "^6.0.9",
    "@angular/platform-browser-dynamic": "^6.0.9",
    "@angular/router": "^6.0.9",
    "aws-sdk": "^2.117.0",
    "bootstrap": "^3.3.7",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.7",
    "elasticsearch": "^15.1.0",
    "ng-pick-datetime": "~5.0.0-beta.11",
    "ngx-dropzone-wrapper": "^4.6.6",
    "ngx-ui-switch": "^1.4.4",
    "rxjs": "^6.2.1",
    "rxjs-compat": "^6.2.1",
    "web-animations-js": "^2.3.1",
    "webpack": "^4.4.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^5.2.4",
    "@types/elasticsearch": "^5.0.24",
    "@types/filesystem": "0.0.28",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^10.5.2",
    "codelyzer": "^4.4.2",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "jasmine-ts": "^0.2.1",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.9.0",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "^5.10.0",
    "typescript": "^2.7.2"
  }
}

Please help me
Thanks!

**Comment by fercaveri** [comment]
just realized that CLI 6 doesn't support anymore some NPM global variables

**Comment by torabshaikh** [comment]
@fercaveri Hey, Did you find a workaround for this issue? I am getting this error while decompressing data compressed on the server. I am using zlib to do this. Please advise if you have some advice for me.

**Comment by Lusey77** [comment]
Little late but I was able to fix this issue by install an npm package next-tick and then within the polyfill.ts file adding this little snippet to satisfy some of the globals that would normally exist in a node.js environment

```
(window as any).global = window;
global.Buffer = global.Buffer || require('buffer').Buffer;
global.process = {
  env: { DEBUG: undefined },
  version: [],
  nextTick: require('next-tick')
} as any;
```

For me however this only kicked the problem down the road because the real issue is that you are using a package that was intended to be used on a node.js server and are instead using it within an Angular application.
