### ISSUE TITLE
Cannot change request type from POST to GET to search

### ISSUE THREAD

**Issue by Charleess** [elastic/elasticsearch-js#683]
When using the `client.search()` method with a body, the client always sends a `POST` request to the server. However, for security purposes, one could need to deny all requests except `GET` to their server.

The API states that both `GET` and `POST` can be used to search the stack. Is there a setting somewhere to switch between the two behaviours ?

**Comment by spalger** [comment]
Nope, unfortunately Node.js and all major browsers don't allow sending GET requests with bodies.
