### ISSUE TITLE
Terrible Documentation for "bulk" Method

### ISSUE THREAD

**Issue by tecfu** [elastic/elasticsearch-js#686]
I'm attempting to use the **bulk** method, and I'm using the documentation found here: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html

I created this issue due to the comments found in the example given there, which I've appended below. 

> client.bulk({
>   body: [
>     // action description
>     { index:  { _index: 'myindex', _type: 'mytype', _id: 1 } },
>      // the document to index
>     { title: 'foo' },
>     // action description
>     { update: { _index: 'myindex', _type: 'mytype', _id: 2 } },
>     // the document to update
>     { doc: { title: 'foo' } },
>     // action description
>     { delete: { _index: 'myindex', _type: 'mytype', _id: 3 } },
>     // no document needed for this delete
>   ]
> }, function (err, resp) {
>   // ...
> });

These comments not only fail to add descriptive value to the example, they also create confusion.

[1] There are 5 elements in the array and 6 comments. Which comment is associated with which element? 

[2] After studying the array in this example it appears that each element contains one of two types of statements. One type of statement selects a document, and one type of statement commits operations against a document. Please convey that idea more succinctly.

[3] Remove "action description" comments. This is useless. All of these array elements are an action. 

>     // action description
>     { index:  { _index: 'myindex', _type: 'mytype', _id: 1 } },

[4]  No document needed for this delete? So we can delete a document without needing a document? What? 

>     { delete: { _index: 'myindex', _type: 'mytype', _id: 3 } },
>     // no document needed for this delete

---
This is really, really disappointing and the issue needs to be raised. I'm don't know your product well enough to issue you a PR to fix your docs, but I really hope that you guys will do better in the future.

**Comment by welkie** [comment]
I don't think the documentation is bad.

The basic documentation for each Elasticsearch API is in the main reference section. The JavaScript client documentation even tells you at the top of each API to go there for the main documentation. If it didn't they'd have to repeat it for each client. It says:

> Perform many index/delete operations in a single API call. Check the API Conventions and the Elasticsearch docs for more information pertaining to this method.

Then, if you follow that link, you get all the information you need about the Bulk API.

> The possible actions are index, create, delete and update. index and create expect a source on the next line, and have the same semantics as the op_type parameter to the standard index API 

The expectation is that as someone familiar with JavaScript, the minimal comments in the JavaScript client example would be enough for you to understand how to link what you know about the Bulk API with what you know about doing things in JavaScript.

**Comment by abdulrahman-khankan** [comment]
I agree that it needs improvements, but the best thing about it is that anyone can edit the documentation and send a pull request to update it 🙂

**Comment by delvedor** [comment]
> Been using elasticsearch.js for a few weeks. Have looked at the docs a couple of dozens times. Not once have I been clear on what I was supposed to do after reading the docs

Hello @jackpilowsky! Please open a new issue in https://github.com/elastic/elasticsearch-js-legacy if you require assistance :)
