### ISSUE TITLE
Socket hang up on AWS Lambda

### ISSUE THREAD

**Issue by paidit-app** [elastic/elasticsearch-js#688]
We recently started logging from our `nodejs8.10` AWS lambda function to an elasticsearch cluster we set up. It seems the logging itself works, but **2 problems** occur as a result:
1. When working locally, after several seconds of running the function, the following error is logged to the console:
`uncaughtException: socket hang up Error: socket hang up`
2. When trying to deploy the service, the deployment fails pretty quickly. Initially the deployment throws warnings like: `WARNING: Function sanity has timeout of 300 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.` and finally it crashes completely with the aforementioned `Error: socket hang up`.

In addition, we have to mention that upon commenting out the _elasticsearch_ require statement, the function started working as expected. We also tried different client configuration flags and other solutions suggested by similar issues here, but nothing worked. Since it seems our environment wasn't discussed yet, we decided to open a separate issue for our case. We would appreciate any help in the matter.

**Comment by austinkelleher** [comment]
I'm also seeing socket hangup errors in AWS Lambda. Did you ever figure it out @paidit-app?

Trace:

```
Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketCloseListener (_http_client.js:363:23)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at _handle.close (net.js:567:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7)
```

/cc @spalger
