### ISSUE TITLE
NullInjectorError: No provider for Client!

### ISSUE THREAD

**Issue by roshanponnappa** [elastic/elasticsearch-js#690]
this is similar to #663 , i am using the exact same setup, with elasticsearch-browser,
However, 
- I am using the Angular 6.1.0
- The below is the error i am getting

> ERROR Error: StaticInjectorError(AppModule)[ElasticsearchService -> Client]: 
>   StaticInjectorError(Platform: core)[ElasticsearchService -> Client]: 
>     NullInjectorError: **No provider for Client!**
>     at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (VM20 vendor.js:32146)
>     at resolveToken (VM20 vendor.js:32384)
>     at tryResolveToken (VM20 vendor.js:32328)
>     at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (VM20 vendor.js:32225)
>     at resolveToken (VM20 vendor.js:32384)
>     at tryResolveToken (VM20 vendor.js:32328)
>     at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (VM20 vendor.js:32225)
>     at resolveNgModuleDep (VM20 vendor.js:39460)
>     at _createClass (VM20 vendor.js:39505)
>     at _createProviderInstance (VM20 vendor.js:39477)

Please let me know if anyone has found a solution to this.

**Comment by roshanponnappa** [comment]
This now works with the newer version of 'elasticsearch-browser'

**Comment by sakshi30** [comment]
Hey, 
I am still stuck on the same issue. Could you let me know how you resolved the same?
PS. I am using elasticsearch-browser too

**Comment by delvedor** [comment]
Hello! In this repository, you can find the new version of the JavaScript client, if you need the legacy one, you can find it in [elastic/elasticsearch-js-legacy](https://github.com/elastic/elasticsearch-js-legacy).

Although, we highly discourage the use of the client in the browser, since it exposes you to security risks and it is an anti-pattern.
We are no longer supporting it.
