### ISSUE TITLE
request [/.kibana] contains unrecognized parameter: [feature]

### ISSUE THREAD

**Issue by Akaren13** [elastic/elasticsearch-js#691]
After installing (npm install --save elasticsearch) I got an error in Kibana

`plugin:elasticsearch@6.1.1 | [illegal_argument_exception] request [/.kibana] contains unrecognized parameter: [feature]`

ELK 6.1.1
Installation was successful, only warnings of optional dependency

`lodash.isempty@4.4.0 node_modules/lodash.isempty lodash.trimend@4.5.1 node_modules/lodash.trimend kibana@6.1.1 /usr/share/kibana └─┬ elasticsearch@15.1.1 ├─┬ agentkeepalive@3.5.1 │ └── humanize-ms@1.2.1 └── lodash@4.17.10 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/ch okidar/node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@ 1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"} ) npm WARN kibana@6.1.1 No license field.`

**Comment by spalger** [comment]
@Akaren13 I'm not sure what's going on here, are you writing a Kibana plugin? Where are you installing elasticsearch with `npm install --save elasticsearch`? In the Kibana repo?

**Comment by Akaren13** [comment]
user/share/kibana

Yes, I want to get data from elasticsearch to my js code

**Comment by spalger** [comment]
I recommend checking out the kibana plugin generator here: https://github.com/elastic/kibana/tree/master/packages/kbn-plugin-generator

Kibana supports developing plugins against the development version of Kibana, not in the distributable installation. Please give that a shot and file issues in the [kibana repo](http://github.com/elastic/kibana) if you run into issues in the process! 😁
