### ISSUE TITLE
Accessing HTTP Status Code - Async/Await

### ISSUE THREAD

**Issue by Johnb21** [elastic/elasticsearch-js#693]
I am using the async/await method to get my response back from the client. However, I cannot figure out a method to retrieve the HTTP Status code of the response. Here is a snippet of what I am doing and what is being returned:

```
const response = await client.search({
          index: 'bonus',
          body: {
            'query': {
              'range': {
                'payment_date': {
                  'gt': '2018-05-01',
                },
              },
            },
            'ag': {
              'group_by_bonus_program': {
                'terms': {
                  'field': 'bonus_program.keyword',
                  'order': {
                    'total_amount': 'desc',
                  },
                },
                'aggs': {
                  'total_amount': {
                    'sum' : {
                      'field': 'amount',
                    },
                  },
                },
              },
            },
            'size': 0,
          },
        })
```

and here is a response:

```
{ took: 5,
  timed_out: false,
  _shards: { total: 5, successful: 5, skipped: 0, failed: 0 },
  hits: { total: 7409, max_score: 0, hits: [] },
  aggregations:
   { group_by_bonus_program:
      { doc_count_error_upper_bound: 0,
        sum_other_doc_count: 0,
        buckets: [Array] } } }
```

There is nothing in here that allows me to see the http status code. Any ideas on how to access this?

**Comment by delvedor** [comment]
Currently, if you are using *async-await* or standard promises, you can't access the response's status code, as stated in our [api conventions](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-conventions.html).

@spalger can you confirm?
I think that in the next major we should return an object as following:
```js
{
  body: Object,
  statusCode: Number
}
```
So the api will become:
```js
client.search({ ... }, (err, response) => {})

client.search({ ... })
  .then(response => {})
  .catch(err => {})

const response = await client.search({ ... })
```

**Comment by delvedor** [comment]
I'm open to both solutions, but we should choose one for the sake of API consistency IMHO.

**Comment by Johnb21** [comment]
@spalger with any `API` you generally get an HTTP Status code back which can allow you to take certain actions based on the status code. Not to mention the status code will generally provide at least some type of information as to what happened during an HTTP request.

If you added `{body, statusCode}` to the Client return, that wouldn't interrupt the usage for anyone that isn't using the status code as it would ultimately depend on the user to include it into their project and decide what they would like to do (if anything) with said response. 

Normally, a 200 response would just indicate that you can proceed with everything else and that status can be included into your project that might be an API itself to return to its front end. However, I don't want to have to cook up my own presumed status codes based on the the `_shards` or `timed_out` items in the current response. I believe that if some errors occurred during an HTTP request, that should be part of the response. An deletion, update, etc would be elasticsearch specific and not HTTP. If I attempt to make a call to a host  or index that does not exist though, I would expect to get a 404 response code.

**Comment by Johnb21** [comment]
Sorry guys - I am not trying to flood this thread, and I know that this is nothing 'official' but these are the standards I am used to seeing with HTTP Requests:

http://jsonapi.org/format/#fetching-resources-responses

**Comment by spalger** [comment]
I understand what HTTP status codes are, and I agree that in general they are useful, but i'm trying to understand how you intend to make use of them as to justify changing the promise interface we've been using for the client since 2013.

> Normally, a 200 response would just indicate that you can proceed with everything else and that status can be included into your project that might be an API itself to return to its front end. However, I don't want to have to cook up my own presumed status codes based on the the _shards or timed_out items in the current response.

It sounds like you're trying to reuse elasticsearch's status code in your API, is that correct? If that was available to the front end, can you help me understand how that would be useful? What is a decision you would make based on the status code? You already know if things went alright or not based on the promise resolving or rejecting, what value would the status code give you if the promise resolved?

**Comment by spalger** [comment]
If you try to make a request to a host that does not exist, that's not going to be a 404 response, because there is no response if there is no host to talk to. But you will get a special type of error back, the `NoConnections` error because the client was unable to connect to any of the elasticsearch nodes you specified: https://github.com/elastic/elasticsearch-js/blob/master/src/lib/errors.js#L53-L56

**Comment by delvedor** [comment]
The new client that has just landed in master might have what you need, check it out! :)
