### ISSUE TITLE
Stable JSON stringify to avoid cache misses

### ISSUE THREAD

**Issue by daedalus28** [elastic/elasticsearch-js#695]
It looks like this lib [is using JSON.stringify](https://github.com/elastic/elasticsearch-js/blob/master/src/lib/serializers/json.js#L24-L26) on requests. Per [the elasticsearch query cache docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html#_cache_key):
> if the JSON changes — for instance if keys are output in a different order — then the cache key will not be recognised.

This means that if we make requests to the elasticsearch client with objects where the keys are not created in the exact same order, we can't take advantage of the request cache. My unstanding is that these two would not be the same from the cache's perspective:

```js
await client.search({
  index: 'twitter',
  type: 'tweets',
  body: {
    query: {
      match: {
        body: 'elasticsearch'
      }
    }
  }
})
```

vs

```js
await client.search({
  type: 'tweets',
  index: 'twitter',
  body: {
    query: {
      match: {
        body: 'elasticsearch'
      }
    }
  }
})
```

If we switch to any of [these libs](https://www.npmjs.com/search?q=stable%20stringify), we could make sure the request cache is hit more often. If it's much slower, maybe we could make it a config option for the client (e.g. `stableStringify: true`)?

**Comment by spalger** [comment]
Yeah, that could happen, but in your example the cache would still be used since only the keys within the body are relevant.

If you want to try out one of these libs you can specify a custom serializer in the config like so:

```js
import DefaultJsonSerializer from 'elasticsearch/src/lib/serializers/json';
import jsonStableStringify from 'json-stable-stringify';

class CustomSerializer extends DefaultJsonSerializer {
  serialize(val, replacer, space) {
    return jsonStableStringify(val, { replacer, space })
  }
}

const client = new elasticsearch.Client({
  serializer: CustomSerializer
})
```

Interested to hear what your experience is, if the potential overhead of a slower serializer is beneficial in the long run for potentially faster querying. I think it would be pretty surprising for JSON bodies from a single application to not always be sent in the same order, but I can imagine the potential in your specific use case.

**Comment by daedalus28** [comment]
Great point about it only being props in the body object, I should have provided a better example 😄

I think any situation in which you can dynamically add or remove filters would likely be affected by this, which I would think includes kibana. In our case, the cost of a few extra milliseconds on serialization is much cheaper than a potential cache miss on our index (which could take a few seconds under peak load, but that's a different story). And while I have not done any benchmarking to back it up, I would suspect that serialization is typically a small part of the execution time even in the general case which might make it a reasonable default.

Either way - I wasn't aware that the client could take a custom serializer. That is 100% sufficient for our use case and definitely seems like something that should be added to the docs. It's better than providing a boolean flag since it allows experimenting with specialized serializers (e.g [fast-stable-stringify](https://www.npmjs.com/package/fast-stable-stringify) over the substack one). Our workaround in the mean time was to do a stable stringify and then a JSON.parse before passing a payload to the elasticsearch client, but this is much better!

I'd be happy to create a PR for the docs - is it just [this file](https://github.com/elastic/elasticsearch-js/blob/master/docs/configuration.asciidoc)? Would a docs only change warrant a version bump (e.g. for CI)?

**Comment by delvedor** [comment]
I would love to see a benchmark about this :)

**Comment by daedalus28** [comment]
Sorry for the delayed response - That's fair, but might be another example where being able to have a custom serializer strategy is worth documenting. If you know you have dynamically changing filters, you might choose to consistently sort the filters by field or something like that. In our case, a cache miss is a pretty expensive thing (we've seen 10+ seconds for some queries) so it's certainly something we're going to explore.

The functionality is all there so there's no code changes needed. Are you open to a PR updating the docs to just add this to the list of configuration options?

**Comment by spalger** [comment]
For sure, that'd be great. Thanks @daedalus28!
