### ISSUE TITLE
Error while searching string with mixed characters Uppercase and Lowercase

### ISSUE THREAD

**Issue by GobindaGobinda** [elastic/elasticsearch-js#696]
I found that when we run the search query for string which has Uppercase and Lowercase characters, it failed to return the correct records while using this npm package.  Anyone faced the problem. 
So, changing the string to lowercase before search solved the problem. 
Can that be changed in the package, so that its easier for other users. 
spent a long time to track down  this problem in system that had 10 machines.

**Comment by delvedor** [comment]
Hi! Can you paste a reproducible example?

**Comment by GobindaGobinda** [comment]
![elasticsearchapierror](https://user-images.githubusercontent.com/20100080/44947920-7ca1e900-ade2-11e8-879f-6e58aa9f20ba.png)

**Comment by GobindaGobinda** [comment]
Hey, Upon further going deep to the problem. Looks like the problem is from the Elastic Search itself. Not this npm api. 
Upon sending the curl request to get data by matching exact query as created in the client.search  i.e bool, match, field. 
It failed to return the correct results with uppercase chars. 
![errorcorrection](https://user-images.githubusercontent.com/20100080/44950751-281c5f00-ae1e-11e8-80e5-f8762984441c.png)

**Comment by delvedor** [comment]
You are using the `term` API which finds documents that contains an exact match of the term you are specifying. This means that `Foo` is different than `foo` or `FOO`.

If the field you are searching is a `keyword` field, I suggest you to lowercase the value before adding it to elasticsearch and lowercase the value before search for it.
If the field is a `text` field, you should try the `match` API, which will handle this cases for you (be aware that if you use the `match` API in a `keyword` field, it will behave like `term`).

I suggest you to checkout our [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/query-dsl-term-query.html) regarding this topic :)
