### ISSUE TITLE
Specifying the type of HTTP method while making an elastic search request.

### ISSUE THREAD

**Issue by dilagurung** [elastic/elasticsearch-js#698]
As given in the document, all the node clients make POST request. I came up with a requirement where I am supposed to make GET request like URL : http://ip:9200/job/_search?q=DevOps. Though I know the result can be met by DSL query, still I want to know as if there is any way the GET request can be made.

**Comment by spalger** [comment]
If you're request includes a body it can't be sent with GET, node.js and the browser don't allow it.
