### ISSUE TITLE
Surface non-JSON errors transparently, useful for proxies

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch-js#701]
When users have Elasticsearch behind a proxy, that proxy can respond with unexpected responses containing non-JSON bodies, e.g. a 50x error could return an error page (https://github.com/elastic/kibana/issues/22355). Currently, the error is opaque because the elasticsearch-js client tries to parse the HTML as JSON, fails, and responds with a 200 but an empty body. Instead, we should return with an error that contains the original response from the Elasticsearch endpoint as well as any related errors, e.g. a parsing error.

**Comment by delvedor** [comment]
Hi! I will investigate into this, thank you for reporting!

**Comment by delvedor** [comment]
As discussed during a meeting, in the [next](https://github.com/elastic/elasticsearch-js/tree/next) version of the client we will expose all this info, inside the error object if is an errored response or behind a symbol in the body.

**Comment by delvedor** [comment]
The new client has been released! 🎉

**Comment by cjcenizal** [comment]
Thanks @delvedor! How difficult would it be to fix this in the old client? Because it might take a long time for Kibana to migrate to the new client, I wonder if it's possible to patch this in the meantime.
