### ISSUE TITLE
Pagination in Completion Suggestor

### ISSUE THREAD

**Issue by dilagurung** [elastic/elasticsearch-js#703]
On text based search, elastic engine supply parameters called "from " and "size" to paginate over result but same is not supported when using completion/suggestion based search. Is it intentionally restricted by Elastic team or should it to be part of enhancement?

**Comment by delvedor** [comment]
Hello!
This issue tracker should be used only for questions or issues related to the JavaScript client. If you have general questions about Elastic I suggest you use our fantastic forum, where your question will probably help others as well :)

https://discuss.elastic.co/
