### ISSUE TITLE
How to make plain request?

### ISSUE THREAD

**Issue by impguard** [elastic/elasticsearch-js#714]
This might be a dumb question, but is there a way to leverage the client to make a raw HTTP request?

That is, leveraging all the built in support for handling secrets, credentials, etc. but performing a raw request to some elastic endpoint?

The use case is needing to create essentially a proxy, and trying to avoid creating a separate "elastic client" of my own that handles the same thing this client handles for arbitrary user queries. I want to enable all API endpoints to the user, so they can hit the service as if it was an elastic instance, without needing to worry about credentials etc.

**Comment by spalger** [comment]
You can use the [`client.transport.request()`](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/transport-reference.html#_request_params_callback) function to do just that.
