### ISSUE TITLE
[Questions] usage of elasticsearch-js client 

### ISSUE THREAD

**Issue by lfoppiano** [elastic/elasticsearch-js#719]
Hi, I'm trying to create a project to index some massive amount of data, in particular I would like to initialise the client, then delete the index and create it. I've just started to try to understand the principles but I feel I'm missing something important here. 

I'm getting some random errors (not always): 
```
(node:54635) UnhandledPromiseRejectionWarning: Error: [index_not_found_exception] no such index, with { index_uuid="IpeBMhQ5RFGVxEPK9H5VlQ" & index="crossref" }
    at respond (/Users/lfoppiano/development/..../matching/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/Users/lfoppiano/development/.../matching/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/Users/lfoppiano/development/.../matching/node_modules/elasticsearch/src/lib/connectors/http.js:165:7)
    at IncomingMessage.wrapper (/Users/lfoppiano/development/.../matching/node_modules/lodash/lodash.js:4935:19)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
(node:54635) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:54635) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here is what I'm doing:  
```
const elasticsearch = require('elasticsearch');

var client = new elasticsearch.Client({
    // hosts: ['localhost:9200', 'localhost:9201'],
    host: 'localhost:9200',
    log: 'error',
    keepAlive: true
    // sniffOnConnectionFault: true,
    // sniffOnStart: true,
    // sniffInterval: 300,
    // suggestCompression: true
});

function print(body) {
    process.stdout.write(body + "\n");
}

//Test connection
client.ping({
    requestTimeout: 30000,
}).then(function (body) {
    print("Cluster alive");
}, function (error) {
    print("Cannot contact cluster: " + error);
});

client.indices
    .delete(
        {
            index: "index_name",
            ignore: [404]
        },
        function (error, response) {
            if (error) {
                print("Error deleting index: " + error)
            }
        }
    );

client.indices
    .create(
        {
            index: 'index_name',
            ignore: [404, 400]
        },
        function (err, resp) {
            if (err)
                print('Failed to create ElasticSearch index, ' + err.message);
            else
                print('Successfully created ElasticSearch index');
        }
    );
```

I'm really confused, what's the problem with the Promise? should I try-catch the promise? Or it's two functions? 

I get error on the creation of the index, why is that? How can I make sure I call the create only after the delete has terminated? 

Thank you in advance

**Comment by delvedor** [comment]
In the first example, you are using the client before instantiating it, while in the second example you are running both calls concurrently.
Can you share the full snippet of code and environment so I can try to reproduce it?

**Comment by lfoppiano** [comment]
@delvedor sorry, I've pasted everything in the wrong order. I've edited the message. 

What you mean I'm running both calls concurrently? You mean the `delete` and `create`? I've also tried to use `await` in front of them, but I get the error `SyntaxError: await is only valid in async function`. 

I'm sorry I believe these problems are most likely due to my lack of knowledge on the subject

**Comment by delvedor** [comment]
Node.js (and JavaScript) is an asynchronous mono-thread language, this means that any asynchronous operation will run concurrently.
In your code, you are running three requests without waiting for the result of the previous one.

You can do that in three ways:

**callbacks**
```js
client.indices.delete({ ... }, (err, body) => {
  if (err) return console.log(err)
  client.indices.create({ ... }, (err, body) => {
    if (err) return console.log(err)
    console.log('done')
  })
})
```

**promises**
```js
client.indices.delete({ ... })
  .then(body => {
    return client.indices.create({ ... })
  })
  .then(body => console.log('done'))
  .catch(console.log)
```

**async-await** (which is just another way to write promises)
```js
async function run () {
  try {
    await client.indices.delete({ ... })
    await client.indices.create({ ... })
    console.log('done')
  } catch (err) {
    console.log(err)
  }
}

run()
```

> I'm sorry I believe these problems are most likely due to my lack of knowledge on the subject

It may be, in case you feel that you need to deepen your knowledge or the language and the platform I highly recommend you the following resources 😄 
- [nodeschool](https://nodeschool.io/#workshopper-list)
- [MDN](https://developer.mozilla.org/en-US/#)

**Comment by lfoppiano** [comment]
Thanks @delvedor 👍
