### ISSUE TITLE
No support for xpack graph

### ISSUE THREAD

**Issue by dllz** [elastic/elasticsearch-js#720]
Hi everyone. 
I am not sure if I just cannot find it but it seems that the client does not support any requests for the explore api. 

If it does have support would someone please point me in the right direction

**Comment by spalger** [comment]
You're right that there isn't explicit support for the xpack apis, but you can use the [`client.transport.request()`](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/transport-reference.html#_request_params_callback) to send arbitrary requests to elasticsearch nodes, paired with the docs for graph this should allow you to use the client to talk to the graph API.
