### ISSUE TITLE
contains unrecognized parameters.why?

### ISSUE THREAD

**Issue by Yangk030208** [elastic/elasticsearch-js#722]
#### I use these codes to run separately as scripts,these codes are perfect.. But when I integrate into a web project, whenever there's a new request coming in, it's a mistake, and I'm depressed.

+ OS :Mac 10.14.1 Beta  
+ java : 1.8 
+ node: 9.8.0
+ ES: 6.4.0

![image](https://user-images.githubusercontent.com/23301914/47844188-b2704780-ddfc-11e8-851c-ba3f0b397701.png)

#### this is my code 
```js
let isInit = false ;
const esTool = {};
let esClient = null ;

esTool.search = async(kw)=>{
    const response = await esClient.search({
        index: conf.es.index,
        q: 'title:'+kw
    });
    return response || "none";
};

esTool.init = ()=>{
    if(isInit){return ;}
    let esAddress = `${conf.es.host}:${conf.es.port}`;
    esClient = new elasticsearch.Client({
        host: esAddress
    });
    isInit = true ;
};
(async()=>{
    esTool.init();
    await esTool.search("北京");
})();
```

**Comment by spalger** [comment]
Are you sure that's the exact code that produces this error? The only way that would be possible is if `esClient.search()` was called with the symbols listed in the error as a string.

**Comment by Yangk030208** [comment]
#### Thank you very much for your answer. There are other mistakes in my code. I'm sorry. @spalger
