### ISSUE TITLE
how to abort prior search 

### ISSUE THREAD

**Issue by dfy167** [elastic/elasticsearch-js#725]
It's normal use at a map search input.
when input changed i want to get the last response. 
but some time the prior search return latest ，and replace the last request result.

**Comment by delvedor** [comment]
Every API call returns an object which contains the `abort` method :)
Be aware that calling `abort` will close the http request, but will not prevent Elasticsearch to do its work.
If you want you can also use the `timeout` parameter to tell to ES to do not spend too much time working on that specific request.
