### ISSUE TITLE
How to restrict only for one shard at the time of creation of new Index?

### ISSUE THREAD

**Issue by himanshuteotia** [elastic/elasticsearch-js#726]

**Comment by delvedor** [comment]
You should configure it in the body of the API call, as documented [here](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/indices-create-index.html) :)

**Comment by himanshuteotia** [comment]
But how do I add in npm package configuration, This is my code :

const client = new elasticsearch.Client({ host: { host, port } })
await client.indices.create({ index })

**Comment by delvedor** [comment]
As you can see in the [docs](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/15.x/api-reference.html#api-indices-create) you just need to pass the body to the API method.

```js
client.indices.create({
  index: 'my-index',
  body: {
    settings: {
      index: {
        number_of_shards: 1, 
        number_of_replicas: 1 
      }
    }
  }
}, console.log)
```

**Comment by himanshuteotia** [comment]
Thanks
