### ISSUE TITLE
"Invalid Host" error when running in the browser

### ISSUE THREAD

**Issue by MichaelAnckaert** [elastic/elasticsearch-js#729]
I'm trying to get elasticsearch-js working in a browser application using the http-aws-es library. My code is currently looking like this but I'm getting a "TypeError: invalid host" in the browser console. 

`
      let AWS = require('aws-sdk')

      let options = {
        hosts: ['https://my-es-host.es.amazonaws.com'],
        connectionClass: require('http-aws-es'),
        awsConfig: new AWS.Config({
          credentials: new AWS.Credentials('AKA...', 'secret'),
          region: 'eu-central-1'
        }),
        httpOptions: {}
      }

      let es = require('elasticsearch-browser').Client(options)

      es.ping({
        requestTimeout: 30000
      }, function (error) {
        if (error) {
          console.error('elasticsearch cluster is down!')
        } else {
          console.log('All is well')
        }
      })`

Did anyone get a similar setup working in the browser and what am I doing wrong? I did some debugging and it seems that the check in ConnectionAbstract is failing: 
`
function ConnectionAbstract(host, config) {
  config = config || {};
  EventEmitter.call(this);

  this.log = config.log || new Log();
  this.pingTimeout = config.pingTimeout || 3000;

  if (!host) {
    throw new TypeError('Missing host');
  } else if (host instanceof Host) {
    this.host = host;
  } else {
    throw new TypeError('Invalid host');
  }
  utils.makeBoundMethods(this);
}
`

**Comment by swbradshaw** [comment]
I had the same problem. In my Angular client I was also using elasticsearch-browser and http-aws-es.  I was able to get it working by removing elasticsearch-browser and using elasticsearch.  Those 2 libraries are conflicting because your Host class in one is not the same as the Host class in the other.
