### ISSUE TITLE
mapper_parsing_exception: unsupported parameter [enabled : false]

### ISSUE THREAD

**Issue by simon-tannai** [elastic/elasticsearch-js#738]
Hi ! :) 

Version: 15.2.0

I'm trying to use this option: https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html

But I got an error from mapper parsing: `[mapper_parsing_exception] Mapping definition for [seo_description] has unsupported parameters:  [enabled : false]`

putMapping: 
```js
res = await elasticClient.indices.putMapping({
  index: 'cm',
  type; 'product',
  body: {
    properties: mapping,
  },
})
```

The mapping definition:
```json
{
	"id": {
		"type": "keyword"
	},
	"category_id": {
		"type": "text"
	},
	"category_label": {
		"type": "text",
		"copy_to": "feature_search"
	},
	"sibling_id": {
		"type": "text"
	},
	"seo_description": {
		"type": "text",
		"enabled": false
	}
}
```

**Comment by mstruve** [comment]
I am seeing this as well with Elasticsearch version 6.3.2

**Comment by michaelzhng** [comment]
> Hi ! :)
> 
> Version: 15.2.0
> 
> I'm trying to use this option: https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html
> 
> But I got an error from mapper parsing: `[mapper_parsing_exception] Mapping definition for [seo_description] has unsupported parameters: [enabled : false]`
> 
> putMapping:
> 
> ```js
> res = await elasticClient.indices.putMapping({
>   index: 'cm',
>   type; 'product',
>   body: {
>     properties: mapping,
>   },
> })
> ```
> 
> The mapping definition:
> 
> ```json
> {
> 	"id": {
> 		"type": "keyword"
> 	},
> 	"category_id": {
> 		"type": "text"
> 	},
> 	"category_label": {
> 		"type": "text",
> 		"copy_to": "feature_search"
> 	},
> 	"sibling_id": {
> 		"type": "text"
> 	},
> 	"seo_description": {
> 		"type": "text",
> 		"enabled": false
> 	}
> }
> ```

You don't need to add `type` fields when you let `enabled` to `false`.

**Comment by shusson** [comment]
> You don't need to add `type` fields when you let `enabled` to `false`.

@michaelzhng  You may not need to, but I don't think you should get an error if you do.

**Comment by michaelzhng** [comment]
@shusson [This section](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/enabled.html#enabled) says the `enabled` setting can be applied only to the mapping type and to object fields. If I send the request below:

```
PUT /test
{
  "mappings": {
    "doc": {
      "properties" : {
        "name": {
          "enalbed": false,
          "type": "keyword"
        }
      }
    }
  }
}
```

, I will get the error response: 

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Mapping definition for [name] has unsupported parameters:  [enalbed : false]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [doc]: Mapping definition for [name] has unsupported parameters:  [enalbed : false]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "Mapping definition for [name] has unsupported parameters:  [enalbed : false]"
    }
  },
  "status": 400
}
```

But if I send this:

```
PUT /test
{
  "mappings": {
    "doc": {
      "properties" : {
        "name": {
          "enalbed": false,
        }
      }
    }
  }
}
```

, there will be no error in the response and the `name` field will be recognized as an object field.

```
{
  "test": {
    "aliases": {},
    "mappings": {
      "doc": {
        "properties": {
          "name": {
            "type": "object",
            "enabled": false
          }
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1550023053448",
        "number_of_shards": "5",
        "number_of_replicas": "1",
        "uuid": "BXtcmoUaSJuDS4qpbdEGCQ",
        "version": {
          "created": "6050499"
        },
        "provided_name": "test"
      }
    }
  }
}
```

**Comment by shusson** [comment]
> `enabled` setting can be applied only to the mapping type and to object fields

@michaelzhng I don't see how this indicates that you cannot have a type parameter.

**Comment by michaelzhng** [comment]
@shusson I can. But there is no need to set it because it will be set to an object field automatically.

**Comment by shusson** [comment]
> But there is no need to set it

@michaelzhng /shrug I don't see the harm in being able to set `type`. It would help us parse data from ES since we use the mapping as a schema for our APIs.

**Comment by michaelzhng** [comment]
@shusson Oh, I see. It will be much easier and reasonable if we can just use `enabled` to set whether a field should be indexed or not no matter what the field's type is.

**Comment by MajidJafari** [comment]
I am using elastic 7.3.1 and I have the same issue. But when I remove the "type" property, everything is OK.

**Comment by tacman** [comment]
I think the parameter name has changed from 'enabled' to 'index', so now use {"index": false}
