### ISSUE TITLE
msearch return only one response

### ISSUE THREAD

**Issue by vichal** [elastic/elasticsearch-js#739]

**Comment by delvedor** [comment]
Hello! Can you paste a full example and the expected result?

**Comment by vichal** [comment]
I am new to ES, and I want to do return multiple search result in the same connection so I used msearch API. 
The result is correct when I did in a API manner with curl, But it return only one response when I call the msearch in the js API.
Below is the parameter I passed into the msearch method
{"index":"tickets_test","type":"project","body":[{"query":{"bool":{"must_not":[{"term":{"name":"<hidden>"}},{"term":{"main_city_code":"310100"}}],"must":{"multi_match":{"query":"音乐节","fields":["name^8","summary^4","description","venue_name"],"fuzziness":"AUTO","type":"most_fields"}},"filter":[{"term":{"active":true}},{"range":{"ended_at":{"gte":"2018-12-05"}}},{"term":{"lang_id":"1"}}]}}},{"query":{"bool":{"must_not":[{"term":{"name":"<hidden>"}}],"must":{"multi_match":{"query":"音乐节","fields":["name^8","summary^4","description","venue_name"],"fuzziness":"AUTO","type":"most_fields"}},"filter":[{"term":{"main_city_code":"310100"}},{"term":{"active":true}},{"range":{"ended_at":{"gte":"2018-12-05"}}},{"term":{"lang_id":"1"}}]}}}]}

**Comment by delvedor** [comment]
Can you share a code example, as well as the result of the query done by this client and then the result you get from curl?

**Comment by vichal** [comment]
Never mind, it's my fault, the trick if that the index and type must be in the body parameter too.
I didn't realize it after I saw the document again.
