### ISSUE TITLE
Any intention for support for a high-level DSL client?

### ISSUE THREAD

**Issue by yoonjesung** [elastic/elasticsearch-js#741]
The Python client has an officially supported high-level DSL wrapper: https://github.com/elastic/elasticsearch-dsl-py

Unofficial repos like https://github.com/sudo-suhas/elastic-builder are useful, but only in building the body of queries and does not contain wrappers for mappings, analyzers, etc. like the Python DSL has. The current documentation for 6.5 even recommends using packages like these to help construct queries (see https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference-6-5.html#api-search-6-5).

Is there any intention for a similar type of wrapper for Node.js as well?

**Comment by delvedor** [comment]
Hello! At the moment, we are in the process of refactoring the current client, you can see the status of the work in the [`next`](https://github.com/elastic/elasticsearch-js/tree/next) branch.
Once it's finished, prototype a high-level DSL wrapper is definitely on the roadmap :)

**Comment by gaui** [comment]
Was also looking for a Lucene/ES DSL query builder. Really disappointing this doesn't exist.

However, found https://github.com/sudo-suhas/elastic-builder so I will use that.

**Comment by b-zurg** [comment]
I was looking at that too but it's 2 full DSL versions behind, which is very unfortunate. 

Honestly I'm a bit unimpressed by the JS tooling for elasticsearch

**Comment by villasv** [comment]
AFAIK [bodybuilder](https://github.com/danpaz/bodybuilder) has been kept up to date.

**Comment by delvedor** [comment]
Hello! We are working on a dsl, we will start asking for feedback soon :)

**Comment by JoshMock** [comment]
This is on the long-term roadmap. Some early efforts were stopped when @delvedor moved away from maintaining the project, so when it moves up the priority list I'll have some good inspirations to help get started. :heart:
