### ISSUE TITLE
using .update() with script and params, params are always null

### ISSUE THREAD

**Issue by zdraganov** [elastic/elasticsearch-js#743]
Problem:
Using update for existing document using script and params, is resulting that param values are null.

Environment:
Elasticsearch version: 6.5.2
elasticsearch-js version: 15.2.0

Script used:
```
const client = require('elasticsearch').Client({ host: [host], apiVersion: '6.5' });

client.update({
  index: 'crm',
  type: 'customers',
  id: 'customer@example.com',
  body: {
    script: "if (ctx._source.events == null) { ctx._source.events = [params.event] } else { ctx._source.events.add(params.event) }",
    lang: 'painless',
    params: { "event": "hello" }
  }
});
```

Resulting document:
```
{
   name: 'John Snow',
   email: 'customer@example.com',
   events: [null]
}
```

**Comment by zdraganov** [comment]
Found the problem. 
Script must be a json like this:
```
script: {
  source: ...,
  params: ...
}
```

Closing the issue

**Comment by taojang** [comment]
The examples in api documentation are wrong:
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-update
