### ISSUE TITLE
Can't pass client.update as a function

### ISSUE THREAD

**Issue by SimonVuong** [elastic/elasticsearch-js#750]
using version "15.2.0."

I setup my client with

`  elastic = new elasticsearch.Client({
    host: 'localhost:9200',
    log: 'warning'
  });
`

I want to do

`const res = await callElasticWithErrorHandler(elastic.update, getRestQueryOptions());`

where `callElasticWithErrorHandler` is

```
export const callElasticWithErrorHandler = async (elasticFn, options) => {
  try {
    return await elasticFn(options);
  } catch (e) {
    console.error('ERROR', e);
    if (e.status === 404) throw new Error(getRestNotFoundErrorMsg(options.id));
    if (e.status === 400) throw new Error(e.body.error.caused_by.caused_by.reason);
    throw new Error('Internal error');
  }
}
```

however, this leads to the following error

```
TypeError: Cannot read property 'defer' of undefined
    at action (C:\Users\simon\Projects\Source\MyProject\node_modules\elasticsearch\src\lib\client_action.js:67:36)
```

If I do `const res = await callElasticWithErrorHandler(options => elastic.update(options), getRestQueryOptions());`

Then it works as expected. Thoughts?

**Comment by delvedor** [comment]
You need to bind the context of the client if you are passing functions around.
```diff
- const res = await callElasticWithErrorHandler(elastic.update, getRestQueryOptions());
+ const res = await callElasticWithErrorHandler(elastic.update.bind(elastic), getRestQueryOptions());
```

**Comment by SimonVuong** [comment]
Very interesting. It works just as you said.

Is this happening because `update` is a member of elastic and when I extract it out, it loses the `this` context as it's no longer a member of some object but a standalone function?

**Comment by delvedor** [comment]
> Is this happening because update is a member of elastic and when I extract it out, it loses the this context as it's no longer a member of some object but a standalone function?

Yes, if you want to go deeper in this subject, I suggest you read this [blog post](http://2ality.com/2017/12/alternate-this.html) :)
