### ISSUE TITLE
Basic auth in elasticsearch.js , not auth , but httpAuth

### ISSUE THREAD

**Issue by occultskyrong** [elastic/elasticsearch-js#751]
In there
> https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/auth-reference.html

```JavaScript
var client = new elasticsearch.Client({
  host: [
    {
      host: 'es1.internal.org',
      auth: 'user:password',
      protocol: 'https',
      port: 9200
    }
  ]
});
```

After I configure `Basic Auth` in nginx . 
Using `auth` configuration, I can't ping.
But using `httpAuth` , I can .

```JavaScript
var client = new elasticsearch.Client({
  host: {
      host: '127.0.0.1',
      httpAuth: 'user:password',
      port: 9200
    }
});
```

And also , in this 
> https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html#config-options

it's also say

> httpAuth
> String — Specifies the default http auth as a String with username and password separated by a colon (eg. user:pass). Applies to any host defined in the original config, and any hosts discovered while sniffing.

So, is it a grammatical error I used or a document error? 
Or is `ElasticSearch. js`  implemented incorrectly?

**Comment by occultskyrong** [comment]
In elasticsearch.js@15.2.0

it's just code like this 

```Typescript

export interface ConfigOptions {
    host?: any;
    hosts?: any;
    httpAuth?: string;
    log?: any;
    apiVersion?: string;
    plugins?: any;
    sniffOnStart?: boolean;
    sniffInterval?: number;
    sniffOnConnectionFault?: boolean;
    maxRetries?: number;
    requestTimeout?: number;
    deadTimeout?: number;
    pingTimeout?: number;
    keepAlive?: boolean;
    maxSockets?: number;
    suggestCompression?: boolean;
    connectionClass?: string | typeof HttpConnector;
    sniffedNodesProtocol?: string;
    ssl?: object;
    selector?: any;
    defer?: () => void;
    nodesToHostCallback?: any;
    createNodeAgent?: any;
}

```

so , i think it's `httpAuth` ,  not `auth`

**Comment by occultskyrong** [comment]
> https://github.com/elastic/elasticsearch-js/blob/9c98262b871f860afccc04f8025c35c45aea2281/src/lib/host.js#L104

**Comment by occultskyrong** [comment]
sorry for that , just code error ...
it's `auth`...

but why in [`Configuration`](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html#configuration) it's `httpAuth` ?

**Comment by thomassuckow** [comment]
Then why do https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/auth-reference.html and https://github.com/elastic/elasticsearch-js/blob/master/docs/configuration.asciidoc conflict with eachother about the naming.
