### ISSUE TITLE
client.update throws document_missing_exception

### ISSUE THREAD

**Issue by souuu** [elastic/elasticsearch-js#757]
Hello,
I have documents having one field : numberReqs
when I execute :

```
client.update({
  index: 'index',
  type: 'type',
  id: 'id',
  body: {
    script: "def docSrc = ctx._source; docSrc.numberReqs+=nubmerReqsToAdd;",
    params: {
      nubmerReqsToAdd: 1
    },
    upsert: {
      numberReqs: 0
    }
  }
}, (err) => { console.log(err) })
```

This code throws document_missing_exception even if I mentioned the upsert.

**Comment by delvedor** [comment]
Hi! It looks like that your body is not well formed.
Can you try in this way?
```js
client.update({
  index: 'index',
  type: 'type',
  id: 'id',
  body: {
    script: {
      source: 'def docSrc = ctx._source; docSrc.numberReqs+=nubmerReqsToAdd;',
      lang: 'painless',
      params: {
        nubmerReqsToAdd: 1
      }
    },
    upsert: {
      numberReqs: 0
    }
  }
}, (err) => { console.log(err) })
```
I suggest you to take a look to our [awesome documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#upserts) :)

**Comment by souuu** [comment]
Thank you for your reply.
It worked perfectly ! but to read the param, we use 
params.nubmerReqsToAdd

The js documentation must be updated than,
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-update
As you can see, upsert & params & script are always in the same level, so we have to mention, when we are going to use upsert & params, we have to use the given format.

Thank you again, you saved the day !
