### ISSUE TITLE
Support for response warning header

### ISSUE THREAD

**Issue by jbudz** [elastic/elasticsearch-js#762]
Elasticsearch includes deprecations in a response warning header, https://github.com/elastic/elasticsearch/pull/17804.  Including these in the response or log methods may be useful for staying up to date.

**Comment by delvedor** [comment]
Hello!
You can access the headers when using the callback style, the function should have the following signature: `err, body, status, headers`.

Currently, I'm working on a complete rewrite of the client, that you can find in the [next](https://github.com/elastic/elasticsearch-js/tree/next) branch. In the next client, the return value will be an object with the following keys `{ body, headers, statusCode, warnings }` for both promises and callbacks.

**Comment by jbudz** [comment]
Awesome, thanks for the info @delvedor
