### ISSUE TITLE
client.updateByQuery throws version_conflict_engine_exception

### ISSUE THREAD

**Issue by souuu** [elastic/elasticsearch-js#764]
I can't find where to put the retry_on_conflict parameter in updateByQuery params.

**Comment by souuu** [comment]
Well, i have put the parameter refresh to true, and it works. But is it the correct way to solve this ?

**Comment by aminosman** [comment]
@souuu I had the same issue and when reading the ES docs I found this: 
https://www.elastic.co/guide/en/elasticsearch/reference/7.1/docs-update.html#_parameters_2

Seems like `retry_on_conflict` should be used
