### ISSUE TITLE
15.4.1 breaking change - unrecognized parameter: _sourceInclude, _sourceExclude

### ISSUE THREAD

**Issue by onehorsetown** [elastic/elasticsearch-js#765]
Not an issue, just a heads up to others that might search for this error.  

```
[illegal_argument_exception] request [...] contains unrecognized parameter: [_sourceInclude] -> did you mean any of [_source_include, _source_includes, _source_exclude, _source_excludes]
```

```
[illegal_argument_exception] request [...] contains unrecognized parameters: [_sourceExclude] -> did you mean any of [_source_exclude, _source_excludes, _source_include, _source_includes]?, [_sourceInclude] -> did you mean any of [_source_include, _source_includes, _source_exclude, _source_excludes]?
```

Upon upgrading to version 15.4.1, my code broke because the breaking change documented here:

https://www.elastic.co/guide/en/elasticsearch/reference/6.6/breaking-changes-6.6.html

Since the TypeScript types (https://www.npmjs.com/package/@types/elasticsearch) have not been updated to support the renamed properties, the easiest solution to explicitly set the `apiVersion` when constructing the Elasticsearch Client object:

```
new Client({  apiVersion: '6.5', ... }
```

otherwise the library will use client version `6.6` and your existing code will break.

```

**Comment by austince** [comment]
As a generally related question, what is the reasoning for releasing breaking changes as patch releases, as was done in 15.4.1?

**Comment by delvedor** [comment]
Hello!
It is not a breaking change since the parameters will continue to work as expected.
In Elasticsearch 6.6 you will get a deprecation warning, while in Elasticsearch they will not work anymore.

The main issue here is that we generate the APIs from a given spec and the client offers both *snake_case* and *camelCase* query parameters. If you pass a query parameter in *camelCase* internally it will be converted to *snake_case*, unless it's an unknown parameter, in which case it will be sent as is.
I'll think about how this can be solved, thanks!

**Comment by devagirir** [comment]
Hi Tomas,
I gave query in snake case, following the format which I sent to client.

{"index":"sampleindex","size":1000,"sort":"doc.ddid.keyword:asc","search_after":"00D1I000003nRMaUAM-11e9-bd8f-4f1e395f9c1c"}

Let me know if I can pass in any other format to make it work.

Thanks,
Ravindra

**Comment by delvedor** [comment]
@devagirir it seems that yours is a different situation, can you please open a new issue with an example to reproduce?

**Comment by austince** [comment]
@delvedor, perhaps this instance isn't a breaking change, but other breaking changes are released in patch releases, such as dropping the [5.x line in 15.4.1](https://github.com/elastic/elasticsearch-js/releases/tag/v15.4.1). Happy to open up another issue about this if you think that is best - just want to get an idea of the methodology you use for versioning.

**Comment by peterdemartini** [comment]
I disagree, this IS a breaking change since upgrading it caused our code to break, without changing anything else. This change caused the client to fail before it even tried to send the request to the server, so the depreciation warning you speak of never happened. In order to fix this, we had to explicitly set the apiVersion to 6.5.

**Comment by onehorsetown** [comment]
Yes, it was a breaking change, but at the same time I bear some responsibility in that I never explicitly set the `apiVersion` value.  

`new Client({ apiVersion: '6.5', ... }`

Perhaps this should be a required parameter in the next major release.

**Comment by delvedor** [comment]
I'm sorry for the inconvenience. Unfortunately we can't fix right now.
In any case, I highly recommend always to set the `apiVersion`.

> Perhaps this should be a required parameter in the next major release.

We are working on a new client, you can find it in the [`next`](https://github.com/elastic/elasticsearch-js/tree/next) branch. We will no longer ship all the versions of the API, but the version of the package will also be the version of Elasticsearch.
The new package will be released as `@elastic/elasticsearch` in npm.

This means that if you install version `6.5` of the client, you will have the version `6.5` of the API and so on.

We are very close to finishing it, I'll let you know more as soon as I can :)

**Comment by austince** [comment]
Even if you set the `apiVersion` explicitly, version `15.4.1` dropped support for anything below `5.6`, which is breaking. In the short lifespan this versioning schema has left, can breaking changes be released as major releases?

**Comment by delvedor** [comment]
With the current client, it is difficult to support all the version of the API at once because of the package size (and as said, the inconvenient of the camelCase vs snake_case), with the next one every breaking change will be released as a major release.

**Comment by austince** [comment]
@delvedor - a potential problem occured to me while working on a project that connects to multiple different elasticsearch clusters, all running different versions: with the new versioning scheme, where package version `6.3` maps directly to API version `6.3`, how will one be able to handle multiple different connections? Will we really have to alias every version we need to use?
