### ISSUE TITLE
contains unrecognized parameter: [search_after]

### ISSUE THREAD

**Issue by devagirir** [elastic/elasticsearch-js#767]
Getting this error when trying to invoke node js client with following query
{"index":"sampleindex","size":1000,"sort":"doc.id.keyword:asc","search_after":"00D1I000003nRMaUAM_000d7fe1-4f1e395f9c1c"}

while debugging checked that its not present in available argument list. is this supported via Node JS

**Comment by delvedor** [comment]
Hello! Can you please write a complete example to reproduce?
Please also add the version of Node.js, the version of the client and the version of Elasticsearch.

**Comment by devagirir** [comment]
i still see that search_after is not supported in in this module. When I debug the code, i see that search_after is not present available operations. Any idea why it is not supported.
