### ISSUE TITLE
Unexplained 400 error

### ISSUE THREAD

**Issue by dllz** [elastic/elasticsearch-js#769]
Hi there. 

Having a weird issue when doing an explore query on the elastic cloud service. 
When trying the same require in postman and in kibana dev tools it works. 
The only error message I get is Bad Request. 

I think this is an issue with the client. 

> Elasticsearch TRACE: 2019-02-26T14:20:48Z
  -> post https://xxxxxxxxxxxxxxxx.eu-west-1.aws.found.io:9243/index/_xpack/graph/_explore
> (body)
> 
>   <- 400
Elasticsearch DEBUG: 2019-02-26T14:20:48Z
  Request complete

**Comment by delvedor** [comment]
Hello! Can you upload a full example to reproduce?

**Comment by dllz** [comment]
Sure thing. 

`  {
    "query": {
      "query_string": {
        "query": "samsung"
      }
    },
    "controls": {
      "use_significance": true,
      "timeout": 5000
    },
    "connections": {
      "vertices": [
        {
          "field": "brand.keyword",
          "size": 10,
          "min_doc_count": 3
        },
        {
          "field": "categories.keyword",
          "size": 10,
          "min_doc_count": 3
        },
        {
          "field": "colour.keyword",
          "size": 10,
          "min_doc_count": 3
        },
        {
          "field": "name.keyword",
          "size": 10,
          "min_doc_count": 3
        },
        {
          "field": "price.keyword",
          "size": 10,
          "min_doc_count": 3
        }
      ]
    },
    "vertices": [
      {
        "field": "brand.keyword",
        "size": 10,
        "min_doc_count": 3
      },
      {
        "field": "categories.keyword",
        "size": 10,
        "min_doc_count": 3
      },
      {
        "field": "colour.keyword",
        "size": 10,
        "min_doc_count": 3
      },
      {
        "field": "name.keyword",
        "size": 10,
        "min_doc_count": 3
      },
      {
        "field": "price.keyword",
        "size": 10,
        "min_doc_count": 3
      }
    ]
  }`

`Elasticsearch TRACE: 2019-02-27T08:49:31Z
  -> post https://XXXXXXXXXXXXXXXXXXX.eu-west-1.aws.found.io:9243/metadata/_xpack/graph/_explore
  {
    "query": {
      "query_string": {
        "query": "samsung"
      }
    },
    "controls": {
      "use_significance": true,
      "timeout": 5000
    },
    "connections": {
      "vertices": [
        {
          "field": "brand.keyword",
          "size": 10,
          "min_doc_count": 3
        },
        {
          "field": "categories.keyword",
          "size": 10,
          "min_doc_count": 3
        },
        {
          "field": "colour.keyword",
          "size": 10,
          "min_doc_count": 3
        },
        {
          "field": "name.keyword",
          "size": 10,
          "min_doc_count": 3
        },
        {
          "field": "price.keyword",
          "size": 10,
          "min_doc_count": 3
        }
      ]
    },
    "vertices": [
      {
        "field": "brand.keyword",
        "size": 10,
        "min_doc_count": 3
      },
      {
        "field": "categories.keyword",
        "size": 10,
        "min_doc_count": 3
      },
      {
        "field": "colour.keyword",
        "size": 10,
        "min_doc_count": 3
      },
      {
        "field": "name.keyword",
        "size": 10,
        "min_doc_count": 3
      },
      {
        "field": "price.keyword",
        "size": 10,
        "min_doc_count": 3
      }
    ]
  }
  <- 400
  

Elasticsearch DEBUG: 2019-02-27T08:49:31Z
  Request complete`

Is what is being sent. 
I cannot give you the database but I have tried it on 2 different data sets using the client and get the same response. 

I should also mention that the dataset was reindexed from another cluster incase that might be a connection but I doubt it as it works in kibana and the rest api.

**Comment by delvedor** [comment]
Can you please write the Client version that you are using, as well as the Stack version in Cloud?

By example to reproduce I mean a complete code example, such as 
```js
const { Client } = requiree('elasticsearch')
const client = new Client({ ... })
// API that you are calling from the client
```
The full log error would be useful as well :)

**Comment by dllz** [comment]
That is the full error log in the trace. The err variable only contains bad message. 

`const elasticsearch = require('elasticsearch');
var elasticClient =  new elasticsearch.Client({
    host: host,
    auth: user +':'+ password,
    log: "trace"
});

module.exports = {
    es: elasticClient
};`

`   if(!explorerQuery)
    {
        let tempQueryHolder = {
            term: query
        };
        explorerQuery = generateExplorerQuery(tempQueryHolder);
    }
    metadataRepository.explore(explorerQuery, function (err, parsedBody, status){})`

`function generateExplorerQuery(query, removedFieldMap)
{
    let queryDefinition = {
        "query": {
            "query_string": {
                "query": query.term
            }
        },
        "controls": {
            "use_significance": true,
            "timeout": 5000
        },
        "connections": {
            "vertices": []
        },
        "vertices": []
    };
    let fieldMap = [{
        field: "brand.keyword",
        exclude: true,
        include: true,
    }, {
        field: "categories.keyword",
        exclude: true,
        include: true
    }, {
        field: "colour.keyword",
        exclude: false,
        include: true
    },  {
        field: "name.keyword",
        exclude: true,
        include: true,
    }, {
        field: "price.keyword",
        exclude: false,
        include: true
    }];
    for (const fieldMapElement of fieldMap) {
        if(removedFieldMap)
        {
            let removedFieldMapElement = _.filter(removedFieldMap, function(o){
                return o.field === fieldMapElement.field
            });
            if(removedFieldMapElement.length > 0)
            {
                for (const removedFieldMapElementElement of removedFieldMapElement) {
                    if(query.vertix.term !== removedFieldMapElementElement.term)
                    {
                        queryDefinition.connections.vertices = pushOrAppend(queryDefinition.connections.vertices, createVertix(fieldMapElement, 10, removedFieldMapElementElement.term));
                    }
                }
            }
            else {
                queryDefinition.connections.vertices.push(createVertix(fieldMapElement, 10));
            }
        }
        else{
            queryDefinition.connections.vertices.push(createVertix(fieldMapElement, 10));
            queryDefinition.vertices.push(createVertix(fieldMapElement, 10));
        }
    }
    if(query.vertix)
    {
        queryDefinition.vertices.push(createVertix(query.vertix, 10, null, query.vertix.term));
    }
    console.log(JSON.stringify(queryDefinition));
    return queryDefinition;
}`

`function explore(queryDefinition, callback) {
    elasticClient.es.transport.request({
        requestTimeout: 10000,
        maxRetries: 2,
        path: index + '/_xpack/graph/_explore',
        method: "post",
        body: queryDefinition
    }, callback);
}`

It started on 15.1.1 and I then updated to 15.4.1 and it persists.

**Comment by delvedor** [comment]
Could you use proper formatting? You can see [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) how to do it.
Furthermore, the http method should be uppercase.
The full error log is still missing, if you can copy and paste the `console.log` of the error in the callback it would be great.

**Comment by dllz** [comment]
Sorry, here is the error log. 
```
{ Error: Bad Request
    at respond (engine.js/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (engine.js/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (engine.js/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (engine.js/node_modules/lodash/lodash.js:4935:19)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
  status: 400,
  displayName: 'BadRequest',
  message: 'Bad Request',
  path: 'generic_metadata_amazon/_xpack/graph/_explore',
  query: undefined,
  body:
   '{"query":{"query_string":{"query":"samsung"}},"controls":{"use_significance":true,"timeout":5000},"connections":{"vertices":[{"field":"brand.keyword","size":10,"min_doc_count":3},{"field":"categories.keyword","size":10,"min_doc_count":3},{"field":"colour.keyword","size":10,"min_doc_count":3},{"field":"name.keyword","size":10,"min_doc_count":3},{"field":"price.keyword","size":10,"min_doc_count":3}]},"vertices":[{"field":"brand.keyword","size":10,"min_doc_count":3},{"field":"categories.keyword","size":10,"min_doc_count":3},{"field":"colour.keyword","size":10,"min_doc_count":3},{"field":"name.keyword","size":10,"min_doc_count":3},{"field":"price.keyword","size":10,"min_doc_count":3}]}',
  statusCode: 400,
  response: '',
  toString: [Function],
  toJSON: [Function] }
```

**Comment by delvedor** [comment]
Can you try to add a `/` in front of the path and use an uppercase method? (`POST` instead of `post`)

**Comment by dllz** [comment]
Awesome that fixed it however I believe another issue has cropped up as I am now getting a 401 with the same explore query. I think its because the transport system is not applying the authentication header 
```
  <- 401
  {
    "error": {
      "root_cause": [
        {
          "type": "security_exception",
          "reason": "action [indices:data/read/xpack/graph/explore] requires authentication",
          "header": {
            "WWW-Authenticate": [
              "Bearer realm=\"security\"",
              "Basic realm=\"security\" charset=\"UTF-8\""
            ]
          }
        }
      ],
      "type": "security_exception",
      "reason": "action [indices:data/read/xpack/graph/explore] requires authentication",
      "header": {
        "WWW-Authenticate": [
          "Bearer realm=\"security\"",
          "Basic realm=\"security\" charset=\"UTF-8\""
        ]
      }
    },
    "status": 401
  }

Elasticsearch DEBUG: 2019-02-28T08:21:07Z
  Request complete

{ Error: [security_exception] action [indices:data/read/xpack/graph/explore] requires authentication, with { header={ WWW-Authenticate={ 0="Bearer realm=\"security\"" & 1="Basic realm=\"security\" charset=\"UTF-8\"" } } }
    at respond (engine.js/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (engine.js/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (engine.js/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (engine.js/node_modules/lodash/lodash.js:4935:19)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
  status: 401,
  displayName: 'AuthenticationException',
  message:
   '[security_exception] action [indices:data/read/xpack/graph/explore] requires authentication, with { header={ WWW-Authenticate={ 0="Bearer realm=\\"security\\"" & 1="Basic realm=\\"security\\" charset=\\"UTF-8\\"" } } }',
  path: '/generic_metadata_amazon/_xpack/graph/_explore',
  query: undefined,
  body:
   '{"query":{"query_string":{"query":"samsung"}},"controls":{"use_significance":true,"timeout":5000},"connections":{"vertices":[{"field":"brand.keyword","size":10,"min_doc_count":3},{"field":"categories.keyword","size":10,"min_doc_count":3},{"field":"colour.keyword","size":10,"min_doc_count":3},{"field":"name.keyword","size":10,"min_doc_count":3},{"field":"price.keyword","size":10,"min_doc_count":3}]},"vertices":[{"field":"brand.keyword","size":10,"min_doc_count":3},{"field":"categories.keyword","size":10,"min_doc_count":3},{"field":"colour.keyword","size":10,"min_doc_count":3},{"field":"name.keyword","size":10,"min_doc_count":3},{"field":"price.keyword","size":10,"min_doc_count":3}]}',
  statusCode: 401,
  response:
   '{"error":{"root_cause":[{"type":"security_exception","reason":"action [indices:data/read/xpack/graph/explore] requires authentication","header":{"WWW-Authenticate":["Bearer realm=\\"security\\"","Basic realm=\\"security\\" charset=\\"UTF-8\\""]}}],"type":"security_exception","reason":"action [indices:data/read/xpack/graph/explore] requires authentication","header":{"WWW-Authenticate":["Bearer realm=\\"security\\"","Basic realm=\\"security\\" charset=\\"UTF-8\\""]}},"status":401}',
  wwwAuthenticateDirective:
   'Bearer realm=security, Basic realm="security" charset="UTF-8"',
  toString: [Function],
  toJSON: [Function] }
GET /axis?term=samsung - - ms - -

**Comment by delvedor** [comment]
It should be supported, but you can quickly fix this by adding the `headers` key to your request.

**Comment by dllz** [comment]
Had the authentication set up wrong. Thanks
