### ISSUE TITLE
Cancel / abord search request

### ISSUE THREAD

**Issue by ebuildy** [elastic/elasticsearch-js#771]
Use case: "in a React application similar to Kibana, user can click on checkbox to select filter" hence, plenty of search queries are sent.

It seems not be obvious (or I miss something...) to cancel the promise returns by ``client.search``, is there a way to do this?

**Comment by spalger** [comment]
The promises returned by `client.search` have an `abort()` method added to them to do just that, just make sure you're accessing the exact promise, calling `.then()` or using an `await` will convert the promise to a new promise, and you won't have access to the `abort()` function anymore. https://github.com/elastic/elasticsearch-js/blob/master/src/lib/transport.js#L180

**Comment by telendt** [comment]
@delvedor that's not the case in the new client, is it?
Is there any way to abort in-flight search request in the new client?

**Comment by telendt** [comment]
Answering my own question:
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-usage.html#_aborting_a_request
