### ISSUE TITLE
client.indices.refresh Authorization Exception

### ISSUE THREAD

**Issue by WillGibson** [elastic/elasticsearch-js#774]
Since enabling security on our new Elasticsearch cluster (6.6.1) `client.indices.refresh` is throwing an `Authorization Exception`.

E.g.

```
client.indices.refresh({
    index: 'my-index-name'
}
```

The user in question has a role with the following privileges...

```
"privileges": [
    "manage",
    "read",
    "view_index_metadata",
    "write"
]
```

Other operations like `client.search` and client.index` are working fine.

Have I found a bug?

If I have, would you be amenable to me submitting a PR to fix it?

**Comment by delvedor** [comment]
Hello!
Can you please share the version of the client and the snippet where you are initializing it?

Have you tried to run the same command with curl?

**Comment by WillGibson** [comment]
I just realised I should have checked the version while walking the dog and got my phone out to say so. Will check that and curling when I get back.

**Comment by WillGibson** [comment]
It's not a bug with `elasticsearch-js`.

Making the request direct results in...

```
action [indices:admin/refresh[s]] is unauthorized for user
```

https://www.elastic.co/guide/en/elastic-stack-overview/current/security-privileges.html says that indices manage gives access to refreshing an index and the user's role definitely has that.

What am I missing?

**Comment by WillGibson** [comment]
Got it.

Today I think I learned that using an index alias in the `names` works fine for things like `read` and `write`, but not others like `manage`. Certainly the job that didn't need to refresh the index worked fine on the original permissions.

**Comment by delvedor** [comment]
Hi! Sorry for the delay!
Glad you could solve it :)
