### ISSUE TITLE
No Living connections

### ISSUE THREAD

**Issue by Surajsdalvi** [elastic/elasticsearch-js#775]
I am using 14.2.2 version of this module and getting following error: No Living connections
May I know the reasons for this issue?

**Comment by delvedor** [comment]
Hello! I recommend you to use the last version of the library :)
Can you please share the configuration you are using to initialize the client?

**Comment by Surajsdalvi** [comment]
I am using the following configuration to initialise the client:
```
{
"host":"https://<<username>>:<<password>>://<<host url>>
}
```
Can latest version solve my issue ?

**Comment by delvedor** [comment]
Not sure how `"host":"https://<<username>>:<<password>>://<<host url>>` could work.
Can you try with `"host":"https://<<username>>:<<password>>@<<host url>>`?

**Comment by Surajsdalvi** [comment]
Sorry I am using like that only:
```
new ES.Client({
"host":"https://<<username>>:<<password>>@<<host url>>
});
```
But Can latest version solve my issue ?

**Comment by delvedor** [comment]
> But Can latest version solve my issue?

It's hard to say, is not clear why you have that error.
Usually, that error happens if the node that you are connecting to is faulty, or if you are using a bad sniffing configuration.

**Comment by Surajsdalvi** [comment]
I am using one custom key during initialising a elastic client here is my configuration: 

```
new ES.Client({
"host":"https://<<username>>:<<password>>@<<host url>>,
"indexName":"<<elastic index name>>"
});
```
where indexName is a customkey that I am using in my logic 
Does because of custom key I am geeting that error? and the issue is coming randomly.
can you please help me into this?

**Comment by delvedor** [comment]
That additional key should not influence the behavior of the client, although, why are you putting it there?

Are you able to craft an example to reproduce the issue?

**Comment by Surajsdalvi** [comment]
I am using customkey(here indexName) there for my own logic. and I don't have any example to reproduce the issue the reason is that the issue is coming randomly. I am not getting any steps to reproduce the issue.

**Comment by Surajsdalvi** [comment]
Hi @delvedor can you please help me in this?

**Comment by delvedor** [comment]
I'm sorry, but without an example to reproduce the issue, it's tough understanding what's happening.
You are getting that error because the client marks the connection as faulty, so you should try to see the logs of Elasticsearch at the time you get the error, and try to understand what's happening.
The client should reheal itself tho, which means that it will try to revive the connection during time.

**Comment by AllenFang** [comment]
@Surajsdalvi did you call client.close() every time you finish a action?

**Comment by Surajsdalvi** [comment]
No I am not calling client.close()

**Comment by frankorama** [comment]
Note there is an issue with Node v8  and v9 and SSL.  If you elastic api client is running on Node 8 or 9 you will probably encounter this issue

https://github.com/nodejs/node/issues/19359
