### ISSUE TITLE
TypeScript/Node -> Error: Cannot find module

### ISSUE THREAD

**Issue by raybog** [elastic/elasticsearch-js#781]
## 💬 Is there any special configuration required for TypeScript, Node and WebPack?
 
I keep getting during runtime: `{ Error: Cannot find module './api/search.js'.......`

Just trying to run an example code from: https://github.com/elastic/elasticsearch-js/blob/master/docs/examples/typescript.asciidoc

It looks like all the /api/* methods that are supposed to be lazy loaded are not in generated, by webpack, bundle.js.

**Comment by delvedor** [comment]
Hello!
Can you please write which library are you using (`@elastic/elasticsearch` or `elasticsearch`) and which version?

**Comment by raybog** [comment]
Ups sorry for not including this...

So I have followed the npm install @elastic/elasticsearch and in package.json it says  `"@elastic/elasticsearch": "0.1.0-beta.2"`

**Comment by delvedor** [comment]
Great, can you upload a full example to reproduce? (a repository with ts and webpack as well would be awesome).

**Comment by raybog** [comment]
Trying this file:
https://github.com/elastic/elasticsearch-js/blob/master/docs/examples/typescript.asciidoc

Build is fine but running: `node bundle.js` generates the `Error: Cannot find module`

I am using customised webpack.config.js but it works fine with other libraries like axios.

**Comment by delvedor** [comment]
I've opened https://github.com/elastic/elasticsearch-js/pull/783, which should fix your issue.
Can you try it?
You can install it with `npm i git://github.com/elastic/elasticsearch-js.git#support-bundlers` :)

**Comment by raybog** [comment]
Thanks, now it works however all APIs methods are included in the bundle. Not sure this is desired outcome?

**Comment by delvedor** [comment]
> however all APIs methods are included in the bundle. Not sure this is desired outcome?

It is. The code is still lazy loaded, so it will not impact the startup speed.

**Comment by katafractari** [comment]
We are still getting this error on 7.4.0. Calling search function works locally but throws the following error when the same code is deployed to aws lambda:
`Cannot find module './api/search.js'`

**Comment by SeanFacer** [comment]
Also getting this issue

**Comment by daywiss** [comment]
We are also seeing this error in production environment using ` @elastic/elasticsearch": "~7.6.1` and `"typescript": "~3.6.2"` being bundled with `"fuse-box": "^3.7.1"`.

**Comment by martsie** [comment]
> I've opened #783, which should fix your issue.
> Can you try it?
> You can install it with `npm i git://github.com/elastic/elasticsearch-js.git#support-bundlers` :)

This is still not working with the latest elastic search and building with parcel. The above code returns 'no matches found: git://github.com/elastic/elasticsearch-js.git#support-bundlers' so it seems like the solution is outdated. How can elasticsearch and typescript work without a bundler on lambda?

**Comment by juanpujol** [comment]
Same problem, finally decided to migrate to `"@elastic/elasticsearch": "7.7.1"` but it doesn't work when I deploy it with the Serverless framework. `"elasticsearch": "16.7.1"` works fine.

**Comment by martsie** [comment]
I ended up sticking with `@elastic/elasticsearch` but using `tsc` instead of `parcel` to build the project. Luckily the elastic search proxy we have is really lightweight so we didn't have to do much refactoring to make `tsc` work but it does make our zip and upload process more arduous because now node_modules needs to be uploaded to lambda along with the project and now our lambda function has gone from less than 1mb to around 40mb. 

If anybody comes up with a fix to make it work with parcel or other package builders please post it up here so we can switch back.

**Comment by delvedor** [comment]
Hey folks, I want to better investigate the support for bundlers, if you would like to contribute please share your experience in https://github.com/elastic/elasticsearch-js/issues/1232, thanks!

**Comment by ankit-bhadja-sf** [comment]
@katafractari were you able to fix issue for TS + Lambda? any help would be appreciated.
