### ISSUE TITLE
collapse can not work

### ISSUE THREAD

**Issue by Hiufan** [elastic/elasticsearch-js#787]
## 💬 Questions and Help
when i post the body like below:
```
{
    "query": {
        "match": {
            "message": "elasticsearch"
        }
    },
    "collapse" : {
        "field" : "user" 
    },
    "sort": ["likes"], 
    "from": 10 
}
```

Some error appear:
```
[search_context_exception] unknown type for collapse field `id`, only keywords and numbers are accepted
```

After I remove the collapse key, it work again.Anyone can tell me how to solve the data dumplicated problem?

**Comment by delvedor** [comment]
Hello! Can you post a complete example to reproduce the issue?
If this is a strictly Elasticsearch related issue (so no a bug/question of this library), I highly recommend you to use https://discuss.elastic.co :)
