### ISSUE TITLE
Instructions for downloading version @6 is incorrect.

### ISSUE THREAD

**Issue by rwlaschin** [elastic/elasticsearch-js#788]
## 🐛 Bug Report

When attempting to install @elastic/elasticsearch@6, an error is displayed.

## To Reproduce

Follow the instructions on the site for installing a elasticsearch 6.*.* compatible version of the library.

Paste your code here:

```js
npm i @elastic/elasticsearch@6
```

## Expected behavior

Paste the results here:

```js
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @elastic/elasticsearch@6
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rwlaschin/.npm/_logs/2019-03-26T04_00_10_205Z-debug.log
Roberts-MacBook-Pro:wholosophy-web rwlaschin$ npm install @elastic/elasticsearch@6
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @elastic/elasticsearch@6
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

## Your Environment

- *npm version*: 6.4.1
- *@elastic/elasticsearch version*: =6.6.2
- *os*: Mac
- *basic install to get library*

**Comment by delvedor** [comment]
Hello! Thank you for checking out the new client!
From the README:

> Warning: currently on npm you will only find a beta release that works with Elasticsearch 7, we will add the support for Elasticsearch 5, 6, and 7 once we release the final version of this library.

I'll release all the versions in the next days.
If you want to try them early, you can still install from one of the branches of the repo. In your case: [`6.x`](https://github.com/elastic/elasticsearch-js/tree/6.x).

**Comment by rkahle** [comment]
Any news about when next-days™ will be? ;)
I'm suffering of https://github.com/elastic/elasticsearch-js/issues/521 and hope that the new release will release me too..

**Comment by delvedor** [comment]
Hello!
The client has been released at the beginning of this week! :)
https://www.elastic.co/blog/announcing-the-new-elasticsearch-javascript-client-rc1

Note that you should install it by using the full version number until we are out of the rc phase.

**Comment by rkahle** [comment]
Thanks a lot! :)

**Comment by njunxuan** [comment]
Hi, any updates on when version @6 will be launched? Still unable to install the package from npm. thanks!

**Comment by delvedor** [comment]
Hello! We ave already published v6 :)
The command `npm i @elastic/elasticsearch@6` is failing because the client is still in RC, and npm does not support pre-releases.
The only way to install it, for now, is `npm i @elastic/elasticsearch@6.7.0-rc.2`. Sorry for the inconvenience!

**Comment by njunxuan** [comment]
> Hello! We ave already published v6 :)
> The command `npm i @elastic/elasticsearch@6` is failing because the client is still in RC, and npm does not support pre-releases.
> The only way to install it, for now, is `npm i @elastic/elasticsearch@6.7.0-rc.2`. Sorry for the inconvenience!
Thanks for the update! Is there any ETA as to when the final for version 6 will be released? Trying to decide whether to use the new client or stick with the legacy one.

**Comment by delvedor** [comment]
> Thanks for the update! Is there any ETA as to when the final for version 6 will be released? Trying to decide whether to use the new client or stick with the legacy one.

Not yet, but very soon!
You can use the new client already, the API is stable and we are gathering feedbacks :)
