### ISSUE TITLE
All releases got removed?

### ISSUE THREAD

**Issue by j0k3r** [elastic/elasticsearch-js#795]
I was about to check changes between version 15.4.0 & 15.4.1 on GitHub but it appears that all previous release were removed...

They still exist [on npm](https://www.npmjs.com/package/elasticsearch) & and are [in the Googe cache](http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fgithub.com%2Felastic%2Felasticsearch-js%2Freleases&oq=cache%3Ahttps%3A%2F%2Fgithub.com%2Felastic%2Felasticsearch-js%2Freleases&aqs=chrome..69i57j69i58.1407j0j9&sourceid=chrome&ie=UTF-8).

But I was wondering did you guys removed all the releases & tags from the GitHub repo? :disappointed_relieved:

**Comment by delvedor** [comment]
Hello!
Quoting from the README:

> Note: In the past months we have worked on the new Elasticsearch Node.js client, we will announce it soon! If you want you can already try it by following the instructions below, while if you're going to use the legacy one or report an issue, please check out [elastic/elasticsearch-js-legacy](https://github.com/elastic/elasticsearch-js-legacy).

You will find in the legacy repo all the tags and the changelog :)

**Comment by j0k3r** [comment]
Great, thanks!
