### ISSUE TITLE
elasticsearch 7 compatible release for indices without types?

### ISSUE THREAD

**Issue by fadijabi** [elastic/elasticsearch-js#802]
When is the expected release for indices without types? I am getting this error as I try to index data to elasticsearch 7 release candidate. 

Error: Unable to build a path with those params. Supply at least index, type

Thanks.

**Comment by delvedor** [comment]
Hello! Which version of the library are you using?
Can you upload a full example to reproduce the issue?

**Comment by fadijabi** [comment]
Hello @delvedor,

I am using the latest version of Elasticsearch client for Node.js v15.4.1. I am running elasticsearch preview release 7.0.0-rc1. 

I came to know doc types are deprecated so when I try to index data without specifying the doc type I get the error: Unable to build a path with those params. Supply at least index, type.

I am not sure if I should specify the doc type as "_doc" or just remove it completely as shown 

`elasticsearch.index({
                index: 'history',
                refresh: true,
                id: Buffer.from(request.SearchText.toLowerCase().trim()).toString('base64'),
                body: {
                    featuretype: 
                })`

**Comment by delvedor** [comment]
You are using our [legacy](https://github.com/elastic/elasticsearch-js-legacy) client, which hasn't been updated to support Elasticsearch 7 yet.
You can try to use the new client, which lives in this repository, you can install the version 7 with `npm i @elastic/elasticsearch@7.0.0-rc.1` :)

**Comment by fadijabi** [comment]
Oh thank you so much. It worked and tackled few breaking changes 👍
