### ISSUE TITLE
Not able to add custom http.agent (createNodeAgent missing?)

### ISSUE THREAD

**Issue by endymonium** [elastic/elasticsearch-js#808]
Hello,

in the past there existed a createNodeAgent argument, which you could use to add a custom htt.agent. That was removed, isn't it? Are there any alternatives?

I need to add proxy support to the the node.http library ...

Thanks,
Jan

**Comment by delvedor** [comment]
Hello!
Are you using the new client? (the one you install with `npm i @elastic/elasticsearch`)
If so, you can't pass a custom http agent at the moment, but it is a good feature request!

**Comment by endymonium** [comment]
Yes, new client. I'll resubmit it as a fututre request then :)
