### ISSUE TITLE
Incomplete typescript documentation

### ISSUE THREAD

**Issue by DASPRiD** [elastic/elasticsearch-js#811]
In the documentation for defining response types for e.g. search results, it only briefly gives an example of defining a `SearchResponse`, but there is no further documentation/example about how to use it. It'd be great to get a complete example using the `.search()` function.

https://github.com/elastic/elasticsearch-js/blob/7.x/docs/typescript.asciidoc

**Comment by delvedor** [comment]
Hello!
Thank you for the suggestion!
I've opened https://github.com/elastic/elasticsearch-js/pull/813, check it out!

**Comment by delvedor** [comment]
Closed in #813.
