### ISSUE TITLE
Issues using { Client }

### ISSUE THREAD

**Issue by mperu92** [elastic/elasticsearch-js#814]
Hi, i'm trying to use the es client with Es6 + React, for connect my app into the elastic cloud using the code from the examples:
`import { Client } from '@elastic/elasticsearch';
const client = new Client({
  cloud: {
    id: 'Cloud-Name:Cloud-Id',
    username: 'elastic',
    password: 'my-password'
  }
});`

But when i launch the program it takes me this error
> [ConnectionPool.js:375] Uncaught TypeError: URL is not a constructor

what could be the issue?

**Comment by delvedor** [comment]
Hello!
Are you using the client in the browser?

**Comment by mperu92** [comment]
yes, i'im

> Hello!
> Are you using the client in the browser?

Yes @delvedor, i'm using React client-side
(are you italian? Really? :))

**Comment by delvedor** [comment]
> Yes @delvedor, i'm using React client-side

This client is **not** intended to be used in a browser environment.
Contact Elasticseach directly from the browser exposes you to many security risks and we do not support that.

> (are you italian? Really? :))

Yes.

**Comment by mperu92** [comment]
Ah, ok thanks for this information.
I will try other ways.
(i'm tryng to build an Autocomplete widget with React and Elastic Search)

**Comment by delvedor** [comment]
> (i'm tryng to build an Autocomplete widget with React and Elastic Search)

In this case, I suggest you take a look at [elastic/search-ui](https://github.com/elastic/search-ui)

If you want to build your own system, I recommend you to put a simple Node.js server (which uses this client) between your React app and Elasticsearch.

**Comment by mperu92** [comment]
> If you want to build your own system, I recommend you to put a simple Node.js server (which uses this client) between your React app and Elasticsearch.

Wow, thank you so much!
There is some documentation about this specific case?

**Comment by mperu92** [comment]
Because i haven't an Elastic App Search

**Comment by mperu92** [comment]
Solved really fast working server-side!

**Comment by delvedor** [comment]
Hello!
I'm closing this since it seems you have solved your issue. Please open a new issue if you have more questions! :)

**Comment by mperu92** [comment]
Hi thank you so much and sorry i forget to close it!



Il giorno ven 26 apr 2019 alle ore 10:48 Tomas Della Vedova <
notifications@github.com> ha scritto:

**Comment by arunesh90** [comment]
It seems like this issue also occurs in Cloudflare's workers, any way to work around it?

**Comment by thetre97** [comment]
@arunesh90 I don't suppose you found the issue with this?

**Comment by thetre97** [comment]
@tdossett I couldn't get it to work, so I just used the es rest api with fetch/exios etc.

**Comment by tdossett** [comment]
I see i was thinking about doing the same thing since elasticsearch.js using { Client } does not work yet. 

THX do you have sample fetch, axios example ?

**Comment by thetre97** [comment]
Pulled from a quick workers & graphql demo app:
```javascript
const endpoint = `${endpoint}/_search`
const credentials = new Buffer.from(`${username}:${password}`).toString('base64')

module.exports = {
  SearchResult: {
    __resolveType(obj, context, info){
      if (obj.first_name) return 'Contact'
      if (obj.name) return 'Company'
      return null
    },
  },
  Query: {
    search: async (parent, { query }, ctx, info) => {
      try {
        const queryBody = {
          multi_match: {
            query,
            fields: ['*_name^3', 'company'],
            fuzziness: 'AUTO'
          }
        }
        const response = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Authorization': `Basic ${credentials}`
          },
          body: JSON.stringify({ query: queryBody })
        })
        const data = await response.json()
        const results = data.hits.hits.map(hit => hit._source)
        return results
      } catch (error) {
        throw new Error(error.message)
      }
    }
  }
}
```

**Comment by tdossett** [comment]
This is sweet 😊 …. I will give it a try.

Ans let you know

THX a million Tim

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tdossett** [comment]
Hi Travis,

I ended up following your lead and did the following:

[cid:image003.jpg@01D58F38.F2F0B720]

  1.  I used ‘axios’ to perform the https get request (normally I had ‘url’ and ‘auth’, but wanted to be more specific).

[cid:image004.png@01D58F38.F2F0B720]

  1.  In my Elastic subscription I enable ‘cors’.
AND NOW IT WORKS in Heroku ….


Thank You Again 😊 …

Tim
