### ISSUE TITLE
Export `ClientOptions`

### ISSUE THREAD

**Issue by onehorsetown** [elastic/elasticsearch-js#817]
##  Regression Report (kind of)

Previously (6.7) the Typescript typings from DefinitelyTyped exported the client`ConfigOptions` - which is seems to have been renamed to `ClientOptions` in 7.x:

See:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/elasticsearch/index.d.ts#L99

versus:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/elasticsearch/index.d.ts#L99

I realize Elastic probably did not publish these types, so this technically an enhancement request, as opposed to a regression, depending on how you look at it.

## Last working version

Worked up to version: 6.7

Stopped working in version: 7.0

## Expected behavior

Please add an `export` here:

https://github.com/elastic/elasticsearch-js/blob/7.x/index.d.ts#L67

as in:

```
export interface ClientOptions { 
   ...
}
```

or export `ClientOptions` where you export everything else on line 562.

## Your Environment

- *node version*: 11.12.0
- `@elastic/elasticsearch` *version*: >=7.0.0
- *os*: MacOS
- *any other relevant information*

**Comment by delvedor** [comment]
Closed in #819.
