### ISSUE TITLE
How to use custom route with bulk method?

### ISSUE THREAD

**Issue by bhavayAnand9** [elastic/elasticsearch-js#826]
## 💬 Questions and Help
so let me start by saying I'm pretty new to ES and working with it's JS client, so please forgive me if it's a stupid question and I don't know if it's the right place to ask this type of question.
In JS API there's a method [bulk](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_bulk), which is used to bulk insert the elements into indices but my problem is I want to input the elements using a custom route, which can be different for different elements, so how should I proceed with that as routing param in bulk method will accept one string.

### Please note that this issue tracker is not a help forum and this issue may be closed.

It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Comment by delvedor** [comment]
Hello! I'm not sure I've understood your issue, can you write a small example?
You can find [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/bulk_examples.html) a small example to understand how the bulk API works :)

**Comment by bhavayAnand9** [comment]
Hi! sorry for replying so late. The example in the link does not use custom routing. For custom routing, every element inserting has to define a route value with it but with using bulk how can I define route value with the element?

This is what I'm doing, I'm looping through my data and inserting the data with a custom routing value defined with it.
```
function indexing(index, type, data){
    data.forEach(item => {
        esClient.index({
            index: index,
            type: type,
            routing: generateRoutingKey(item.client_id), // generateRoutingKey returns an int value which will be used as routing key 
            body: {
                active: item.active,
                archivedSessions: item.archivedSessions,
                progress: item.progress,
            }
        }).then(response => console.log(`item indexed fields, ${item.client_id}`))
        .catch(e => {
            throw e;
        });
    });
}
```

and this is in the [ES js-api](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_bulk)
```
client.bulk([params] [, options] [, callback])
routing: string - Specific routing value

```

now just like indexing function, I want to put a custom routing value with each element using bulk but the bulk method just takes one string arg. 
The bulk method expects us to first provide one set of elements who share the same routing key and then again use the bulk method on another set of elements who again share the same routing key.

please let me know if anything is unclear.

**Comment by delvedor** [comment]
Hello!
You should use the [`_routing`](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-routing) key in the bulk request.

For example:
```js
client.bulk({
  body: [
    { index: { _index: 'game-of-thrones', _id: '1', _routing: 'routing-key-1' } },
    { character: 'Ned Stark', quote: 'Winter is coming.' },

    { index: { _index: 'game-of-thrones', _id: '2', _routing: 'routing-key-2' } },
    { character: 'Daenerys Targaryen', quote: 'I am the blood of the dragon.' },

    ...
  ]
}, console.log)
```

**Comment by bhavayAnand9** [comment]
Winter has come ^_^, Thank you so much.
Closing the issue now.

**Comment by ubombi** [comment]
btw, now it's `routing`, not `_routing`.
