### ISSUE TITLE
Helper for accessing parts of response body

### ISSUE THREAD

**Issue by tylersmalley** [elastic/elasticsearch-js#830]
## 🚀 Feature Proposal

There are many times I find myself needing to access something deep within a response body, and while this is easy to do, a helper could provide a much cleaner solution.

## Example

In the example, I am needing to access `features.graph.enabled` and instead of checking each property before accessing it, a `get` function is provided, similar to lodash's `get`

```
'use strict'

const { Client } = require('@elastic/elasticsearch')
const client = new Client({ node: 'http://elasitc:changeme@localhost:9200' })

async function run () {
  const response = await client.xpack.info();
  const isGraphEnabled = response.get('body.features.graph.enabled', false);
  console.log(isGraphEnabled)
}

run().catch(console.log)
```

**Comment by delvedor** [comment]
Hello! I like the idea, but I'm not sure this is the right place for that kind of utility.
I'm working on a *dsl* version of the client, which features various utilities, such as a helper for the query language and for the search.
We can think about adding there the helper you are suggesting :)

**Comment by tylersmalley** [comment]
@delvedor, a DSL would be awesome and would probably resolve the issue here. Feel free to close if you're tracking that effort elsewhere.

**Comment by delvedor** [comment]
Thanks for the input!
