### ISSUE TITLE
404 for most links in the Docs section of the REAME.md

### ISSUE THREAD

**Issue by tcollinsworth** [elastic/elasticsearch-js#836]
404 for most links in the Docs section of the REAME.md

https://www.npmjs.com/package/elasticsearch#docs

Only the following 2 of 7 currently work:

- API
- Development/Contributing

**Comment by papandreou** [comment]
I also have a hard time finding the changelog now?

**Comment by delvedor** [comment]
Hello!
We have published the new Elasticsearch client, you can install it with
```
npm i @elastic/elasticsearch 
```
And you can find the breaking changes list [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/7.x/breaking-changes.html).

All the old documentation has been moved [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/16.x/index.html).
Thank you for the issue, I'll fix the link in the old package.

**Comment by alanorth** [comment]
Release notes for the JavaScript client are 404 again. From the last few releases here on GitHub, for example 7.16 links here:

https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/7.x/changelog-client.html

This is the same URL you linked above but it's broken now... where can we find them now? Thanks...

**Comment by delvedor** [comment]
Heya, sorry or the confusion, you can find the changelog here: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/changelog-client.html
I'll update the links.
