### ISSUE TITLE
TypeScript typedefs do not export error types

### ISSUE THREAD

**Issue by gauthierm** [elastic/elasticsearch-js#841]
## 🐛 Bug Report

The TypeScript typedefs in `index.d.ts` do not include the `errors` key that is exported in `index.js`. This makes it impossible to import error types and check them in try/catch statements.

## To Reproduce

Paste your code here:

```js
import { Client, errors } from '@elastic/elasticsearch';
```

## Expected behavior

I expect the errors structure to be imported so I can check `e instanceof errors.ResponseError`.

Paste the results here:

```js
TypeScript says: `Module has no exported member 'errors'.`
```

## Your Environment

- *node version*: 10
- `@elastic/elasticsearch` *version*: >=7.0.0
- *os*: Mac
- *Using TypeScript typedefs*

**Comment by delvedor** [comment]
Hello, good catch!
Do you want to open a pr? :)

**Comment by gauthierm** [comment]
Sure, I can do that later today.

**Comment by delvedor** [comment]
Hello! I've opened https://github.com/elastic/elasticsearch-js/pull/842 since I would like to cut a new release later today.
Thank you again for the report!
