### ISSUE TITLE
Compatibility with node.js v12.x?

### ISSUE THREAD

**Issue by StarkShang** [elastic/elasticsearch-js#844]
I am installing elasticsearch@v7.0.0-rc.1 with node.js@12.x and angular@7.2.0. The following error appear when I use "ng build".

Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 12.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 10.x

**Comment by delvedor** [comment]
Hello!
I guess you are trying to use the client in the browser, if so, it is not supported since it will expose you to security risks and it is an antipattern.

**Comment by StarkShang** [comment]
Thanks for your explanation.
I have used "elasticsearch-browser" instead. I wonder if there is a typescrite definition for it?
It seems that the "@types/elasticsearch" has the same definitions as that in "elasticsearch-browser", but it inconvenient to use. I have import "elasticsearch" when edit my code, and switch to "elasticsearch-browser" when build and publish project.

**Comment by delvedor** [comment]
That's fine, but please remember that connect to Elasticsearch from the browser is a really bad idea.
