### ISSUE TITLE
password passed through url while creating new Client is getting URL encoded ie @ to %40

### ISSUE THREAD

**Issue by matsyavatar** [elastic/elasticsearch-js#857]
It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `not reproducible` label.**

## To Reproduce

**All that you need to reproduce this bug is to use @elastic/elasticsearch@6 and try to connect to and elastic account with password having '@' symbol**

Paste your code here:

```js
const client = new Client(
    {node: 'http://' + process.env.ELASTIC_USERNAME + ':' + process.env.ELASTIC_PASSWORD + '@localhost:9200',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    }})

```

## Expected behavior

The Elasticsearch user has an '@' in their password and whenever we pass the password through the url string, it does URL encoding to %40 and result is
**ResponseError: security_exception**
However for passwords without special characters works.

## Your Environment

- *node version*: 8
- `@elastic/elasticsearch` *version*: >=6.0.0
- *os*:  Linux*

**Comment by delvedor** [comment]
Thank you for reporting!
Apparently, the [URL](https://nodejs.org/api/url.html#url_url_password) constructor encodes every non-url friendly character.
I could easily fix this by decoding the username and password every time before to send them to Elasticsearch, but the performance hit would be too high.
I'll add an option to specify username and password, as it works currently in the cloud configuration.

**Comment by delvedor** [comment]
I was able to fix this without introducing a new parameter, I'll open a pr soon.

**Comment by matsyavatar** [comment]
Hi, @delvedor. When will this new merge be available in npm?

**Comment by delvedor** [comment]
Sorry for the delay! The fix is already available on npm.
