### ISSUE TITLE
extending connection class throws an error

### ISSUE THREAD

**Issue by parthdesai93** [elastic/elasticsearch-js#860]
It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `not reproducible` label.**

## 🐛 Bug Report

Even just following the docs to extend the Connection class throws an Error.

## To Reproduce

Steps to reproduce the behaviour:

```js
const { Client, Connection } = require('@elastic/elasticsearch')

class MyConnection extends Connection {
  request (params, callback) {
     console.log('here?')
  }
}

const client = new Client({
  node: 'url',
  Connection: MyConnection
})
```

output 
`TypeError: Class constructor Connection cannot be invoked without 'new'`

## Expected behavior

Connection class should be instantiated. 

## Your Environment

- *node version*: 8,10
- `@elastic/elasticsearch` *version*: >=6.x
- *os*: Mac

**Comment by delvedor** [comment]
I just tried your code and it works as expected.
Pay attention that the `url` property should always be a valid url.

**Comment by parthdesai93** [comment]
Nvm, it was an issue on my side.  My apologizes.
