### ISSUE TITLE
cat.count return incorrect number

### ISSUE THREAD

**Issue by linchen2chris** [elastic/elasticsearch-js#863]
It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `not reproducible` label.**

## 🐛 Bug Report

I buck import a few data to ES, after that I count the number, but every time it return different incorrect number,
But I use kibnana to count api to query, it return correct number.

## To Reproduce

Paste your code here:

```js

```

## Expected behavior

Paste the results here:

```js

```

## Your Environment

- *node version*: 6,8,10
- `@elastic/elasticsearch` *version*: >=7.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by delvedor** [comment]
Hello!
Can you try to reproduce the issue by using [this template](https://github.com/delvedor/es-reproduce-issue)?

**Comment by linchen2chris** [comment]
@delvedor thanks for your replay. I fix it, so I think this issue can be closed.
the reason for the issue is that: I using bulk api to insert a bunch of data, then call cat.count to query how many items I inserted, but when bulk return correctly, it doesn't mean all of them already inserted, that's why cat.count return random number which always less than the number I expected

**Comment by delvedor** [comment]
@linchen2chris you are right :)
This depends on the index refresh interval of Elasticsearch, which usually is 1 second. You can add `refresh: 'wait_for'` to your bulk configuration and the cat count should be what you expect :)
