### ISSUE TITLE
Object.assign not copying passed parameters

### ISSUE THREAD

**Issue by BitForger** [elastic/elasticsearch-js#866]
## 🐛 Bug Report

Using docker container with NodeJS 10.15.3 and elasticsearch-js ^6.7.1 the parameters object passed during construction doesn't properly copy in some instances using `Object.assign`. 

## To Reproduce

* Create new client

Paste your code here:

```js
const ES = require('@elastic/elasticsearch');
const client = new ES.Client({nodes: ['http://localhost:9200']});

```
https://github.com/elastic/elasticsearch-js/blob/95007b8c9d91b162c547a7d79d326c70daf48c2a/index.js#L64

<details>
<summary>Full File of ours</summary><p>

```js
"use strict";
/**
 * @author (Noah Kovacs)
 * Date: 2019-05-09
 * Time: 17:13
 */

const ES = require('@elastic/elasticsearch');
const AWS = require('aws-sdk');
class UpdateElasticSearchService {

  constructor() {
    /**
     *
     * @type {ClientOptions}
     */
    const params = {
      nodes: this.getHosts(),
    };
    this.esClient = new ES.Client(params);
  }

  getHosts() {
    return process.env.ELASTICSEARCH_DOMAIN.includes(',') ? process.env.ELASTICSEARCH_DOMAIN.split(',') : [process.env.ELASTICSEARCH_DOMAIN];
  }

  /**
   *
   * @param doc {mongoose.MongooseDocument}
   * @param type {string}
   * @return {Promise<boolean>}
   */
  async run(doc, type) {
    const opts = {
      id: doc._id.toString(),
      index: type,
      type: '_doc',
      body: this.buildBody(doc)
    };
    const result = await this.esClient.index(opts)
      .catch(err => {
        console.log('Error re-indexing document', err);
      });
    return true;
  }

  buildBody(doc) {
    return {
      title: doc.title,
      subtitle: doc.subtitle,
      author: this.getAuthor(doc),
      keywords: doc.keywords
    }
  }

  getAuthor(doc) {
    let author;
    if ('author' in doc) {
      author = doc.author;
    } else if ('speaker' in doc) {
      author = doc.speaker;
    } else if ('presenter' in doc) {
      author = doc.presenter;
    }
    return author;
  }
}

module.exports = UpdateElasticSearchService;
```

</p></details>

## Expected behavior

On construction, when the client attempts to add new connections the options variable should not be undefined because the copying of passed parameters happens properly.

Paste the results here:

```js
TypeError: Cannot read property 'url' of undefined
    at ConnectionPool.addConnection (/srv/app/node_modules/@elastic/elasticsearch/lib/ConnectionPool.js:223:14)
    at new Client (/srv/app/node_modules/@elastic/elasticsearch/index.js:107:27)
    at new UpdateElasticSearchService (/srv/app/service/updateElasticSearchService.js:20:21)
```
Offending line:
https://github.com/elastic/elasticsearch-js/blob/95007b8c9d91b162c547a7d79d326c70daf48c2a/lib/ConnectionPool.js#L223

## Your Environment

- *node version*: 10
- `@elastic/elasticsearch` *version*: >=6.7.x
- *os*: Mac (Linux docker container)
- *any other relevant information*
  - Using Elasticsearch@6.4

cc: @abourge

**Comment by delvedor** [comment]
Hello!
I just tried to reproduce your issue, but I'm not able to.
I've created a clean project, installed `@elastic/elasticsearch` version `6.7.1` and copy-pasted your snipped.
It works as expected.

Would you mind reproduce the issue with [this template](https://github.com/delvedor/es-reproduce-issue)?

**Comment by BitForger** [comment]
@delvedor sure thing. 

If it helps, it's using keystonejs save hooks to update indexed documents. We had a fix working using the spread operator based on our finding from this stackoverflow question: https://stackoverflow.com/questions/171251/how-can-i-merge-properties-of-two-javascript-objects-dynamically#comment83371731_171256

Seeing as you're targeting backwards compatibility with Node 5 I don't think that is going to work.

**Comment by delvedor** [comment]
> It reproduced for us on multiple different machines using our dev environments but I'm beginning to believe that it's a result of keystone doing something weird. It's an old version (0.3.15 I believe).

It may be, if you can reproduce the problem outside your environment in the repository I gave you it means that the issue is in the client, otherwise is in your code.
You can also try to add an `assert` to verify that the value exists before passing it to the client.
