### ISSUE TITLE
Adding timeout to Bulk API???

### ISSUE THREAD

**Issue by rosman21** [elastic/elasticsearch-js#867]
The [documentation](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_bulk) offers `timeout` but when I pass to my `client.bulk` command I get this error 
`[parse_exception] failed to parse setting [timeout] with value [30000] as a time value`

My Code
```
client.bulk({
  "timeout": 3000,
   body: { 
              "update": {
                      "_index": "myindex",
                      "_type":"mytype",
                      "_id": 1
                }
   }
}, function (err, resp) {
   if (err) {
      console.log("Error: " +err.message);
   } else {
     console.log(resp)
  }
});
```

Any help is appreciated.

**Comment by delvedor** [comment]
Hello! You should use a string representation, you can find [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/common-options.html#time-units) the supported formats :)

If you want to specify a request timeout instead, you should use the `requestTimeout` option.
```js
await client.bulk({
  body: [...]
}, {
  requestTimeout: 3000 // milliseconds or string
})
```

**Comment by rosman21** [comment]
> Hello! You should use a string representation, you can find [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/common-options.html#time-units) the supported formats :)
> 
> If you want to specify a request timeout instead, you should use the `requestTimeout` option.
> 
> ```js
> await client.bulk({
>   body: [...]
> }, {
>   requestTimeout: 3000 // milliseconds or string
> })
> ```

Thank you very much. That seemed to work for me!
