### ISSUE TITLE
Discrepancy in using ElasticsearchJS and Elasticsearch API

### ISSUE THREAD

**Issue by MonkiTyping** [elastic/elasticsearch-js#868]
I am trying to execute a compound search using the *bool* in a query. For some reason, I am unable to get the bool query to work on ElasticsearchJS ( even though I pass the same query to the Elasticsearch API ( Using curl/ Postman)

## 🐛 Bug Report
BOOL query is not working as expected with ElasticsearchJS. Using a single must/must_not/should/should_not is fully functional, But when I use the clause within an array, The query returns no results. The same query passed to ElasticSearch API works fine.

## To Reproduce
Search an index with multiple match conditions as shown below

1) Perform a search using the ElasticsearchJS with multiple conditions in an array
2) Perform the same search via ElasticSearch API

The below query works ONLY for ElasticSearch API and not Elasticsearch JS
*(Note I omitted index, type and the query being embedded inside a body key)*

```js
{
	"query": {
			"bool": {
				"must": [{
					"match": {
						"address": "avenue"
					}
				}]
			}
		}
}
```
Weirdly, The below query works using ElasticsearchJS
```js
{
	"index": "bank",
	"type": "account",
	"body": {
		"query": {
			"bool": {
				"must": {
					"match": {
						"address": "avenue"
					}
				}
			}
		}
	}
}
```

## Expected behavior
Same set of data for both the query executions, But what actually happens is that the ElasticSearchAPI fetches the results while ElasticsearchJS fetches no results.

## Your Environment
- *node version*: 10.11.0
- `@elastic/elasticsearch` *version*: =6.8.0
- *os*: Linux

**Comment by delvedor** [comment]
Hello! Sorry but I don't understand your issue, the second example you wrote **is** how you should use the client.
You can find [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/search_examples.html) a search example.
