### ISSUE TITLE
filter_path added to client.search makes search invalid

### ISSUE THREAD

**Issue by naseemali925** [elastic/elasticsearch-js#869]
I'm using elasticsearch 6.0 and trying to add the filter_path to get only aggregations, but the client adds it to the query and makes the search invalid.

I already searched in the issues and found #616 
That issue has not been resolved but it's closed

It treats filterPath as query and makes the search invalid:

  starting request {
    "method": "POST",
    "path": "/_search",
    "body": [
      {
        "index": "item"
      },
      {
        "sort": [
          {
            "modified": {
              "order": "desc"
            }
          }
        ],
        "size": 10,
        "from": 0
      }
    ],
    "query": {
      "filter_path": "aggregations"
    }
  }

Kindly suggest a solution,

**Comment by delvedor** [comment]
Hello!
Are you trying to use the `search` API or the `msearch`?
If you are trying to use the `search`, the body format is wrong.
You should pass an object with the query in the body and every other parameter as a top-level key.
```js
client.search({
  index: 'item',
  filter_path: 'aggregations',
  body: {
    sort: [...],
    size: 10,
    from: 0,
    query: { ... }
  }
})
````

**Comment by naseemali925** [comment]
Hi @delvedor thanks for the response. I am using `search` with following value for `body`. And I am unable to get the expected result. I also checked kibana to do the same and it works with filter_path
```
{
    size: 0,
    query: {
      bool: {
        must: [
          {
            term: {
              controllerId: {
                value: controllerId,
              },
            },
          },
          {
            range: {
              ts: {
                gte: startTime,
                lte: endTime,
              },
            },
          },
          {
            exists: {
              field: 'networkStrength',
            },
          },
        ],
      },
    },
    aggs: {
      average: {
        avg: {
          script: 'params._source.networkStrength',
        },
      },
    },
  }
````

**Comment by delvedor** [comment]
I don's see the `filter_path` and the query looks ok.
Can you post a complete example to reproduce (I also need a data sample of your dataset)?
You can use [this template](https://github.com/delvedor/es-reproduce-issue).

**Comment by naseemali925** [comment]
Hi @delvedor Thanks for looking into this issue. It seems to work now, I was using `filterPath` instead of `filter_path`  But Still When I See The Request Done By Client It Is Appending A New Query For It But The Result Is Correct As Expected
```
"body": {
      "query": {
        "bool": {
          "must": [
            {
              "term": {
                "controllerId": {
                  "value": "2752"
                }
              }
            },
            {
              "range": {
                "ts": {
                  "gte": "2019-05-25 00:00:00",
                  "lte": "2019-05-30 00:59:00"
                }
              }
            },
            {
              "exists": {
                "field": "networkStrength"
              }
            }
          ]
        }
      },
      "aggs": {
        "average": {
          "avg": {
            "script": "params._source.networkStrength"
          }
        }
      }
    },
    "query": {
      "filter_path": "aggregations"
    }
  }
```

**Comment by delvedor** [comment]
It's fine to use `filterPath`.
You are putting it in the wrong place, it should be like follows:
```js
client.search({
  index: 'my-index',
  filterPath: '...',
  body: {
    query: { ... }
  }
}, console.log)
```

**Comment by naseemali925** [comment]
Hi, @delvedor Thank's For The Help.
I was actually using it as the way it's given in docs
```js
esClient
        .search({
          index: indexes,
          filterPath: 'aggregations',
          body: query,
        })
```
And I wasn't getting results.

But when I use 
```js
esClient
        .search({
          index: indexes,
          filter_path: 'aggregations',
          body: query,
        })
```

I am actually getting only the `aggregations` part only.
I am unsure if that's the expected behavior of the client.?
