### ISSUE TITLE
Typescript: Missing type for SSL configuration

### ISSUE THREAD

**Issue by Fgerthoffert** [elastic/elasticsearch-js#871]
## 🐛 Bug Report

Following the documentation https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/auth-reference.html for SSL configuration, tslint complains about `rejectUnauthorized`.

```
error TS2345: Argument of type '{ node: string | undefined; ssl: { ca: Buffer; rejectUnauthorized: boolean; }; }' is not assignable to parameter of type 'ClientOptions'.
Types of property 'ssl' are incompatible.
Type '{ ca: Buffer; rejectUnauthorized: boolean; }' is not assignable to type 'SecureContextOptions'.
Object literal may only specify known properties, and 'rejectUnauthorized' does not exist in type 'SecureContextOptions'.
```

## To Reproduce

Obtained while running `tslint -p test -t stylish` on the following code:

```js
new Client({
      node: 'A_NODE',
      ssl: {
        ca: fs.readFileSync('A_PATH'),
        rejectUnauthorized: true
      }
    })
```
## Expected behavior

No linting error

## Your Environment

- *node version*: 10.16.0
- *tslint version*: 5.16.0
- `@elastic/elasticsearch` *version*: >=7.0.0
- *os*: Mac
- *any other relevant information*

**Comment by delvedor** [comment]
Hello! Which version of `@types/node` are you using?

**Comment by Fgerthoffert** [comment]
Hi Tomas, 

When I created the ticket I was using: 10.14.7
I just updated to: 12.0.4, but I see the same type error.

**Comment by delvedor** [comment]
I'll investigate over this.
In the meantime, I've tested that you can avoid the use of `rejectUnauthorized`, your code should work fine. *(you can see [here](https://github.com/delvedor/es-reproduce-issue/blob/master/index.ts) an example)*

**Comment by Fgerthoffert** [comment]
Sounds good, thanks.

**Comment by mrauter** [comment]
We also want to set tls.connect options like rejectUnauthorized or checkServerIdentity which should be support but get the same error. It seems there is something wrong with the types?

**Comment by delvedor** [comment]
Currently, the `ssl` options accept [`SecureContextOptions`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/022dbd5d9115992722c50043b930b2dbafa94b43/types/node/v11/tls.d.ts#L339-L370), maybe the correct type should be [`TlsOptions`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/022dbd5d9115992722c50043b930b2dbafa94b43/types/node/v11/tls.d.ts#L250-L259)?

**Comment by mrauter** [comment]
I think the correct type would be `ConnectionOptions` it is also the input of the `tls.connect` method:

`function connect(options: ConnectionOptions, secureConnectListener?: () => void): TLSSocket;`

**Comment by delvedor** [comment]
It may be, would you like to open a pull request? :)
