### ISSUE TITLE
cat.snapshots response error when anything other than repository param is set

### ISSUE THREAD

**Issue by Rodolffo** [elastic/elasticsearch-js#872]
## 🐛 Bug Report

A _Response Error_ is returned when anything other than the _repository_ parameter is set in client.cat.snapshots parameters. When only the _repository_ parameter is set, it returns and executes just fine.

## To Reproduce

We have an AWS managed Elasticsearch service, so I needed to set up request signing by setting the _Connection_ parameter of the client to a different implementation. Other methods (e.g. _client.snapshot.create_, _client.indices.delete_ etc.) work just fine, so I assume it's not causing any problems, and also no problems at all when calling client.cat.snapshots without the _format_ and _s_ parameters. However, when I call it with those parameters set, I recieve the following error:
```
{
    "errorMessage": "Response Error",
    "errorType": "ResponseError",
    "stackTrace": [
        "ResponseError: Response Error",
        "    at IncomingMessage.response.on ([path to project]/elasticsearch-archiver/node_modules/@elastic/elasticsearch/lib/Transport.js:302:25)",
        "    at IncomingMessage.emit (events.js:202:15)",
        "    at IncomingMessage.EventEmitter.emit (domain.js:446:20)",
        "    at endReadableNT (_stream_readable.js:1129:12)",
        "    at processTicksAndRejections (internal/process/next_tick.js:76:17)"
    ]
}
```

Paste your code here:

```js
const allSnapshots = await client.cat.snapshots({
        repository: REPOSITORY_NAME,
        format: 'json',
        s: 'start_epoch',
    });
```

## Expected behavior

I expected the code to return a json object containing the list of snapshots ordered by starting time.

## Your Environment

- *node version*: v11.10.1
- `@elastic/elasticsearch` *version*: ^6.8.0
- *os*: Ubuntu 18.04

**Comment by delvedor** [comment]
Hello! Can you paste the full error object?
Are you able to reproduce the issue with [es-reproduce-issue](https://github.com/delvedor/es-reproduce-issue)?

**Comment by Rodolffo** [comment]
Hi @delvedor, thank you for the reply! As it turned out, the error was related to the request not being properly signed for AWS (the additional parameters added a parameter named querystring to the request object, and also the URL was sent without the GET parameters). By fixing these in the custom Connection implementation, I could get it working. Thanks for the help, and sorry for the false positive!
