### ISSUE TITLE
doc for termvectors

### ISSUE THREAD

**Issue by mohammadsalem** [elastic/elasticsearch-js#874]
Is it possible to use "doc" as param in [termvectors API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-termvectors.html#docs-termvectors-artificial-doc)?

I got this error 

> "[illegal_argument_exception] request [/report_file_files_content_v2/files/_termvectors] contains unrecognized parameter: [doc]"

when 

```
                es_client.termvectors({
                    index: 'report_file_files_content_v2',
                    type: 'files',
                    doc: {
                        file_content: 'agriculture'
                    },
                    fields: ['file_content'],
                    offsets: false,
                    payloads: false,
                    positions: false,
                    term_statistics: true,
                    field_statistics: false
                }, (error, response) => {
                    if (error == null) {
                        res.ok(response);
                    } else {
                        res.serverError(error);

                    }
                });
```

**Comment by delvedor** [comment]
Hello! You should put the `doc` field in the body :)
You can see [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_termvectors) which keys the API accepts, everything you don't see in the configuration object should go inside the body.

So you code should be updated to:
```js
client.termvectors({
  index: 'report_file_files_content_v2',
  type: 'files',
  fields: ['file_content'],
  offsets: false,
  payloads: false,
  positions: false,
  term_statistics: true,
  field_statistics: false,
  body: {
    doc: {
      file_content: 'agriculture'
    }
  }
}, console.log)
```
