### ISSUE TITLE
how to integrate postgresql database in expressjs with elastic search

### ISSUE THREAD

**Issue by asifswinjit** [elastic/elasticsearch-js#889]
### Please note that this issue tracker is not a help forum and this issue may be closed.

It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Comment by delvedor** [comment]
Hello!
Can you please write a more extensive question with an example of what you would like to achieve?
