### ISSUE TITLE
requestTimeout has no effect (@elastic/elasticsearch v6.8.0),

### ISSUE THREAD

**Issue by havber** [elastic/elasticsearch-js#890]
I am trying to set a relavtively short requestTimout, but it seems that the requestTimeout has no effect at all. Tried setting it to 0ms ans 1ms, but it does not time out, and the requests finishes successfully.

Client is created like this:
```js
const client = new Client({
		node: url,
		requestTimeout: 0
	});
```
and I do an `mget()` to fetch multiple documents:
```js

const fetchDocuments = (ids) => {
	const docs = ids.map((id) => {
		return {
			_index: 'my-index',
			_type: '_doc',
			_id: id,
		};
	});
	return client.mget({
		body: { docs }
	});
};
```

No matter what I set the requestTimeout to, it does not time out. This becomes an issue if elastic is unresponsive, and the requests hang.

**Comment by havber** [comment]
Also, I cannot see any effect when using the request specific `requestTimeout` option.

i.e. setting 
```
return client.mget({
		body: { docs }
	}, {
		requestTimeout: 0,
	});
```
Does not cause the request to time out. Is this not supperted on `mget`?

**Comment by delvedor** [comment]
Hello!
The `requestTimeout` works for every API. Internally the client is using the Node.js core `http` module, and if you set the timeout to `0`, then the timeout will be disabled.

**Comment by havber** [comment]
Hi! Thanks for you reply. I had a feeling that `0` might not be a valid value, so I have also tested with other (positive) values to try to force a timeout, but it does not seem to have an effect. 

Not sure if I might be doing something wrong in my code:

**Comment by delvedor** [comment]
As you can see here, I'm testing the timeout support and it's working.
https://github.com/elastic/elasticsearch-js/blob/ca50f580f41f509f1633103d3d69b5065af006c4/test/unit/connection.test.js#L235-L258

Which `requestTimeout` value are you using?
Are you able to reproduce the issue with https://github.com/delvedor/es-reproduce-issue?

**Comment by havber** [comment]
I have tried several different values. `1`, `10`, `100` etc. I will try to reproduce using the repo above. Thx.

**Comment by havber** [comment]
@delvedor I was able to work around this using `Promise.race([...])` (https://italonascimento.github.io/applying-a-timeout-to-your-promises/). I'll try to se if I can reproduce using `es-reproduce-issue`, or determine if there is a flaw in my implmentation, when I have the time to look into it.

**Comment by shusson** [comment]
I'm also seeing `requestTimeout` have seemingly no effect with v6.8.3.
