### ISSUE TITLE
why not support brower client?and the docs is not found

### ISSUE THREAD

**Issue by liukeqing** [elastic/elasticsearch-js#891]
### Please note that this issue tracker is not a help forum and this issue may be closed.

It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Comment by delvedor** [comment]
Hello! There is no official support for the browser since expose your Elasticsearch instance to the rest of the world will cause you security issues eventually.
I recommend you to write a lightweight proxy that uses this client instead.

**Comment by liukeqing** [comment]
ok,thank you.in the brower,http get method not support request body.what should i do.

**Comment by delvedor** [comment]
Hello! As said before, there is no support for the browser environment.
Furthermore, it's highly discouraged, since it will expose you to security issues.
