### ISSUE TITLE
npm install flags 12 high severity vulnerabilities

### ISSUE THREAD

**Issue by martin-displayr** [elastic/elasticsearch-js#892]
It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `not reproducible` label.**

## To Reproduce

Paste your code here:

```js

```

## Expected behavior

Paste the results here:

```js

```

## Your Environment

- *node version*: 6,8,10
- `@elastic/elasticsearch` *version*: >=7.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by delvedor** [comment]
I've just installed the client in a project without any other dependency and there are not vulnerabilities according to `npm audit`.
It must be another dependency of your project, I suggest you use [`npm audit`](https://docs.npmjs.com/cli/audit) for further investigation.

**Comment by martin-displayr** [comment]
Sorry to waste your time - I immediately closed the ticket. I think something screwed up with NPM on my machine because no problems on another machine.
