### ISSUE TITLE
Documentation for the deprecated client was DELETED

### ISSUE THREAD

**Issue by acarstoiu** [elastic/elasticsearch-js#895]
## 💥 Regression Report

The deprecated JS client is still in use and it has currently no official documentation. I tried to generate one locally and the procedure is not working - it crashes with
```
Error: spawn rm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

The [Elasticsearch clients page](https://www.elastic.co/guide/en/elasticsearch/client/index.html) should contain a link to this documentation, preferably at the same location where the [_**Docs**_  section within the _npm_ page](https://www.npmjs.com/package/elasticsearch#docs) points at!

It's insane to delete the official documentation of a deprecated client **less than 2 months** after releasing the first production-grade version of the new client. Please allow for _at least_ half a year of transition.

People don't just change hundreds of calls to your client in production code just because there's shiny new toy available. Not to mention that we also have patches that must be checked for applicability (and ported) on the new client.

**Comment by acarstoiu** [comment]
In the meantime, Google is our saviour:
https://webcache.googleusercontent.com/search?q=cache:OgvGiBmIKdgJ:https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/16.x/api-reference.html+&cd=1&hl=en&ct=clnk&gl=ro&client=firefox-b-d

**Comment by acarstoiu** [comment]
:thinking:  Also, if need be, here's an example of an extremely popular open source product (akin Elasticsearch) which cares to provide documentation for versions that have long been retired (**6 years +**)
https://nodejs.org/en/docs/

**Comment by delvedor** [comment]
Hello!
I'm sorry you had trouble using our legacy Client. Please consult this [link](https://github.com/elastic/elasticsearch-js-legacy/tree/16.x/docs) which hosts the entire legacy documentation.
Furthermore, we are looking into a fix for this problem, see https://github.com/elastic/elasticsearch-js-legacy/issues/3 and https://github.com/elastic/docs/pull/964.
Are you alright with closing this issue since, as you might have seen, we are already tracking the issue elsewhere?
Wish you a nice day.

**Comment by acarstoiu** [comment]
Yes, I know where the source files for the documentation reside, I did say I tried to build it.
The matter [is solved](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/16.x/index.html), anyway, thank you!
