### ISSUE TITLE
Connection problem with 7.2 version

### ISSUE THREAD

**Issue by hamdibayhan** [elastic/elasticsearch-js#925]
Hi,

I am getting problem with 7.2 version when connecting to elastic server but I am not getting problem connecting with 16.3 version for same IP and port. What is the problem? Thanks.

For 7.2 version:
```
  const { Client } = require('@elastic/elasticsearch')
  const client = new Client({
    node: 'http://.........'
  })
```

For 16.3 version:
```
  var elasticsearch = require("elasticsearch");
  var client = new elasticsearch.Client({
     host: "http://.........",
     requestTimeout: Infinity,
     keepAlive: true
  });
```

The rest of code:

```
  client.ping({
    requestTimeout: 30000,
  }, function (error) {
    if (error) {
      console.error(error.message);
      console.error('elasticsearch cluster is down!');
    } else {
      console.log('All is well');
    }
  });
```

Result for 7.2:  
**Response Error
elasticsearch cluster is down!**

Result for 16.3:  
**All is well**

**Comment by delvedor** [comment]
I just tried to run the following code:

```js
'use strict'

const { Client } = require('@elastic/elasticsearch')
const client = new Client({
  node: 'http://localhost:9200',
  requestTimeout: Infinity,
  keepAlive: true
})

client.ping({
  requestTimeout: 30000
}, function (error) {
  if (error) {
    console.error(error.message)
    console.error('elasticsearch cluster is down!')
  } else {
    console.log('All is well')
  }
})
```

And I get the following error:
```
RangeError [ERR_OUT_OF_RANGE]: The value of "msecs" is out of range. It must be a non-negative finite number. Received Infinity
```
Which is correct. The new client separates the client options from the Elasticsearch options, so you should rewrite the above example as follows:
```diff
- client.ping({
+ client.ping({}, {
  requestTimeout: 30000
}, function (error) {
  if (error) {
    console.error(error.message)
    console.error('elasticsearch cluster is down!')
  } else {
    console.log('All is well')
  }
})
```
With this change I get:
```
All is well
```

If after this change you are still encountering the issue, please use [this project](https://github.com/delvedor/es-reproduce-issue) to reproduce the issue, so I can better investigate it :)

**Comment by hamdibayhan** [comment]
@delvedor actually I typed wrong for version 7.2 in my issue, I am getting same error like you with `requestTimeout: Infinity, keepAlive: true` options. I have edited my issue without `requestTimeout: Infinity, keepAlive: true` options.

**Comment by delvedor** [comment]
Hello! I'm not encountering any issue with the latest `7.x` version from npm.
Can you use [es-reproduce-issue](https://github.com/delvedor/es-reproduce-issue) to create a simple case to reproduce the issue you are encountering?
