### ISSUE TITLE
Fix documentation generator

### ISSUE THREAD

**Issue by delvedor** [elastic/elasticsearch-js#931]
Some APIs support the same parameter both in the url and in the querystring. The current implementation of the [documentation generator](https://github.com/elastic/elasticsearch-js/blob/master/scripts/utils/generateDocs.js) does not take into account this, and as result *some* APIs will have duplicated parameters in the description (see `bulk` or `scroll` for example).

**Comment by alemagio** [comment]
Hi, i would like to work on this, any hint?

**Comment by delvedor** [comment]
Hello @alemagio, sorry for the delay!
I'm in the process of updating the code generator to use the new spec adopted in the Elasticsearch repository, with that I'll probably fix also this issue as well.
