### ISSUE TITLE
how set type 

### ISSUE THREAD

**Issue by Yangk030208** [elastic/elasticsearch-js#941]
use this library to store data in ES,
but now there's a problem.
```
client.index({
     index: index,
     type: type,
     body: body
}, (error, response) => {
    ......
});
```
I saw in the log： ```http://192.168.1.6:9200/index/_doc?type=type```
obviously, my type is wrong😢。
I hope the url is： ```http://192.168.1.6:9200/index/type```
I don't know how to set . Who can help me?thank you .
es version：6.4.2。
nodejs version: 8.0.0
os: mac (10.14.1 Beta (18B73a))
elasticsearch-js: 16.3.0

**Comment by delvedor** [comment]
Hello!
In the issue template there is a list of things that are very helpful to debug this kind of issues, can you fill it?

- *node version*: ...
- `@elastic/elasticsearch` *version*: ...
- *os*: ...

My gut feeling is that you are using Elasticsearch version 6 but the client version 7, which has different handling of types.
I would also recommend you to read [this blog post](https://www.elastic.co/blog/moving-from-types-to-typeless-apis-in-elasticsearch-7-0).

**Comment by Yangk030208** [comment]
@delvedor Thank you for your answer. Last question，my ES version is 6.4.2.。Which version of elasticsearch-js should I use?

**Comment by delvedor** [comment]
Quoting from the [README](https://github.com/elastic/elasticsearch-js#compatibility):

> The library is compatible with all Elasticsearch versions since 5.x, and you should use the same major version of the Elasticsearch instance that you are using.

Which means that if you are using Elasticsearch v6, you should use the client v6.
