### ISSUE TITLE
Sorting fields list with space characted failing

### ISSUE THREAD

**Issue by vbontempi** [elastic/elasticsearch-js#947]
It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

## 💥 Regression Report

Trying to run the following query on ES 5.6.16

```
"body":{"_source":{"exclude":["metadata"]},"query":{"query_string":{"query":" [ ... OUR QUERY BODY ... ] "}}},"from":0,"size":10,"sort":"resource_id:asc, crn:asc"... }
```

 is causing the following error 

```
{"type":"query_shard_exception","reason":"No mapping found for [ crn] in order to sort on","index_uuid":"YFDDFzNXQUmewBx28Zx5Ww","index":"index_name"}
```

The problem is with the fields list used to sort the results, which is a comma separated fields list, which contains the 'space' character after the comma

## Last working version

Worked up to version: "elasticsearch": "15.5.0" (legacy client)

Stopped working in version: "@elastic/elasticsearch": "^5.6.20" (new client version)

## To Reproduce

Steps to reproduce the behavior: trigger a query with a comma separated fields list using a 'space' after a comma

## Expected behavior

The expected behavior is the query to run correctly.
Otherwise, if it is the expected behavior it should be reported in the 'breaking changes' for the new client

- *node version*: 8
- `@elastic/elasticsearch` *version*: >=5.6.20
- *os*: Mac

**Comment by delvedor** [comment]
Hello, sorry for the delay!
Can you please write a small example to reproduce the issue?
