### ISSUE TITLE
Connection.request params expected RequestOptions without querystring

### ISSUE THREAD

**Issue by villasv** [elastic/elasticsearch-js#951]
## 🐛 Bug Report

The typing for `Connection.request` (defined [here](https://github.com/elastic/elasticsearch-js/blob/a948a98be652529204b64bd8b366ff0944090ee8/lib/Connection.d.ts#L61)) states that `params` is of type `RequestOptions`.

At runtime, I observe the following object for an `indices.exists` call:

```
{ method: 'HEAD',
  path: '/_alias/idxname',
  body: null,
  querystring: '',
  headers:
   { 'User-Agent':
      'elasticsearch-js/7.3.0 (linux 4.19.57-microsoft-standard-x64; Node.js v10.14.1)' },
```

But `RequestOptions` has no attributes `body` and `querystring`. I expected to find those in `TransportRequestParams` instead. But `TransportRequestParams` also has `headers` missing, so it can't be it either (defined [here](https://github.com/elastic/elasticsearch-js/blob/a948a98be652529204b64bd8b366ff0944090ee8/lib/Transport.d.ts#L74)).

## To Reproduce

I ran into this when trying to sign requests with AWS credentials.

```ts
import { Connection as UnsignedConnection } from '@elastic/elasticsearch';
import * as AWS from 'aws-sdk';
import RequestSigner from 'aws-sdk/lib/signers/v4';
import { ClientRequest, RequestOptions, IncomingMessage } from 'http';

class AwsElasticsearchError extends Error {}


class AwsSignedConnection extends UnsignedConnection {
  public request(
    params: RequestOptions,
    callback: (err: Error | null, response: IncomingMessage | null) => void,
  ): ClientRequest {
    const signedParams = this.signParams(params);
    return super.request(signedParams, callback);
  }

  private signParams(params: any): RequestOptions {
    const region = AWS.config.region || process.env.AWS_DEFAULT_REGION;
    if (!region) {
      throw new AwsElasticsearchError('missing region configuration');
    }

    const endpoint = new AWS.Endpoint(this.url.href);
    const request = new AWS.HttpRequest(endpoint, region);

    request.method = params.method;
    request.path = params.querystring
      ? `${params.path}/?${params.querystring}`
      : params.path;
    request.body = params.body;

    request.headers = params.headers;
    request.headers.Host = endpoint.host;

    const signer = new RequestSigner(request, 'es');
    signer.addAuthorization(AWS.config.credentials, new Date());
    return request;
  }
}

export { AwsSignedConnection, UnsignedConnection, AwsElasticsearchError };

...
```

## Expected behavior

No type errors.

## Your Environment

- *node version*: 10.14.1
- `@elastic/elasticsearch` *version*: =7.3.0
- *os*: Windows

**Comment by delvedor** [comment]
Hello! You are right, we should add `body` and `querystring` here: https://github.com/elastic/elasticsearch-js/blob/f7be49f2bafa3b9ddc90b0caac5b70932e6db35b/lib/Connection.d.ts#L26-L28

This is happening because the client is using the Node.js http.request API, which uses `.end` to send the body, while the querystring lives in `search`.

Would you mind open a pull request to fix this?

**Comment by villasv** [comment]
Hi @jawadmjn, here's the code I've been using:

```
import { Connection as UnsignedConnection } from '@elastic/elasticsearch';
import * as AWS from 'aws-sdk';
import RequestSigner from 'aws-sdk/lib/signers/v4';
import { ClientRequest, RequestOptions, IncomingMessage } from 'http';

class AwsElasticsearchError extends Error {}


class AwsSignedConnection extends UnsignedConnection {
  public request(
    params: RequestOptions,
    callback: (err: Error | null, response: IncomingMessage | null) => void,
  ): ClientRequest {
    const signedParams = this.signParams(params);
    return super.request(signedParams, callback);
  }

  // TODO: better type after https://github.com/elastic/elasticsearch-js/issues/951
  private signParams(params: any): RequestOptions {
    const region = AWS.config.region || process.env.AWS_DEFAULT_REGION;
    if (!region) {
      throw new AwsElasticsearchError('missing region configuration');
    }

    const endpoint = new AWS.Endpoint(this.url.href);
    const request = new AWS.HttpRequest(endpoint, region);

    request.method = params.method;
    request.path = params.querystring
      ? `${params.path}/?${params.querystring}`
      : params.path;
    request.body = params.body;

    request.headers = params.headers;
    request.headers.Host = endpoint.host;

    const signer = new RequestSigner(request, 'es');
    signer.addAuthorization(AWS.config.credentials, new Date());
    return request;
  }
}

export { AwsSignedConnection, UnsignedConnection, AwsElasticsearchError };
```

**Comment by jawadmjn** [comment]
@villasv thanks man I have this, and how are you doing this part, part of injecting this connection in the client,
what I have is

`
const params: RequestParams.Search = {
            index: this.index,
            body: {
                query: {
                    multi_match: {
                        query: text,
                        type: "most_fields",
                        fields: [
                            "title^30",
                            "headline^25"
                        ]
                    }
                }
            }
        };

        let awsSignedConnection = new AwsSignedConnection(this.aws, this.esHost);
        
        let requestParams = {
            path: `/${this.index}/_search/`,
            method: "POST",
        };

        const client = new Client({
            node: this.esHost,
            Connection: awsSignedConnection.request(requestParams)
        });

        return client.search(params);
`

**Comment by jawadmjn** [comment]
TS2345: Argument of type '{ node: any; Connection: ClientRequest; }' is not assignable to parameter of type 'ClientOptions'.   Types of property 'Connection' are incompatible.     Type 'ClientRequest' is missing the following properties from type 'typeof Connection': prototype, statuses, roles

**Comment by villasv** [comment]
That's not you're supposed to use connection classes. Here's an example:

```
  const esClient = new Client({
    Connection: AWS.config.credentials ? AwsSignedConnection : UnsignedConnection,
    node: 'http://localhost:9200', // esHost
  });
```
Then you can just use `client.search(...)` without worrying about signatures.

**Comment by jawadmjn** [comment]
@villasv You are a rock star, It worked man. Thanks a lot 👍 :)
