### ISSUE TITLE
Typescript: Definition of _source parameter doest not allow boolean false

### ISSUE THREAD

**Issue by pierremalletneo9** [elastic/elasticsearch-js#955]
## 🐛 Bug Report

The typescript definition of the `_source` params is `_source?: string | string[];` 

```
export interface Search<T = any> extends Generic {
  index?: string | string[];
  type?: string | string[];
  ...
  _source?: string | string[];
  _source_excludes?: string | string[];
  _source_includes?: string | string[];
  ...
}
```

But it should allow boolean false value since the behavior of an Es request is totally different with `source: false` and `source: ''`. The first one strips the source deserialization by elasticsearch where the second need to deserialize the source of the documents and return nothing in the response. 

## Expected behavior

It should be possible to set `_source` to the boolean value false

## Your Environment

- *node version*: 10
- `@elastic/elasticsearch` *version*: >=7.3.0
- *os*: Linux

**Comment by twixr** [comment]
I ran into the same issue. Trying to update a document with _source: false
```
Overload 1 of 4, '(params?: Update<{ doc: Record<string, unknown>; }> | undefined, options?: TransportRequestOptions | undefined): TransportRequestPromise<ApiResponse<Record<string, any>, unknown>>', gave the following error.
    Type 'false' is not assignable to type 'string | string[] | undefined'.
```

According to the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#docs-update-api-query-params):
```
_source
(Optional, list) Set to false to disable source retrieval (default: true). You can also specify a comma-separated list of the fields you want to retrieve.
```

**Comment by delvedor** [comment]
This now has been fixed.
