### ISSUE TITLE
Typescript: Incomplete definition track_total_hits parameter

### ISSUE THREAD

**Issue by pierremalletneo9** [elastic/elasticsearch-js#956]
## 🐛 Bug Report

The definition of track_total_hits in the RequestParams.Search interface is 

`track_total_hits?: boolean; ` 

from [here] (https://github.com/elastic/elasticsearch-js/blob/master/api/requestParams.d.ts#L1117)

But according to the documentation [ track_total_hits ](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-body.html#request-body-search-track-total-hits) we should be able to use number for this parameter. 

## Expected behavior

The definition should use something like `number | boolean`

## Your Environment

- *node version*: 10
- `@elastic/elasticsearch` *version*: >=7.3.0
- *os*: Linux

**Comment by delvedor** [comment]
Hello! You are right. The definitions are generated from the [rest-api-spec](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/main/resources/rest-api-spec), and there is a bug there about this option (same for https://github.com/elastic/elasticsearch-js/issues/955).
We'll look into it, thank you for contributing!

**Comment by khalilmansouri** [comment]
I believe track_total_hits already support number `track_total_hits?: boolean | number;` in [requestParams.d.ts#L85](https://github.com/elastic/elasticsearch-js/blob/master/api/requestParams.d.ts#L85)

**Comment by pierremalletneo9** [comment]
Ok then I close this issue since it has been corrected. Thanks for the update.
