### ISSUE TITLE
Cannot delete document by node js client

### ISSUE THREAD

**Issue by measwel** [elastic/elasticsearch-js#960]
"@elastic/elasticsearch": "^6.8.2"
Elastic:
  "version": {
    "number": "6.2.3",
  },
  "tagline": "You Know, for Search"
}

I am trying to delete a document with the client.delete method, but it throws a null pointer exception:
"error": {
  "msg": "[remote_transport_exception] [127.0.0.1][127.0.0.1:9300][indices:data/write/bulk[s][p]]",
  "path": "/arbotti_post/_doc/73b6ba77-1f3d-46dd-a8d2-206f0b8f2d6f",
  "query": {
   "type": "post",
   "refresh": "wait_for"
  },
  "statusCode": 500,
  "response": "{\"error\":{\"root_cause\":[{\"type\":\"remote_transport_exception\",\"reason\":\"[127.0.0.1][127.0.0.1:9300][indices:data/write/bulk[s][p]]\"}],\"type\":\"null_pointer_exception\",\"reason\":null},\"status\":500}"
 },

I noticed that the path generated by the client contains _doc instead of the provided document type: 

"path": "/arbotti_post/_doc/73b6ba77-1f3d-46dd-a8d2-206f0b8f2d6f"

If I change it to the document type, then the operations succeeds.

I am providing the document type in the call to .delete :

deleteoptions = { id: '73b6ba77-1f3d-46dd-a8d2-206f0b8f2d6f',
  index: 'arbotti_post',
  type: 'post',
  refresh: 'wait_for' }

esClient.delete(deleteoptions, (err, result) => { ...

Why is the client not including the provided document type in the path for the request?

Update: I wrongly used a client included by another module. It works with the newer client.

**Comment by delvedor** [comment]
Hello! 

>  It works with the newer client.

Great to see you have solved the issue, can we close the ticket?

**Comment by measwel** [comment]
Yes, this issue is solved. Thank you.
