### ISSUE TITLE
Stream/follow/tail an index

### ISSUE THREAD

**Issue by ORESoftware** [elastic/elasticsearch-js#962]
Just wondering if there is a way to something like this:

```typescript

client.search({
  follow: true,
  index: 'my-index',
  body: { foo: 'bar' }
}, (err, stream) => {
   stream.on('data', console.log);
});


```

is there some way to tail/stream/follow an ES index?  Something like ChangeStreams in MongoDB?

**Comment by delvedor** [comment]
Hello! There is not an API like that yet.
You can follow the discussion in https://github.com/elastic/elasticsearch/issues/1242 :)
