### ISSUE TITLE
Document error object properties

### ISSUE THREAD

**Issue by delvedor** [elastic/elasticsearch-js#964]
Currently, the [error handling](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-usage.html#_error_handling) documentation is not showing the properties that each error class has. The document should be updated to add those properties and a brief description.
The error definitions can be found [here](https://github.com/elastic/elasticsearch-js/blob/master/lib/errors.js).

Related: https://github.com/elastic/elasticsearch-js/issues/963

**Comment by dhuang612** [comment]
Hi, 
Made a PR for this issue #982 
I signed the agreement after I created the PR
