### ISSUE TITLE
Elasticsearch ConnectionError in 7.3.0 version

### ISSUE THREAD

**Issue by sarahakhtar** [elastic/elasticsearch-js#965]
I'm trying to interact with elasticsearch node client, it was working fine with elastic cloud, but when I changed the configurations to google compute engine instance of elasticsearch it's giving following error:

{
    "name": "ConnectionError",
    "meta": {
        "body": null,
        "statusCode": null,
        "headers": null,
        "warnings": null,
        "meta": {
            "context": null,
            "request": {
                "params": {
                    "method": "POST",
                    "path": "/users/_search",
                    "body": "{\"query\":{\"bool\":{\"must\":{\"query_string\":{\"query\":\"*2032*\"}}}}}",
                    "querystring": "",
                    "headers": {
                        "User-Agent": "elasticsearch-js/7.3.0 (darwin 17.7.0-x64; Node.js v10.15.0)",
                        "Content-Type": "application/json",
                        "Content-Length": "63"
                    },
                    "timeout": 30000
                },
                "options": {
                    "warnings": null
                },
                "id": 2
            },
            "name": "elasticsearch-js",
            "connection": {
                "headers": {},
                "deadCount": 0,
                "resurrectTimeout": 0,
                "_openRequests": 0,
                "status": "alive",
                "roles": {
                    "master": true,
                    "data": true,
                    "ingest": true,
                    "ml": false
                }
            },
            "attempts": 3,
            "aborted": false
        }
    }
}

**Comment by delvedor** [comment]
Hello! Can you share the code you are using to connect to Elastic Cloud and GCP?

**Comment by sarahakhtar** [comment]
I'm creating the client this way:

let elasticSearchClient = new Client({
    node: `https://${functions.config().elasticsearch.username}:${functions.config().elasticsearch.password}@${functions.config().elasticsearch.host}`
})

**Comment by sarahakhtar** [comment]
It's working fine in Elastic Cloud case, but I suppose it's SSL problem in client case. I deployed bitnami google app engine elastic instance, I'm able to connect via postman, but not able to ping through client.

**Comment by delvedor** [comment]
Are you able to connect with `curl`?
If so, can you paste here the curl command that are you using? *(with redacted url/username/passowrd)*
