### ISSUE TITLE
TypeScript Error: Module '"url"' has no exported member 'URL'. Did you mean 'Url'?

### ISSUE THREAD

**Issue by SergeyBarskiy** [elastic/elasticsearch-js#973]
## 🐛 Bug Report
Building a TypeScript Node js project with "@elastic/elasticsearch": "~6.8.2" results in the following error:
TypeScript Error: Module '"url"' has no exported member 'URL'. Did you mean 'Url'?

## To Reproduce

Create a new node project with Elastic using TypeScript
Compile with TypeScript
Error in the description comes up.

The offending line is 
import { URL } from 'url';

The actual class from node is Url.

## Expected behavior
SHould not generate an error

- *node version*: 8.12
- `@elastic/elasticsearch` *version*: 6.8.2
- *os*: Windows

Thank you!

**Comment by delvedor** [comment]
Hello! Did you install the Node.js type definition?
```
npm install --save-dev @types/node
```
As you can see [here](https://nodejs.org/api/url.html#url_url) the import is correct.

**Comment by SergeyBarskiy** [comment]
No I have not.  I thought it was built into basic project.  And type will be found,  I will try next week.  You can close for now.  I will post new issue if this does not work.  Thanks for looking into it.
