### ISSUE TITLE
Client should send appropriate content headers

### ISSUE THREAD

**Issue by bsander** [elastic/elasticsearch-js#98]
We use the elasticsearch client in an environment where elasticsearch is proxied by a node.js restify app that performs some content modification. By default, this proxy interprets all requests performed by elasticsearch-js as plain text, because no `Content-Type: application/json` header is set. Adding this header (and for completeness, also `Accept: application/json`) would really help here.

**Comment by sliontc** [comment]
how to set the header config dynamically?

**Comment by spalger** [comment]
This has been done for a while, and now that elasticsearch requires `Content-Type`s (or is going to soon) we will continue to send them with every request.
