### ISSUE TITLE
self-signed ssl certificates not allowed by default - different from legacy client

### ISSUE THREAD

**Issue by vbontempi** [elastic/elasticsearch-js#991]
The legacy client (and previous official one) supported the self-signed ssl certificates: connections with ES servers using self-signed ssl certificates was possible by default, so by default seems that old client has the configuration ssl.rejectUnauthorized set to false by default

New client seems to have ssl.rejectUnauthorized set to true by default: it means that the old code working with old client, failed to connect to ES clusters using self-signed certificates.
Is it expected?

**Comment by delvedor** [comment]
Hello! There are no defaults for SSL, if you don't configure anything the client will use the defaults defined by [Node.js itself](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback), which in this case is `true`.
